### ISSUE TITLE
Kafka SASL - Exception while loading Zookeeper JAAS: user not found

### ISSUE THREAD

**Issue by iomv** [bitnami/charts#1018]
**Which chart**:
Kafka v2.1.0
Zookeeper v3.4.12

**Description**
Attempt to deploy kafka chart with SASL_SSL and auth enabled. 
Deploying kafka chart after generating necessary secrets following instructions here https://github.com/bitnami/bitnami-docker-kafka#security to create relevant JKS and certificates and with command 
```
helm install --name sandbox kafka/ --set auth.enabled=true \
             --set auth.brokerUser=brokerUser --set auth.brokerPassword=brokerPassword \
             --set auth.interBrokerUser=interBrokerUser --set auth.interBrokerPassword=interBrokerPassword \
             --set auth.zookeeperUser=zookeeperUser --set auth.zookeeperPassword=zookeeperPassword \
             --set zookeeper.auth.enabled=true --set zookeeper.auth.serverUser=zookeeperUser --set zookeeper.auth.serverPassword=zookeeperPassword \
             --set zookeeper.auth.clientUser=zookeeperUser --set zookeeper.auth.clientPassword=zookeeperPassword \
             --set auth.certificatesSecret=kafka-tls --set auth.certificatesPassword=kafkastorepassword
```

results in an error:

```
2019-01-10 12:58:54,974 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:SaslServerCallbackHandler@93] - User 'zookeeperUser' not found in list of DIGEST-MD5 authenticateable users.
2019-01-10 12:58:54,974 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:SaslServerCallbackHandler@107] - No password found for user: null
2019-01-10 12:58:54,974 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@1050] - Client failed to SASL authenticate: javax.security.sasl.SaslException: DIGEST-MD5: cannot acquire password for zookeeperUser in realm : zk-sasl-md5
javax.security.sasl.SaslException: DIGEST-MD5: cannot acquire password for zookeeperUser in realm : zk-sasl-md5
	at com.sun.security.sasl.digest.DigestMD5Server.validateClientResponse(DigestMD5Server.java:603)
	at com.sun.security.sasl.digest.DigestMD5Server.evaluateResponse(DigestMD5Server.java:244)
	at org.apache.zookeeper.server.ZooKeeperSaslServer.evaluateResponse(ZooKeeperSaslServer.java:50)
	at org.apache.zookeeper.server.ZooKeeperServer.processSasl(ZooKeeperServer.java:1042)
	at org.apache.zookeeper.server.ZooKeeperServer.processPacket(ZooKeeperServer.java:1014)
	at org.apache.zookeeper.server.NIOServerCnxn.readRequest(NIOServerCnxn.java:393)
	at org.apache.zookeeper.server.NIOServerCnxn.readPayload(NIOServerCnxn.java:211)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:264)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:226)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce the issue:**

1. Deploy chart with helm's command to deploy as above
2. Wait for zookeeper to start and tail logs until you notice the issue
3. You will also notice that kafka cluster is restarting continuously 

**Describe the results you received:**

Kafka fail to start

**Describe the results you expected:**

Kafka to start with SASL auth enabled

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by iomv** [comment]
Also noticed that using the values_production file accordingly set to pass the set of credentials to kafka and zookeeper instead, results in an exception:
```
[2019-01-08 18:37:32,916] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context 'Client'
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:45)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:358)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:42)
	... 5 more
```

**Comment by javsalgar** [comment]
Hi,

Thanks for filing the ticket. We will try to reproduce the issue and let you know more details about it.

**Comment by javsalgar** [comment]
Hi,

We saw that there is an issue with the documentation. The values is not zookeeper.auth.serverUser but zookeeper.auth.serverUsers. The same with zookeeper.auth.serverPassword, it is zookeeper.auth.serverPasswords. Could you try with that?

**Comment by Aravindumasankar** [comment]
After setting zookeeper.auth.serverUsers, zookeeper.auth.serverPasswords Error remains the same..
org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context 'Client'
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:45)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:358)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)

**Comment by Aravindumasankar** [comment]
Hello Team, any update on this issue?

**Comment by carrodher** [comment]
Hi,

It seems there are some needed files that are not present. Can you run
```bash
ls -la /opt/bitnami/kafka/conf/
```
and paste here the output?
