### ISSUE TITLE
bitnami/keycloak v18 Chart v9.0.0 doesn't work with reverse proxy

### ISSUE THREAD

**Issue by tirelibirefe** [bitnami/charts#10295]
### Name and Version

bitnami/keycloak v9.0.0

### What steps will reproduce the bug?

Hello,
A similar problem is discribed [here](https://keycloak.discourse.group/t/problems-with-keycloak-in-kubernetes-behind-a-network-load-balancer-in-aws/10843).

I have a Keycloak v16 which was installed via Bitnami/Keycloak Helm Chart v7.1.7 and it works pretty well.
Now I need to upgrade Keycloak v18 by using Bitnami/Keycloak Helm Chart v9.0.0 .

This is my system:
http/https >>>> ALB (SSL Offloading)>>> (http) Nginx Ingress >>> (http) Keycloak
my existing Keycloak v16 settings are:

```

```
...
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://keycloak.mydomain.com/auth"
...
...
proxyAddressForwarding: false
...
```

...and here my Keycloak v18 confiuration:

...
extraEnvVars:
- name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
  value: "true"
- name: KEYCLOAK_FRONTEND_URL
  value: "https://keycloak.mydomain.com/auth"
# - name: KEYCLOAK_EXTRA_ARGS
#   value: "-Dkeycloak.frontendUrl=https://keycloak.mydomain.com/auth"
...
...
proxy: passthrough
...
annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location /auth {
        proxy_set_header    X-Real-IP          $remote_addr;
        proxy_set_header    X-Forwarded-Port   $server_port;
        proxy_set_header    X-Forwarded-Proto  $scheme;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Host   $host;
        proxy_set_header    X-Forwarded-Server $host;
        proxy_set_header Host keycloak.mydomain.com;
      }
...
```

### Are you using any custom parameters or values?

Actually I tried many combainations too many times like:

proxy: passthrough/edge/none/reencrytpt
- name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
  value: "true/false"
etc.

None of them work...

When I check the debug logs, things try to reach to http not https.

Could you please advise is it a bug or am I missing something?

Thanks & Regards

### What is the expected behavior?

I expect to reach Keycloak UI from https.

### What do you see instead?

![image](https://user-images.githubusercontent.com/45227339/169023613-719357b5-ef3f-4b8f-bf13-be84b73e29bc.png)

### Additional information

```
2022-05-18 10:57:58,873 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (executor-thread-0) Recalculated absoluteURI to http://keycloak.u2.mydomain.com/auth/
2022-05-18 10:57:58,888 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Error response 404: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://keycloak.u2.mydomain.com/auth/
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:152)
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:74)
        at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:47)
        at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:480)
        at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:332)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:253)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-18 10:57:59,042 DEBUG [freemarker.cache] (executor-thread-0) Couldn't find template in cache for "error.ftl"("en_US", UTF-8, parsed); will try to load it.
2022-05-18 10:57:59,044 DEBUG [freemarker.cache] (executor-thread-0) TemplateLoader.findTemplateSource("error_en_US.ftl"): Not found
2022-05-18 10:57:59,045 DEBUG [freemarker.cache] (executor-thread-0) TemplateLoader.findTemplateSource("error_en.ftl"): Not found
2022-05-18 10:57:59,046 DEBUG [freemarker.cache] (executor-thread-0) TemplateLoader.findTemplateSource("error.ftl"): Found
2022-05-18 10:57:59,046 DEBUG [freemarker.cache] (executor-thread-0) Loading template for "error.ftl"("en_US", UTF-8, parsed) from "jar:file:/opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-themes-18.0.0.jar!/theme/base/login/error.ftl"
2022-05-18 10:57:59,132 DEBUG [freemarker.cache] (executor-thread-0) Couldn't find template in cache for "template.ftl"("en_US", UTF-8, parsed); will try to load it.
2022-05-18 10:57:59,134 DEBUG [freemarker.cache] (executor-thread-0) TemplateLoader.findTemplateSource("template_en_US.ftl"): Not found
2022-05-18 10:57:59,134 DEBUG [freemarker.cache] (executor-thread-0) TemplateLoader.findTemplateSource("template_en.ftl"): Not found
2022-05-18 10:57:59,135 DEBUG [freemarker.cache] (executor-thread-0) TemplateLoader.findTemplateSource("template.ftl"): Found
2022-05-18 10:57:59,135 DEBUG [freemarker.cache] (executor-thread-0) Loading template for "template.ftl"("en_US", UTF-8, parsed) from "jar:file:/opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-themes-18.0.0.jar!/theme/base/login/template.ftl"
2022-05-18 10:57:59,341 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-0) JtaTransactionWrapper rollback
2022-05-18 10:57:59,341 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-0) JtaTransactionWrapper end
2022-05-18 10:57:59,525 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-0) new JtaTransactionWrapper
2022-05-18 10:57:59,525 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-0) was existing? false
2022-05-18 10:57:59,526 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (executor-thread-0) Recalculated absoluteURI to http://keycloak.u2.mydomain.com/resources/8dvuk/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css
```

**Comment by tirelibirefe** [comment]
> @tirelibirefe have a look at some the config options I've documented within #10236 as that enables it to work with the `KC_HOSTNAME` (replacement of frontend URL piece) and TLS offloaded by your external LB

Thank you @jack1902 

Let me clarify a few points pls:

1)
There is an indentation problem for the line:
`  path: "/()(.*)"`

2)
What is the `"proxy:"` parameter? is it `"proxy: edge"` ?

3)
Do we need to set `proxyAddressForwarding: true` at v9.0.0 ?

4)
Were you able to get rid of `WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.`
? It is my another issue which has lower priority.

5)
Should I set the X-Forwarded stuff?

```
kubernetes.io/ingress.class: nginx
    # nginx.org/server-snippets: |
    #   location / {
    #     proxy_set_header X-Forwarded-Host $host;
    #     proxy_set_header X-Forwarded-Server $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header Host $http_host;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "Upgrade";
    #     proxy_pass_request_headers on;
    #   }
```
Thanks & Regards

**Comment by jack1902** [comment]
1. `ingress.path` within the values you pass into the chart (path and extraPaths) ensre `/` and `/auth` both work (you should look to remove the ingress snippets once you are sure you no longer use `/auth` anywhere
2. `proxy: edge` in my case as I have SSL terminated at my edge, which then passes everything through my system as `http` (with x-forwarded-for headers so that keycloak knows the original request was https). Check https://www.keycloak.org/server/reverseproxy for more info
3. `proxyAddressForwarding` is no longer a value in the `values.yaml` of the chart (you might want to check what overrides you had before and compare them to the latest `values.yaml` to see if they are still a thing) - This is what point 2 is for, the `proxy` piece configures all the bits inside keycloak
4. I got rid of the `DO NOT` piece by using my own `command` by running `setup.sh && build && start` (Refer to https://github.com/bitnami/charts/issues/10236#issuecomment-1128858062 for better guidance)
5. I have an external edge in my setup which forwards traffic to NGINX which then pushes it to the relevant service within my cluster. For this reason, I have enabled `use-forwarded-headers` within my nginx config. Refer to this for more info https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers

**Comment by tirelibirefe** [comment]
@jack1902 
#1 I didn't understand what you meant.
#2 ok; that's exactly what my config is.
#3 ok
#4 ok. I just noticed in your config.
#5 Yes, I have the same structure. 
My snipplets:
 I tried with/without `location /` and also with/without `location /auth`, nothing changed.

    ```
nginx.org/server-snippets: |
      location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
      }
      location /auth {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
      }
```

**Comment by jack1902** [comment]
1. basically, only use the `/auth` snippet piece if you have a requirement to do it, if you can shift all of your workflows to use the paths `/<keycloak-endpoint>` instead of `/auth/<keycloak-endpoint>` do that without using the ingress stuff I have had to do
5. you shouldn't need the snippets if you have enabled the config option within `ingress-nginx`, to ensure x-forwarded-for headers are propagated (nginx defaults to not trusting them as it is usually exposed at the edge but if you have a L7 LB in front of it you can tell nginx to trust those headers)

**Comment by tirelibirefe** [comment]
(1) ok now. Currently as I use only /auth, no need to set snipplets for other paths, thanks for explanation.

(2) Yes, I have L7 LB which is ALB in front of NGINX.

if I have enabled the config option within ingress-nginx... >>> My ingress config is below. Have I enabled the config option within ingress-nginx? I didn't understand, sorry.

 ```
 annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.org/server-snippets: |
      location /auth {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
      }

```

**Comment by tirelibirefe** [comment]
@jack1902 another clue, it maybe useful to understand:
When I try to access here >> `http://keycloak.mydomain.com/admin/`

Keycloak redirects me to here:

`https://keycloak.mydomain.com/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https%3A%2F%2Fkeycloak.mydomain.com%2Fadmin%2Fmaster%2Fconsole%2F&state=98XXXfc5-4064-49d9-b19d-ac44d86fac10&response_mode=fragment&response_type=code&scope=openid&nonce=da34782f-8963-4e52-a78a-ab1eb54da822&code_challenge=LCL2dzWOgGlaHKTh-B_HY8pRrXXXI9U4YTDTXJ8&code_challenge_method=S256`

...and the result:
![image](https://user-images.githubusercontent.com/45227339/169072119-a00e03b8-a3c6-474f-b251-0716f96557f3.png)

"Back to Application" >>> redirects again to the long URL  above.

**Comment by jack1902** [comment]
`redirect_uri` got removed in v18 of keycloak, potentially something I cached locally resulting in that address?

**Comment by tirelibirefe** [comment]
@jack1902 Could you please advise for https://github.com/bitnami/charts/issues/10295#issuecomment-1130113844 ?

I checked https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers regarding to your advise; there is no any syntax like neither `proxy_header `nor` X-Forwarded-Host`.

Is my sniplet correct? What are the correct/tested config options to enable X-Forwarded stuff?

Thanks & Regards

**Comment by jack1902** [comment]
@tirelibirefe you shouldn't need to add the `server-snippet` if your `ingress-nginx` config (check the configmap) has the relevant `use-forwarded-headers` piece. I haven't got a snippet for the `x-forwarded` pieces and it works behind my reverse-proxy.

If you require the `server-snippet` my only advice would be to see what others have done for `x-forwarded` pieces to backend applications (keycloak isn't unique here so at least you'll have a wider search). Sorry if that isn't any help, but I'm unsure of the configuration you need for your environment 😕

**Comment by hugodopradofernandes** [comment]
I have a similar issue, works on 7.1.17, but not on chart v9

Working config on 7.1.17
```
        - name: extraStartupArgs
          value: '-Dkc.hostname=https://skullkid.ddns.net -Dkc.hostname.path=/auth -Dkc.hostname.port=4443 -Dkc.proxy=edge'
        - name: proxyAddressForwarding
          value: 'true'
        - name: ingress.enabled
          value: 'true'
        - name: ingress.path
          value: '/auth'
        - name: service.type
          value: 'ClusterIP'
```

I also noted on Keycloak documentatio that theu changed the configs of Frontendforward, now it's hostname
https://www.keycloak.org/server/hostname

KC_HOSTNAME, KC_HOSTNAME_PORT, KC_HOSTNAME_PATH, etc are the new env vars needed when changing the domain **and subpath**

**Comment by tirelibirefe** [comment]
> use-forwarded-headers

@jack1902 you're the man!!!
I wasn't aware of "use-forwarded-headers" config of config.
It was point!
I checked the configmap, it wasn't enabled. I enabled it and booom!
Party time!

Thank you man! I am very appreciated.

**Comment by jack1902** [comment]
refer to https://github.com/bitnami/charts/issues/10236#issuecomment-1129075612

These are the settings I have, to ensure that inbound requests to `/auth/some/path/` and `/some/path` get treated as the same to the backend, so the backend only ever sees requests coming in as `/some/path` but in reality, some requests hitting `nginx` (the piece backing the ingress object) will see `/auth/some/path` and `/some/path`.

This `/auth` remapping is meant to be temporary to buy you time to update frontend applications to no longer use `/auth` in their requests to your keycloak instance. In reality, you shouldn't use `/auth` anywhere anymore but its a bit of hack to enable it to work like before but if keycloak change `/some/path` to become `/some/new/path` then older requests would be completely broken (this isn't the case right now but it becomes a ticking time bomb to check the keycloak changelogs on each release)

**Comment by tirelibirefe** [comment]
thank you @jack1902 it worked; I removed all /auth mappings and it works now.
