### ISSUE TITLE
use --set replicaCount=3 or -f values-production.yaml ,install zookeeper error.

### ISSUE THREAD

**Issue by liupeng0518** [bitnami/charts#1051]
**Which chart**:

zookeeper

**Description**

**Steps to reproduce the issue:**

```
helm install bitnami/zookeeper --set replicaCount=3
```

**Describe the results you received:**

```
ls /
2019-02-12 08:22:02,882 [myid:] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1029] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2019-02-12 08:22:02,883 [myid:] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@879] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2019-02-12 08:22:02,885 [myid:] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1162] - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1541)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1569)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:732)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:600)
	at org.apache.zookeeper.ZooKeeperMain.executeLine(ZooKeeperMain.java:372)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:332)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:291)

```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liupeng0518** [comment]
when i install 
```
helm install bitnami/zookeeper --set replicaCount=3
```
the same error.

thanks.

**Comment by tompizmor** [comment]
Hi!

I am not able to reproduce the issue with any of your commands. I only see the following transient error while all the nodes are being deployed:

```
java.net.UnknownHostException: zum-zookeeper-2.zum-zookeeper-headless.default.svc.cluster.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.Learner.connectToLeader(Learner.java:229)
	at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:72)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:981)
```

Can you let me know which version of the zookeeper chart are you trying to install? I tried with the latest one (`1.2.3`)

```
$ helm list
NAME        	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
bunking-flee	1       	Tue Feb 12 09:21:57 2019	DEPLOYED	zookeeper-1.2.3	3.4.13     	default
```
> You can run `$ helm repo update` in order to update the chart versions.

**Comment by liupeng0518** [comment]
I tried with the latest one (`1.2.3`) also.

```
[root@k8s-m1 ~]# helm list
NAME          	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
ringed-meerkat	1       	Tue Feb 12 18:04:21 2019	DEPLOYED	zookeeper-1.2.3	3.4.13     	default 
```

**Comment by liupeng0518** [comment]
What is the reason? Multiple images have this problem.

**Comment by liupeng0518** [comment]
When i deploy with okd cluster ,it`s ok. but deploy  with k8s cluster is error

verson:
```
[root@k8s-m1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@k8s-m1 ~]# uname -a
Linux k8s-m1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@k8s-m1 ~]# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
helm :
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
k8s:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a

```

**Comment by tompizmor** [comment]
It is strange. Can you let us know the specifics of the k8s cluster were the chart doesn't work? Is it running on GKE (google cloud), AKS (azure cloud), EKS (amazon cloud), bare metal, ...?

In the previous comment is not clear to me if the versions are for the OKD cluster or the other one.

Can you also check if there was any persistent volume that could have been reused? You can run `kubectl get pvc` to see the list of PVCs.

**Comment by liupeng0518** [comment]
bare metal.
K8S Cluster deployed in binary mode.
pvc just created
```
data-opining-bird-zookeeper-0                Bound     pvc-9135f977-39a1-11e9-83b0-525400c2f7ee   8Gi        RWO            nfs-dynamic-class   64s
data-opining-bird-zookeeper-1                Bound     pvc-9189b61e-39a1-11e9-83b0-525400c2f7ee   8Gi        RWO            nfs-dynamic-class   64s
data-opining-bird-zookeeper-2                Bound     pvc-9216a442-39a1-11e9-83b0-525400c2f7ee   8Gi        RWO            nfs-dynamic-class   63s
```

**Comment by tompizmor** [comment]
@liupeng0518 

I am afraid I don't know yet how to to reproduce it. I do have some questions that might help me to understand the scenario:

- Can you let me know the versions of your **bare metal cluster** (Sorry to insist, it is just that I don't if the previous version you shared where the bare-metal or the okd ones)
- Also, what does mean that the cluster has been deployed in binary mode?
- Does this issue also happen when only one zookeeper node?
- How many physical nodes have your cluster?
- Did you deploy 
https://github.com/helm/charts/blob/master/incubator/zookeeper with 1 or more nodes?

**Comment by liupeng0518** [comment]
@tompizmor 
- Use this project deployment： https://github.com/gjmzj/kubeasz 
- kubernetes v1.12
- one zookeeper node not happen
- 3 master(node)
-  deploy
https://github.com/helm/charts/blob/master/incubator/zookeeper  more nodes

**Comment by tompizmor** [comment]
I am able to reproduce the error only when not all the zookeeper pods are ready. For example, in the following state:

```
$ k get pods -w -l "app=zookeeper"
NAME              READY   STATUS    RESTARTS   AGE
zoo-zookeeper-0   1/1     Running   0          9m56s
zoo-zookeeper-1   0/1     Running   0          9s
zoo-zookeeper-2   0/1     Running   0          9s
```

Did you check that all your zookeeper nodes were 1/1 ready before executing the `ls /` command in one of them?

**Comment by liupeng0518** [comment]
> I am able to reproduce the error only when not all the zookeeper pods are ready. For example, in the following state:
> 
> ```
> $ k get pods -w -l "app=zookeeper"
> NAME              READY   STATUS    RESTARTS   AGE
> zoo-zookeeper-0   1/1     Running   0          9m56s
> zoo-zookeeper-1   0/1     Running   0          9s
> zoo-zookeeper-2   0/1     Running   0          9s
> ```
> Did you check that all your zookeeper nodes were 1/1 ready before executing the `ls /` command in one of them?
```
[root@k8s01 percona-xtradb-cluster]# kubectl get pod -owide
NAME                             READY   STATUS            RESTARTS   AGE     IP            NODE              NOMINATED NODE
local-volume-provisioner-55ckt   1/1     Running           4          2d22h   172.20.2.25   192.168.122.234   <none>
local-volume-provisioner-9f9jp   1/1     Running           5          2d22h   172.20.0.19   192.168.122.252   <none>
local-volume-provisioner-bbwsr   1/1     Running           4          2d22h   172.20.1.45   192.168.122.27    <none>
unhinged-nightingale-pxc-0       0/2     PodInitializing   0          18m     172.20.2.29   192.168.122.234   <none>
womping-toucan-zookeeper-0       1/1     Running           0          10h     172.20.2.28   192.168.122.234   <none>
womping-toucan-zookeeper-1       1/1     Running           1          10h     172.20.0.17   192.168.122.252   <none>
womping-toucan-zookeeper-2       1/1     Running           0          10h     172.20.1.50   192.168.122.27    <none>
```
It`s all 1/1
But it is not ok~
```
[root@k8s01 percona-xtradb-cluster]# kubectl exec -it womping-toucan-zookeeper-2 -- sh
$ zkServer.sh status
ZooKeeper JMX enabled by default
Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
Error contacting service. It is probably not running.

```
with flannel and coredns

**Comment by tompizmor** [comment]
Can you run the following command on each zookeeper pod?

- To check the zookeeper service is actually running:

```
kubectl exec -it YOUR_ZOOKEEPER_POD_X -- cat /opt/bitnami/zookeeper/data/myid
```

```
kubectl exec -it YOUR_ZOOKEEPER_POD_X -- ps aux
```

- To check zookeeper ensemble configuration:

```
kubectl exec -it YOUR_ZOOKEEPER_POD_X -- cat /opt/bitnami/zookeeper/conf/zoo.cfg
```
