### ISSUE TITLE
Getting error while enabling X-PACK on Elasticsearch 

### ISSUE THREAD

**Issue by prashantmishraorahi** [bitnami/charts#10870]
### Name and Version

bitnami/elasticsearch-15.10.5

### What steps will reproduce the bug?

Just adding `xpack.security.enabled: True`
in extraConfig parameter of values.yaml

### Are you using any custom parameters or values?

xpack.security.enabled: True

### What is the expected behavior?

Pods in running state, and to create password required for different set of users.

### What do you see instead?

Issue: Pods are in Crashloopbackoff state with the below logs
```
[2022-06-24T08:15:37,494][INFO ][o.e.x.s.a.s.FileRolesStore] [elasticsearch-master-2] parsed [0] roles from file [/opt/bitnami/elasticsearch/config/roles.yml]
[2022-06-24T08:15:38,882][INFO ][o.e.i.g.LocalDatabases   ] [elasticsearch-master-2] initialized default databases [[GeoLite2-Country.mmdb, GeoLite2-City.mmdb, GeoLite2-ASN.mmdb]], config databases [[]] and watching [/opt/bitnami/elasticsearch/config/ingest-geoip] for changes
[2022-06-24T08:15:38,884][INFO ][o.e.i.g.DatabaseRegistry ] [elasticsearch-master-2] initialized database registry, using geoip-databases directory [/tmp/elasticsearch-7948679639126692014/geoip-databases/TSUMIl08SBeA-W4xAaqo4A]
[2022-06-24T08:15:39,688][INFO ][o.e.t.NettyAllocator     ] [elasticsearch-master-2] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=false, g1gc_region_size=0b, heap_size=495.3mb}]
[2022-06-24T08:15:39,790][INFO ][o.e.d.DiscoveryModule    ] [elasticsearch-master-2] using discovery type [zen] and seed hosts providers [settings]
[2022-06-24T08:15:40,418][INFO ][o.e.g.DanglingIndicesState] [elasticsearch-master-2] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
[2022-06-24T08:15:40,997][INFO ][o.e.n.Node               ] [elasticsearch-master-2] initialized
[2022-06-24T08:15:40,997][INFO ][o.e.n.Node               ] [elasticsearch-master-2] starting ...
[2022-06-24T08:15:41,136][INFO ][o.e.t.TransportService   ] [elasticsearch-master-2] publish_address {X.X.X.X:9300}, bound_addresses {0.0.0.0:9300}
[2022-06-24T08:15:41,481][INFO ][o.e.b.BootstrapChecks    ] [elasticsearch-master-2] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.
bootstrap check failure [1] of [1]: Transport SSL must be enabled if security is enabled on a [basic] license. Please set [xpack.security.transport.ssl.enabled] to [true] or disable security by setting [xpack.security.enabled] to [false]
ERROR: Elasticsearch did not exit normally - check the logs at /opt/bitnami/elasticsearch/logs/elastic.log
[2022-06-24T08:15:41,529][INFO ][o.e.n.Node               ] [elasticsearch-master-2] stopping ...
[2022-06-24T08:15:41,565][INFO ][o.e.n.Node               ] [elasticsearch-master-2] stopped
[2022-06-24T08:15:41,566][INFO ][o.e.n.Node               ] [elasticsearch-master-2] closing ...
[2022-06-24T08:15:41,580][INFO ][o.e.n.Node               ] [elasticsearch-master-2] closed
```

**Comment by prashantmishraorahi** [comment]
After this error I tried enabling **[ xpack.security.transport.ssl.enabled ]**  as mentioned in above logs

**But got another error:**

[2022-06-24T08:03:10,614][WARN ][o.e.t.TcpTransport       ] [elasticsearch-master-0] exception caught on transport layer [Netty4TcpChannel{localAddress=0.0.0.0/0.0.0.0:9300, remoteAddress=/x.x.x.x:52464, profile=default}], closing connection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: No available authentication scheme
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by iammishraprashant** [comment]
@FraPazGal If there is any documentation available for the same?

**Comment by FraPazGal** [comment]
Hello @iammishraprashant,

I'm not sure which documentation you are referring to. You can check the chart's [README](https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/README.md) to access the available config params and each of their descriptions. If you are looking for the instructions prompted at installation time, you can find them in the chart's [NOTES.txt](https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/NOTES.txt).
