### ISSUE TITLE
AccessDenied Exception on upgrading helm chart

### ISSUE THREAD

**Issue by Aadarsh-Verma** [bitnami/charts#11061]
### Name and Version

bitnami/solr 5.0.0

### What steps will reproduce the bug?

helm upgrade the chart and disable auth or disable metrics that were enabled while installing the chart.
Basically upgrading the chart while changing some parameters is not working.

### Are you using any custom parameters or values?
```yaml
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: manual

image:
  registry: docker.io
  repository: bitnami/solr
  tag: 8.11.1-debian-10-r146
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

auth:
  enabled: false
#  existingSecret: solrsecret
#  existingSecretPasswordKey: "solr-password"

replicaCount: 3

#resources:
#  limits:
#    cpu: 600m
#    memory: 1Gi
#  requests:
#    cpu: 200m
#    memory: 300Mi

podSecurityContext:
  enabled: true
  fsGroup: 0

containerSecurityContext:
  enabled: true
  runAsUser: 0
  runAsNonRoot: false

nodeAffinityPreset:
  type: hard
  key: 99app
  values:
    - statefulapp
 
service:
  type: NodePort
  nodePorts:
    http: 32110

persistence:
  enabled: true
  storageClass: manual
  accessModes:
    - ReadWriteOnce
  size: 3Gi
  mountPath: /bitnami/solr
  selector:
    matchLabels:
      app: solr

volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r430
    pullPolicy: IfNotPresent
    pullSecrets: []

#metrics:
#  containerSecurityContext:
#    enabled: true
#    runAsUser: 0
#    runAsNonRoot: false
#  podSecurityContext:
#    enabled: true
#    fsGroup: 0

zookeeper:
  volumePermissions:
    enabled: true
  enabled: true
  networkPolicy:
    enabled: true
  service:
    type: NodePort
    nodePorts:
      client: 30015
  containerPorts:
    client: 2181
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: manual
    accessModes:
      - ReadWriteOnce
    size: 3Gi
    selector:
      matchLabels:
        app: zookeeper
  podSecurityContext:
    enabled: true
    fsGroup: 0
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsNonRoot: false
  nodeAffinityPreset:
    type: hard
    key: 99app
    values:
      - statefulapp
```

### What is the expected behavior?

The upgrade should work fine

### What do you see instead?
```
solr 10:15:08.64
solr 10:15:08.64 Welcome to the Bitnami solr container
solr 10:15:08.65 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr 10:15:08.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr 10:15:08.65
solr 10:15:08.65 INFO ==> ** Starting solr setup **
solr 10:15:08.67 INFO ==> Validating settings in SOLR_* env vars...
solr 10:15:08.67 INFO ==> Initializing Solr ...
solr 10:15:08.68 INFO ==> Configuring file permissions for Solr
solr 10:15:08.68 INFO ==> Deploying Solr Cloud from scratch
solr 10:15:08.68 INFO ==> Waiting for Zookeeper to be up
solr 10:15:08.69 INFO ==> Waiting for solr root in zookeeper
solr 10:16:21.14 ERROR ==> Failed to connect to the zookeeper
(base) fa059037@aadarsh-ubuntu:~/Documents/rough$ kk logs -f solr-2
solr 10:47:55.31
solr 10:47:55.31 Welcome to the Bitnami solr container
solr 10:47:55.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr 10:47:55.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr 10:47:55.32
solr 10:47:55.32 INFO ==> ** Starting solr setup **
solr 10:47:55.34 INFO ==> Validating settings in SOLR_* env vars...
solr 10:47:55.34 INFO ==> Initializing Solr ...
solr 10:47:55.35 INFO ==> Restoring persisted Solr installation
solr 10:47:55.36 INFO ==> ** solr setup finished! **

solr 10:47:55.38 INFO ==> ** Starting solr **
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
2022-07-06 10:47:57.510 INFO (main) [ ] o.e.j.u.log Logging initialized @2032ms to org.eclipse.jetty.util.log.Slf4jLog
2022-07-06 10:47:58.098 INFO (main) [ ] o.e.j.s.Server jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 1.8.0_332-b09
2022-07-06 10:47:58.173 INFO (main) [ ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///opt/bitnami/solr/server/contexts/] at interval 0
2022-07-06 10:47:58.753 INFO (main) [ ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
2022-07-06 10:47:58.766 INFO (main) [ ] o.e.j.s.session DefaultSessionIdManager workerName=node0
2022-07-06 10:47:58.766 INFO (main) [ ] o.e.j.s.session No SessionScavenger set, using defaults
2022-07-06 10:47:58.768 INFO (main) [ ] o.e.j.s.session node0 Scavenging every 600000ms
2022-07-06 10:47:58.834 INFO (main) [ ] o.a.s.s.SolrDispatchFilter Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
2022-07-06 10:47:58.850 INFO (main) [ ] o.a.s.s.SolrDispatchFilter ___ _ Welcome to Apache Solr? version 8.11.1
2022-07-06 10:47:58.851 INFO (main) [ ] o.a.s.s.SolrDispatchFilter / | | | _ Starting in cloud mode on port 8983
2022-07-06 10:47:58.851 INFO (main) [ ] o.a.s.s.SolrDispatchFilter _ / _ \ | '| Install dir: /opt/bitnami/solr
2022-07-06 10:47:58.852 INFO (main) [ ] o.a.s.s.SolrDispatchFilter |/__/|| Start time: 2022-07-06T10:47:58.852Z
2022-07-06 10:47:58.860 INFO (main) [ ] o.a.s.c.SolrPaths Using system property solr.solr.home: /opt/bitnami/solr/server/solr
2022-07-06 10:47:58.921 INFO (main) [ ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2022-07-06 10:47:58.951 INFO (zkConnectionManagerCallback-2-thread-1) [ ] o.a.s.c.c.ConnectionManager zkClient has connected
2022-07-06 10:47:58.951 INFO (main) [ ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2022-07-06 10:47:59.061 INFO (main) [ ] o.a.s.s.SolrDispatchFilter Loading solr.xml from SolrHome (not found in ZooKeeper)
2022-07-06 10:47:59.062 INFO (main) [ ] o.a.s.c.SolrXmlConfig Loading container configuration from /opt/bitnami/solr/server/solr/solr.xml
2022-07-06 10:47:59.134 INFO (main) [ ] o.a.s.c.SolrXmlConfig MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@49d904ec, but no JMX reporters were configured - adding default JMX reporter.
2022-07-06 10:47:59.683 INFO (main) [ ] o.a.s.h.c.HttpShardHandlerFactory Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
2022-07-06 10:47:59.826 WARN (main) [ ] o.e.j.u.s.S.config Trusting all certificates configured for Client@6865c751[provider=null,keyStore=null,trustStore=null]
2022-07-06 10:47:59.827 WARN (main) [ ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@6865c751[provider=null,keyStore=null,trustStore=null]
2022-07-06 10:47:59.963 WARN (main) [ ] o.e.j.u.s.S.config Trusting all certificates configured for Client@8ab78bc[provider=null,keyStore=null,trustStore=null]
2022-07-06 10:47:59.963 WARN (main) [ ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@8ab78bc[provider=null,keyStore=null,trustStore=null]
2022-07-06 10:48:00.004 INFO (main) [ ] o.a.s.c.ZkContainer Zookeeper client=solr-zookeeper:2181/solr
2022-07-06 10:48:00.018 INFO (main) [ ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2022-07-06 10:48:00.025 INFO (zkConnectionManagerCallback-13-thread-1) [ ] o.a.s.c.c.ConnectionManager zkClient has connected
2022-07-06 10:48:00.025 INFO (main) [ ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2022-07-06 10:48:00.140 INFO (main) [ ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2022-07-06 10:48:00.142 INFO (zkConnectionManagerCallback-15-thread-1) [ ] o.a.s.c.c.ConnectionManager zkClient has connected
2022-07-06 10:48:00.142 INFO (main) [ ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2022-07-06 10:48:00.171 WARN (main) [ ] o.a.s.c.ZkController Contents of zookeeper /security.json are world-readable; consider setting up ACLs as described in https://solr.apache.org/guide/zookeeper-access-control.html
2022-07-06 10:48:00.183 INFO (main) [ ] o.a.s.c.c.ZkStateReader Updated live nodes from ZooKeeper... (0) -> (3)
2022-07-06 10:48:23.308 INFO (zkCallback-14-thread-2) [ ] o.a.s.c.c.ZkStateReader Updated live nodes from ZooKeeper... (3) -> (2)
2022-07-06 10:48:23.318 INFO (main) [ ] o.a.s.c.ZkController Publish node=solr-2.solr-headless.default.svc.cluster.local:8983_solr as DOWN
2022-07-06 10:48:23.328 INFO (main) [ ] o.a.s.c.TransientSolrCoreCacheDefault Allocating transient core cache for max 2147483647 cores with initial capacity of 1024
2022-07-06 10:48:23.344 INFO (main) [ ] o.a.s.c.ZkController Register node as live in ZooKeeper:/live_nodes/solr-2.solr-headless.default.svc.cluster.local:8983_solr
2022-07-06 10:48:23.354 INFO (zkCallback-14-thread-2) [ ] o.a.s.c.c.ZkStateReader Updated live nodes from ZooKeeper... (2) -> (3)
2022-07-06 10:48:23.399 INFO (main) [ ] o.a.s.p.PackageLoader /packages.json updated to version -1
2022-07-06 10:48:23.418 INFO (main) [ ] o.a.s.c.CoreContainer Initializing authorization plugin: solr.RuleBasedAuthorizationPlugin
2022-07-06 10:48:23.431 INFO (main) [ ] o.a.s.c.CoreContainer Initializing authentication plugin: solr.BasicAuthPlugin
2022-07-06 10:48:23.440 WARN (main) [ ] o.a.s.c.CoreContainer Solr authentication is enabled, but SSL is off. Consider enabling SSL to protect user credentials and data with encryption.
2022-07-06 10:48:23.667 INFO (main) [ ] o.a.s.h.a.MetricsHistoryHandler No .system collection, keeping metrics history in memory.
2022-07-06 10:48:23.735 INFO (main) [ ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@49d904ec
2022-07-06 10:48:23.735 INFO (main) [ ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@49d904ec
2022-07-06 10:48:23.736 INFO (main) [ ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@49d904ec
2022-07-06 10:48:23.772 INFO (main) [ ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /opt/bitnami/solr/server/solr
2022-07-06 10:48:23.772 INFO (main) [ ] o.a.s.c.CorePropertiesLocator Cores are: [my-collection_shard1_replica_n2]
2022-07-06 10:48:23.839 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.c.SolrConfig Using Lucene MatchVersion: 8.11.1
2022-07-06 10:48:23.861 INFO (main) [ ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@1972e513{/solr,file:///opt/bitnami/solr/server/solr-webapp/webapp/,AVAILABLE}{/opt/bitnami/solr/server/solr-webapp/webapp}
2022-07-06 10:48:23.875 INFO (main) [ ] o.e.j.s.AbstractConnector Started ServerConnector@53ce1329{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8983}
2022-07-06 10:48:23.876 INFO (main) [ ] o.e.j.s.Server Started @28401ms
2022-07-06 10:48:23.879 WARN (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.c.SolrConfig solrconfig.xml: is no longer supported, use solr.xml:/metrics/reporter section instead
2022-07-06 10:48:23.936 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.s.IndexSchema Schema name=default-config
2022-07-06 10:48:24.484 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.s.IndexSchema Loaded schema default-config/1.6 with uniqueid field id
2022-07-06 10:48:24.611 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [c:my-collection s:shard1 r:core_node4 x:my-collection_shard1_replica_n2] o.a.s.c.SolrConfig Using Lucene MatchVersion: 8.11.1
2022-07-06 10:48:24.612 WARN (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [c:my-collection s:shard1 r:core_node4 x:my-collection_shard1_replica_n2] o.a.s.c.SolrConfig solrconfig.xml: is no longer supported, use solr.xml:/metrics/reporter section instead
2022-07-06 10:48:24.617 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [c:my-collection s:shard1 r:core_node4 x:my-collection_shard1_replica_n2] o.a.s.s.IndexSchema Schema name=default-config
2022-07-06 10:48:24.728 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [c:my-collection s:shard1 r:core_node4 x:my-collection_shard1_replica_n2] o.a.s.s.IndexSchema Loaded schema default-config/1.6 with uniqueid field id
2022-07-06 10:48:24.808 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [c:my-collection s:shard1 r:core_node4 x:my-collection_shard1_replica_n2] o.a.s.c.CoreContainer Creating SolrCore 'my-collection_shard1_replica_n2' using configuration from configset my-collection.AUTOCREATED, trusted=true
2022-07-06 10:48:24.843 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [c:my-collection s:shard1 r:core_node4 x:my-collection_shard1_replica_n2] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.core.my-collection.shard1.replica_n2' (registry 'solr.core.my-collection.shard1.replica_n2') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@49d904ec
2022-07-06 10:48:24.852 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [c:my-collection s:shard1 r:core_node4 x:my-collection_shard1_replica_n2] o.a.s.c.SolrCore [[my-collection_shard1_replica_n2] ] Opening new SolrCore at [/opt/bitnami/solr/server/solr/my-collection_shard1_replica_n2], dataDir=[/opt/bitnami/solr/server/solr/my-collection_shard1_replica_n2/data/]
2022-07-06 10:48:24.921 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.c.SolrCore [my-collection_shard1_replica_n2] CLOSING SolrCore org.apache.solr.core.SolrCore@ef94909
2022-07-06 10:48:24.921 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.m.SolrMetricManager Closing metric reporters for registry=solr.core.my-collection.shard1.replica_n2 tag=SolrCore@ef94909
2022-07-06 10:48:24.921 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.m.r.SolrJmxReporter Closing reporter [org.apache.solr.metrics.reporters.SolrJmxReporter@a0322fc: rootName = null, domain = solr.core.my-collection.shard1.replica_n2, service url = null, agent id = null] for registry solr.core.my-collection.shard1.replica_n2/com.codahale.metrics.MetricRegistry@8d4945d
2022-07-06 10:48:24.937 INFO (coreLoadExecutor-23-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.m.SolrMetricManager Closing metric reporters for registry=solr.collection.my-collection.shard1.leader tag=SolrCore@ef94909
2022-07-06 10:48:24.950 ERROR (coreContainerWorkExecutor-4-thread-1-processing-n:solr-2.solr-headless.default.svc.cluster.local:8983_solr) [ ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup => java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [my-collection_shard1_replica_n2]
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [my-collection_shard1_replica_n2]
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_332]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_332]
at org.apache.solr.core.CoreContainer.lambda$load$12(CoreContainer.java:902) ~[?:?]
at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) ~[metrics-core-4.1.5.jar:4.1.5]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:218) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: org.apache.solr.common.SolrException: Unable to create core [my-collection_shard1_replica_n2]
at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1473) ~[?:?]
at org.apache.solr.core.CoreContainer.lambda$load$11(CoreContainer.java:873) ~[?:?]
at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.5.jar:4.1.5]
... 5 more
Caused by: org.apache.solr.common.SolrException: /bitnami/solr/server/solr/my-collection_shard1_replica_n2/data/index/write.lock
at org.apache.solr.core.SolrCore.(SolrCore.java:1086) ~[?:?]
at org.apache.solr.core.SolrCore.(SolrCore.java:921) ~[?:?]
at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1452) ~[?:?]
at org.apache.solr.core.CoreContainer.lambda$load$11(CoreContainer.java:873) ~[?:?]
at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.5.jar:4.1.5]
... 5 more
Caused by: java.nio.file.AccessDeniedException: /bitnami/solr/server/solr/my-collection_shard1_replica_n2/data/index/write.lock
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_332]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_332]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_332]
at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177) ~[?:1.8.0_332]
at java.nio.channels.FileChannel.open(FileChannel.java:287) ~[?:1.8.0_332]
at java.nio.channels.FileChannel.open(FileChannel.java:335) ~[?:1.8.0_332]
at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:125) ~[?:?]
at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[?:?]
at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[?:?]
at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:105) ~[?:?]
at org.apache.solr.core.SolrCore.isWriterLocked(SolrCore.java:773) ~[?:?]
at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:794) ~[?:?]
at org.apache.solr.core.SolrCore.(SolrCore.java:1003) ~[?:?]
at org.apache.solr.core.SolrCore.(SolrCore.java:921) ~[?:?]
at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1452) ~[?:?]
at org.apache.solr.core.CoreContainer.lambda$load$11(CoreContainer.java:873) ~[?:?]
at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.5.jar:4.1.5]
... 5 more
2022-07-06 10:48:51.993 INFO (qtp576020159-18) [ ] o.a.s.s.PKIAuthenticationPlugin New Key obtained from node: solr-1.solr-headless.default.svc.cluster.local:8983_solr / MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwoXtqXnOQSV5eyUYBTA/RrPsi1lE+/QGEOjyASlIvuFCqmzdDDz4OV6OY2OFBpQl/sr9JYzEmLFhL4ff75b9B19zMqh6mx9Zh+EishhQR7Cg9C7HkFbB6z1KEDnf9v2M+Dw/drJosR1R2nsijZpELMeCGbc4XC2n3SEUuOE3j73wDSYrtWc2RwVRLCj/po365UxJtvUNbT21+qTT4jDWd3mAYZ1r/p9fVwgYrC9U4wExqD8RxvJ4XpJsleyICeqi4iB32SxSsk3i7W4iqZ+JBU4X8HCciJoXOoU6APUqCGN7WBgZW0PbsOShe2FDSZdGqCq5VZ0rREHjbfpC/1khyQIDAQAB
```
### Additional information

I have tried elevating the permissions of the data directory

**Comment by Aadarsh-Verma** [comment]
same version I am trying to change some parameters

**Comment by javsalgar** [comment]
Do you have some minimal values that trigger the issue?
