### ISSUE TITLE
Got error produce response with correlation id 59 on topic-partition p4changes_EXTRACT-0, retrying (9 attempts left). Error: NETWORK_EXCEPTION

### ISSUE THREAD

**Issue by bipinanghanvmware** [bitnami/charts#11163]
### Name and Version

kafka-18.0.0

### What steps will reproduce the bug?

i have deployed kafka with 3 broker but i am facing below error 
```
2022-07-13 13:30:30.803  WARN 20594 --- [ad | producer-1] o.a.k.clients.producer.internals.Sender  : [Producer clientId=producer-1] Got error produce response with correlation id 59 on topic-partition p4changes_EXTRACT-0, retrying (9 attempts left). Error: NETWORK_EXCEPTION
2022-07-13 13:30:30.803  WARN 20594 --- [ad | producer-1] o.a.k.clients.producer.internals.Sender  : [Producer clientId=producer-1] Received invalid metadata error in produce request on partition p4changes_EXTRACT-0 due to org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received.. Going to request metadata update now
2022-07-13 13:30:58.294  INFO 20594 --- [thread | p4cgrp] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-p4cgrp-1, groupId=p4cgrp] Group coordinator vps-kafka-scad-app-0-external-ara-scad-kafka-stage.ara.decc.vmware.com:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery
2022-07-13 13:30:58.294  INFO 20594 --- [thread | p4cgrp] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-p4cgrp-2, groupId=p4cgrp] Group coordinator vps-kafka-scad-app-0-external-ara-scad-kafka-stage.ara.decc.vmware.com:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery
2022-07-13 13:30:58.296  INFO 20594 --- [thread | p4cgrp] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-p4cgrp-3, groupId=p4cgrp] Group coordinator vps-kafka-scad-app-0-external-ara-scad-kafka-stage.ara.decc.vmware.com:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery
2022-07-13 13:31:02.692  INFO 20594 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-p4cgrp-2, groupId=p4cgrp] Discovered group coordinator vps-kafka-scad-app-0-external-ara-scad-kafka-stage.ara.decc.vmware.com:9092 (id: 2147483647 rack: null)
2022-07-13 13:31:02.692  INFO 20594 --- [ntainer#1-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-p4cgrp-3, groupId=p4cgrp] Discovered group coordinator vps-kafka-scad-app-0-external-ara-scad-kafka-stage.ara.decc.vmware.com:9092 (id: 2147483647 rack: null)
2022-07-13 13:31:03.311  INFO 20594 --- [ntainer#2-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-p4cgrp-1, groupId=p4cgrp] Discovered group coordinator vps-kafka-scad-app-0-external-ara-scad-kafka-stage.ara.decc.vmware.com:9092 (id: 2147483647 rack: null)


2022-07-13 13:33:53.154 ERROR 20594 --- [nio-8080-exec-1] c.v.s.p.e.PerforceBulkIngester           : ES Bulk Insert error for Index: p4python-
com.vmware.scad.perforce.elasticsearch.ESIngestException: ES Bulk Insert error for Index: p4python-
	at com.vmware.scad.perforce.elasticsearch.PerforceBulkIngester.changeLogIngest(PerforceBulkIngester.java:140)
	at com.vmware.scad.perforce.controller.TestController.p4Ingest(TestController.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.perforce.p4java.exception.ConnectionException: java.net.SocketTimeoutException: Read timed out
	at com.perforce.p4java.impl.mapbased.rpc.packet.RpcPacketDispatcher.dispatch(RpcPacketDispatcher.java:225)
	at com.perforce.p4java.impl.mapbased.rpc.OneShotServerImpl.execMapCmdList(OneShotServerImpl.java:363)
	at com.perforce.p4java.impl.mapbased.rpc.OneShotServerImpl.execMapCmd(OneShotServerImpl.java:292)
	at com.perforce.p4java.impl.mapbased.rpc.OneShotServerImpl.execMapCmd(OneShotServerImpl.java:194)
	at com.vmware.scad.perforce.elasticsearch.PerforceBulkIngester.changeLogIngest(PerforceBulkIngester.java:119)
	... 51 more
Caused by: com.perforce.p4java.exception.ConnectionException: java.net.SocketTimeoutException: Read timed out
	at com.perforce.p4java.common.base.P4JavaExceptions.throwConnectionException(P4JavaExceptions.java:49)
	at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:451)
	at com.perforce.p4java.impl.mapbased.rpc.packet.RpcPacketDispatcher.dispatch(RpcPacketDispatcher.java:127)
	... 55 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at com.perforce.p4java.impl.mapbased.rpc.stream.RpcSocketInputStream.read(RpcSocketInputStream.java:101)
	at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.continueReadIfIncompleteRead(RpcStreamConnection.java:494)
	at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:439)
	... 56 more




********************
After this not able to send message.


Producer Configuration as below :

  Map<String, Object> props = new HashMap<>();
         Map<String, Object> props = new HashMap<>();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, kafkaServerUrl);
        props.put(ConsumerConfig.GROUP_ID_CONFIG, p4changeLogGroupId);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        props.put("acks", "all");
        props.put("retries", "10");
        props.put("linger.ms",0);
        props.put("buffer.memory",10240000);
        props.put("max.request.size", 1024000);
        //TODO:: Single object Serialize keep as ref
        //props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, ChangeLogDeserializer.class.getName());
        //return new DefaultKafkaConsumerFactory<>(props);

        //TODO: List of Object serialize keep as ref
        ObjectMapper om = new ObjectMapper();
        JavaType type = om.getTypeFactory().constructParametricType(List.class, ChangeLog.class);
    new DefaultKafkaConsumerFactory<>(props,new StringDeserializer(), new JsonDeserializer<List<ChangeLog>>(type, om, false));

### Are you using any custom parameters or values?

Yes that all parameter i have defined as above

### What is the expected behavior?

It should send continuously without giving any error 

### What do you see instead?

getting error as mentioned above

### Additional information

NA

**Comment by javsalgar** [comment]
Hi,

It seems that there was some sort of networking error. Did you try debugging the networking issues in the cluster?

**Comment by bipinanghanvmware** [comment]
Hi @javsalgar  
 Any update what we can do to?

**Comment by fmulero** [comment]
Hi @bipinanghanvmware 

Could you provide the following information?:
* The values used to install the chart
* The logs you shared, are from you client? a producer or consumer trying to connect to the new cluster?
* Is it in kubernetes or outside (for example in your local machine)?
* Run the following command to know if all brokers are connected (you should see the list of ids at the end [0], [1] and [2]):
```
kubectl exec -it sts/<release-name>-zookeeper -- zkCli.sh ls /brokers/ids
```

**Comment by bipinanghanvmware** [comment]
HI @fmulero 

values.yaml
```
global:
  storageClass: 5dd10995558841809e9ffbecd89c0291

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 3Gi

#this is for producer and consumer spacific.
autoCreateTopicsEnable: true
deleteTopicEnable: true
# maxMessageBytes: 1000012
#heapOpts: -Xmx1024m -Xms1024m

replicaCount: 3
#10 node - 1 msg and at least send to 2 leader and then after acknoledge
#transactionStateLogMinIsr: 2

maxMessageBytes: _10000012
##########
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    ports:
      external: 9092
    #loadBalancerIPs: ['10.168.1.30','10.168.0.246','10.168.0.73']
    loadBalancerNames: [ 'vps-kafka-scad-app-0-external-ara-scad-kafka-stage.ara.decc.vmware.com','vps-kafka-scad-app-1-external-ara-scad-kafka-stage.ara.decc.vmware.com','vps-kafka-scad-app-2-external-ara-scad-kafka-stage.ara.decc.vmware.com']

zookeeper:
  resources:
    limits:
      cpu: 2
      memory: 3Gi
    requests:
      cpu: 2
      memory: 1Gi
#  replicaCount: 1

livenessProbe:
  initialDelaySeconds: 120
readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10


Yes logs are from client side from producer side.

yes it is kubenetes 


output of commad :
```
bipina@bipina-a01 kafka % kubectl exec -it pod/vps-kafka-scad-app-zookeeper-0 -- zkCli.sh ls /brokers/ids~
/opt/bitnami/java/bin/java
Connecting to localhost:2181
2022-07-18 08:32:57,254 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:zookeeper.version=3.8.0-5a02a05eddb59aee6ac762f7ea82e92a68eb9c0f, built on 2022-02-25 08:49 UTC
2022-07-18 08:32:57,257 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:host.name=vps-kafka-scad-app-zookeeper-0.vps-kafka-scad-app-zookeeper-headless.ara-scad-kafka-stage.svc.cluster.local
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:java.version=11.0.15
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:java.vendor=BellSoft
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:java.home=/opt/bitnami/java
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:java.class.path=/opt/bitnami/zookeeper/bin/../zookeeper-server/target/classes:/opt/bitnami/zookeeper/bin/../build/classes:/opt/bitnami/zookeeper/bin/../zookeeper-server/target/lib/*.jar:/opt/bitnami/zookeeper/bin/../build/lib/*.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-prometheus-metrics-3.8.0.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-jute-3.8.0.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-3.8.0.jar:/opt/bitnami/zookeeper/bin/../lib/snappy-java-1.1.7.7.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-api-1.7.30.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_servlet-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_hotspot-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_common-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-unix-common-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-epoll-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-classes-epoll-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-tcnative-classes-2.0.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-tcnative-2.0.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-resolver-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-handler-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-common-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-codec-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-buffer-4.1.73.Final.jar:/opt/bitnami/zookeeper/bin/../lib/metrics-core-4.1.12.1.jar:/opt/bitnami/zookeeper/bin/../lib/logback-core-1.2.10.jar:/opt/bitnami/zookeeper/bin/../lib/logback-classic-1.2.10.jar:/opt/bitnami/zookeeper/bin/../lib/jline-2.14.6.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-ajax-9.4.43.v20210629.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-9.4.43.v20210629.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-servlet-9.4.43.v20210629.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-server-9.4.43.v20210629.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-security-9.4.43.v20210629.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-io-9.4.43.v20210629.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-http-9.4.43.v20210629.jar:/opt/bitnami/zookeeper/bin/../lib/javax.servlet-api-3.1.0.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-databind-2.13.1.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-core-2.13.1.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-annotations-2.13.1.jar:/opt/bitnami/zookeeper/bin/../lib/commons-io-2.11.0.jar:/opt/bitnami/zookeeper/bin/../lib/commons-cli-1.4.jar:/opt/bitnami/zookeeper/bin/../lib/audience-annotations-0.12.0.jar:/opt/bitnami/zookeeper/bin/../zookeeper-*.jar:/opt/bitnami/zookeeper/bin/../zookeeper-server/src/main/resources/lib/*.jar:/opt/bitnami/zookeeper/bin/../conf:
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:java.io.tmpdir=/tmp
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:java.compiler=<NA>
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:os.name=Linux
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:os.arch=amd64
2022-07-18 08:32:57,258 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:os.version=5.4.0-62-generic
2022-07-18 08:32:57,259 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:user.name=?
2022-07-18 08:32:57,259 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:user.home=?
2022-07-18 08:32:57,259 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:user.dir=/
2022-07-18 08:32:57,259 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:os.memory.free=1013MB
2022-07-18 08:32:57,259 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:os.memory.max=1024MB
2022-07-18 08:32:57,259 [myid:] - INFO  [main:o.a.z.Environment@98] - Client environment:os.memory.total=1024MB
2022-07-18 08:32:57,263 [myid:] - INFO  [main:o.a.z.ZooKeeper@637] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@2b662a77
2022-07-18 08:32:57,275 [myid:] - INFO  [main:o.a.z.c.X509Util@77] - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2022-07-18 08:32:57,288 [myid:] - INFO  [main:o.a.z.ClientCnxnSocket@239] - jute.maxbuffer value is 1048575 Bytes
2022-07-18 08:32:57,306 [myid:] - INFO  [main:o.a.z.ClientCnxn@1732] - zookeeper.request.timeout value is 0. feature enabled=false
2022-07-18 08:32:57,321 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):o.a.z.ClientCnxn$SendThread@1171] - Opening socket connection to server localhost/127.0.0.1:2181.
2022-07-18 08:32:57,322 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):o.a.z.ClientCnxn$SendThread@1173] - SASL config status: Will not attempt to authenticate using SASL (unknown error)
2022-07-18 08:32:57,344 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):o.a.z.ClientCnxn$SendThread@1005] - Socket connection established, initiating session, client: /127.0.0.1:46716, server: localhost/127.0.0.1:2181
2022-07-18 08:32:57,368 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):o.a.z.ClientCnxn$SendThread@1444] - Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x109d4efedef0007, negotiated timeout = 30000

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
Node does not exist: /brokers/ids~
2022-07-18 08:32:57,379 [myid:] - ERROR [main:o.a.z.u.ServiceUtils@42] - Exiting JVM with code 1
command terminated with exit code 1
bipina@bipina-a01 kafka %

**Comment by bipinanghanvmware** [comment]
@OneCricketeer  : already executed but facing same issue.....

**Comment by OneCricketeer** [comment]
Based on what was copied, you ran the command with an extra character

Please use `kubectl exec -it pod/vps-kafka-scad-app-zookeeper-0 -- zkCli.sh ls /brokers/ids` directly 

Note that the output will help us diagnose the problem, not solve the error.
