### ISSUE TITLE
setting ssl.endpoint.identification.algorithm for Kafka Docker image/Helm chart

### ISSUE THREAD

**Issue by antimack** [bitnami/charts#1123]
Helm chart: Kafka
Version: 1.9.0

Since Kafka 2.0.x `ssl.endpoint.identification.algorithm` set to HTTPS by default, this is ok, but deploying Kafka with SASL_SSL means that it will do the hostname validation, it is ok within the Kubernetes cluster internally but if we will expose Kafka with load balancer we won't be available to connect since we will receive `SSL handshake` error.
 
In order to have ssl.endpoint.identification.algorithm option in `server.properties` and to be available to change it, it would be really awesome if you guys can add it to the Kafka Docker image and Kafka Helm chart, @tompizmor I know you helped with similar for replication factor before.

Regarding config, yes, I can try to put the setting to the `config` variable in the Helm chart, but the problem is that it will override `server.properties` created with nami and also I am not sure how I can set for example `advertised.listeners` in the config to something dynamic like:
`advertised.listeners=SASL_SSL://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}:$(KAFKA_PORT_NUMBER)` since that variables only available during the startup. 

Also I have an error when using `config`:
```
[2019-04-05 08:01:12,203] INFO Connecting to zookeeper on kafka-zookeeper:2181 (kafka.server.KafkaServer)
[2019-04-05 08:01:12,213] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context 'Client'
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:45)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:371)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:205)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:42)
	... 5 more
Caused by: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
	at sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:666)
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:262)
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
	... 16 more
```
but maybe this is related to the fact that I can't set `advertised.listeners` in config.

Thanks in advance!

**Comment by tompizmor** [comment]
@antimack I am releasing a new version of the Kafka container with the `KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM` environment variable available.

The chart will also be updated once https://github.com/bitnami/charts/pull/1129 gets merged.

**Comment by tompizmor** [comment]
New version released and chart updated!

**Comment by antimack** [comment]
Awesome! Thanks a lot for such fast reply and PR!

**Comment by tompizmor** [comment]
You are welcome! I will close this issue. Please open a new one if you encounter any trouble.
