### ISSUE TITLE
Getting error: Kibana server is not ready

### ISSUE THREAD

**Issue by ajitkumartanwade** [bitnami/charts#11763]
### Name and Version

Kibana 10.1.10

### What steps will reproduce the bug?

Trying to setup the elasticsearch and kibana on AKS cluster. Using below command

helm install elasticsearch -n elastic azure-marketplace/elasticsearch --set security.elasticPassword="vamshi@1234" --set master.masterOnly=true --set service.type=LoadBalancer --set security.enabled=true --set security.tls.autoGenerated=true --set global.kibanaEnabled=true --set kibana.elasticsearch.security.tls.enabled=true --set kibana.elasticsearch.security.tls.kibanaUsername=elastic --set kibana.elasticsearch.security.tls.kibanaPassword="vamshi@1234" --set kibana.elasticsearch.security.tls.existingSecret=elasticsearch-coordinating-crt --set kibana.elasticsearch.security.tls.usePemCerts=true --set kibana.tls.enabled=true --set kibana.tls.autoGenerated=true --set kibana.service.type=LoadBalancer 

### What is the expected behavior?

Ideally it should work

### What do you see instead?

Getting error: Kibana server is not ready

**Comment by fmulero** [comment]
Hi @ajitkumartanwade 

Could you share the logs from pods?

**Comment by ajitkumartanwade** [comment]
Logs from Kibana pod:

←[38;5;6mkibana ←[38;5;5m21:11:45.59 ←[0m
←[38;5;6mkibana ←[38;5;5m21:11:45.59 ←[0m←[1mWelcome to the Bitnami kibana container←[0m
←[38;5;6mkibana ←[38;5;5m21:11:45.60 ←[0mSubscribe to project updates by watching ←[1mhttps://github.com/bitnami/containers←[0m
←[38;5;6mkibana ←[38;5;5m21:11:45.60 ←[0mSubmit issues and feature requests at ←[1mhttps://github.com/bitnami/containers/issues←[0m
←[38;5;6mkibana ←[38;5;5m21:11:45.60 ←[0m
←[38;5;6mkibana ←[38;5;5m21:11:45.60 ←[0m←[38;5;2mINFO ←[0m ==> * Starting Kibana setup *
←[38;5;6mkibana ←[38;5;5m21:11:45.62 ←[0m←[38;5;2mINFO ←[0m ==> Configuring/Initializing Kibana...
←[38;5;6mkibana ←[38;5;5m21:11:45.66 ←[0m←[38;5;2mINFO ←[0m ==> Found mounted configuration directory
←[38;5;6mkibana ←[38;5;5m21:11:45.76 ←[0m←[38;5;2mINFO ←[0m ==> * Kibana setup finished! *

←[38;5;6mkibana ←[38;5;5m21:11:45.78 ←[0m←[38;5;2mINFO ←[0m ==> * Starting Kibana *
[2022-08-15T21:11:59.459+00:00][INFO ][plugins-service] Plugin "cloudSecurityPosture" is disabled.
[2022-08-15T21:11:59.599+00:00][INFO ][http.server.Preboot] http server running at https://:::5601
[2022-08-15T21:11:59.648+00:00][INFO ][plugins-system.preboot] Setting up [1] plugins: [interactiveSetup]
[2022-08-15T21:11:59.692+00:00][WARN ][config.deprecation] The default mechanism for Reporting privileges will work differently in future versions, which will affect the behavior of this cluster. Set "xpack.reporting.roles.enabled" to "false" to adopt the future behavior before upgrading.
[2022-08-15T21:12:00.027+00:00][INFO ][plugins-system.standard] Setting up [118] plugins: [translations,monitoringCollection,licensing,globalSearch,globalSearchProviders,features,mapsEms,licenseApiGuard,usageCollection,taskManager,telemetryCollectionManager,telemetryCollectionXpack,share,embeddable,uiActionsEnhanced,screenshotMode,banners,newsfeed,fieldFormats,expressions,eventAnnotation,dataViews,charts,esUiShared,customIntegrations,home,searchprofiler,painlessLab,grokdebugger,management,advancedSettings,spaces,security,lists,encryptedSavedObjects,cloud,snapshotRestore,screenshotting,telemetry,licenseManagement,kibanaUsageCollection,eventLog,actions,console,bfetch,data,watcher,reporting,fileUpload,ingestPipelines,alerting,aiops,unifiedSearch,savedObjects,triggersActionsUi,transform,stackAlerts,ruleRegistry,graph,savedObjectsTagging,savedObjectsManagement,presentationUtil,expressionShape,expressionRevealImage,expressionRepeatImage,expressionMetric,expressionImage,controls,dataViewFieldEditor,visualizations,canvas,visTypeXy,visTypeVislib,visTypeVega,visTypeTimeseries,visTypeTimelion,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeHeatmap,visTypeMarkdown,dashboard,dashboardEnhanced,expressionXY,expressionTagcloud,expressionPartitionVis,visTypePie,expressionMetricVis,expressionHeatmap,expressionGauge,visTypeGauge,sharedUX,discover,lens,maps,dataVisualizer,ml,cases,timelines,sessionView,observability,fleet,synthetics,osquery,securitySolution,infra,upgradeAssistant,monitoring,logstash,enterpriseSearch,apm,indexManagement,rollup,remoteClusters,crossClusterReplication,indexLifecycleManagement,discoverEnhanced,dataViewManagement]
[2022-08-15T21:12:00.047+00:00][INFO ][plugins.taskManager] TaskManager is identified by the Kibana UUID: 39f8bcf6-a990-49c0-86e5-da5aff7acd1c
[2022-08-15T21:12:00.124+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-08-15T21:12:00.160+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-08-15T21:12:00.170+00:00][WARN ][plugins.encryptedSavedObjects] Saved objects encryption key is not set. This will severely limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-08-15T21:12:00.201+00:00][WARN ][plugins.actions] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-08-15T21:12:00.312+00:00][WARN ][plugins.reporting.config] Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-08-15T21:12:00.313+00:00][WARN ][plugins.reporting.config] Found 'server.host: "0.0.0.0"' in Kibana configuration. Reporting is not able to use this as the Kibana server hostname. To enable PNG/PDF Reporting to work, 'xpack.reporting.kibanaServer.hostname: localhost' is automatically set in the configuration. You can prevent this message by adding 'xpack.reporting.kibanaServer.hostname: localhost' in kibana.yml.
[2022-08-15T21:12:00.324+00:00][WARN ][plugins.alerting] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-08-15T21:12:00.348+00:00][INFO ][plugins.ruleRegistry] Installing common resources shared between all indices
[2022-08-15T21:12:01.079+00:00][WARN ][plugins.screenshotting.config] Chromium sandbox provides an additional layer of protection, but is not supported for Linux Debian 11.4 OS. Automatically setting 'xpack.screenshotting.browser.chromium.disableSandbox: true'.
[2022-08-15T21:12:01.209+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. Hostname/IP does not match certificate's altnames: Host: elasticsearch.elastic.svc.cluster.local. is not in the cert's altnames: DNS:elasticsearch, DNS:elasticsearch.%!s(MISSING).svc.%!s(MISSING), DNS:*.elasticsearch-coordinating-hl.elastic.svc.cluster.local, DNS:elasticsearch-coordinating-hl.elastic.svc.cluster.local, DNS:elasticsearch-coordinating, DNS:127.0.0.1, DNS:localhost
[2022-08-15T21:12:01.840+00:00][INFO ][plugins.screenshotting.chromium] Browser executable: /opt/bitnami/kibana/x-pack/plugins/screenshotting/chromium/headless_shell-linux_x64/headless_shell
[2022-08-15T21:32:00.350+00:00][ERROR][plugins.ruleRegistry] Error: Timeout: it took more than 1200000ms
    at Timeout._onTimeout (/opt/bitnami/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:54:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-08-15T21:32:00.352+00:00][ERROR][plugins.ruleRegistry] Error: Failure installing common resources shared between all indices. Timeout: it took more than 1200000ms
    at ResourceInstaller.installWithTimeout (/opt/bitnami/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:63:13)
    at ResourceInstaller.installCommonResources (/opt/bitnami/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:77:5)

**Comment by fmulero** [comment]
It seems to be related to this issue: #11632

**Comment by ajitkumartanwade** [comment]
Hi @fmulero, I have passed the kibana.elasticsearch.security.tls.existingSecret=elasticsearch-coordinating-crt

Do you want me to pass it as elasticsearch-elasticsearch-coordinating-crt? Or how to find the releasename?

**Comment by fmulero** [comment]
#11632  was recently closed, in couple of hours (I hope) a new version for elasticsearch (19.1.11) will be published with the fix for this error:

```
[2022-08-15T21:12:01.209+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. Hostname/IP does not match certificate's altnames: Host: elasticsearch.elastic.svc.cluster.local. is not in the cert's altnames: DNS:elasticsearch, DNS:elasticsearch.%!s(MISSING).svc.%!s(MISSING), DNS:*.elasticsearch-coordinating-hl.elastic.svc.cluster.local, DNS:elasticsearch-coordinating-hl.elastic.svc.cluster.local, DNS:elasticsearch-coordinating, DNS:127.0.0.1, DNS:localhost
```

Could you give it a try an share the results
