### ISSUE TITLE
Failed to upgrade Jenkins from 10.2.3 to 11.0.0

### ISSUE THREAD

**Issue by KosShutenko** [bitnami/charts#12329]
### Name and Version

bitnami/jenkins 11.0.0

### What steps will reproduce the bug?

1. Install Jenkins Helm Chart 10.2.3 via FluxCD
2. Change chart version from 10.2.3 to 11.0.0

### Are you using any custom parameters or values?

I use persistent volume:
```yaml
    persistence:
      size: 50Gi
```

### What is the expected behavior?

Should be upgraded

### What do you see instead?

I see errors in the logs:
```
jenkins 07:48:36.40 INFO  ==> ** Starting Jenkins **
Running from: /opt/bitnami/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-09-08 07:48:36.802+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @381ms to org.eclipse.jetty.util.log.JavaUtilLog
2022-09-08 07:48:36.893+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2022-09-08 07:48:36.918+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-09-08 07:48:36.971+0000 [id=1]	INFO	winstone.Logger#logInternal: Jetty shutdown successfully
java.io.IOException: Failed to start a listener: winstone.HttpsConnectorFactory
	at winstone.Launcher.spawnListener(Launcher.java:261)
	at winstone.Launcher.<init>(Launcher.java:190)
	at winstone.Launcher.main(Launcher.java:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Main._main(Main.java:342)
	at Main.main(Main.java:117)
Caused by: winstone.WinstoneException: No SSL key store found at /bitnami/jenkins/home/jenkins.jks
	at winstone.AbstractSecuredConnectorFactory.configureSsl(AbstractSecuredConnectorFactory.java:66)
	at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:54)
	at winstone.Launcher.spawnListener(Launcher.java:255)
	... 8 more
2022-09-08 07:48:36.972+0000 [id=1]	SEVERE	winstone.Logger#logInternal: Container startup failed
winstone.WinstoneException: No SSL key store found at /bitnami/jenkins/home/jenkins.jks
	at winstone.AbstractSecuredConnectorFactory.configureSsl(AbstractSecuredConnectorFactory.java:66)
	at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:54)
	at winstone.Launcher.spawnListener(Launcher.java:255)
Caused: java.io.IOException: Failed to start a listener: winstone.HttpsConnectorFactory
	at winstone.Launcher.spawnListener(Launcher.java:261)
	at winstone.Launcher.<init>(Launcher.java:190)
	at winstone.Launcher.main(Launcher.java:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Main._main(Main.java:342)
	at Main.main(Main.java:117)
```

**Comment by marcosbc** [comment]
It seems like your error is caused by this:

```
winstone.WinstoneException: No SSL key store found at /bitnami/jenkins/home/jenkins.jks
```

Note that the `jenkins.jks` file should be present in a default installation. If you continue to find issues, you could try and add that file to the PVC (e.g. by deploying a container with access to the volume).

**Comment by c-mckenzie** [comment]
I experienced the exact same issue after upgrading from 10.2.4 and had to roll back
I've since deployed a new 11.0.4 instance in parallel and confirmed it did contain the jenkins.jks file that was missing from the older releases, I then copied this file to the PVC on my other deployment (ensuing the same permissions/owner) and tried the upgrade again which succeeded.
