### ISSUE TITLE
[bitnami/kafka] incorrect controller recoreded

### ISSUE THREAD

**Issue by zhenzh** [bitnami/charts#12830]
### Name and Version

bitnami/kafka 18.5.0/3.2.3

### What steps will reproduce the bug?

When installing kafka helm chart in kubernetes with 3 replicas, all my 3 kafka brokers recorded themselves as the same controller:

```
[2022-10-06 04:04:57,123] INFO Stat of the created znode at /brokers/ids/0 is: 4294967518,4294967518,1665029097115,1665029097115,1,0,0,144270231059628036,363,0,4294967518
 (kafka.zk.KafkaZkClient)
[2022-10-06 04:04:57,123] INFO Registered broker 0 at path /brokers/ids/0 with addresses: INTERNAL://kafka-0.kafka-headless.common.svc.cluster.local:9093,CLIENT://kafka-0.kafka-headless.common.svc.cluster.local:9092, czxid (broker epoch): 4294967518 (kafka.zk.KafkaZkClient)
[2022-10-06 04:04:57,202] INFO [ControllerEventThread controllerId=0] Starting (kafka.controller.ControllerEventManager$ControllerEventThread)
[2022-10-06 04:04:57,216] INFO [ExpirationReaper-0-topic]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:04:57,218] DEBUG [Controller id=0] Broker 2 has been elected as the controller, so stopping the election process. (kafka.controller.KafkaController)
[2022-10-06 04:04:57,225] INFO [ExpirationReaper-0-Heartbeat]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:04:57,225] INFO [ExpirationReaper-0-Rebalance]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:04:57,242] INFO [GroupCoordinator 0]: Starting up. (kafka.coordinator.group.GroupCoordinator)
[2022-10-06 04:04:57,246] INFO [GroupCoordinator 0]: Startup complete. (kafka.coordinator.group.GroupCoordinator)
[2022-10-06 04:04:57,312] INFO [TransactionCoordinator id=0] Starting up. (kafka.coordinator.transaction.TransactionCoordinator)
[2022-10-06 04:04:57,314] INFO [TransactionCoordinator id=0] Startup complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2022-10-06 04:04:57,314] INFO [Transaction Marker Channel Manager 0]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2022-10-06 04:04:57,337] INFO [ExpirationReaper-0-AlterAcls]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:04:57,413] INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
[2022-10-06 04:04:57,420] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Starting socket server acceptors and processors (kafka.network.SocketServer)
[2022-10-06 04:04:57,424] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Started data-plane acceptor and processor(s) for endpoint : ListenerName(INTERNAL) (kafka.network.SocketServer)
[2022-10-06 04:04:57,425] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Started data-plane acceptor and processor(s) for endpoint : ListenerName(CLIENT) (kafka.network.SocketServer)
[2022-10-06 04:04:57,425] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Started socket server acceptors and processors (kafka.network.SocketServer)
[2022-10-06 04:04:57,430] INFO Kafka version: 3.2.3 (org.apache.kafka.common.utils.AppInfoParser)
[2022-10-06 04:04:57,430] INFO Kafka commitId: 50029d3ed8ba576f (org.apache.kafka.common.utils.AppInfoParser)
[2022-10-06 04:04:57,430] INFO Kafka startTimeMs: 1665029097425 (org.apache.kafka.common.utils.AppInfoParser)
[2022-10-06 04:04:57,431] INFO [KafkaServer id=0] started (kafka.server.KafkaServer)
[2022-10-06 04:05:07,257] INFO [BrokerToControllerChannelManager broker=0 name=alterPartition]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
[2022-10-06 04:05:07,333] INFO [BrokerToControllerChannelManager broker=0 name=forwarding]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
```

```
[2022-10-06 04:06:13,750] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-10-06 04:06:13,812] INFO Stat of the created znode at /brokers/ids/1 is: 4294967534,4294967534,1665029173759,1665029173759,1,0,0,72222535971700740,363,0,4294967534
 (kafka.zk.KafkaZkClient)
[2022-10-06 04:06:13,813] INFO Registered broker 1 at path /brokers/ids/1 with addresses: INTERNAL://kafka-1.kafka-headless.common.svc.cluster.local:9093,CLIENT://kafka-1.kafka-headless.common.svc.cluster.local:9092, czxid (broker epoch): 4294967534 (kafka.zk.KafkaZkClient)
[2022-10-06 04:06:13,859] INFO [ControllerEventThread controllerId=1] Starting (kafka.controller.ControllerEventManager$ControllerEventThread)
[2022-10-06 04:06:13,864] INFO [ExpirationReaper-1-topic]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:06:13,915] INFO [ExpirationReaper-1-Heartbeat]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:06:13,917] INFO [ExpirationReaper-1-Rebalance]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:06:13,918] DEBUG [Controller id=1] Broker 2 has been elected as the controller, so stopping the election process. (kafka.controller.KafkaController)
[2022-10-06 04:06:13,934] INFO [GroupCoordinator 1]: Starting up. (kafka.coordinator.group.GroupCoordinator)
[2022-10-06 04:06:13,938] INFO [GroupCoordinator 1]: Startup complete. (kafka.coordinator.group.GroupCoordinator)
[2022-10-06 04:06:13,954] INFO [TransactionCoordinator id=1] Starting up. (kafka.coordinator.transaction.TransactionCoordinator)
[2022-10-06 04:06:14,011] INFO [Transaction Marker Channel Manager 1]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2022-10-06 04:06:14,011] INFO [TransactionCoordinator id=1] Startup complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2022-10-06 04:06:14,036] INFO [ExpirationReaper-1-AlterAcls]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-10-06 04:06:14,049] INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
[2022-10-06 04:06:14,119] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Starting socket server acceptors and processors (kafka.network.SocketServer)
[2022-10-06 04:06:14,122] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Started data-plane acceptor and processor(s) for endpoint : ListenerName(INTERNAL) (kafka.network.SocketServer)
[2022-10-06 04:06:14,124] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Started data-plane acceptor and processor(s) for endpoint : ListenerName(CLIENT) (kafka.network.SocketServer)
[2022-10-06 04:06:14,124] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Started socket server acceptors and processors (kafka.network.SocketServer)
[2022-10-06 04:06:14,127] INFO Kafka version: 3.2.3 (org.apache.kafka.common.utils.AppInfoParser)
[2022-10-06 04:06:14,127] INFO Kafka commitId: 50029d3ed8ba576f (org.apache.kafka.common.utils.AppInfoParser)
[2022-10-06 04:06:14,127] INFO Kafka startTimeMs: 1665029174124 (org.apache.kafka.common.utils.AppInfoParser)
[2022-10-06 04:06:14,128] INFO [KafkaServer id=1] started (kafka.server.KafkaServer)
[2022-10-06 04:06:23,857] INFO [BrokerToControllerChannelManager broker=1 name=alterPartition]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
[2022-10-06 04:06:23,857] INFO [BrokerToControllerChannelManager broker=1 name=forwarding]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
```

### What do you see instead?

incorrect controller recorded

**Comment by carrodher** [comment]
Could you please provide the command and parameters you're using to deploy the Helm chart?

**Comment by zhenzh** [comment]
I used terraform helm provider to install the kafka helm chart:
```
resource "helm_release" "kafka" {
  name = "kafka"
  namespace = "common"
  chart  = "kafka"
  version = "18.5.0"
  
  values = [<<EOT
"deleteTopicEnable": true
"externalZookeeper":
    "servers":
    - "zookeeper.common:2181"
"fullnameOverride": "kafka"
"heapOpts": "-Xms1024m -Xmx3072m"
"logRetentionBytes": "_4294967296"
"logRetentionHours": 168
"metrics":
    "jmx":
    "enabled": true
    "kafka":
    "enabled": false
    "tolerations":
    - "effect": "NoSchedule"
        "key": "group"
        "operator": "Equal"
        "value": "common"
"offsetsTopicReplicationFactor": 3
"rbac":
    "create": true
"replicaCount": 3
"service":
    "port": 9092
"serviceAccount":
    "name": "kafka"
"tolerations":
- "effect": "NoSchedule"
    "key": "group"
    "operator": "Equal"
    "value": "common"
"transactionStateLogReplicationFactor": 3
"zookeeper":
    "enabled": false
  EOT
  ]
}
```

**Comment by zhenzh** [comment]
I have tried manually helm install and the issue remains. You can try command below to reproduce the issue:

```
helm upgrade --install -n common kafka bitnami/kafka -f -<< EOF
persistence:
    enabled: false
externalZookeeper:
    servers:
    - zookeeper.common:2181
rbac:
    create: true
replicaCount: 3
zookeeper:
    enabled: false
EOF
```

**Comment by marcosbc** [comment]
Hi, I cannot see any error nor warnings in the logs. Could you share the specific lines that you are worried about?

We haven't seen similar reports in the past, so I'm wondering if this could be a false positive.

**Comment by zhenzh** [comment]
Look at these lines:
```
[2022-10-06 04:04:57,123] INFO Registered broker 0 at path /brokers/ids/0 with addresses: INTERNAL://kafka-0.kafka-headless.common.svc.cluster.local:9093,CLIENT://kafka-0.kafka-headless.common.svc.cluster.local:9092, czxid (broker epoch): 4294967518 (kafka.zk.KafkaZkClient)
[2022-10-06 04:05:07,257] INFO [BrokerToControllerChannelManager broker=0 name=alterPartition]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
[2022-10-06 04:05:07,333] INFO [BrokerToControllerChannelManager broker=0 name=forwarding]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
```
and
```
[2022-10-06 04:06:13,813] INFO Registered broker 1 at path /brokers/ids/1 with addresses: INTERNAL://kafka-1.kafka-headless.common.svc.cluster.local:9093,CLIENT://kafka-1.kafka-headless.common.svc.cluster.local:9092, czxid (broker epoch): 4294967534 (kafka.zk.KafkaZkClient)
[2022-10-06 04:06:23,857] INFO [BrokerToControllerChannelManager broker=1 name=alterPartition]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
[2022-10-06 04:06:23,857] INFO [BrokerToControllerChannelManager broker=1 name=forwarding]: Recorded new controller, from now on will use broker kafka-2.kafka-headless.common.svc.cluster.local:9093 (id: 2 rack: null) (kafka.server.BrokerToControllerRequestThread)
```
Both my broker0 and broker1 were recorded as kafka-2.kafka-headless.common.svc.cluster.local:9093

**Comment by marcosbc** [comment]
Hi @zhenzh, I don't think that is what those logs are referring to. If you see this documentation: https://jaceklaskowski.gitbooks.io/apache-kafka/content/kafka-controller.html

> Controller Broker ([KafkaController](https://jaceklaskowski.gitbooks.io/apache-kafka/content/kafka-controller-KafkaController.html)) is a Kafka service that runs on every broker in a Kafka cluster, but **only one can be [active](https://jaceklaskowski.gitbooks.io/apache-kafka/content/kafka-controller.html#isActive) (elected) at any point in time**.

It seems like the cluster elected a controller, `kafka-2`, and there can only be one active/elected in the whole cluster.

**Comment by zhenzh** [comment]
ok, I have such concern as I saw a lot error reported during my kafka startup:
```
[2022-10-21 02:04:39,130] WARN [Controller id=2, targetBrokerId=1] Error connecting to node kafka-1.kafka-headless.common.svc.cluster.local:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: kafka-1.kafka-headless.common.svc.cluster.local
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:111)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:513)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:172)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:985)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:292)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:246)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-10-21 02:04:39,130] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker kafka-1.kafka-headless.common.svc.cluster.local:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to kafka-1.kafka-headless.common.svc.cluster.local:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:292)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:246)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
```
I used to think it's caused by the issue I mentioned above that the actual kafka-1 broker was recorded as `kafka-2.kafka-headless.common.svc.cluster.local:9093`.

Now I find the warning will disappear after kafka boot a while, and the connection can be completed finally. It may need some more time to wait all broker service ready.
