### ISSUE TITLE
Not able to perform only SSL

### ISSUE THREAD

**Issue by ananthprasads** [bitnami/charts#1301]
Which chart:

bitnami/kafka

Description

When setting only SSL faicng issue with /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)

Steps to reproduce the issue:

Install kafka by setting only SSL
```
helm install --name kafka bitnami/kafka --set auth.enabled=true --set listeners="SSL://:9092" --set advertisedListeners="SSL://:9092" --set auth.brokerUser=ka --set auth.brokerPassword=sdpon123 --set auth.certificatesSecret=kafka-certificates --set auth.certificatesPassword=sdpon123
```
It throws error stating
```
java.lang.IllegalArgumentException: requirement failed: inter.broker.listener.name must be a listener name defined in advertised.listeners. The valid options based on currently configured listeners are SSL
```

Then I changed inter.broker.listener.name in values.yaml to SSL

Now getting following error
Caused by: 
```
java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
```

Version of Helm and Kubernetes:

Output of helm version:
```
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Output of kubectl version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Describe pod output:
```
demo@demo:~$ kubectl describe pod kafka-0
Name:           kafka-0
Namespace:      default
Node:           demo/172.27.172.80
Start Time:     Tue, 23 Jul 2019 11:00:36 +0530
Labels:         app.kubernetes.io/component=kafka
                app.kubernetes.io/instance=kafka
                app.kubernetes.io/managed-by=Tiller
                app.kubernetes.io/name=kafka
                controller-revision-hash=kafka-798d7d4bf5
                helm.sh/chart=kafka-4.0.1
                statefulset.kubernetes.io/pod-name=kafka-0
Annotations:    <none>
Status:         Running
IP:             10.233.71.120
Controlled By:  StatefulSet/kafka
Containers:
  kafka:
    Container ID:   docker://de9bc8994967a419cc38002f76f0085fd47711ea6bef4038bebbc8e1dd09b10b
    Image:          docker.io/bitnami/kafka:2.3.0-debian-9-r4
    Image ID:       docker-pullable://bitnami/kafka@sha256:7c377418272ae8d6c33b4cc1d892cdc22bb364dd0a0d29c1337155fea935c859
    Port:           9092/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 23 Jul 2019 12:29:38 +0530
      Finished:     Tue, 23 Jul 2019 12:29:40 +0530
    Ready:          False
    Restart Count:  22
    Liveness:       tcp-socket :kafka delay=10s timeout=5s period=10s #success=1 #failure=2
    Readiness:      tcp-socket :kafka delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      MY_POD_IP:                                            (v1:status.podIP)
      MY_POD_NAME:                                         kafka-0 (v1:metadata.name)
      KAFKA_CFG_ZOOKEEPER_CONNECT:                         kafka-zookeeper
      KAFKA_PORT_NUMBER:                                   9092
      KAFKA_CFG_LISTENERS:                                 SSL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS:                      SSL://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME:                    SSL
      KAFKA_OPTS:                                          -Djava.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf
      KAFKA_BROKER_USER:                                   ka
      KAFKA_BROKER_PASSWORD:                               <set to the key 'kafka-broker-password' in secret 'kafka'>  Optional: false
      KAFKA_INTER_BROKER_USER:                             admin
      KAFKA_INTER_BROKER_PASSWORD:                         <set to the key 'kafka-inter-broker-password' in secret 'kafka'>  Optional: false
      KAFKA_CERTIFICATE_PASSWORD:                          sdpon123
      ALLOW_PLAINTEXT_LISTENER:                            yes
      KAFKA_CFG_BROKER_ID:                                 -1
      KAFKA_CFG_DELETE_TOPIC_ENABLE:                       false
      KAFKA_HEAP_OPTS:                                     -Xmx1024m -Xms1024m
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES:               10000
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MS:                     1000
      KAFKA_CFG_LOG_RETENTION_BYTES:                       1073741824
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS:          300000
      KAFKA_CFG_LOG_RETENTION_HOURS:                       168
      KAFKA_CFG_LOG_MESSAGE_FORMAT_VERSION:
      KAFKA_CFG_MAX_MESSAGE_BYTES:                         1000012
      KAFKA_CFG_SEGMENT_BYTES:                             1073741824
      KAFKA_CFG_LOGS_DIRS:                                 /opt/bitnami/kafka/data
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR:                1
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR:          1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:  1
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:     https
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR:             1
      KAFKA_CFG_NUM_IO_THREADS:                            8
      KAFKA_CFG_NUM_NETWORK_THREADS:                       3
      KAFKA_CFG_NUM_PARTITIONS:                            1
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR:         1
      KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES:               102400
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES:                  104857600
      KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES:                  102400
      KAFKA_CFG_ZOOKEEPER_CONNECT_TIMEOUT_MS:              6000
    Mounts:
      /bitnami/kafka from data (rw)
      /opt/bitnami/kafka/conf/certs/ from kafka-certificates (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mkc29 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-kafka-0
    ReadOnly:   false
  kafka-certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kafka-certificates
    Optional:    false
  default-token-mkc29:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mkc29
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason   Age                From           Message
  ----     ------   ----               ----           -------
  Warning  BackOff  3m (x413 over 1h)  kubelet, demo  Back-off restarting failed container
demo@demo:~$`

```
```
demo@demo:~$ kubectl logs -f kafka-0

Welcome to the Bitnami kafka container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Kafka setup **
WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing Kafka...
INFO  ==> No injected configuration files found, creating default config files
INFO  ==> ** Kafka setup finished! **

INFO  ==> ** Starting Kafka **
[2019-07-23 05:34:25,769] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2019-07-23 05:34:26,178] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-07-23 05:34:26,179] INFO starting (kafka.server.KafkaServer)
[2019-07-23 05:34:26,180] INFO Connecting to zookeeper on kafka-zookeeper (kafka.server.KafkaServer)
[2019-07-23 05:34:26,191] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context 'Client'
        at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:45)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:373)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:84)
        at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
        at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
        at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at javax.security.auth.login.Configuration$2.run(Configuration.java:255)
        at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
        at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:42)
        ... 5 more
Caused by: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
        at sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:666)
        at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:262)
        at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
        ... 16 more
[2019-07-23 05:34:26,194] INFO shutting down (kafka.server.KafkaServer)
[2019-07-23 05:34:26,200] INFO shut down completed (kafka.server.KafkaServer)
[2019-07-23 05:34:26,200] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2019-07-23 05:34:26,203] INFO shutting down (kafka.server.KafkaServer)
demo@demo:~$
```

**Comment by andresbono** [comment]
Hi @ananthprasads, we can't reproduce it. We will continue investigating it and we will get back to you.

**Comment by ananthprasads** [comment]
Please let me know any information required.

**Comment by andresbono** [comment]
Hi @ananthprasads, we continue checking it, with no luck.

Did you install the chart from scratch? Are you reusing volumes from previous installations?

**Comment by ananthprasads** [comment]
Hi @andresbono, I did fresh Installation. No, I did not used previous volumes. Only thing I did is used SSL instead of SASL.

**Comment by andresbono** [comment]
Hi @ananthprasads, I have created an internal task to investigate it in more depth.

Even if I can't reproduce the issue in the same way you are telling me, the Kafka container doesn't support SSL only configuration which is a desired feature.

We'll keep this issue open until we have more news.
