### ISSUE TITLE
[bitnami/spark] Unable to submit a spark application to a remote Kubernetes cluster

### ISSUE THREAD

**Issue by sanchi2019** [bitnami/charts#13341]
### Name and Version

bitnami/spark CHART NAME: spark CHART VERSION: 6.3.8 APP VERSION: 3.3.0

### What steps will reproduce the bug?

I am getting following RPC related transport error while trying to submit a Scala application to remote Spark Kubernetes cluster with service.type=LoadBalancer

```
export SUBMIT_IP=$(kubectl get --namespace <namespace name> svc <service name> -o jsonpath="{.status.loadBalancer.ingress[0]['ip', 'hostname'] }") 
```

```
kubectl get service
NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                       AGE
<svc-name>   LoadBalancer   <cluster-ip>   <external-ip>   7077:32387/TCP,80:31160/TCP   3m
```
```
export SUBMIT_PORT=7077
```
```
spark-submit --class <className> --jars <local jars> --master k8s://http://<k8s-apiserver-host:k8s-apiserver-port> --conf spark.kubernetes.driverEnv.SPARK_MASTER_URL=<spark service name>:7077  --conf spark.kubernetes.container.image=bitnami/spark:3.3.0-debian-11-r40 5 --deploy-mode cluster
```
### Are you using any custom parameters or values?
```
--set worker.memoryLimit=1024m --set master.livenessProbe.timeoutSeconds=360 --set master.readinessProbe.timeoutSeconds=360 --set master.readinessProbe.failureThreshold=10 --set worker.livenessProbe.timeoutSeconds=360 --set worker.readinessProbe.timeoutSeconds=360 --set master.containerPorts.http=8081 --set worker.containerPorts.http=8082 --set master.memoryLimit=3192m --set image.debug=true --set worker.resources.limits.memory='1024Mi' --set worker.resources.limits.cpu='100m' --set master.resources.limits.memory='2048Mi' --set service.type=LoadBalancer 
```
### What is the expected behavior?

Spark application completes successfully

### What do you see instead?

Got following error when the job is submitted:
```
22/11/03 16:58:29 INFO SparkEnv: Registering OutputCommitCoordinator
22/11/03 16:58:30 INFO Utils: Successfully started service 'SparkUI' on port 4040.
22/11/03 16:58:30 INFO SparkContext: Added JAR file:///
..
.
.
.
.
22/11/03 16:58:30 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://test-release-spark-master-svc:7077...
22/11/03 16:58:30 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master test-release-spark-master-svc:7077
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Failed to connect to test-release-spark-master-svc:7077
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
	... 4 more
Caused by: java.net.UnknownHostException: test-release-spark-master-svc
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1248)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

```

**Comment by javsalgar** [comment]
Hi,

Do you have the example project that we can use to reproduce the issue?

**Comment by sanchi2019** [comment]
Hi, please confirm the values to be submitted for the following parameters 
--conf spark.kubernetes.authenticate.oauthTokenFile
--conf spark.kubernetes.authenticate.submission.oauthTokenFile
Also, despite setting the configuration parameter --conf spark.kubernetes.namespace , the spark-submit fails because the job tries to create a pod in the default namespace.

**Comment by javsalgar** [comment]
Hi!

It seems to me that indeed, you may need to make ports externally available.

**Comment by sanchi2019** [comment]
Thanks @javsalgar. You can close this issue.
