### ISSUE TITLE
Ability to override variables in airflow.cfg for Airflow chart

### ISSUE THREAD

**Issue by anadkatmeet** [bitnami/charts#1345]
This is for **Airflow helm chart**
I didn't find a way to override variables in airflow.cfg file.
There is a way I can pass custom airflow.cfg file which will replace the existing default one, but would be nice to update just few variables if needed.
e.g. By default it uses public schema in postgres which I would like to change.

Thanks in advance.

**Comment by alemorcuq** [comment]
Hi, @anadkatmeet.

Our airflow container supports setting some variables in the `airflow.cfg` file using environment variables: https://github.com/bitnami/bitnami-docker-airflow/#environment-variables

However, the database schema is not one of them. To change that, you would need to use your custom `airflow.cfg`.

Regards,
Alejandro

**Comment by anadkatmeet** [comment]
Thanks for your response. I was able to update variables in airflow.cfg as needed. However, when I tried to update schema with AIRFLOW__CORE__SQL_ALCHEMY_SCHEMA, docker images failed to initialize. On reading upon the docs, found that it only uses public schema.
Do you know if there is a way to use different schema?

Thanks in advance.

**Comment by alemorcuq** [comment]
Hi, @anadkatmeet.

First, sorry for the incorrect information I gave you earlier: I totally forgot about the `AIRFLOW__{SECTION}__{KEY}` syntax to configure values in the `airflow.cfg` file.

Second, could you share more information about your issue? Steps to reproduce, errors shown... It will be very helpful in order to try to understand the root of the issue.

Regards,
Alejandro

**Comment by anadkatmeet** [comment]
Steps to reproduce: Just set the environment variable AIRFLOW__CORE__SQL_ALCHEMY_SCHEMA=foobar
It complains that foobar.connection table doesn't exist

**Comment by alemorcuq** [comment]
Hi, @anadkatmeet.

I'm getting this error, is this the same as you are experiencing?

```
INFO  [alembic.runtime.migration] Running upgrade dd4ecb8fbee3 -> 939bb1e647c8, task reschedule fk on cascade delete
INFO  [alembic.runtime.migration] Running upgrade c8ffec048a3b -> a56c9515abdc, Remove dag_stat table
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: foobar.connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 32, in <module>
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 1096, in initdb
    db.initdb(settings.RBAC)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 97, in initdb
    schema='airflow'))
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 81, in merge_conn
    if not session.query(Connection).filter(Connection.conn_id == conn.conn_id).first():
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2979, in first
    ret = list(self[0:1])
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2771, in __getitem__
    return list(res)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3106, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: foobar.connection [SQL: 'SELECT foobar.connection.password AS foobar_connection_password, foobar.connection.extra AS foobar_connection_extra, foobar.connection.id AS foobar_connection_id, foobar.connection.conn_id AS foobar_connection_conn_id, foobar.connection.conn_type AS foobar_connection_conn_type, foobar.connection.host AS foobar_connection_host, foobar.connection.schema AS foobar_connection_schema, foobar.connection.login AS foobar_connection_login, foobar.connection.port AS foobar_connection_port, foobar.connection.is_encrypted AS foobar_connection_is_encrypted, foobar.connection.is_extra_encrypted AS foobar_connection_is_extra_encrypted \nFROM foobar.connection \nWHERE foobar.connection.conn_id = ?\n LIMIT ? OFFSET ?'] [parameters: ('airflow_db', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

I'm not an Airflow expert, but this line is intriguing me:

```
sqlite3.OperationalError: no such table: foobar.connection
```

It looks like somehow it's trying to use SQLite. Does this tell you anything?

Regards,
Alejandro

**Comment by anadkatmeet** [comment]
Yes that's what I am getting. I was reading some docs in Airflow official documentation, it says that alchemy doesn't allow overriding schema name, only public it has to be.

**Comment by alemorcuq** [comment]
Hi, @anadkatmeet.

If the official documentation says it doesn't allow overriding the schema name, this is probably something you should ask to Airflow. By the way, may I have a link to that page in the documentation?

Regards,
Alejandro

**Comment by anadkatmeet** [comment]
Here is the link: https://airflow.readthedocs.io/en/1.9.0/configuration.html
Tried to update the default schema but still got the same error.
Anyways, we can close the issue since its more Airflow related.
