### ISSUE TITLE
Hi @lconnell

### ISSUE THREAD

**Issue by anhdv98** [bitnami/charts#13807]
I am newbie in Kafka.I try to implement security in kafka docker-compose with your instructions and get this error. Can you see if you can help me? Thanks!
```
kafka 10:55:50.52
docker_bitnami_security-kafka-1      | kafka 10:55:50.52 Welcome to the Bitnami kafka container
docker_bitnami_security-kafka-1      | kafka 10:55:50.53 Subscribe to project updates by watching https://github.com/bitnami/containers
docker_bitnami_security-kafka-1      | kafka 10:55:50.53 Submit issues and feature requests at https://github.com/bitnami/containers/issues
docker_bitnami_security-kafka-1      | kafka 10:55:50.53
docker_bitnami_security-kafka-1      | kafka 10:55:50.53 INFO  ==> ** Starting Kafka setup **
docker_bitnami_security-kafka-1      | kafka 10:55:50.58 INFO  ==> Initializing Kafka...
docker_bitnami_security-kafka-1      | kafka 10:55:50.62 INFO  ==> Copying truststore /bitnami/kafka/config/certs/kafka.truststore.jks to /opt/bitnami/kafka/config/certs
docker_bitnami_security-kafka-1      | kafka 10:55:50.63 INFO  ==> Copying truststore /bitnami/kafka/config/certs/zookeeper.truststore.jks to /opt/bitnami/kafka/config/certs
docker_bitnami_security-kafka-1      | kafka 10:55:50.64 INFO  ==> No injected configuration files found, creating default config files
docker_bitnami_security-kafka-1      | kafka 10:55:50.77 INFO  ==> Configuring Kafka for inter-broker communications with SASL_SSL authentication.
docker_bitnami_security-kafka-1      | kafka 10:55:50.99 INFO  ==> Configuring Kafka for client communications with SASL_SSL authentication.
docker_bitnami_security-kafka-1      | kafka 10:55:51.00 INFO  ==> Generating JAAS authentication file
docker_bitnami_security-kafka-1      | kafka 10:55:51.02 INFO  ==> ** Kafka setup finished! **
docker_bitnami_security-kafka-1      |
docker_bitnami_security-kafka-1      | kafka 10:55:51.03 INFO  ==> ** Starting Kafka **
docker_bitnami_security-kafka-1      | [2022-12-02 10:55:51,601] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
docker_bitnami_security-kafka-1      | [2022-12-02 10:55:51,968] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
docker_bitnami_security-kafka-1      | [2022-12-02 10:55:52,012] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
docker_bitnami_security-kafka-1      | java.lang.IllegalArgumentException: Error creating broker listeners from 'INTERNAL://:9093,CLIENT://:9092"': Unable to parse CLIENT://:9092" to a broker endpoint
docker_bitnami_security-kafka-1      |  at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:273)
docker_bitnami_security-kafka-1      |  at kafka.server.KafkaConfig.effectiveAdvertisedListeners(KafkaConfig.scala:1990)
docker_bitnami_security-kafka-1      |  at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2099)
docker_bitnami_security-kafka-1      |  at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2063)
docker_bitnami_security-kafka-1      |  at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1495)
docker_bitnami_security-kafka-1      |  at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1418)
docker_bitnami_security-kafka-1      |  at kafka.Kafka$.buildServer(Kafka.scala:67)
docker_bitnami_security-kafka-1      |  at kafka.Kafka$.main(Kafka.scala:87)
docker_bitnami_security-kafka-1      |  at kafka.Kafka.main(Kafka.scala)
docker_bitnami_security-kafka-1      | Caused by: org.apache.kafka.common.KafkaException: Unable to parse CLIENT://:9092" to a broker endpoint
docker_bitnami_security-kafka-1      |  at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:58)
docker_bitnami_security-kafka-1      |  at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:270)
docker_bitnami_security-kafka-1      |  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
docker_bitnami_security-kafka-1      |  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
docker_bitnami_security-kafka-1      |  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
docker_bitnami_security-kafka-1      |  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
docker_bitnami_security-kafka-1      |  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
docker_bitnami_security-kafka-1      |  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
docker_bitnami_security-kafka-1      |  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
docker_bitnami_security-kafka-1      |  at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:270)
docker_bitnami_security-kafka-1      |  ... 8 more
docker_bitnami_security-kafka-1 exited with code 1
```

**Comment by javsalgar** [comment]
Hi,

Could you change the issue title so it is more readable and follows the `[bitnami/XXX] Title` approach? I think the mention you performed did was not seen by the user.

**Comment by OneCricketeer** [comment]
> security in kafka docker-compose

This repo is for Kubernetes Helm Charts. You will want to relocate your issue to https://github.com/bitnami/containers/issues
