### ISSUE TITLE
[bitnami/keycloak] vault agent injector configuration error

### ISSUE THREAD

**Issue by iamaverrick** [bitnami/charts#13825]
### Name and Version

bitnami/keycloak -  v10.1.2

### What steps will reproduce the bug?

We are running a custom keycloak deployment on k8s cluster. We are trying to implement hasicorp vault to use dynamic database username and passwords for this software. the main issue is that the helm chart uses two solutions to implement a PostgreSQL database which is an internal database or an external database, and they are both hard coed. internal postgres is out of the question because we are using a centralized Postgresql database from bitnami. the external solution requires username and password in order to pass the arguments in the following code block.

```
externalDatabase:
  host: "database.url"
  port: "5432"
  user: ""
  database: "keycloak"
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""
```

we are looking for a solution where we can inject the hasicorp username and password using annotations and for the helm chart to automatically use them.

using the annotation described below we are able to inject the username and password into the pod. but because the externalDatabase is hard coded we can't use it because this section overrides the values in the annotations thus failing the pod with database creds being incorrect.

**one solution we tried was to** 

somehow override the values using Environment variables which did not work. still looks for values located in externalDatabase:

```
extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
    value: "true"
  - name: KEYCLOAK_DATABASE_HOST
    value: "postgresql-db-url"
  - name: KEYCLOAK_DATABASE_PORT
    value: "5432"
  - name: KEYCLOAK_DATABASE_NAME
    value: "keycloak"
```

### Are you using any custom parameters or values?

```
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret-keycloak: "database/creds/keycloak"
  vault.hashicorp.com/agent-inject-template-keycloak: |
    {{`{{- with secret "database/creds/keycloak" -}}
      postgres://{{ .Data.username }}:{{ .Data.password }}@postgresql-db-url.local:5432/db?sslmode=disable
    {{- end }}`}}
  vault.hashicorp.com/service: "https://vault.example.com"
  vault.hashicorp.com/namespace: "auth"
  vault.hashicorp.com/role: "internal-app"
```

### What is the expected behavior?

We are looking to implement the vault injector to inject the username and password using annotations and override the values in the externalDatabase: section. 

### What do you see instead?

Error log from the pod. 

```
keycloak 02:08:51.04 
keycloak 02:08:51.04 Welcome to the Bitnami keycloak container
keycloak 02:08:51.05 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 02:08:51.05 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 02:08:51.06 
keycloak 02:08:51.06 INFO  ==> ** Starting keycloak setup **
keycloak 02:08:51.08 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 02:08:51.11 INFO  ==> Trying to connect to PostgreSQL server postgresql-master.db.svc.cluster.local...
keycloak 02:08:51.15 INFO  ==> Found PostgreSQL server listening at postgresql-master.db.svc.cluster.local:5432
keycloak 02:08:51.17 INFO  ==> Configuring database settings
keycloak 02:08:51.22 INFO  ==> Enabling statistics
keycloak 02:08:51.24 INFO  ==> Configuring http settings
keycloak 02:08:51.28 INFO  ==> Configuring hostname settings
keycloak 02:08:51.29 INFO  ==> Configuring cache count
keycloak 02:08:51.31 INFO  ==> Configuring log level
keycloak 02:08:51.33 INFO  ==> Configuring proxy
keycloak 02:08:51.34 INFO  ==> Configuring TLS by setting keystore and truststore
keycloak 02:08:51.38 INFO  ==> ** keycloak setup finished! **

keycloak 02:08:51.41 INFO  ==> ** Starting keycloak **
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2022-12-04 02:08:57,898 WARN  [org.keycloak.services] (build-32) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
2022-12-04 02:08:58,895 WARN  [org.keycloak.services] (build-32) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2022-12-04 02:09:03,532 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 9064ms
Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config

Next time you run the server, just run:

	kc.sh start --optimized -cf=/opt/bitnami/keycloak/conf/keycloak.conf

2022-12-04 02:09:06,364 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2022-12-04 02:09:08,344 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-12-04 02:09:09,685 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': FATAL: role "bn_keycloak" does not exist
2022-12-04 02:09:09,687 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: role "bn_keycloak" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2787)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:173)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:290)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-12-04 02:09:10,544 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-12-04 02:09:10,815 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-12-04 02:09:10,846 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-12-04 02:09:11,282 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-12-04 02:09:11,850 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_875226, Site name: null
2022-12-04 02:09:11,868 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': FATAL: role "bn_keycloak" does not exist
2022-12-04 02:09:12,082 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-12-04 02:09:12,082 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-12-04 02:09:12,083 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: FATAL: role "bn_keycloak" does not exist
2022-12-04 02:09:12,083 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

**Comment by iamaverrick** [comment]
Thanks for the prompt response, but this is not an option since I would have to manually input the secret, constantly changing when the lease is up every 24h. 

Upon further review of the helm chart configmap-env-vars.yaml, all values are provided via Environment Variables which enables overriding my values. 

```
  KEYCLOAK_DATABASE_HOST: {{ include "keycloak.databaseHost" . | quote }}
  KEYCLOAK_DATABASE_PORT: {{ include "keycloak.databasePort" . }}
  KEYCLOAK_DATABASE_NAME: {{ include "keycloak.databaseName" . | quote }}
  KEYCLOAK_DATABASE_USER: {{ include "keycloak.databaseUser" . | quote }}
```

Unless I'm doing something wrong here the snippet 

```
  vault.hashicorp.com/agent-inject-secret-keycloak: "database/creds/keycloak"
  vault.hashicorp.com/agent-inject-template-keycloak: |
    {{`{{- with secret "database/creds/keycloak" -}}
      postgres://{{ .Data.username }}:{{ .Data.password }}@postgresql-db-url.local:5432/db?sslmode=disable
    {{- end }}`}}
```

should inject the proper values to the external postgress database.

**Comment by iamaverrick** [comment]
**Update**

I came across a better approach, and that is to inject the secrets as Environment variables. following the docs provided by  [hasicorp](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/examples) in the section Environment Variable Example.

```
  vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/keycloak"
  vault.hashicorp.com/agent-inject-template-db-creds: |
    {{`{{- with secret "database/creds/keycloak" -}}
      export KEYCLOAK_DATABASE_USER="{{ .Data.username }}"
      export KEYCLOAK_DATABASE_PASSWORD="{{ .Data.password }}"
    {{- end }}`}}
```

i export the EV and passed in the injected secrets. When I deploy the helm chart and exec into the pod and run `cat /vault/secrets/db-creds`, I'm able to retrieve the secrets, so I know that the injections are working. 
when i run printenv i see all the EV. 
What I'm I missing?

**Comment by corico44** [comment]
Hello @iamaverrick, if you are correctly injecting the username and password variables into the pod and the value is assigned correctly, what is the current error you have?

**Comment by iamaverrick** [comment]
Hello All, 

I was able to resolve the issue. It turned out to be more on vault side as opposed to the service and or bitnami. For those who wish to utilize vault in the future and or if bitnami ever wishes to package the derive and run to same issues as described above you can find resolution [here](https://github.com/hashicorp/vault-helm/issues/816#issuecomment-1344672808). Thank you all who toke time to provide guidance.
