### ISSUE TITLE
Kibana fails - Kibana server is not Ready Yet - Elasticsearch Chart

### ISSUE THREAD

**Issue by VitorNilson** [bitnami/charts#14112]
### Name and Version

bitnami/elasticsearch-19.5.5

### What steps will reproduce the bug?

1. Deploy elasticsearch: 
`helm install  elasticsearch bitnami/elasticsearch --set global.storageClass=managed-nfs-storage --set global.kibanaEnabled=true`
1.1. Wait for all pods be running ok.
2. Do a port-forward to your Kibana service: `kubectl port-forward svc/elasticsearch-kibana 5601:5601`
3. Access it on browser and get the error:
![image](https://user-images.githubusercontent.com/63609321/209711963-62ac36ba-b899-46df-bfb9-e43a7c0fac10.png)

### Are you using any custom parameters or values?

` --set global.storageClass=managed-nfs-storage --set global.kibanaEnabled=true`

### What is the expected behavior?

Access Kibana with success.

### What do you see instead?

An error: "Kibana server is not ready yet."

### Additional information

Hello, folks.

I can't access Kibana with success.

When I do a port-forward to Kibana, this is what I see on browser:
![image](https://user-images.githubusercontent.com/63609321/209707782-5109db21-d750-486d-bf41-7ad23d2fb1a0.png)

Command used to deploy elastic:

`helm install  elasticsearch bitnami/elasticsearch --set global.storageClass=managed-nfs-storage --set global.kibanaEnabled=true`

Here are some outputs:
`$ kubectl get all`:

```
NAME                                         READY   STATUS    RESTARTS   AGE
pod/nfs-client-provisioner-c8b85bd55-pvq87   1/1     Running   0          20m
pod/elasticsearch-kibana-758c8bd4dc-tq9p4    1/1     Running   0          14m
pod/elasticsearch-master-0                   1/1     Running   0          14m
pod/elasticsearch-data-1                     1/1     Running   0          14m
pod/elasticsearch-coordinating-0             1/1     Running   0          14m
pod/elasticsearch-data-0                     1/1     Running   0          14m
pod/elasticsearch-coordinating-1             1/1     Running   0          14m
pod/elasticsearch-ingest-0                   1/1     Running   0          14m
pod/elasticsearch-master-1                   1/1     Running   0          14m
pod/elasticsearch-ingest-1                   1/1     Running   0          14m

NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/kubernetes                      ClusterIP   10.152.183.1     <none>        443/TCP             5h46m
service/elasticsearch                   ClusterIP   10.152.183.80    <none>        9200/TCP,9300/TCP   14m
service/elasticsearch-data-hl           ClusterIP   10.152.183.219   <none>        9200/TCP,9300/TCP   14m
service/elasticsearch-master-hl         ClusterIP   10.152.183.50    <none>        9200/TCP,9300/TCP   14m
service/elasticsearch-coordinating-hl   ClusterIP   10.152.183.125   <none>        9200/TCP,9300/TCP   14m
service/elasticsearch-ingest-hl         ClusterIP   10.152.183.91    <none>        9200/TCP,9300/TCP   14m
service/elasticsearch-kibana            ClusterIP   10.152.183.58    <none>        5601/TCP            14m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nfs-client-provisioner   1/1     1            1           128m
deployment.apps/elasticsearch-kibana     1/1     1            1           14m

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/nfs-client-provisioner-c8b85bd55   1         1         1       128m
replicaset.apps/elasticsearch-kibana-758c8bd4dc    1         1         1       14m

NAME                                          READY   AGE
statefulset.apps/elasticsearch-data           2/2     14m
statefulset.apps/elasticsearch-coordinating   2/2     14m
statefulset.apps/elasticsearch-master         2/2     14m
statefulset.apps/elasticsearch-ingest         2/2     14m
```

`$ kubectl get pv,pvc`:

```
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS          REASON   AGE
persistentvolume/pvc-416b0280-33f7-4505-abc1-01b527c20dd1   8Gi        RWO            Delete           Bound    default/data-elasticsearch-master-0   managed-nfs-storage            111m
persistentvolume/pvc-fb8bd29f-3803-43d5-97dc-4aa6624585d6   8Gi        RWO            Delete           Bound    default/data-elasticsearch-data-0     managed-nfs-storage            111m
persistentvolume/pvc-68756883-c2e9-411f-a2df-5ae3c8cccaee   8Gi        RWO            Delete           Bound    default/data-elasticsearch-master-1   managed-nfs-storage            111m
persistentvolume/pvc-8991c755-7352-440b-87b5-e2af80e4f04e   8Gi        RWO            Delete           Bound    default/data-elasticsearch-data-1     managed-nfs-storage            111m
persistentvolume/pvc-75ceda04-cdbf-41d3-b9c0-7f3dbcce14ac   10Gi       RWO            Delete           Bound    default/elasticsearch-kibana          managed-nfs-storage            15m

NAME                                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
persistentvolumeclaim/data-elasticsearch-master-0   Bound    pvc-416b0280-33f7-4505-abc1-01b527c20dd1   8Gi        RWO            managed-nfs-storage   111m
persistentvolumeclaim/data-elasticsearch-data-0     Bound    pvc-fb8bd29f-3803-43d5-97dc-4aa6624585d6   8Gi        RWO            managed-nfs-storage   111m
persistentvolumeclaim/data-elasticsearch-master-1   Bound    pvc-68756883-c2e9-411f-a2df-5ae3c8cccaee   8Gi        RWO            managed-nfs-storage   111m
persistentvolumeclaim/data-elasticsearch-data-1     Bound    pvc-8991c755-7352-440b-87b5-e2af80e4f04e   8Gi        RWO            managed-nfs-storage   111m
persistentvolumeclaim/elasticsearch-kibana          Bound    pvc-75ceda04-cdbf-41d3-b9c0-7f3dbcce14ac   10Gi       RWO            managed-nfs-storage   15m
```

Accessing the pod `pod/elasticsearch-kibana-758c8bd4dc-tq9p4 `:

`$ kubectl exec -it elasticsearch-kibana-758c8bd4dc-tq9p4 bash`

![image](https://user-images.githubusercontent.com/63609321/209708260-7afbfc48-45b7-4d96-aa81-ddaca037dc56.png)

This is the kibana.yaml:

![image](https://user-images.githubusercontent.com/63609321/209708515-4f70fa8c-d043-4c65-8f33-bf51331e81a4.png)

And here are the Kibana pod logs:

```
kibana 18:16:38.90 
kibana 18:16:38.90 Welcome to the Bitnami kibana container
kibana 18:16:38.90 Subscribe to project updates by watching https://github.com/bitnami/containers
kibana 18:16:38.90 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kibana 18:16:38.90 
kibana 18:16:38.90 INFO  ==> ** Starting Kibana setup **
kibana 18:16:38.91 INFO  ==> Configuring/Initializing Kibana...
kibana 18:16:38.93 INFO  ==> Found mounted configuration directory
kibana 18:16:38.94 INFO  ==> ** Kibana setup finished! **

kibana 18:16:38.95 INFO  ==> ** Starting Kibana **
[2022-12-27T18:16:40.645+00:00][INFO ][node] Kibana process configured with roles: [background_tasks, ui]
[2022-12-27T18:16:50.456+00:00][INFO ][plugins-service] Plugin "cloudExperiments" is disabled.
[2022-12-27T18:16:50.468+00:00][INFO ][plugins-service] Plugin "profiling" is disabled.
[2022-12-27T18:16:50.550+00:00][INFO ][http.server.Preboot] http server running at http://:::5601
[2022-12-27T18:16:50.592+00:00][INFO ][plugins-system.preboot] Setting up [1] plugins: [interactiveSetup]
[2022-12-27T18:16:50.630+00:00][WARN ][config.deprecation] The default mechanism for Reporting privileges will work differently in future versions, which will affect the behavior of this cluster. Set "xpack.reporting.roles.enabled" to "false" to adopt the future behavior before upgrading.
[2022-12-27T18:16:50.878+00:00][INFO ][plugins-system.standard] Setting up [125] plugins: [translations,monitoringCollection,licensing,globalSearch,globalSearchProviders,features,mapsEms,licenseApiGuard,usageCollection,taskManager,telemetryCollectionManager,telemetryCollectionXpack,kibanaUsageCollection,share,screenshotMode,banners,newsfeed,guidedOnboarding,fieldFormats,expressions,dataViews,embeddable,uiActionsEnhanced,charts,esUiShared,customIntegrations,home,searchprofiler,painlessLab,grokdebugger,management,advancedSettings,spaces,security,lists,files,encryptedSavedObjects,cloud,snapshotRestore,screenshotting,telemetry,licenseManagement,eventLog,actions,stackConnectors,console,bfetch,data,watcher,reporting,fileUpload,ingestPipelines,alerting,aiops,unifiedSearch,unifiedFieldList,savedSearch,savedObjects,graph,savedObjectsTagging,savedObjectsManagement,presentationUtil,expressionShape,expressionRevealImage,expressionRepeatImage,expressionMetric,expressionImage,controls,eventAnnotation,dataViewFieldEditor,triggersActionsUi,transform,stackAlerts,ruleRegistry,discover,fleet,indexManagement,remoteClusters,crossClusterReplication,indexLifecycleManagement,cloudSecurityPosture,discoverEnhanced,visualizations,canvas,visTypeXy,visTypeVislib,visTypeVega,visTypeTimeseries,rollup,visTypeTimelion,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeHeatmap,visTypeMarkdown,dashboard,dashboardEnhanced,expressionXY,expressionTagcloud,expressionPartitionVis,visTypePie,expressionMetricVis,expressionLegacyMetricVis,expressionHeatmap,expressionGauge,lens,maps,dataVisualizer,cases,timelines,sessionView,kubernetesSecurity,observability,osquery,ml,synthetics,securitySolution,infra,upgradeAssistant,monitoring,logstash,enterpriseSearch,apm,visTypeGauge,dataViewManagement]
[2022-12-27T18:16:50.898+00:00][INFO ][plugins.taskManager] TaskManager is identified by the Kibana UUID: 9ae6f237-271f-43a4-aad2-e5dd07cd4dc2
[2022-12-27T18:16:50.977+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-12-27T18:16:50.978+00:00][WARN ][plugins.security.config] Session cookies will be transmitted over insecure connections. This is not recommended.
[2022-12-27T18:16:51.003+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-12-27T18:16:51.004+00:00][WARN ][plugins.security.config] Session cookies will be transmitted over insecure connections. This is not recommended.
[2022-12-27T18:16:51.012+00:00][WARN ][plugins.encryptedSavedObjects] Saved objects encryption key is not set. This will severely limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-12-27T18:16:51.028+00:00][WARN ][plugins.actions] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-12-27T18:16:51.127+00:00][WARN ][plugins.reporting.config] Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-12-27T18:16:51.129+00:00][WARN ][plugins.reporting.config] Found 'server.host: "0.0.0.0"' in Kibana configuration. Reporting is not able to use this as the Kibana server hostname. To enable PNG/PDF Reporting to work, 'xpack.reporting.kibanaServer.hostname: localhost' is automatically set in the configuration. You can prevent this message by adding 'xpack.reporting.kibanaServer.hostname: localhost' in kibana.yml.
[2022-12-27T18:16:51.136+00:00][WARN ][plugins.alerting] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-12-27T18:16:51.197+00:00][INFO ][plugins.ruleRegistry] Installing common resources shared between all indices
[2022-12-27T18:16:51.243+00:00][INFO ][plugins.cloudSecurityPosture] Registered task successfully [Task: cloud_security_posture-stats_task]
[2022-12-27T18:16:51.812+00:00][WARN ][plugins.screenshotting.config] Chromium sandbox provides an additional layer of protection, but is not supported for Linux Debian 11.5 OS. Automatically setting 'xpack.screenshotting.browser.chromium.disableSandbox: true'.
[2022-12-27T18:16:52.228+00:00][INFO ][plugins.screenshotting.chromium] Browser executable: /opt/bitnami/kibana/x-pack/plugins/screenshotting/chromium/headless_shell-linux_x64/headless_shell
[2022-12-27T18:16:55.922+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 10.152.183.80:9200
[2022-12-27T18:19:35.547+00:00][INFO ][savedobjects-service] Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations...
[2022-12-27T18:19:35.558+00:00][INFO ][savedobjects-service] Starting saved objects migrations
[2022-12-27T18:19:35.832+00:00][INFO ][savedobjects-service] [.kibana] INIT -> CREATE_NEW_TARGET. took: 208ms.
[2022-12-27T18:19:36.002+00:00][INFO ][savedobjects-service] [.kibana_task_manager] INIT -> CREATE_NEW_TARGET. took: 370ms.
[2022-12-27T18:20:36.487+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 1 in 2 seconds.
[2022-12-27T18:20:36.487+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 60485ms.
[2022-12-27T18:20:36.511+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 1 in 2 seconds.
[2022-12-27T18:20:36.511+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 60679ms.
[2022-12-27T18:21:38.496+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 2 in 4 seconds.
[2022-12-27T18:21:38.496+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 62009ms.
[2022-12-27T18:21:38.522+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 2 in 4 seconds.
[2022-12-27T18:21:38.522+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 62011ms.
[2022-12-27T18:22:42.508+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 3 in 8 seconds.
[2022-12-27T18:22:42.508+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 64012ms.
[2022-12-27T18:22:42.533+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 3 in 8 seconds.
[2022-12-27T18:22:42.533+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 64011ms.
[2022-12-27T18:23:50.517+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 4 in 16 seconds.
[2022-12-27T18:23:50.517+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 68009ms.
[2022-12-27T18:23:50.546+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 4 in 16 seconds.
[2022-12-27T18:23:50.546+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 68013ms.
[2022-12-27T18:25:06.527+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 5 in 32 seconds.
[2022-12-27T18:25:06.527+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 76010ms.
[2022-12-27T18:25:06.558+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 5 in 32 seconds.
[2022-12-27T18:25:06.558+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 76012ms.
[2022-12-27T18:26:38.534+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 6 in 64 seconds.
[2022-12-27T18:26:38.534+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 92007ms.
[2022-12-27T18:26:38.567+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 6 in 64 seconds.
[2022-12-27T18:26:38.567+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 92009ms.
[2022-12-27T18:28:42.542+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 7 in 64 seconds.
[2022-12-27T18:28:42.542+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124008ms.
[2022-12-27T18:28:42.577+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 7 in 64 seconds.
[2022-12-27T18:28:42.577+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124010ms.
[2022-12-27T18:30:46.549+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 8 in 64 seconds.
[2022-12-27T18:30:46.549+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124007ms.
[2022-12-27T18:30:46.586+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 8 in 64 seconds.
[2022-12-27T18:30:46.587+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124009ms.
[2022-12-27T18:32:50.558+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 9 in 64 seconds.
[2022-12-27T18:32:50.558+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124009ms.
[2022-12-27T18:32:50.595+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 9 in 64 seconds.
[2022-12-27T18:32:50.596+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124009ms.
[2022-12-27T18:34:54.564+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 10 in 64 seconds.
[2022-12-27T18:34:54.564+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124006ms.
[2022-12-27T18:34:54.605+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 10 in 64 seconds.
[2022-12-27T18:34:54.605+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124010ms.
[2022-12-27T18:36:51.199+00:00][ERROR][plugins.ruleRegistry] Error: Timeout: it took more than 1200000ms
    at Timeout._onTimeout (/opt/bitnami/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:61:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-12-27T18:36:51.201+00:00][ERROR][plugins.ruleRegistry] Error: Failure installing common resources shared between all indices. Timeout: it took more than 1200000ms
    at ResourceInstaller.installWithTimeout (/opt/bitnami/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:75:13)
    at ResourceInstaller.installCommonResources (/opt/bitnami/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:89:5)
[2022-12-27T18:36:58.571+00:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_task_manager_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 11 in 64 seconds.
[2022-12-27T18:36:58.571+00:00][INFO ][savedobjects-service] [.kibana_task_manager] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124007ms.
[2022-12-27T18:36:58.614+00:00][ERROR][savedobjects-service] [.kibana] Action failed with '[index_not_green_timeout] Timeout waiting for the status of the [.kibana_8.5.2_001] index to become 'green' Refer to https://www.elastic.co/guide/en/kibana/8.5/resolve-migrations-failures.html#_repeated_time_out_requests_that_eventually_fail for information on how to resolve the issue.'. Retrying attempt 11 in 64 seconds.
[2022-12-27T18:36:58.614+00:00][INFO ][savedobjects-service] [.kibana] CREATE_NEW_TARGET -> CREATE_NEW_TARGET. took: 124009ms.
```

My kubernetes version:

```
clientVersion:
  buildDate: "2022-07-13T14:30:46Z"
  compiler: gc
  gitCommit: aef86a93758dc3cb2c658dd9657ab4ad4afc21cb
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-11-14T22:13:32Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/amd64
```
I'm running on bare-metal (my computer) a microk8s cluster.

Can somebody help me here? I really don't know what's going on.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Elasticsearch container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by Tect-Arct** [comment]
Facing the same issue after the deployment of ECK on AKS using Helmchart
![image](https://github.com/bitnami/charts/assets/78071039/3bc94d49-53a4-434f-b81a-d7b7b8c8b9fe)
