### ISSUE TITLE
[bitnami/clickhouse]

### ISSUE THREAD

**Issue by Gorniv** [bitnami/charts#14302]
### Name and Version

bitnami/clickhouse 2.2.2

### What steps will reproduce the bug?

helm install clickhouse-aso bitnami/clickhouse --namespace=clickhouse-aso --timeout=10m0s --values=aso/clickhouse/values.yaml

### Are you using any custom parameters or values?

# clickhouse-aso
---
global:
  storageClass: "local-storage"
persistence: 
  enabled: true
  size: "8Gi"
  storageClass: "local-storage"
image:
  tag: 22.12.3-debian-11-r0
replicaCount: 3
shards: 1

### What do you see instead?

zookeeper 04:25:37.03
--
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.04 Welcome to the Bitnami zookeeper container
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.04 Subscribe to project updates by watching https://github.com/bitnami/containers
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.04 Submit issues and feature requests at https://github.com/bitnami/containers/issues
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.04
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.05 INFO ==> ** Starting ZooKeeper setup **
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.08 WARN ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.10 INFO ==> Initializing ZooKeeper...
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.10 INFO ==> No injected configuration file found, creating default config files...
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.17 INFO ==> Adding server: clickhouse-aso-zookeeper-0.clickhouse-aso-zookeeper-headless.clickhouse-aso.svc.cluster.local:2888:3888 with id: 1
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.17 INFO ==> Adding server: clickhouse-aso-zookeeper-1.clickhouse-aso-zookeeper-headless.clickhouse-aso.svc.cluster.local:2888:3888 with id: 2
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.17 INFO ==> Adding server: clickhouse-aso-zookeeper-2.clickhouse-aso-zookeeper-headless.clickhouse-aso.svc.cluster.local:2888:3888 with id: 3
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.18 INFO ==> Deploying ZooKeeper with persisted data...
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.19 INFO ==> ** ZooKeeper setup finished! **
Thu, Jan 12 2023 11:25:37 am |  
Thu, Jan 12 2023 11:25:37 am | zookeeper 04:25:37.20 INFO ==> ** Starting ZooKeeper **
Thu, Jan 12 2023 11:25:37 am | /opt/bitnami/java/bin/java
Thu, Jan 12 2023 11:25:37 am | ZooKeeper JMX enabled by default
Thu, Jan 12 2023 11:25:37 am | Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
Thu, Jan 12 2023 11:25:38 am | 2023-01-12 04:25:38,393 [myid:] - ERROR [main:o.a.z.s.q.QuorumPeerMain@99] - Invalid config, exiting abnormally
Thu, Jan 12 2023 11:25:38 am | org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
Thu, Jan 12 2023 11:25:38 am | at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:198)
Thu, Jan 12 2023 11:25:38 am | at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:125)
Thu, Jan 12 2023 11:25:38 am | at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:91)
Thu, Jan 12 2023 11:25:38 am | Caused by: java.lang.IllegalArgumentException: myid file is missing
Thu, Jan 12 2023 11:25:38 am | at org.apache.zookeeper.server.quorum.QuorumPeerConfig.checkValidity(QuorumPeerConfig.java:792)
Thu, Jan 12 2023 11:25:38 am | at org.apache.zookeeper.server.quorum.QuorumPeerConfig.setupQuorumPeerConfig(QuorumPeerConfig.java:663)
Thu, Jan 12 2023 11:25:38 am | at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:487)
Thu, Jan 12 2023 11:25:38 am | at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:194)
Thu, Jan 12 2023 11:25:38 am | ... 2 common frames omitted
Thu, Jan 12 2023 11:25:38 am | Invalid config, exiting abnormally
Thu, Jan 12 2023 11:25:38 am | 2023-01-12 04:25:38,398 [myid:] - ERROR [main:o.a.z.u.ServiceUtils@42] - Exiting JVM with code 2

**Comment by Gorniv** [comment]
fixed in 2.2.4
