### ISSUE TITLE
cannot connect to loadbalancer externally

### ISSUE THREAD

**Issue by nervouscat** [bitnami/charts#1448]
hello all,

I cannot seem to connect to my kafka instance through the loadbalancer externally.

I wind up kafka with the following command: 
helm install --name franz2   bitnami/kafka --set service.type=LoadBalancer

when all services are up i try to launch a consumer that links to the ip of the loadbalancer, i get the following result:

```
CONNECTED! CONSUMER
TOPIC SUBSCRIBED
{"level":"INFO","timestamp":"2019-09-30T14:10:51.734Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group"}
{"level":"ERROR","timestamp":"2019-09-30T14:10:52.741Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app"}
{"level":"ERROR","timestamp":"2019-09-30T14:10:52.744Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":0,"retryTime":358}
{"level":"ERROR","timestamp":"2019-09-30T14:10:54.108Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app"}
{"level":"ERROR","timestamp":"2019-09-30T14:10:54.108Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":1,"retryTime":680}
{"level":"ERROR","timestamp":"2019-09-30T14:10:55.795Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app"}
{"level":"ERROR","timestamp":"2019-09-30T14:10:55.796Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":2,"retryTime":1136}
{"level":"ERROR","timestamp":"2019-09-30T14:10:56.742Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}
{"level":"ERROR","timestamp":"2019-09-30T14:10:57.938Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app"}
{"level":"ERROR","timestamp":"2019-09-30T14:10:57.938Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":3,"retryTime":2392}
{"level":"ERROR","timestamp":"2019-09-30T14:10:58.108Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:01.338Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:01.338Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":4,"retryTime":4476}
{"level":"ERROR","timestamp":"2019-09-30T14:11:01.745Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:03.112Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:06.749Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:06.821Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:06.821Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":5,"retryTime":9700}
{"level":"ERROR","timestamp":"2019-09-30T14:11:06.822Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Connection timeout","groupId":"test-group","retryCount":5,"stack":"KafkaJSNumberOfRetriesExceeded\n  Caused by: KafkaJSConnectionError: Connection timeout\n    at Timeout.onTimeout [as _onTimeout] (/Users/tarek/kafka-client/node_modules/kafkajs/src/network/connection.js:149:23)\n    at listOnTimeout (internal/timers.js:531:17)\n    at processTimers (internal/timers.js:475:7)"}
{"level":"INFO","timestamp":"2019-09-30T14:11:06.822Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"test-group"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:06.822Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 9700ms","retryCount":5,"retryTime":9700,"groupId":"test-group"}
{"level":"ERROR","timestamp":"2019-09-30T14:11:10.820Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local","broker":"franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND franz2-kafka-0.franz2-kafka-headless.default.svc.cluster.local\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}
```

**Comment by miguelaeh** [comment]
Hi @nervouscat ,
It seems that the LoadBalancer is not correctly working, could you proide the output of the following commands?
```
$ kubectl get svc
$ kubectl get endpoints
```

It should appear two services for `Kafka` and two more for `Zookeeper`.

In some clusters the `LoadBalancer` is not created and they need an annotation on the service to allow the `LoadBalancer` creation.

**Comment by pedrohjordao** [comment]
I have a similar issue running on minikube. The service is ok and reachable, and running the consumer through the pod works fine, but when trying to subscribe through kafkacat i get the following error:

```bash
$ kafkacat -b <service-ip:service-port> -t <topic>
% Auto-selecting Consumer mode (use -P or -C to override)
% ERROR: Local: Host resolution failure: kafka-0.kafka-headless.default.svc.cluster.local:9092/1001: Failed to resolve 'kafka-0.kafka-headless.default.svc.cluster.local:9092': Name or service not known (after 786893ms in state INIT)
```

Looking at OPs error it seems to be a similar issue

**Comment by miguelaeh** [comment]
Hi @pedrohjordao  ,
Minikube does not provide an external IP, a `LoadBalancer` is reachable throw `minikube service <loadBalancer_name>` but not from your host. 
Where are you trying to connect to it? From within Minikube or from your host?

**Comment by pedrohjordao** [comment]
From my host. Shouldn't minikube's tunnel solve this? the service does expose a external ip, but maybe I'm missing something

**Comment by miguelaeh** [comment]
I think it should solve it. Have you try the following command?

```
minikube service <service-name> --url
```

**Comment by pedrohjordao** [comment]
Sorry, i've been busy and couldn't test it earlier

Is this a particular issue with minikube? 
The command just seems to be stuck, I need to try to debug that later.

**Comment by miguelaeh** [comment]
I think this is not any issue with minikube.
You can find more information about LoadBalancer services [here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/)

**Comment by sarumont** [comment]
I'm far from a Kafka expert, but the issue ends up being, I believe, that you can't advertise a host you aren't bound to. And without some sort of split-horizon DNS, you are generally up :hankey: creek.

I've gotten external access to work with `minikube` and `NodePort`, however, with the following configuration:

```yaml
## Allow to use the PLAINTEXT listener.
allowPlaintextListener: true

## The address the socket server listens on.
listeners: INTERNAL://:32092

## Hostname and port the broker will advertise to producers and consumers.
advertisedListeners: INTERNAL://:32092

## The protocol->listener mapping
listenerSecurityProtocolMap: INTERNAL:PLAINTEXT

## The listener that the brokers should communicate on
interBrokerListenerName: INTERNAL
```
And:

```yaml
service:
  type: NodePort
  port: 32092
  nodePort: 32092
```

On the host machine, you'll need to edit `/etc/hosts` as @miguelaeh suggested above:

```192.168.99.105 my-kafka-0.my-kafka-headless.default.svc.cluster.local```

Use the IP from `minikube ip` and the hostname that the helm chart outputs.

I can then use `kafkacat` with the above hostname (though I have a shorter one: `platform.local`):

```
kafkacat -b platform.local:32092 -L
kafkacat -b platform.local:32092 -C -t foobar
# in another terminal:
echo testing | kafkacat -b platform.local:32092 -P -t foobar
```

Hope this helps someone!

**Comment by miguelaeh** [comment]
Thank you very much @sarumont for the detailed explanation!!! I hope that can help.
