### ISSUE TITLE
[bitnami/mongodb] mongodb-exporter keeps crashing with "incomplete read of full message: context canceled"

### ISSUE THREAD

**Issue by StevenCyb** [bitnami/charts#14515]
### Name and Version

bitnami/mongodb 13.6.4

### What steps will reproduce the bug?

I already found a related [issue 12717](https://github.com/bitnami/charts/issues/12717) that was closed and whose suggestion does not work in my case. 

I run the `bitnami/mongodb` chart on AWS EKS with Kubernetes `v1.24.8` and the `values.yaml` below and the chart version above.
Nothing was configured or changed additionally.

The `mongodb` container (`mongodb:6.0.4-debian-11-r0`) works fine but the `metrics` sidecar container (`mongodb-exporter:0.36.0-debian-11-r6`) is in a crashloop:
```bash
level=info ts=2023-01-24T07:58:42.511Z caller=tls_config.go:195 msg="TLS is disabled." http2=false                                                                                                    
time="2023-01-24T07:59:07Z" level=error msg="cannot get replSetGetStatus: connection(localhost:27017[-24]) incomplete read of full message: context canceled"                                         
time="2023-01-24T07:59:12Z" level=error msg="Failed to get $dbstats for database local: connection(localhost:27017[-31]) unable to write wire message to network: context canceled"                   
2023/01/24 07:59:12 http: panic serving 10.10.1.51:52808: descriptor Desc{fqName: "", help: "", constLabels: {}, variableLabels: []} is invalid: connection(localhost:27017[-30]) incomplete read of m
goroutine 735 [running]:                                                                                                                                                                              
net/http.(*conn).serve.func1() 
    /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:1802 +0xb9                                                                                                                             
panic({0xb21820, 0xc00054af60})                                                                                                                                                                       
    /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1047 +0x266                                                                                                                              
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xd961a0, {0xc0006217d0, 0x1, 0x8})                                                                                           
    /home/runner/go/pkg/mod/github.com/!percona-!lab/client_golang@v1.12.2-0.20220701073455-ee06569fd6a5/prometheus/registry.go:403 +0x7f                                                             
github.com/percona/mongodb_exporter/exporter.(*Exporter).makeRegistry(0xc00007d450, {0xd961a0, 0xc000525f80}, 0xc000198380, {0xd915a8, 0xc000ef0720}, {{0xc000316140, 0x1, 0x1}, 0x0, ...})           
    /home/runner/work/mongodb_exporter/mongodb_exporter/exporter/exporter.go:200 +0xbc5                                                                                                               
github.com/percona/mongodb_exporter/exporter.(*Exporter).Handler.func1({0xd933d8, 0xc0001982a0}, 0xc0000d4b00)                                                                                        
    /home/runner/work/mongodb_exporter/mongodb_exporter/exporter/exporter.go:318 +0x4c5                                                                                                               
net/http.HandlerFunc.ServeHTTP(0x0, {0xd933d8, 0xc0001982a0}, 0x0)                                                                                                                                    
    /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:2047 +0x2f                                                                                                                             
net/http.(*ServeMux).ServeHTTP(0x0, {0xd933d8, 0xc0001982a0}, 0xc0000d4b00)                                                                                                                           
    /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:2425 +0x149                                                                                                                            
net/http.serverHandler.ServeHTTP({0xc00112c3c0}, {0xd933d8, 0xc0001982a0}, 0xc0000d4b00)                                                                                                              
    /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:2879 +0x43b                                                                                                                            
net/http.(*conn).serve(0xc0002d0c80, {0xd961d8, 0xc0002d3b60})                                                                                                                                        
    /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:1930 +0xb08                                                                                                                            
created by net/http.(*Server).Serve                                                                                                                                                                   
    /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:3034 +0x4e8    
```
and after some time
```bash
time="2023-01-24T08:12:18Z" level=error msg="cannot decode getCmdLineOtpions: cannot execute getCmdLineOpts command: context canceled"                                                                
time="2023-01-24T08:12:18Z" level=error msg="cannot retrieve MongoDB buildInfo: Failed to run buildInfo command: context canceled"                                                                    
time="2023-01-24T08:12:18Z" level=error msg="Cannot get node type to check if this is a mongos: context canceled" component=diagnosticDataCollector                                                   
time="2023-01-24T08:12:19Z" level=error msg="cannot decode getCmdLineOtpions: cannot execute getCmdLineOpts command: context canceled"                                                                
time="2023-01-24T08:12:19Z" level=error msg="cannot retrieve MongoDB buildInfo: Failed to run buildInfo command: context canceled"                                                                    
time="2023-01-24T08:12:20Z" level=error msg="Cannot get node type to check if this is a mongos: context canceled" component=diagnosticDataCollector   
```

### Are you using any custom parameters or values?

I use the following `values.yaml`:
```yaml
architecture: replicaset
replicaCount: 2

auth:
  rootUser: root
  rootPassword: <ROOT_PASSWORD>
  replicaSetKey: <MONGO_REPLICA_SET_KEY>

persistence:
  size: 10Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  readinessProbe:
    timeoutSeconds: 5
```

### What is the expected behavior?

That the metrics sidecar does not crash by default.

### What do you see instead?

A crashing metrics sidecar that seems to have problems with the mongodb container.

### Additional information

Nothing to add.

**Comment by dgomezleon** [comment]
Hello @StevenCyb,

Could you try with higher values for readiness and liveness probes? E.g.:

```
metrics:
...
  livenessProbe:
    enabled: true
    initialDelaySeconds: 25
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
 ...
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
```

**Comment by StevenCyb** [comment]
I had taken over your values and it worked. After that I have progressively reduced it to 10 and it still runs. 
I also noticed that 10 sec timeout corresponds to the chart default. That was probably a mistake on my part to set the value to 5. 
```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  livenessProbe:
    timeoutSeconds: 10
  readinessProbe:
    timeoutSeconds: 10
```

Now it seams to work stable. At least I know that increasing the timeout could fix the problem in the future.
Thanks 👍

**Comment by busyboy77** [comment]
I had to increase the limits/requests to adjust CrashLoopBackoffs

```YAML
  resources:
    ## Example:
    limits:
        cpu: 200m
        memory: 512Mi
    ##
    #limits: {}
    ## Examples:
    requests:
       cpu: 150m
       memory: 512Mi
```
along with

```YAML
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 30
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 30
    failureThreshold: 3
    successThreshold: 1
```

mongodb exporter is stable now, 

```
root@devops63:~/cim-solution/kubernetes# k -n ef-external get pods -o wide
NAME                     READY   STATUS    RESTARTS   AGE     IP           NODE              NOMINATED NODE   READINESS GATES
mongo-mongodb-0          2/2     Running   0          5h44m   10.42.4.43   devops68.ef.com   <none>           <none>
```


but still getting these errors in logs


```
time="2023-11-05T19:27:47Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
time="2023-11-05T19:27:56Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
time="2023-11-05T19:28:12Z" level=error msg="Failed to get $dbstats for database admin: context deadline exceeded"
time="2023-11-05T19:28:12Z" level=error msg="Failed to get $dbstats for database config: context deadline exceeded"
time="2023-11-05T19:28:12Z" level=error msg="Failed to get $dbstats for database local: context deadline exceeded"
time="2023-11-05T19:28:22Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
time="2023-11-05T19:28:24Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
time="2023-11-05T19:28:44Z" level=error msg="cannot get replSetGetStatus: context deadline exceeded"
time="2023-11-05T19:28:45Z" level=error msg="Cannot get node type to check if this is a mongos: timed out while checking out a connection from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0" component=diagnosticDataCollector
time="2023-11-05T19:29:45Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
2023/11/05 19:30:15 http: panic serving 10.42.5.20:49044: descriptor Desc{fqName: "", help: "", constLabels: {}, variableLabels: []} is invalid: context deadline exceeded
goroutine 411106 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:1802 +0xb9
panic({0xb22da0, 0xc001120510})
        /opt/hostedtoolcache/go/1.17.12/x64/src/runtime/panic.go:1047 +0x266
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xd97ce0, {0xc0007897e0, 0x1, 0x8})
        /home/runner/go/pkg/mod/github.com/!percona-!lab/client_golang@v1.12.2-0.20220701073455-ee06569fd6a5/prometheus/registry.go:403 +0x7f
github.com/percona/mongodb_exporter/exporter.(*Exporter).makeRegistry(0xc00007ff90, {0xd97ce0, 0xc000fe2000}, 0xc000690000, {0xd93168, 0xc0012c6f30}, {{0xc00016fc90, 0x1, 0x1}, 0x0, ...})
        /home/runner/work/mongodb_exporter/mongodb_exporter/exporter/exporter.go:195 +0xbc5
github.com/percona/mongodb_exporter/exporter.(*Exporter).Handler.func1({0xd94f80, 0xc0002a00e0}, 0xc000b72000)
        /home/runner/work/mongodb_exporter/mongodb_exporter/exporter/exporter.go:306 +0x405
net/http.HandlerFunc.ServeHTTP(0x0, {0xd94f80, 0xc0002a00e0}, 0x0)
        /opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0xd94f80, 0xc0002a00e0}, 0xc000b72000)
        /opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc000a94090}, {0xd94f80, 0xc0002a00e0}, 0xc000b72000)
        /opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc001572140, {0xd97d18, 0xc0002d2c00})
        /opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:3034 +0x4e8
time="2023-11-05T19:30:36Z" level=error msg="cannot get replSetGetStatus: connection(localhost:27017[-14322]) failed to read: context deadline exceeded"
time="2023-11-05T19:30:46Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
time="2023-11-05T19:30:48Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
time="2023-11-05T19:30:56Z" level=error msg="cannot get replSetGetStatus: connection(localhost:27017[-14334]) failed to read: context deadline exceeded"
time="2023-11-05T19:31:10Z" level=error msg="Failed to get $dbstats for database admin: connection(localhost:27017[-14343]) incomplete read of full message: context deadline exceeded"
time="2023-11-05T19:31:10Z" level=error msg="Failed to get $dbstats for database config: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 1"
time="2023-11-05T19:31:10Z" level=error msg="Failed to get $dbstats for database local: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 1"
time="2023-11-05T19:31:18Z" level=error msg="Cannot get node type to check if this is a mongos: context deadline exceeded" component=diagnosticDataCollector
time="2023-11-05T19:31:45Z" level=error msg="Cannot get node type to check if this is a mongos: timed out while checking out a connection from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0" component=diagnosticDataCollector
```
