### ISSUE TITLE
[bitnami/airflow] git sync dags and packages bug

### ISSUE THREAD

**Issue by alon050** [bitnami/charts#14922]
### Name and Version

bitnami/airflow 14.0.2

### What steps will reproduce the bug?

we are running airflow helm chart on an on-prem openshift cluster and we did the git sync interval to 30 seconds and tasks that run more than 30 seconds.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

task working fluently

### What do you see instead?

instead we get an error Dag '*' could not be found; either it does not exist or it failed to parse. and the next log is celery command failed on host: worker-name with celery_task id <task-id> 
from my understanding that happens when a worker is running a task and the git pull command running over the file that the task is pointing to, and then the worker no longer knows which task he should run .

### Additional information

in the original helm chart of airflow they use git-sync container which they state that: GitSync does it properly - it checks out the whole DAG folder to a separate folder and swaps symbolic link pointing to it, so that there is never a case that DAG files are empty or missing

**Comment by Mauraza** [comment]
Hi @alon050,

Could you add the logs? Are you using a private repository?
Do you obtain the same result if you run a `git pull`?

**Comment by alon050** [comment]
Unfortunately i cant provide the full stacktrace because it is in a closed network, but it looks something like this:
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 282, in task_run
    dag = get_dag(args.subdir, args.dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 193, in get_dag
    f"Dag {dag_id!r} could not be found; either it does not exist or it failed to parse."
airflow.exceptions.AirflowException: Dag 'xxxxx' could not be found; either it does not exist or it failed to parse
[2022-01-20 18:22:09,784: ERROR/ForkPoolWorker-16] Task airflow.executors.celery_executor.execute_command[2911ab23-945b-4526-9971-aadf20a04536] raised unexpected: AirflowException('Celery command failed on host: airflow-act.internal.cloudapp.net')
Traceback (most recent call last):
  File "/opt/airflow/.env/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/airflow/.env/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/airflow/.env/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/opt/airflow/.env/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 101, in _execute_in_fork
    raise AirflowException('Celery command failed on host: ' + get_hostname())
airflow.exceptions.AirflowException: Celery command failed on host:*
The repo is public and the files are being pulled, but if there was a change in the repo and a dag was running at the time, it crashes those are the logs

**Comment by alon050** [comment]
I got those logs from the internet so they are not accurate 100% but this is what i see

**Comment by Mauraza** [comment]
Hi @alon050,

Is Your only change of values the configuration of the repo? If you change something more could you share that values?

**Comment by alon050** [comment]
hey, i have changed alot in the values and the images themselves but they contain confidential information.
in short, i only configured them to work with a private pip repo, uploaded to the git, a certificate to a private gitlab server, and added oracle client to every image of the airflow. i know its alot of thing but the issue is not here, to my knowledge

**Comment by alon050** [comment]
accidently pressed close with comment

**Comment by Mauraza** [comment]
Hi @alon050,

Did you try to change debug to true? and check if there is more information in the logs. 
https://github.com/bitnami/charts/blob/44a96694cc259f65fec4b98641e5b7ad64d70477/bitnami/airflow/values.yaml#L203-L205

**Comment by alon050** [comment]
I will try that and return to u with an answer. THX

**Comment by alon050** [comment]
I will try that and return to u with an answer. THX

**Comment by Mauraza** [comment]
Hi @alon050,

Has anything else shown up in the logs?
