### ISSUE TITLE
[bitnami/kafka] kafka image - zookeper script is being called when KAFKA_ENABLE_KRAFT="yes"

### ISSUE THREAD

**Issue by jwojcie** [bitnami/charts#15111]
### Name and Version

bitnami/kafka:3.3.1-debian-11-r25

### What steps will reproduce the bug?

My kubectl conf file relevant fragment:

```
 spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.3.1-debian-11-r25
          volumeMounts:
            - name: kafka-keystore
              mountPath: /bitnami/kafka/config/certs
              readOnly: true
            - name: kafka-truststore
              mountPath: /bitnami/kafka/config/certs/truststore
              readOnly: true
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LISTENERS
              value: "INTERNAL://:9093,CLIENT://:9092,CONTROLLER://:9094"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:SSL,CLIENT:SASL_SSL"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:9093,CLIENT://127.0.0.1:30035"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CLIENT_USERS
              value: "user"
            - name: KAFKA_CLIENT_PASSWORDS
              value: "password"
            - name: KAFKA_CERTIFICATE_PASSWORD
              value: "password"
            - name: KAFKA_TLS_TRUSTSTORE_FILE
              value: "/bitnami/kafka/config/certs/truststore/kafka.truststore.jks"
          ports:
            - containerPort: 9092
            - containerPort: 9093
      volumes:
        - name: kafka-keystore
          secret:
            secretName: ssl-keystore-cert
        - name: kafka-truststore
          secret:
            secretName: ssl-truststore-cert
```

Container freezes at that last zookeper related line:
```
kafka 23:34:43.24 
kafka 23:34:43.24 Welcome to the Bitnami kafka container
kafka 23:34:43.25 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 23:34:43.25 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 23:34:43.25 
kafka 23:34:43.25 INFO  ==> ** Starting Kafka setup **
kafka 23:34:43.36 INFO  ==> Initializing Kafka...
kafka 23:34:43.38 INFO  ==> Copying truststore /bitnami/kafka/config/certs/truststore/kafka.truststore.jks to /opt/bitnami/kafka/config/certs
kafka 23:34:43.38 INFO  ==> No injected configuration files found, creating default config files
kafka 23:34:43.87 INFO  ==> Configuring Kafka for inter-broker communications with SSL authentication.
kafka 23:34:44.11 INFO  ==> Configuring Kafka for client communications with SASL_SSL authentication.
kafka 23:34:44.20 INFO  ==> Generating JAAS authentication file
kafka 23:34:44.28 INFO  ==> Creating users in Zookeeper
```
looking at the scripts, in libkafka.sh in kafka_initialize function in that fragment:
```
        if [[ "${internal_protocol:-}" =~ "SASL" || "${client_protocol:-}" =~ "SASL" || "${external_client_protocol:-}" =~ "SASL" ]] || [[ "${KAFKA_ZOOKEEPER_PROTOCOL}" =~ SASL ]]; then
            if [[ -n "$KAFKA_CFG_SASL_ENABLED_MECHANISMS" ]]; then
                kafka_server_conf_set sasl.enabled.mechanisms "$KAFKA_CFG_SASL_ENABLED_MECHANISMS"
                kafka_generate_jaas_authentication_file "${internal_protocol:-}" "${client_protocol:-}"
                [[ "$KAFKA_CFG_SASL_ENABLED_MECHANISMS" =~ "SCRAM" ]] && kafka_create_sasl_scram_zookeeper_users
            else
                print_validation_error "Specified SASL protocol but no SASL mechanisms provided in KAFKA_CFG_SASL_ENABLED_MECHANISMS"
            fi
        fi
```

it looks to me that kafka_create_sasl_scram_zookeeper_users is being called.
I don't understand why should it since I've choosen KRAFT as per my settings:
```
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
```
I should mention that before adding security settings, image was working fine in the KRAFT mode.

Is it something wrong with my settings or is there kraft flag missing in that ini function?

### What is the expected behavior?

Secured kraft version of container.

### What do you see instead?

Freezed initialization and container failure.

**Comment by javsalgar** [comment]
Hi,

Could enable the debug flag in the image? It is `image.debug=true`. This should add more insight on the issue.

**Comment by jwojcie** [comment]
Hi,

I've added that flage to my kubectl config file:
 ```
           - name: BITNAMI_DEBUG
              value: "true"
```
and I got more info:

```
kafka 14:59:06.21 
kafka 14:59:06.22 Welcome to the Bitnami kafka container
kafka 14:59:06.22 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 14:59:06.23 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 14:59:06.23 
kafka 14:59:06.23 INFO  ==> ** Starting Kafka setup **
kafka 14:59:06.34 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka 14:59:06.38 INFO  ==> Initializing Kafka...
kafka 14:59:06.41 INFO  ==> Copying truststore /bitnami/kafka/config/certs/truststore/kafka.truststore.jks to /opt/bitnami/kafka/config/certs
kafka 14:59:06.41 INFO  ==> No injected configuration files found, creating default config files
kafka 14:59:06.86 INFO  ==> Configuring Kafka for inter-broker communications with SSL authentication.
kafka 14:59:07.06 INFO  ==> Configuring Kafka for client communications with SASL_SSL authentication.
kafka 14:59:07.11 INFO  ==> Generating JAAS authentication file
kafka 14:59:07.17 INFO  ==> Creating users in Zookeeper
kafka 14:59:07.19 DEBUG ==> Creating user user in zookeeper
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
[2023-02-24 14:59:11,879] WARN SASL configuration failed. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/opt/bitnami/kafka/config/kafka_jaas.conf'.
        at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:189)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1161)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1210)
[2023-02-24 14:59:11,911] ERROR [ZooKeeperClient ConfigCommand] Auth failed, initialized=false connectionState=CONNECTING (kafka.zookeeper.ZooKeeperClient)
[2023-02-24 14:59:11,938] WARN Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2023-02-24 14:59:13,041] WARN SASL configuration failed. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/opt/bitnami/kafka/config/kafka_jaas.conf'.
        at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:189)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1161)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1210)
[2023-02-24 14:59:13,043] ERROR [ZooKeeperClient ConfigCommand] Auth failed, initialized=false connectionState=CONNECTING (kafka.zookeeper.ZooKeeperClient)
[2023-02-24 14:59:13,044] WARN Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2023-02-24 14:59:14,145] WARN SASL configuration failed. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/opt/bitnami/kafka/config/kafka_jaas.conf'.
        at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:189)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1161)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1210)
[2023-02-24 14:59:14,147] ERROR [ZooKeeperClient ConfigCommand] Auth failed, initialized=false connectionState=CONNECTING (kafka.zookeeper.ZooKeeperClient)
[2023-02-24 14:59:14,147] WARN Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2023-02-24 14:59:15,249] WARN SASL configuration failed. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/opt/bitnami/kafka/config/kafka_jaas.conf'.
        at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:189)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1161)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1210)
[2023-02-24 14:59:15,250] ERROR [ZooKeeperClient ConfigCommand] Auth failed, initialized=false connectionState=CONNECTING (kafka.zookeeper.ZooKeeperClient)
[2023-02-24 14:59:15,250] WARN Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
```

That exception is being raised over and over again. Just to again put that in the context: I've set flag to NOT use zookeper in the deployment but KRAFT. It looks like though it is trying to connect to zookeper anyway.

**Comment by corico44** [comment]
Hello @jwojcie,

We are currently working on the implementation to add support for Kraft mode in Kafka. We will review the error that you tell us and we will notify you as soon as possible.

**Comment by fmulero** [comment]
Thanks to @koraven, a new version of the chart with [kraft mode was released](https://github.com/bitnami/charts/pull/14850) Could you give it a try?

**Comment by corico44** [comment]
Hello @jwojcie,

Using the latest version of the chart with the image indicated in the values.yaml should work. You shouldn't have to indicate any specific image. Only using version 21.3.0 or higher of the chart should work.

**Comment by jwojcie** [comment]
hi @corico44,

so I did try it and the issue persists:
- I cleaned docker
- I used I think the latest version of image: bitnami/kafka:3.4.0-debian-11-r11

and again the image fails to start and frozes at the line: "Creating users in Zookeeper" though I used the flag:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"

am I doing something wrong?

Regards

**Comment by corico44** [comment]
@jwojcie Could you try using image _bitnami/kafka:3.4.0-debian-11-r13_? And the value of _KAFKA_ENABLE_KRAFT_ should be _"true"_ and not _"yes"_, as we can see in the file _bitnami/kafka/templates/statefulset.yaml_ in _line 381_ [here.](https://github.com/bitnami/charts/pull/14850/files#diff-7896265e1ff0b94b6c11ea77fcd0c8827339cea0b3fe40328887aba55e8bb4fa)

**Comment by Bockit** [comment]
I have run into this as well, though through docker-compose.

Noticed with `image: docker.io/bitnami/kafka:3.4` and tried with `bitnami/kafka:3.4.0-debian-11-r13` as well. I've used `true` and `yes` for `KAFKA_ENABLE_KRAFT`. In all 4 cases (yes and true with each image) it has the following output:

```
kafka 05:45:54.58 Welcome to the Bitnami kafka container
kafka 05:45:54.58 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 05:45:54.58 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 05:45:54.58 
kafka 05:45:54.59 INFO  ==> ** Starting Kafka setup **
kafka 05:45:54.67 INFO  ==> Initializing Kafka...
kafka 05:45:54.67 INFO  ==> No injected configuration files found, creating default config files
kafka 05:45:54.82 INFO  ==> Configuring Kafka for client communications with SASL_SSL authentication.
kafka 05:45:54.86 INFO  ==> Generating JAAS authentication file
kafka 05:45:54.87 INFO  ==> Creating users in Zookeeper
```

Docker compose file.

```
version: '3.9'

volumes:
  kafka_data:
    driver: local

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4.0-debian-11-r13
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
      - './secrets/broker/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './secrets/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,CLIENT:SASL_SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://127.0.0.1:9092
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CLIENT_USERS=application
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_TLS_TYPE=JKS
```

Disclaimer: I'm not sure the SSL configuration is going to work, I'm trying to work out how it should be set up with Kraft instead of Zookeeper.

**Comment by carrodher** [comment]
Yes, Kraft support was added, [here](https://github.com/bitnami/charts/pulls?q=is%3Apr+kraft+label%3Akafka+) you can see some PRs implementing this feature, mainly https://github.com/bitnami/charts/pull/14850 and https://github.com/bitnami/charts/pull/15768
