### ISSUE TITLE
Unable to acquire JDBC Connection - Kubernetes Bitnami Chart, PostgreSQL HA, Node Down

### ISSUE THREAD

**Issue by todortanevski** [bitnami/charts#15335]
### Name and Version

keycloak 13.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Before reporting an issue

I have searched existing issues
I have reproduced the issue with the latest release

Area

dist/quarkus
Describe the bug

Hello Team,

Kubernetes cluster, these apps installed:

    bitnami chart - keycloak
    bitnami chart - postgresql-ha

Everything works until we test with shutting down one kubernetes worker node (on which keycloak and/or postgresql pods are running).

Then we get an error which seems related to inability to create new JDBC connections, it only reuses existing ones, so actually keycloak works sporadically.

Current workaround is to start the node and delete active keycloak pods.

Is this fixable with manipulating these (or similar) Quarkus values?

```
quarkus.datasource.jdbc.min-size=4
quarkus.datasource.jdbc.max-size=50
quarkus.datasource.jdbc.max-lifetime=150
quarkus.datasource.jdbc.idle-removal-interval=50
```
Can these or similar parameters be enabled in this helm chart?

Logs are like this:

```
2023-02-28 12:36:02,282 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 0, SQLState: null
2023-02-28 12:36:02,282 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) Acquisition timeout while waiting for new connection
2023-02-28 12:36:02,283 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredUserSessions: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
...
```

Have you noticed these issues and is this something that has been worked upon?

Thanks!

### Are you using any custom parameters or values?

```
auth:
  adminUser: admin
  adminPassword: ****

replicaCount: 3

httpRelativePath: "/auth/"

postgresql:
  enabled: false

externalDatabase:
  host: ****
  port: 5432
  user: ****
  database: ****
  password: ****
```

### What is the expected behavior?

Shutting down the kubernetes worker node should not affect Keycloak functioning.

### What do you see instead?

Keycloak malfunctions as described in 'What steps will reproduce the bug?' text.

### Additional information

Posted this bug to keycloak forum, albeit here is more appropriate as to enabling the parameters going to keycloak/quarkus.

**Comment by dgomezleon** [comment]
Hi @todortanevski ,

Checking [this quarkus documentation](https://es.quarkus.io/guides/config-reference#system-properties), you could try something like this to use those values:


```
+++ b/bitnami/keycloak/templates/configmap-env-vars.yaml
@@ -47,7 +47,7 @@ data:
   {{- if .Values.cache.stackFile }}
   KEYCLOAK_CACHE_CONFIG_FILE: {{ .Values.cache.stackFile | quote }}
   {{- end }}
-  JAVA_OPTS_APPEND: {{ printf "-Djgroups.dns.query=%s-headless.%s.svc.%s" (include "common.names.fullname" .) (include "common.names.namespace" .) .Values.clusterDomain | quote }}
+  JAVA_OPTS_APPEND: {{ printf "-Dquarkus.datasource.jdbc.max-lifetime=150 -Dquarkus.datasource.jdbc.idle-removal-interval=50 -Dquarkus.datasource.jdbc.max-size=50 -Dquarkus.datasource.jdbc.min-size=4 -Djgroups.dns.query=%s-headless.%s.svc.%s" (include "common.names.fullname" .) (include "common.names.namespace" .) .Values.clusterDomain | quote }}
   {{- else }}
   KEYCLOAK_CACHE_TYPE: "local"
   {{- end }}
```

I hope it helps

**Comment by todortanevski** [comment]
Hi @dgomezleon !

This seems to work almost perfectly. We added this line:

`JAVA_OPTS_APPEND: {{ printf "-Dquarkus.datasource.jdbc.min-size=10 -Dquarkus.datasource.jdbc.initial-size=10 -Dquarkus.datasource.jdbc.max-size=20 -Dquarkus.datasource.jdbc.max-lifetime=600 -Dquarkus.datasource.jdbc.idle-removal-interval=300 -Dquarkus.datasource.jdbc.background-validation-interval=15 -Dquarkus.datasource.jdbc.foreground-validation-interval=15 -Djgroups.dns.query=%s-headless.%s.svc.%s" (include "common.names.fullname" .) (include "common.names.namespace" .) .Values.clusterDomain | quote }}
`

There is a, still, sometimes later, occurrence of that bug. It needs time (like 5+ times of shutting random k8s node down and bringing it up again). The error is "_Unable to acquire JDBC Connection_":

```
2023-03-09T11:34:44.477656248+01:00 2023-03-09 10:34:44,477 WARN [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-5) SQL Error: 0, SQLState: null

2023-03-09T11:34:44.477690360+01:00 2023-03-09 10:34:44,477 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-5) Acquisition timeout while waiting for new connection

2023-03-09T11:34:44.478441348+01:00 2023-03-09 10:34:44,477 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection

2023-03-09T11:34:44.478459114+01:00 at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)

2023-03-09T11:34:44.478461309+01:00 at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)

2023-03-09T11:34:44.478463099+01:00 at org.hibernate.query.Query.getResultList(Query.java:165)

2023-03-09T11:34:44.478464654+01:00 at org.keycloak.models.jpa.JpaRealmProvider.getRealmByName(JpaRealmProvider.java:155)
...
```

This might be keycloak's own bug, untied to this chart; regardless, do you think it can be solved within this forum?

Thanks very much!

Best Regards,
Todor

**Comment by dgomezleon** [comment]
Hi @todortanevski ,

I'm glad it helped.

In this case, I would suggest opening an upstream ticket so keycloak's experts can help you to fine-tune these parameters for your scenario.

**Comment by vcakarov** [comment]
Hi @dgomezleon , 

We opened an issue on Keycloak about this (https://github.com/keycloak/keycloak/issues/17610), but they insist it's not their problem, as it happens when using 3rd party (your) HELM chart. 

What do you suggest?

Best regards,
Vladimir

**Comment by dgomezleon** [comment]
Hi @vcakarov ,

Thanks for sharing the case you opened.

We were not able to reproduce the issue. It seems a very specific use case difficult to reproduce on our side and very tied to some specific scenarios.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology. Although in this case, it seems this path doesn’t help at all. Maybe, they could help to find the best combination of quarkus values to avoid issues.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
