### ISSUE TITLE
Cannot enable permissions on Groups and Realm Roles

### ISSUE THREAD

**Issue by rizziemma** [bitnami/charts#15480]
### Name and Version

bitnami/keycloak:20.0.5-debian-11-r4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deployed Keycloak on kubernetes 1.26 with the Helm chart and an external Postgresql database in the same namespace.
2. On Keycloak as admin : create a realm and a group
3. On group settings, Permissions tab : click Permissions enabled
4. Nothing happens

### Are you using any custom parameters or values?

```yaml
auth:
  adminUser: ###
  adminPassword: ###

production: false
proxy: passthrough

service:
  type: NodePort
  http:
    enabled: true
    http: 80
    https: 443

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  hostname: ###
  path: /
  servicePort: http
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt-prod",
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  }
  tls: true

postgresql:
  enabled: false
externalDatabase:
  host: database
  port: 5432
  user: ###
  password: ###
  database: keycloak
```

### What is the expected behavior?

The permission toggles switch to ON

### What do you see instead?

Nothing changed on the UI.

With network inspection, I see the following error : 
```json
PUT : https://###/admin/realms/services/roles-by-id/1ee9ef50-e9b5-457b-9988-801bc90e039f/management/permissions
RESPONSE :
{
  "message": "Request failed with status code 500",
  "name": "AxiosError",
  "code": "ERR_BAD_RESPONSE",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {
      "FormData": null
    },
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json",
      "Authorization": "bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIc3pXV1YtcGNRNmZXWnp5d00tSWpDVGk0OTliWS1hdk1OUGpEQ2hKLVRvIn0.eyJleHAiOjE2Nzg3MjU4NTgsImlhdCI6MTY3ODcyNTc5OCwiYXV0aF90aW1lIjoxNjc4NzIyNTk4LCJqdGkiOiJlZjMwNGNjNC0xMThlLTQ2MmUtOTliYi1iMjJiMTYyYzQ4ZDciLCJpc3MiOiJodHRwczovL2F1dGgubXVybXVyZW8uY29tL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI2MjM1MGMxMy0yNmEzLTQ3M2YtYWRmNS0zZGNkZGVkZmExNjgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzZWN1cml0eS1hZG1pbi1jb25zb2xlIiwibm9uY2UiOiI3NGQ4ZjZiOS1mZjVhLTRhZjEtODM3ZC02ODEzYmM4ZTIxMDYiLCJzZXNzaW9uX3N0YXRlIjoiMWI5MTI1YTYtMzQyMC00ODIxLThiOTEtMzRiOTIyNGEwMjgxIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2F1dGgubXVybXVyZW8uY29tIl0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiIxYjkxMjVhNi0zNDIwLTQ4MjEtOGI5MS0zNGI5MjI0YTAyODEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6Im11cm11cmVvIn0.db3Uni7KmlQdbQLXps-Ng55qync9q6P2cLzurFsRIeg3-GCBwGz0Wp0wwSqcNESBikg63y6IuLVUshs1zqBEiBlnZgQWKu40skqFGc30Y1JHd9kezE6aK95RJ1-Is7HJEqOKyqWvyaZDhhN9eBhmqXrSDSl67F7Oak_MBUA110Xho70dLK8iQE3Dlvp1nt9Io46CKLJoUwouG5vTjWtHbxk822uiBzAeRHJE4soxFsWvXe-u4-viRwAGn1aCC_zbrV1HvHAxiRveainM2p0QCKO7AKUvCM95N1_HoUJV3wYDjsXeHFv3DfhupIIxpq7LClu8Mf5tqyLT6rInBnwQTQ"
    },
    "method": "put",
    "url": "https://###/admin/realms/services/roles-by-id/1ee9ef50-e9b5-457b-9988-801bc90e039f/management/permissions",
    "data": "{\"enabled\":true}",
    "params": {}
  },
  "request": {},
  "response": {
    "data": {
      "error": "unknown_error"
    },
    "status": 500,
    "statusText": "Internal Server Error",
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "https://###",
      "access-control-expose-headers": "Location",
      "content-length": "25",
      "content-type": "application/json",
      "date": "Mon, 13 Mar 2023 16:43:23 GMT",
      "referrer-policy": "no-referrer",
      "strict-transport-security": "max-age=15724800; includeSubDomains",
      "x-content-type-options": "nosniff",
      "x-firefox-spdy": "h2",
      "x-frame-options": "SAMEORIGIN",
      "x-xss-protection": "1; mode=block"
    },
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {
        "FormData": null
      },
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "Authorization": "bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIc3pXV1YtcGNRNmZXWnp5d00tSWpDVGk0OTliWS1hdk1OUGpEQ2hKLVRvIn0.eyJleHAiOjE2Nzg3MjU4NTgsImlhdCI6MTY3ODcyNTc5OCwiYXV0aF90aW1lIjoxNjc4NzIyNTk4LCJqdGkiOiJlZjMwNGNjNC0xMThlLTQ2MmUtOTliYi1iMjJiMTYyYzQ4ZDciLCJpc3MiOiJodHRwczovL2F1dGgubXVybXVyZW8uY29tL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI2MjM1MGMxMy0yNmEzLTQ3M2YtYWRmNS0zZGNkZGVkZmExNjgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzZWN1cml0eS1hZG1pbi1jb25zb2xlIiwibm9uY2UiOiI3NGQ4ZjZiOS1mZjVhLTRhZjEtODM3ZC02ODEzYmM4ZTIxMDYiLCJzZXNzaW9uX3N0YXRlIjoiMWI5MTI1YTYtMzQyMC00ODIxLThiOTEtMzRiOTIyNGEwMjgxIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2F1dGgubXVybXVyZW8uY29tIl0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiIxYjkxMjVhNi0zNDIwLTQ4MjEtOGI5MS0zNGI5MjI0YTAyODEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6Im11cm11cmVvIn0.db3Uni7KmlQdbQLXps-Ng55qync9q6P2cLzurFsRIeg3-GCBwGz0Wp0wwSqcNESBikg63y6IuLVUshs1zqBEiBlnZgQWKu40skqFGc30Y1JHd9kezE6aK95RJ1-Is7HJEqOKyqWvyaZDhhN9eBhmqXrSDSl67F7Oak_MBUA110Xho70dLK8iQE3Dlvp1nt9Io46CKLJoUwouG5vTjWtHbxk822uiBzAeRHJE4soxFsWvXe-u4-viRwAGn1aCC_zbrV1HvHAxiRveainM2p0QCKO7AKUvCM95N1_HoUJV3wYDjsXeHFv3DfhupIIxpq7LClu8Mf5tqyLT6rInBnwQTQ"
      },
      "method": "put",
      "url": "https://###/admin/realms/services/roles-by-id/1ee9ef50-e9b5-457b-9988-801bc90e039f/management/permissions",
      "data": "{\"enabled\":true}",
      "params": {}
    },
    "request": {}
  }
}

```

In the server logs I see : 

```
2023-03-13 16:33:11,980 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-34) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.authorization.model.Resource.getId()" because the return value of "org.keycloak.services.resources.admin.permissions.RolePermissionManagement.resource(org.keycloak.models.RoleModel)" is null
        at org.keycloak.services.resources.admin.RoleByIdResource.toMgmtRef(RoleByIdResource.java:276)
        at org.keycloak.services.resources.admin.RoleByIdResource.setManagementPermissionsEnabled(RoleByIdResource.java:300)
        at jdk.internal.reflect.GeneratedMethodAccessor421.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Additional information

My goal is to define group based permissions on sub-domains. Example, group1 should have access to pages on `my.service.com/group1/*`. I'm still trying to understand Keycloak so maybe I'm not looking at the right feature to do this!

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami keycloak container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by popdaniel942** [comment]
Hello. I ran into the same problem but then I found this [https://github.com/keycloak/keycloak/issues/17186](url) . Maybe this will help.
