### ISSUE TITLE
In kuberneteExecutor with ezternal dag using config through error dag cannot be imported

### ISSUE THREAD

**Issue by adsouza75** [bitnami/charts#15516]
### Name and Version

bitnami/airflow

### What architecture are you using?

None

### What steps will reproduce the bug?

In kuberneteExecutor with external dag using config through error dag cannot be imported
```
Requirement already satisfied: oauthlib>=3.0.0 in /opt/bitnami/airflow/venv/lib/python3.8/site-packages (from requests-oauthlib>=0.5.0->msrest>=0.6.18->azure-storage-blob->-r /bitnami/python/requirements.txt (line 1)) (3.2.0)
Installing collected packages: pyodbc, pycryptodomex, oscrypto, snowflake-connector-python, snowflake-sqlalchemy
Successfully installed oscrypto-1.3.0 pycryptodomex-3.17 pyodbc-4.0.35 snowflake-connector-python-3.0.1 snowflake-sqlalchemy-1.4.6

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip

[←[34m2023-03-15 23:22:27,952←[0m] {←[34mcli_action_loggers.py:←[0m105} WARNING←[0m - Failed to log action with (psycopg2.OperationalError) server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
FATAL:  SSL connection is required. Please specify SSL options and retry.

(Background on this error at: https://sqlalche.me/e/14/e3q8)←[0m
[←[34m2023-03-15 23:22:27,965←[0m] {←[34mdagbag.py:←[0m508} INFO←[0m - Filling up the DagBag from /opt/bitnami/airflow/dags/external/CobraPipeByTPA.py←[0m
/opt/bitnami/airflow/venv/lib/python3.8/site-packages/snowflake/connector/options.py:107 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[←[34m2023-03-15 23:22:28,907←[0m] {←[34mdagbag.py:←[0m321} ERROR←[0m - Failed to import: /opt/bitnami/airflow/dags/external/CobraPipeByTPA.py←[0m
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/external/CobraPipeByTPA.py", line 13, in <module>
    import pyodbc;
ImportError: libodbc.so.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 38, in main
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 361, in task_run
    dag = get_dag(args.subdir, args.dag_id)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 203, in get_dag
    raise AirflowException(
airflow.exceptions.AirflowException: Dag 'CobraPipeByTPA' could not be found; either it does not exist or it failed to parse.
```
### Are you using any custom parameters or values?
```yaml
global:
  imagePullSecrets:
  - algrptcrmuseadataint

existingConfigmap: airflow-config

dags:
  existingConfigmap: airflow-dagdeploy

externalDatabase:
  database: airflow
  port: 5432

externalRedis:
  port: 6380

extraVolumeMounts:
  - name: airflow-requirements
    mountPath: /bitnami/python/requirements.txt
    subPath: requirements.txt
    readOnly: true

extraVolumes: 
  - name: airflow-requirements
    configMap: 
      name: airflow-requirements

postgresql:
  enabled: false

redis:
  enabled: false

scheduler:
  image:
    registry: 
    repository: bitnami/airflow-scheduler

web:
  image:
    registry: algrptcrmuseadataint.azurecr.io
    repository: bitnami/airflow

#worker:
#   podTemplate:
#     name: pod-template
#  image:
#    debug: true -n airflow
#    registry: 
#    repository: bitnami/airflow-worker
#    tag: 154758
#  autoscaling:
#    enabled: true
#  resources:
#    requests.cpu: 200m
#    requests:
#      memory: 250Mi

#airflow:
#  workerImage: :154758

# executor: KubernetesExecutor

rbac:
  create: true

serviceaccount:
  create: true
```
### What is the expected behavior?

Dag to run successfully

### What do you see instead?

Error

**Comment by fmulero** [comment]
Sorry @adsouza75 I'll need a more time to try to reproduce your issue. Please bare with me.
