### ISSUE TITLE
CASSANDRA: (Connection error: ('Unable to connect to any servers)

### ISSUE THREAD

**Issue by antikilahdjs** [bitnami/charts#15548]
### Name and Version

bitnami/cassandra:4.1.0-debian-11-r17

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install using the normal way `helm install bitnami/cassandra ...`

### What is the expected behavior?

I am facing many troubles inside of my environment due to a large workload and many requests like, read and write. The Cassandra running for almost 3 hours the error happens.

Connection error: 
```
'Unable to connect to any servers', {'1xx.xx.xx.xx': OperationTimedOut('errors=None, last_host=None',)}
```

I saw a forum and the guys guide to change `~./cassandra/cqlshrc` timeout and `cqlsh.py`. My question is, there is possible a way to change it permanently? I tried to check the source from Cassandra but I guess it does not exist because I can clone and change files and build it again but I guess Bitnami does not have it as well. 

During the day I get many errors like that too:

![image](https://user-images.githubusercontent.com/33559260/226061158-318b3529-8a06-4dd9-88d2-1ba7bfc22e3f.png)

### What do you see instead?

Working without timeout error

**Comment by Mauraza** [comment]
Hi @antikilahdjs,

Could you check if the timeout you want to change appears in [here](https://github.com/bitnami/containers/tree/main/bitnami/cassandra#setting-up-a-cluster)?

**Comment by antikilahdjs** [comment]
Hi @Mauraza , I hope you doing great.

First of all thank you for the attention about it. I really appreciate that and I guess it will help about the sleep environment and so on. Thank you so much

**Comment by antikilahdjs** [comment]
Hi @Mauraza . I tried changed but I keeping get the same error . Do you have some idea? 

I guess the issue is releated with cqlsh.py

![image](https://user-images.githubusercontent.com/33559260/226616478-22be414d-78b7-43bc-b4b2-b6405c3b66d1.png)

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Cassandra container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by antikilahdjs** [comment]
Hi @carrodher  I got it and thank you . I all the time get the error below and I saw it needs chance in cqlsh.py and bitnami cassandra does not have it inside the folder to build it, then I need change it directly in folder. Do you saw this error before and know how I can try to fix it?

SMALL_MESSAGES-[no-channel] failed to connect

 io.netty.channel.ConnectTimeoutException: connection timed out: cassandra-sts-master-2.cassandra-sts-master-headless.telconet-resources.svc.cluster.local/10.233.70.230:7000

 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:576)

 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)

 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)

 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)

 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)

 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)

 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

 	at java.lang.Thread.run(Thread.java:750)

 INFO  [AntiEntropyStage:1] 2023-03-21 19:25:18,537 RepairSession.java:220 - [repair #f7d8f0f0-c81d-11ed-9420-a31d3c298811] Received merkle tree for inferences from /10.233.118.56:7000
