### ISSUE TITLE
[kafka] Error connecting to node (accessing from the outside)

### ISSUE THREAD

**Issue by TemaKozyrev** [bitnami/charts#1572]
**Which chart**: kafka

**Description**
There is no way to run a producer or consumer.

Installed according to the documentation:
`helm install --name my-release bitnami/kafka`

When you try to connect, the error falls on the inability to connect to the node.

**Steps to reproduce the issue:**

1. `helm install --name kafka-release bitnami/kafka`
2. `kubectl port-forward --namespace default svc/kafka-release 9092:9092`
3. Create a new topic - success (via `kubectl exec`)
4. `./kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic balance`

**Describe the results you received:**

```
[2019-11-08 11:06:06,601] WARN [Producer clientId=console-producer] Error connecting to node kafka-release-0.kafka-release-headless.default.svc.cluster.local:9092 (id: 1001 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: kafka-release-0.kafka-release-headless.default.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:104)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:403)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:363)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:151)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:943)
        at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:331)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:238)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi @TemaKozyrev ,
  I am trying to reproduce the issue.

**Comment by rafariossaa** [comment]
How are you running the client ?

**Comment by alisivgin** [comment]
I have the same situation. Did anyone find a solution?

**Comment by Korzi** [comment]
I didn't use helm for kafka but came across the same issue.
Temporary solution that worked for me is adding following annotation to headless kafka service
```
metadata:
    annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
```

However right now I'm trying to add livenessProbe to restart kafka pod if such situation occurs - but so far I didn't find a way how to check if Kafka has successfully joined the cluster (there is a brokerId of the broken Kafka pod in the Zookeeper so I can't use `echo dump | nc localhost 2181 | grep brokers` for that)

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing your workaround. 
  @alisivgin , this issue was close but don't hesitate to open a new one so we can do a proper handling of your issue.
