### ISSUE TITLE
[bitnami/fluentd] `getaddrinfo: Name or service not known (SocketError)` occurs when deploying Fluentd on EKS cluster

### ISSUE THREAD

**Issue by sunhongmin225** [bitnami/charts#15740]
### Name and Version

bitnami/fluentd 1.15.3-debian-11-r46

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I've deployed Elasticsearch and Kibana on AWS EKS cluster, using helm of the official elastic repositry. Here are the commands that I've used to deploy them.

```console
kubectl create namespace logging
helm repo add elastic https://helm.elastic.co
helm repo update
helm install -f elasticsearch-values.yaml elasticsearch elastic/elasticsearch --namespace logging
helm install kibana elastic/kibana --namespace logging
```

I've changed minor things in `elasticsearch-values.yaml`. Here are the changes that I've made to the file.

```yaml
esJavaOpts: "-Xmx1g -Xms1g"

initResources:
  limits:
    cpu: "25m"
    memory: "128Mi"
  requests:
    cpu: "25m"
    memory: "128Mi"

extraInitContainers:
  - name: fix-permissions
    image: busybox
    command: ["chown", "-R", "1000:1000", "/usr/share/elasticsearch/"]
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: elasticsearch-master
      mountPath: /usr/share/elasticsearch/data

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 300Gi
  storageClassName: gp2
```

Now, I'm trying to deploy Fluentd and link it to Elasticsearch backend.

Here are the commands and the content of `fluentd-values.yaml` that I've used to deploy Fluentd.

```console
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install -f fluentd-values.yaml fluentd bitnami/fluentd --namespace logging
```

Here are the parts that I've changed compared to original [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/fluentd/values.yaml) file.

```yaml
aggregator:
  configMapFiles:
    fluentd-output.conf: |
      # Send the logs to elasticsearch service # Line 739 of original values.yaml
      <match **>
        @type elasticsearch
        include_tag_key true
        host "elasticsearch-master.logging.svc.cluster.local"
        port "9200"
        logstash_format true

        <buffer>
          @type file
          path /opt/bitnami/fluentd/logs/buffers/logs.buffer
          flush_thread_count 2
          flush_interval 5s
        </buffer>
      </match>
```

This results in CrashLoopBackOff error, and when I check the logs of one of the fluentd pod (deployed via DaemonSet), it shows following:

```console
fluentd 06:21:23.72
fluentd 06:21:23.72 Welcome to the Bitnami fluentd container
fluentd 06:21:23.72 Subscribe to project updates by watching https://github.com/bitnami/containers
fluentd 06:21:23.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues
fluentd 06:21:23.73
fluentd 06:21:23.73 INFO  ==> ** Starting Fluentd setup **
find: '/docker-entrypoint-initdb.d/': No such file or directory
fluentd 06:21:23.73 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
fluentd 06:21:23.74 INFO  ==> ** Fluentd setup finished! **

fluentd 06:21:23.74 INFO  ==> ** Starting Fluentd **
2023-03-27 06:21:25 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
2023-03-27 06:21:25 +0000 [info]: parsing config file is succeeded path="/opt/bitnami/fluentd/conf/fluentd.conf"
2023-03-27 06:21:25 +0000 [info]: gem 'fluentd' version '1.15.3'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-concat' version '2.5.0'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.14'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '5.2.4'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-grafana-loki' version '1.2.20'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-kafka' version '0.18.1'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '3.1.3'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.3'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.1'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-s3' version '1.7.2'
2023-03-27 06:21:25 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.5'
2023-03-27 06:21:26 +0000 [warn]: !! The environment variable 'K8S_NODE_NAME' is not set to the node name which can affect the API server and watch efficiency !!
2023-03-27 06:21:26 +0000 [info]: adding forwarding server 'fluentd-0.fluentd-headless.logging.svc.cluster.local:24224' host="fluentd-0.fluentd-headless.logging.svc.cluster.local" port=24224 weight=60 plugin_id="object:c9a4"
/opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:745:in `getaddrinfo': 	
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:745:in `resolve_dns!'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:731:in `resolved_host'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:591:in `validate_host_resolution!'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:244:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:239:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:239:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin.rb:187:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:132:in `add_match'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:74:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:64:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:64:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:149:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/engine.rb:105:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:731:in `run_supervisor'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:350:in `<top (required)>'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:25:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:25:in `<main>'
```

What might be causing this?

Also, there is one more seems-to-be-related question. Even when I don't edit `fluentd-values.yaml` at all and just use the raw file in [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/fluentd/values.yaml), i.e., I did not explicitly link the aggregator to connect to Elasticsearch service, `kubectl get pods -l "app.kubernetes.io/name=fluentd,app.kubernetes.io/instance=fluentd"` results in following:

```console
NAME            READY   STATUS             RESTARTS     AGE
fluentd-0       0/1     Running            0            13s
fluentd-4dwbc   0/1     CrashLoopBackOff   1 (4s ago)   12s
fluentd-7ntdd   0/1     CrashLoopBackOff   1 (5s ago)   12s
fluentd-cv9lj   0/1     CrashLoopBackOff   1 (4s ago)   12s
fluentd-gfpx4   0/1     CrashLoopBackOff   1 (4s ago)   12s
fluentd-lfg9c   0/1     CrashLoopBackOff   1 (5s ago)   12s
fluentd-tj4m2   0/1     CrashLoopBackOff   1 (6s ago)   12s
fluentd-wpjq2   0/1     CrashLoopBackOff   1 (4s ago)   12s
```

Below are the outputs of `kubectl logs fluentd-4dwbc -n logging`.

```console
fluentd 06:29:49.25
fluentd 06:29:49.25 Welcome to the Bitnami fluentd container
fluentd 06:29:49.25 Subscribe to project updates by watching https://github.com/bitnami/containers
fluentd 06:29:49.25 Submit issues and feature requests at https://github.com/bitnami/containers/issues
fluentd 06:29:49.25
fluentd 06:29:49.25 INFO  ==> ** Starting Fluentd setup **
find: '/docker-entrypoint-initdb.d/': No such file or directory
fluentd 06:29:49.26 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
fluentd 06:29:49.26 INFO  ==> ** Fluentd setup finished! **

fluentd 06:29:49.27 INFO  ==> ** Starting Fluentd **
2023-03-27 06:29:50 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
2023-03-27 06:29:50 +0000 [info]: parsing config file is succeeded path="/opt/bitnami/fluentd/conf/fluentd.conf"
2023-03-27 06:29:50 +0000 [info]: gem 'fluentd' version '1.15.3'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-concat' version '2.5.0'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.14'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '5.2.4'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-grafana-loki' version '1.2.20'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-kafka' version '0.18.1'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '3.1.3'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.3'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.1'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-s3' version '1.7.2'
2023-03-27 06:29:50 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.5'
2023-03-27 06:29:51 +0000 [warn]: !! The environment variable 'K8S_NODE_NAME' is not set to the node name which can affect the API server and watch efficiency !!
2023-03-27 06:29:52 +0000 [info]: adding forwarding server 'fluentd-0.fluentd-headless.logging.svc.cluster.local:24224' host="fluentd-0.fluentd-headless.logging.svc.cluster.local" port=24224 weight=60 plugin_id="object:c9a4"
/opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:745:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:745:in `resolve_dns!'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:731:in `resolved_host'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:591:in `validate_host_resolution!'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:244:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:239:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:239:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/plugin.rb:187:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:132:in `add_match'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:74:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:64:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/agent.rb:64:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:149:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/engine.rb:105:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:731:in `run_supervisor'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:350:in `<top (required)>'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from <internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:25:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:25:in `<main>'
```

It seems to be a same issue with the one above w.r.t. linking to elasticsearch backend. However this time, if I wait for about several minutes, then after several restarts, `kubectl get pods -l "app.kubernetes.io/name=fluentd,app.kubernetes.io/instance=fluentd"` results in following:

```console
NAME            READY   STATUS    RESTARTS       AGE
fluentd-0       1/1     Running   0              2m50s
fluentd-4dwbc   1/1     Running   4 (119s ago)   2m49s
fluentd-7ntdd   1/1     Running   4 (110s ago)   2m49s
fluentd-cv9lj   1/1     Running   4 (110s ago)   2m49s
fluentd-gfpx4   1/1     Running   4 (110s ago)   2m49s
fluentd-lfg9c   1/1     Running   4 (110s ago)   2m49s
fluentd-tj4m2   1/1     Running   4 (110s ago)   2m49s
fluentd-wpjq2   1/1     Running   4 (111s ago)   2m49s
```

It is a nice thing that all pods are now running in ready states, but I am quite uncomfortable with the fact that several restarts have happened, and pods have suddenly changed to ready state. What might be the cause of such change?

### Are you using any custom parameters or values?

I've written above.

### What is the expected behavior?

Fluentd DaemonSet is successfully deployed and all pods are running in a ready state.

### What do you see instead?

I've written above.

**Comment by aoterolorenzo** [comment]
Hi @sunhongmin225 ,

Seems both or a problem with the elasticsearch-master service address or with dns resolution. Could you show the services running behind your cluster?

`kubectl get svc -n logging`

**Comment by sunhongmin225** [comment]
Hi @aoterolorenzo , thanks for your reply.

Here is the output of the above command.

```console
NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/elasticsearch-master            ClusterIP   10.100.43.19    <none>        9200/TCP,9300/TCP   31h
service/elasticsearch-master-headless   ClusterIP   None            <none>        9200/TCP,9300/TCP   31h
service/kibana-kibana                   ClusterIP   10.100.83.127   <none>        5601/TCP            31h
```

**Comment by aoterolorenzo** [comment]
Maybe setting the host as the cluster IP and upgrade could work:

```
        @type elasticsearch
        include_tag_key true
        host "<CLUSTER_IP>"
        port "9200"
        logstash_format true
```

**Comment by Masitommaso** [comment]
@sunhongmin225 Hello! Im having the same identical issue , could you please share if you solved it and eventually how you solved it ? Thx !

**Comment by sunhongmin225** [comment]
@Masitommaso Hi, unfortunately, I failed to solve this issue directly. Instead, I used helm repository of bitnami (not the official https://helm.elastic.co) to deploy Elasticsearch and Kibana. I.e.,

```console
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install elasticsearch bitnami/elasticsearch
helm install kibana bitnami/kibana
```

I thought that using Elasticsearch and Kibana from one repository (https://helm.elastic.co) and Fluentd from another (https://charts.bitnami.com/bitnami) may introduce some discrepancy. So I figured to walk around.

**Comment by Masitommaso** [comment]
> @Masitommaso Hi, unfortunately, I failed to solve this issue directly. Instead, I used helm repository of bitnami (not the official https://helm.elastic.co) to deploy Elasticsearch and Kibana. I.e.,
> 
> ```
> helm repo add bitnami https://charts.bitnami.com/bitnami
> helm repo update
> helm install elasticsearch bitnami/elasticsearch
> helm install kibana bitnami/kibana
> ```
> 
> I thought that using Elasticsearch and Kibana from one repository (https://helm.elastic.co) and Fluentd from another (https://charts.bitnami.com/bitnami) may introduce some discrepancy. So I figured to walk around.

Thx for the super fast reply :) i'll try using the same helmrepo too
