### ISSUE TITLE
[bitnami/kafka] ACL not working when kafka_jaas.conf is injected

### ISSUE THREAD

**Issue by ppapla** [bitnami/charts#15794]
### Name and Version

bitnami/kafka latest

### What architecture are you using?

I don't want t store credentials in yaml file so I want to inject kafka_jaas.conf

### What steps will reproduce the bug?

Mount some config at `/bitnami/kafka/config/jaas_kafka.conf` using volumeMounts:
```
KafkaClient {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="user"
   password="user";
   };
KafkaServer {
   org.apache.kafka.common.security.scram.ScramLoginModule required
   username="admin"
   password="admin";
   };
```

### Are you using any custom parameters or values?

I have configured ACls.

```
authorizerClassName: kafka.security.authorizer.AclAuthorizer
allowEveryoneIfNoAclFound: false
superUsers: User:admin;User:user
auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  externalClientProtocol: sasl
  sasl:
    mechanisms: plain,scram-sha-256,scram-sha-512
    interBrokerMechanism: scram-sha-512
    jaas:
      clientUsers: ['user']
      clientPasswords: ['willBeOverriden']
      interBrokerUser: admin
      interBrokerPassword: 'willBeOverriden'
```

### What is the expected behavior?

I should connect to kafka, using defined users.

### What do you see instead?

Injected config is detected and used but I cannot connect to kafka. (I think that users created in zookeeper are still taken from envs (values.yaml) not kafka_jaas.conf)

```
java.lang.Exception: SaslAuthenticationException: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512
	at org.apache.kafka.clients.admin.KafkaAdminClient$Call.fail(KafkaAdminClient.java:824)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.maybeDrainPendingCall(KafkaAdminClient.java:1115)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.maybeDrainPendingCalls(KafkaAdminClient.java:1088)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1390)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "main" org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512
```

when I use old password from vaules then Im getting this (looping forever):
```
[kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.KafkaAdminClient - [AdminClient clientId=adminclient-1] Sending MetadataRequestData(topics=[], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false) to xxx:9094 (id: -1 rack: null). correlationId=20, timeoutMs=30000
[kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Sending METADATA request with header RequestHeader(apiKey=METADATA, apiVersion=12, clientId=adminclient-1, correlationId=20, headerVersion=2) and timeout 30000 to node -1: MetadataRequestData(topics=[], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false)
[kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Received METADATA response from node -1 for request with header RequestHeader(apiKey=METADATA, apiVersion=12, clientId=adminclient-1, correlationId=20, headerVersion=2): MetadataResponseData(throttleTimeMs=0, brokers=[], clusterId='nMVwHldvQLaNCuvIAnNILA', controllerId=-1, topics=[], clusterAuthorizedOperations=-2147483648)
[kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.internals.AdminMetadataManager - [AdminClient clientId=adminclient-1] Updating cluster metadata to Cluster(id = nMVwHldvQLaNCuvIAnNILA, nodes = [], partitions = [], controller = null)
[kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.internals.AdminMetadataManager - [AdminClient clientId=adminclient-1] Requesting metadata update.
[kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.KafkaAdminClient - [AdminClient clientId=adminclient-1] Sending MetadataRequestData(topics=[], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false) to xxx:9094 (id: -1 rack: null). correlationId=21, timeoutMs=30000
[kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Sending METADATA request with header RequestHeader(apiKey=METADATA, apiVersion=12, clientId=adminclient-1, correlationId=21, headerVersion=2) and timeout 30000 to node -1: MetadataRequestData(topics=[], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false)
```

**Comment by ppapla** [comment]
Indeed, when manually fixing password for specified users it will work.

**Comment by rafariossaa** [comment]
Hi,
 > Injected config is detected and used but I cannot connect to kafka. (I think that users created in zookeeper are still taken from envs (values.yaml) not kafka_jaas.conf)
  Yes, the user are set by values.yaml, if you are mouting a config file it is not going to be processed to extract users from there, hence you need to indicate them explicitly.
