### ISSUE TITLE
[bitnami/zookeeper] External access for zookeeper cluster

### ISSUE THREAD

**Issue by ivan909020** [bitnami/charts#16002]
### Name and Version

bitnami/zookeeper 11.1.6

### What is the problem this feature will solve?

Currently, Zookeeper StatefulSet is created with headless DNS:
```yaml
        - name: ZOO_SERVERS
          value: zookeeper-0.zookeeper-headless.scheduler.svc.cluster.local:2888:3888::1
            zookeeper-1.zookeeper-headless.scheduler.svc.cluster.local:2888:3888::2
            zookeeper-2.zookeeper-headless.scheduler.svc.cluster.local:2888:3888::3
```

When I am trying to connect outside the Kubernetes cluster using ClusterIP it doesn't work because Zookeeper client receives DNS servers that are not resolvable on the client side:
```
 New config event received: {server.2=zookeeper-1.zookeeper-headless.scheduler.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.1=zookeeper-0.zookeeper-headless.scheduler.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.3=zookeeper-2.zookeeper-headless.scheduler.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=0}
 Using org.apache.zookeeper.server.quorum.MultipleAddresses
 Background exception was not retry-able or retry gave up

java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:na]
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:630) ~[zookeeper-3.6.0.jar:3.6.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:551) ~[zookeeper-3.6.0.jar:3.6.0]
```

### What is the feature you are proposing to solve the problem?

Will be possible to connect outside the Kubernetes cluster?

### What alternatives have you considered?

Something similar to the `externalAccess.enabled` Kafka configuration

**Comment by ivan909020** [comment]
Hello @dgomezleon,

1.
https://github.com/bitnami/charts/pull/11853 Only adds support for ClusterIP. External access support was added earlier: https://github.com/bitnami/charts/commit/8dba9d1cb0d58dfa580c02231126da154b5814a6

2.
I am installing zookeeper using:
```
helm install bitnami/zookeeper \
--set global.storageClass=... \
--set replicaCount=3 \
--set service.type=ClusterIP
```

3. I don't think it will work with `LoadBalancerIP` because headless is DNS set to `ZOO_SERVERS` https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/templates/statefulset.yaml#L220
When I am trying to connect to the zookeeper using `ClusterIP` the server sends its config with `ZOO_SERVERS` to the client. Client code is outside the Kubernetes cluster, and it is not aware of that DNS.

**Comment by dgomezleon** [comment]
Hi @ivan909020 ,

You are right, it was added in a previous commit.

Thanks for reporting this. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by robertlich** [comment]
I know this is closed, but we would also really benefit from this feature. As it is now the helm chart can't be used with external clients. We're in the position of needing to migrate legacy applications into a kubernetes cluster and it would be useful to deploy zookeeper first and then have external applications continue to use it.

**Comment by aiellomau** [comment]
Is there any chance this will be worked on? Or has there been an attempt? We really need to expose Zookeeper outside of Kubernetes for external access.
