### ISSUE TITLE
One of the Kafka Broker pod in the cluster fails and goes to crashloopback state with the error : Failed to acquire lock on file .lock in /bitnami/kafka/data. A Kafka instance in another process or thread is using this directory

### ISSUE THREAD

**Issue by vinaykw** [bitnami/charts#16044]
### Name and Version

bitnami/kafka

### What architecture are you using?

arm64

### What steps will reproduce the bug?

In K8s environment we have deployed 3 kafka pods to form a cluster. In some random scenaro one of the kafka broker pod restarts and fails to come back again. The reason from the logs is as follows:

```
[2023-04-12 10:40:29,818] ERROR [KafkaServer id=2] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Failed to acquire lock on file .lock in /bitnami/kafka/data. A Kafka instance in another process or thread is using this directory.
	at kafka.log.LogManager.$anonfun$lockLogDirs$1(LogManager.scala:243)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at kafka.log.LogManager.lockLogDirs(LogManager.scala:238)
	at kafka.log.LogManager.<init>(LogManager.scala:114)
	at kafka.log.LogManager$.apply(LogManager.scala:1383)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:261)
	at kafka.Kafka$.main(Kafka.scala:109)
	at kafka.Kafka.main(Kafka.scala) 

```

Each broker pods have their own pvcs attached to them. Any reason why there is such error and how to overcome it

### Are you using any custom parameters or values?

no

### What is the expected behavior?

Kafka broker pod should comeback again after the crash

### What do you see instead?

Kafka Broker pod stuck in crashloopback state

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Kafka container image or Helm chart but about how the application or environment is being used/configured. In the same way, it's a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by skvishy27** [comment]
I am also facing the same issues,

Here is the error log
"
[2023-07-21 16:48:13,732] INFO [KafkaServer id=1] shut down completed (kafka.server.KafkaServer)
[2023-07-21 16:48:13,732] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
org.apache.kafka.common.KafkaException: Failed to acquire lock on file .lock in /bitnami/kafka/data. A Kafka instance in another process or thread is using this directory.
	at kafka.log.LogManager.$anonfun$lockLogDirs$1(LogManager.scala:243)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at kafka.log.LogManager.lockLogDirs(LogManager.scala:238)
	at kafka.log.LogManager.<init>(LogManager.scala:114)
	at kafka.log.LogManager$.apply(LogManager.scala:1384)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:271)
	at kafka.Kafka$.main(Kafka.scala:115)
	at kafka.Kafka.main(Kafka.scala)
[2023-07-21 16:48:13,733] INFO [KafkaServer id=1] shutting down (kafka.server.KafkaServer)
"
CHART VERSION: 21.4.4
APP VERSION: 3.4.0

**Comment by skvishy27** [comment]
@vinaykw , did you able to get the solution to the issues which you posted?

**Comment by anonimnor** [comment]
seems some kind of mis-configuration, since several kafka brokers seem not be able to use same dir. - we should probably mount each broker his own storage or something.. not use one storage for all brokers..?...

**Comment by theblinkingusb** [comment]
If helpful for the thread/community - 
Is/Are your statefulsets deploying to the same node? I experienced this. You may need to add an antiaffinity 

```
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - controller-eligible # or broker
          topologyKey: kubernetes.io/hostname
```
