### ISSUE TITLE
Scaling down kafka shows errors connecting to disconnected nodes; schema-registry doesn't recover

### ISSUE THREAD

**Issue by emeraldhieu** [bitnami/charts#16344]
### Name and Version

bitnami/schema-registry:10.0.0

### What architecture are you using?

amd64

#### Step 1:
```sh
helm install local -f values.yaml oci://registry-1.docker.io/bitnamicharts/schema-registry --version 10.0.0
```
with values.yaml
```yaml
kafka:
  replicaCount: 3
```

#### Step2: 
```sh
helm upgrade local -f values.yaml oci://registry-1.docker.io/bitnamicharts/schema-registry --version 10.0.0
```
with values.yaml
```yaml
kafka:
  replicaCount: 1
```

### Are you using any custom parameters or values?

```yaml
kafka:
  replicaCount: 3
```

then
```yaml
kafka:
  replicaCount: 1
```

### What is the expected behavior?

Kafka node-0 doesn't show errors and warnings. Both kafka and schema registry run stably.

### What do you see instead?

Kafka node0's errors and warnings
```
[2023-05-02 19:52:19,113] ERROR [Controller 0] processBrokerHeartbeat: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
[2023-05-02 19:52:19,114] INFO [BrokerToControllerChannelManager broker=0 name=heartbeat] Client requested disconnect from node 0 (org.apache.kafka.clients.NetworkClient)
[2023-05-02 19:52:19,114] INFO [BrokerToControllerChannelManager broker=0 name=heartbeat]: Recorded new controller, from now on will use node local-kafka-0.local-kafka-headless.default.svc.cluster.local:9093 (id: 0 rack: null) (kafka.server.BrokerToControllerRequestThread)
[2023-05-02 19:52:19,115] WARN [RaftManager nodeId=0] Error connecting to node local-kafka-1.local-kafka-headless.default.svc.cluster.local:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: local-kafka-1.local-kafka-headless.default.svc.cluster.local
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:990)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.scala:103)
	at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendThread.scala:99)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at kafka.common.InterBrokerSendThread.sendRequests(InterBrokerSendThread.scala:99)
	at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:73)
	at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:94)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
```

Schema registry retries many times and fails to start.
```
[2023-05-02 20:04:03,120] ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication:77)
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryInitializationException: io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryTimeoutException: Timed out waiting for join group to complete
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.electLeader(KafkaSchemaRegistry.java:349)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:330)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:75)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:99)
	at io.confluent.rest.Application.configureHandler(Application.java:285)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:270)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
Caused by: io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryTimeoutException: Timed out waiting for join group to complete
	at io.confluent.kafka.schemaregistry.leaderelector.kafka.KafkaGroupLeaderElector.init(KafkaGroupLeaderElector.java:211)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.electLeader(KafkaSchemaRegistry.java:344)
	... 7 more
```

```
[~]$ kubectl get po
NAME                      READY   STATUS             RESTARTS        AGE
local-kafka-0             1/1     Running            0               24m
local-schema-registry-0   0/1     CrashLoopBackOff   7 (3m36s ago)   21m
```

### Additional information

No response

**Comment by Mauraza** [comment]
Hi @emeraldhieu,

Thanks for reporting! I was able to reproduce it, I'm going to create an internal task to try to resolve this. We will update this issue when we have more information.

**Comment by fi-ecavc** [comment]
I also ran into this issue and the command I executed was: 
helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka    \
--set image.tag=3.5.0-debian-11-r3  \
  --set global.storageClass=nfs   \
  --set replicaCount=3   \
  --set persistence.enabled=true \
  --set persistence.size=30Gi 

and the errors is：
[2023-07-10 09:12:55,027] WARN [RaftManager id=0] Error connecting to node kafka-1.kafka-headle
ss.default.svc.cluster.local:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: kafka-1.kafka-headless.default.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(
ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(Clus
terConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionSta
tes.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.sca
la:107)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendTh
read.scala:103)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)

**Comment by juan131** [comment]
Reopening since this issue was never addressed

**Comment by juan131** [comment]
Hi @emeraldhieu @fi-ecavc 

It seems this is an issue related with losing some kind of minimum qorum all of a sudden. I'm able to reproduce the issue if I follow the steps below:

- Install Schema Registry with 3 Kafka controller-eligible (controller+broker) nodes:

```console
$ helm install schema-registry oci://registry-1.docker.io/bitnamicharts/schema-registry --set kafka.controller.replicaCount=3
Pulled: registry-1.docker.io/bitnamicharts/schema-registry:16.2.4
Digest: sha256:a5634ef6e5abfdf1a34ab09925ea63fd7bafa65c5cc7623066ff062b8f9ae395
(...)
$ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
schema-registry-0                    1/1     Running   0          2m
schema-registry-kafka-controller-0   1/1     Running   0          2m
schema-registry-kafka-controller-1   1/1     Running   0          2m
schema-registry-kafka-controller-2   1/1     Running   0          2m
```

- Double-check Schema Registry is configured to connect to all 3 available brokers:

```console
$ kubectl describe pod schema-registry-0 | grep SCHEMA_REGISTRY_KAFKA_BROKERS
      SCHEMA_REGISTRY_KAFKA_BROKERS:           PLAINTEXT://schema-registry-kafka-controller-0.schema-registry-kafka-controller-headless.default.svc.cluster.local:9092,PLAINTEXT://schema-registry-kafka-controller-1.schema-registry-kafka-controller-headless.default.svc.cluster.local:9092,PLAINTEXT://schema-registry-kafka-controller-2.schema-registry-kafka-controller-headless.default.svc.cluster.local:9092
```

- Upgrade release scaling down Kafka nodes:

```console
$ helm upgrade schema-registry oci://registry-1.docker.io/bitnamicharts/schema-registry --set kafka.controller.replicaCount=1
```

- Ensure Schema Registry is now configured to connect to only one broker:

```console
$ kubectl describe pod schema-registry-0 | grep SCHEMA_REGISTRY_KAFKA_BROKERS
      SCHEMA_REGISTRY_KAFKA_BROKERS:           PLAINTEXT://schema-registry-kafka-controller-0.schema-registry-kafka-controller-headless.default.svc.cluster.local:9092
```

- Inspect schema registry logs after it enters into CrashloopBackOff state:

```console
$ kubectl logs schema-registry-0
(...)
[2023-12-20 09:56:44,253] ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication:79)
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryInitializationException: io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryTimeoutException: Timed out waiting for join group to complete
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.electLeader(KafkaSchemaRegistry.java:439)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:419)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:77)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:101)
	at io.confluent.rest.Application.configureHandler(Application.java:299)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:201)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
Caused by: io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryTimeoutException: Timed out waiting for join group to complete
	at io.confluent.kafka.schemaregistry.leaderelector.kafka.KafkaGroupLeaderElector.init(KafkaGroupLeaderElector.java:214)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.electLeader(KafkaSchemaRegistry.java:434)
	... 7 more
```

However, it seems the problem can be "easily" workaround by scaling down in a less aggressive way. Once it's stable with 3 replicas, I was able to scale it down to 2 replicas, then wait for it to be stabilized, then scale it down to 1 replica:

```console
$ helm upgrade --install schema-registry oci://registry-1.docker.io/bitnamicharts/schema-registry --set kafka.controller.replicaCount=2
(...)
$ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
schema-registry-0                    1/1     Running   0          5m46s
schema-registry-kafka-controller-0   1/1     Running   0          5m30s
schema-registry-kafka-controller-1   1/1     Running   0          5m46s
$ helm upgrade --install schema-registry oci://registry-1.docker.io/bitnamicharts/schema-registry --set kafka.controller.replicaCount=1
(...)
$ kubectl get pods
NAME                                 READY   STATUS    RESTARTS        AGE
schema-registry-0                    1/1     Running   1 (4m39s ago)   7m9s
schema-registry-kafka-controller-0   1/1     Running   0               7m9s
```

Could you please try this approach?
