### ISSUE TITLE
KAFKA_EXTRA_FLAGS env not working

### ISSUE THREAD

**Issue by 5hareef** [bitnami/charts#16404]
### Name and Version

bitnami/kafka 12.18.0

### What is the problem this feature will solve?

Using KAFKA_EXTRA_FLAGS to override the kafka attributes does not work as intended. For example, running the following pod manifest  with  KAFKA_EXTRA_FLAGS set, results in "joptsimple.UnrecognizedOptionException: override broker.id is not a recognised option." 

```bash
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  containers:
    - name: kafka
      image: docker.io/bitnami/kafka:2.8.0-debian-10-r0
      imagePullPolicy: "IfNotPresent"
      command:
        - /bin/sh
        - -ec
        - |
          tail -f /dev/null
      env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_LISTENERS
          value: "INTERNAL://$(MY_POD_NAME):9092"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "INTERNAL://$(MY_POD_NAME):9092"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_EXTRA_FLAGS
          value: "--override broker.id=1"
      ports:
        - name: kafka
          containerPort: 9092
```

Result:
```bash
❯ kubectl exec -it pod/kafka -- bash
I have no name!@kafka:/$ /entrypoint.sh /run.sh
 11:15:59.47
 11:15:59.47 Welcome to the Bitnami kafka container
 11:15:59.48 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 11:15:59.48 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 11:15:59.48
 11:15:59.48 INFO  ==> ** Starting Kafka setup **
 11:15:59.59 DEBUG ==> Validating settings in KAFKA_* env vars...
 11:15:59.60 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
 11:15:59.62 INFO  ==> Initializing Kafka...
 11:15:59.63 INFO  ==> No injected configuration files found, creating default config files
 11:15:59.78 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
 11:15:59.79 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
 11:15:59.79 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
 11:15:59.81 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
 11:15:59.82 INFO  ==> ** Kafka setup finished! **

 11:15:59.85 INFO  ==> ** Starting Kafka **
[2023-05-05 11:16:01,373] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2023-05-05 11:16:01,698] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
joptsimple.UnrecognizedOptionException: override broker.id is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at kafka.Kafka$.getPropsFromArgs(Kafka.scala:55)
	at kafka.Kafka$.main(Kafka.scala:86)
	at kafka.Kafka.main(Kafka.scala)
I have no name!@kafka:/$ exit
```

Is the env variable `KAFKA_EXTRA_FLAGS` correctly tested? If so, could you give an example of how to set it correctly?

### What is the feature you are proposing to solve the problem?

If this is the desired behaviour, Can we modify the run.sh script to properly handle the KAFKA_EXTRA_FLAGS env variables.

Suggestion:
Maybe we can construct the array, before executing the command array. Like:
```bash
```

**Comment by 5hareef** [comment]
Thanks @fevisera for the feedback.

Sure, I will try to upgrade to a supported version. But it would be beneficial if the fix was added to the `KAKFA_EXTRA_FLAGS` flags because it is useful when the pod is run with the `securityContext.readOnlyRootFilesystem` field set to `true`. So that, one can mount the `server.properties` file as configMap and override certain properties with `KAKFA_EXTRA_FLAGS`.

**Comment by fevisera** [comment]
Hi @5hareef,

It seems like the feature you are proposing might already be covered by the following [parameters](https://github.com/bitnami/charts/tree/main/bitnami/kafka#kafka-parameters) in `values.yaml`:

```yaml
## config: |-
##   broker.id=-1
##   listeners=PLAINTEXT://:9092
##   advertised.listeners=PLAINTEXT://KAFKA_IP:9092
##   num.network.threads=3
##   num.io.threads=8
##   socket.send.buffer.bytes=102400
##   socket.receive.buffer.bytes=102400
##   socket.request.max.bytes=104857600
##   log.dirs=/bitnami/kafka/data
##   num.partitions=1
##   num.recovery.threads.per.data.dir=1
##   offsets.topic.replication.factor=1
##   transaction.state.log.replication.factor=1
##   transaction.state.log.min.isr=1
##   log.flush.interval.messages=10000
##   log.flush.interval.ms=1000
##   log.retention.hours=168
##   log.retention.bytes=1073741824
##   log.segment.bytes=1073741824
##   log.retention.check.interval.ms=300000
##   zookeeper.connect=ZOOKEEPER_SERVICE_NAME
##   zookeeper.connection.timeout.ms=6000
##   group.initial.rebalance.delay.ms=0
##
config: ""
## @param existingConfigmap ConfigMap with Kafka Configuration
## NOTE: This will override `config` AND any KAFKA_CFG_ environment variables
##
existingConfigmap: ""
```

I would kindly suggest checking out the [Readme](https://github.com/bitnami/charts/tree/main/bitnami/kafka#setting-custom-parameters) section, which provides valuable information related to setting custom parameters.

If you have any specific scenarios or requirements in mind that are not covered by this approach, please provide more details, and I will be glad to assist you further.

Thanks.
