### ISSUE TITLE
[bitnami/kafka] SSL/TLS handshake error

### ISSUE THREAD

**Issue by kumaraswa** [bitnami/charts#16859]
### Name and Version

confluent 7.3.3

### What is the problem this feature will solve?

We use a simple messaging queue, therefore I had to use the security (SSL/TLS) I had set up in the broker. The broker is connected when I run the command openssl s_client -connect kafka:9093 -servername FQDN. however, I'm getting a handshake issue when I try to list the topics with SSL port 9093. Please review the logs below.
```
[root@kafka confluent-7.3.3]# ./bin/kafka-topics --list --bootstrap-server  kafka.dev..in:9093
Error while executing topic command : The AdminClient thread has exited. Call: listTopics
[2023-05-22 12:54:16,278] ERROR org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited. Call: listTopics
 (kafka.admin.TopicCommand$)
[2023-05-22 12:54:16,282] ERROR Uncaught exception in thread 'kafka-admin-client-thread | adminclient-1': (org.apache.kafka.common.utils.KafkaThread)
java.lang.OutOfMemoryError: Java heap space
at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:113)
at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560)
at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1415)
at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1346)
at java.lang.Thread.run(Thread.java:748)
[root@kafka confluent-7.3.3]# 
```

Please help me to resolve this issue

### What is the feature you are proposing to solve the problem?

please some one help me to close this issue.

**Comment by Sbennett99** [comment]
Increase the size of your java heap, all the ssl credentials are stored and are quite large

**Comment by javsalgar** [comment]
Hi,

Could you confirm which Bitnami chart you are deploying? It is bitnami/schema-registry or bitnami/kafka?

**Comment by Sbennett99** [comment]
Bitnami Kafka and I am using the image with docket
________________________________

**Comment by javsalgar** [comment]
Could you share the values and the command you are using to deploy the Kafka chart?
