### ISSUE TITLE
Kafka with mTLS, ACL and KRaft seems to still try to start a Zookeeper

### ISSUE THREAD

**Issue by LuxTheDude** [bitnami/charts#16855]
### Name and Version

bitnami/kafka 22.1.3

### What steps will reproduce the bug?

Trying to helm Install kafka with mTLS, ACL and KRaft fails.

### Are you using any custom parameters or values?
```yaml
auth:
  clientProtocol: mtls
  interBrokerProtocol: tls
  tls:
    type: jks
    pemChainIncluded: false
    existingSecrets:
    - "kafka-jks"
    existingSecret: "kafka-jks-password"
    jksTruststore: "kafka.truststore.jks"
    jksKeystoreSAN: "kafka.keystore.jks"
    endpointIdentificationAlgorithm: ""

authorizerClassName: "kafka.security.authorizer.AclAuthorizer"
allowEveryoneIfNoAclFound: false

allowPlaintextListener: false
```
### What is the expected behavior?

Kafka should be installed without any errors.

### What do you see instead?
```
kafka 11:25:24.35
kafka 11:25:24.36 Welcome to the Bitnami kafka container
kafka 11:25:24.36 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 11:25:24.36 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 11:25:24.36
kafka 11:25:24.36 INFO  ==> ** Starting Kafka setup **
kafka 11:25:24.42 INFO  ==> Initializing Kafka...
kafka 11:25:24.43 INFO  ==> No injected configuration files found, creating default config files
kafka 11:25:24.86 INFO  ==> Configuring Kafka for inter-broker communications with SSL authentication.
kafka 11:25:24.90 INFO  ==> Configuring Kafka for client communications with SSL authentication.
kafka 11:25:24.91 INFO  ==> Configuring Kafka for external client communications with SSL authentication.
kafka 11:25:24.92 INFO  ==> Initializing KRaft...
kafka 11:25:24.92 INFO  ==> Formatting storage directories to add metadata...

kafka 11:25:26.15 INFO  ==> ** Kafka setup finished! **
kafka 11:25:26.17 INFO  ==> ** Starting Kafka **
[2023-05-22 11:25:26,805] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2023-05-22 11:25:27,107] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2023-05-22 11:25:27,240] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2023-05-22 11:25:27,243] INFO Starting controller (kafka.server.ControllerServer)
[2023-05-22 11:25:27,295] ERROR [ControllerServer id=0] Fatal error during controller startup. Prepare to shutdown (kafka.server.ControllerServer)
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "connectString" is null
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:2246)
        at kafka.security.authorizer.AclAuthorizer.configure(AclAuthorizer.scala:184)
        at kafka.server.ControllerServer.$anonfun$startup$11(ControllerServer.scala:149)
        at kafka.server.ControllerServer.$anonfun$startup$11$adapted(ControllerServer.scala:149)
        at scala.Option.foreach(Option.scala:407)
        at kafka.server.ControllerServer.startup(ControllerServer.scala:149)
        at kafka.server.KafkaRaftServer.$anonfun$startup$1(KafkaRaftServer.scala:98)
        at kafka.server.KafkaRaftServer.$anonfun$startup$1$adapted(KafkaRaftServer.scala:98)
        at scala.Option.foreach(Option.scala:407)
        at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:98)
        at kafka.Kafka$.main(Kafka.scala:115)
        at kafka.Kafka.main(Kafka.scala)
[2023-05-22 11:25:27,297] INFO [ControllerServer id=0] shutting down (kafka.server.ControllerServer)
[2023-05-22 11:25:27,300] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "connectString" is null
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:2246)
        at kafka.security.authorizer.AclAuthorizer.configure(AclAuthorizer.scala:184)
        at kafka.server.ControllerServer.$anonfun$startup$11(ControllerServer.scala:149)
        at kafka.server.ControllerServer.$anonfun$startup$11$adapted(ControllerServer.scala:149)
        at scala.Option.foreach(Option.scala:407)
        at kafka.server.ControllerServer.startup(ControllerServer.scala:149)
        at kafka.server.KafkaRaftServer.$anonfun$startup$1(KafkaRaftServer.scala:98)
        at kafka.server.KafkaRaftServer.$anonfun$startup$1$adapted(KafkaRaftServer.scala:98)
        at scala.Option.foreach(Option.scala:407)
        at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:98)
        at kafka.Kafka$.main(Kafka.scala:115)
        at kafka.Kafka.main(Kafka.scala)
[2023-05-22 11:25:27,306] INFO App info kafka.server for 0 unregistered (org.apache.kafka.common.utils.AppInfoParser)
```
### Additional information

This error specifically started appearing when I tried to enable ACL with the two following additions to the values file:
```yaml
authorizerClassName: "kafka.security.authorizer.AclAuthorizer"
allowEveryoneIfNoAclFound: false
```
The error seems to suggest that these somehow partially or fully enable some Zookeeper stuff.

**Comment by aoterolorenzo** [comment]
Relates to #26866.

**Comment by aoterolorenzo** [comment]
Hi @LuxTheDude,

We are currently investigating several issues related to Kraft mode. As this seems one of the affected reports, I will maintain this as on hold and add a new internal task to append to the one we have on the line right now about reviewing the kraft mode feature, hoping its solved once addressed.

**Comment by atrbgithub** [comment]
@LuxTheDude was you able to get this working?

Seeing the same issue.

**Comment by LuxTheDude** [comment]
Hello @atrbgithub

I was not, as I haven't worked on it since. I'm currently in the process of using Keycloak for authentication instead.
I will return to this issue afterwards, and will update here if I find a solution.

**Comment by atrbgithub** [comment]
Thanks for responding @LuxTheDude , much appreciated. Are you using [this](https://github.com/strimzi/strimzi-kafka-oauth) by any chance to support keycloak auth?

**Comment by LuxTheDude** [comment]
No problem @atrbgithub 

I am indeed using that for inspiration, but I am trying to write my own AuthenticationCallback classes, to simplify them, since I only need to support Keycloak, and not any other OAuth. Also, I would very much like for it to work with the Bitnami charts.

**Comment by atrbgithub** [comment]
This seemed to work for me (At least to get around the issue above 🙂  ):

```
KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
```

Or as above:

```
authorizerClassName: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
```

**Comment by deepak-ksolves** [comment]
> This seemed to work for me (At least to get around the issue above 🙂 ):
> 
> ```
> KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
> ```
> 
> Or as above:
> 
> ```
> authorizerClassName: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
> ```

Didn't work for me :(
Getting this in the logs: **_org.apache.kafka.common.errors.AuthorizerNotReadyException_**

**Comment by kmdlcp** [comment]
> 

That is indeed the solution. The class i was using, unbeknownst to me, still needs a Zookeeper to work. That is not a bitnami issue, but a Kafka issue. The class you propose to use, is the solution that Kafka has made for KRaft.

Link: https://cwiki.apache.org/confluence/display/KAFKA/KIP-801%3A+Implement+an+Authorizer+that+stores+metadata+in+__cluster_metadata

**Comment by LuxTheDude** [comment]
That is indeed the solution. The class i was using, unbeknownst to me, still needs a Zookeeper to work. That is not a bitnami issue, but a Kafka issue. The class you propose to use, is the solution that Kafka has made for KRaft.

Link: https://cwiki.apache.org/confluence/display/KAFKA/KIP-801%3A+Implement+an+Authorizer+that+stores+metadata+in+__cluster_metadata

**Comment by thejass10** [comment]
Using Bitnami Kafka Helm 23.0, Kafka 3.5.0

I have set KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
KAFKA_CFG_SUPER_USERS=User:user;User:controller_user;User:ANONYMOUS

Using TLS pem based with auto_generation=true

Post deployment logged into pod/container and ran this command and it was successful
kafka-acls.sh --bootstrap-server xxxxx:9094 --command-config /tmp/client.properties --add --allow-principal User:test_producer --operation Read --topic 'test-acl'

I have added one user "test_producer" to a topic "test-acl" with "Read" permission but still am able to write to the "test-acl" topic with test_producer user and also its working for any user.

Authorization is not working

Any fix for this ? Not seeing any error in the broker logs

**Comment by carrodher** [comment]
We will check the same issue reported in a [separate ticket](https://github.com/bitnami/charts/issues/18997)
