### ISSUE TITLE
[bitnami/solr] not running in standalone mode

### ISSUE THREAD

**Issue by Aadarsh-Verma** [bitnami/charts#17586]
### Name and Version

bitnami/solr 5.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running solr in standalone mode

### Are you using any custom parameters or values?
```
replicaCount: 1
collectionReplicas: 1
collectionShards: 1
collection: ""
coreNames:
  - ""

cloudEnabled: false
cloudBootstrap: false

persistence:
  enabled: false
zookeeper:
  enabled: false
```

### What do you see instead?
```
2023-07-13 06:30:00.935 INFO  (qtp1423561005-46) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json} status=0 QTime=2
2023-07-13 06:30:00.979 ERROR (qtp1423561005-28) [   ] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Solr instance is not running in SolrCloud mode. => org.apache.solr.common.SolrException: Solr instance is not running in SolrCloud mode.
        at org.apache.solr.handler.admin.CollectionsHandler.checkErrors(CollectionsHandler.java:273)
org.apache.solr.common.SolrException: Solr instance is not running in SolrCloud mode.
        at org.apache.solr.handler.admin.CollectionsHandler.checkErrors(CollectionsHandler.java:273) ~[?:?]
        at org.apache.solr.handler.admin.CollectionsHandler.handleRequestBody(CollectionsHandler.java:241) ~[?:?]
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216) ~[?:?]
        at org.apache.solr.servlet.HttpSolrCall.handleAdmin(HttpSolrCall.java:836) ~[?:?]
        at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:800) ~[?:?]
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:545) ~[?:?]
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:427) ~[?:?]
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:357) ~[?:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.4
```

**Comment by migruiz4** [comment]
Hi @Aadarsh-Verma,

Thank you for reporting this issue and sorry for the late response. 

I have submitted this PR (#17774) which should fix this issue.
The error is caused by the pod liveness/readiness probes executing the command 
```
SOLR_AUTH_TYPE=basic SOLR_AUTHENTICATION_OPTS="-Dbasicauth=${SOLR_ADMIN_USERNAME}:${SOLR_ADMIN_PASSWORD}" solr assert --timeout 15 --not-cloud "http://localhost:${SOLR_PORT_NUMBER}/solr/"
```

Although the command succeeds, it appears to be triggering some HTTP requests that are not compatible with Standalone Solr although `--not-cloud` flag is being used, resulting in the errors you shared continually showing in the Solr logs.
