### ISSUE TITLE
Worker pod failing to reach master pod (DNS resolution failure)

### ISSUE THREAD

**Issue by BenjaminSalah** [bitnami/charts#17725]
### Name and Version

bitnami/spark-7.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have installed Kubernetes on EC2s using kubeadm + containerd + systemd + calico
I then installed Spark via helm https://bitnami.com/stack/spark/helm

Upon completion i now see 3 pods and 2 services (one with a clusterIP) related to Spark:

pods:
>NAMESPACE          NAME                                       READY   STATUS    RESTARTS        AGE
default            my-release-spark-master-0                  1/1     Running   0               16h
default            my-release-spark-worker-0                  1/1     Running   79 (13m ago)    16h
default            my-release-spark-worker-1                  1/1     Running   78 (8m2s ago)   16h

services:
>NAME                          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)           AGE
my-release-spark-headless     ClusterIP   None           <none>        <none>            17h
my-release-spark-master-svc   ClusterIP   10.101.85.99   <none>        7077/TCP,80/TCP   17h

endpoints:
>NAME                          ENDPOINTS                                     AGE
my-release-spark-headless     192.168.218.199,192.168.228.2,192.168.228.3   17h
my-release-spark-master-svc   192.168.228.3:7077,192.168.228.3:8080         17h

However worker-0 and worker-1 pod have restarted many times and keep restarting due to DNS resolution failure against the master pod. Why is the DNS resolution failing? I have tested that the machines themselves can be pinged from one another by public IP and by private IP DNS name. What would you recommend i try next? 

### Are you using any custom parameters or values?

no

### What is the expected behavior?

worker pods should be able to reach master pod

### What do you see instead?

worker pods not able to reach master pod

kubectl logs -f my-release-spark-worker-0

>starting org.apache.spark.deploy.worker.Worker, logging to /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.worker.Worker-1-my-release-spark-worker-0.out
Spark Command: /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org.apache.spark.deploy.worker.Worker --webui-port 8080 spark://my-release-spark-master-svc:7077
========================================
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
23/07/16 21:08:00 INFO Worker: Started daemon with process name: 34@my-release-spark-worker-0
23/07/16 21:08:00 INFO SignalUtils: Registering signal handler for TERM
23/07/16 21:08:00 INFO SignalUtils: Registering signal handler for HUP
23/07/16 21:08:00 INFO SignalUtils: Registering signal handler for INT
23/07/16 21:08:00 INFO SecurityManager: Changing view acls to: spark
23/07/16 21:08:00 INFO SecurityManager: Changing modify acls to: spark
23/07/16 21:08:00 INFO SecurityManager: Changing view acls groups to: 
23/07/16 21:08:00 INFO SecurityManager: Changing modify acls groups to: 
23/07/16 21:08:00 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark; groups with view permissions: EMPTY; users with modify permissions: spark; groups with modify permissions: EMPTY
23/07/16 21:08:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
23/07/16 21:08:01 INFO Utils: Successfully started service 'sparkWorker' on port 41365.
23/07/16 21:08:01 INFO Worker: Worker decommissioning not enabled.
23/07/16 21:08:02 INFO Worker: Starting Spark worker 192.168.228.2:41365 with 2 cores, 2.8 GiB RAM
23/07/16 21:08:02 INFO Worker: Running Spark version 3.4.1
23/07/16 21:08:02 INFO Worker: Spark home: /opt/bitnami/spark
23/07/16 21:08:02 INFO ResourceUtils: ==============================================================
23/07/16 21:08:02 INFO ResourceUtils: No custom resources configured for spark.worker.
23/07/16 21:08:02 INFO ResourceUtils: ==============================================================
23/07/16 21:08:02 INFO JettyUtils: Start Jetty 0.0.0.0:8080 for WorkerUI
23/07/16 21:08:02 INFO Utils: Successfully started service 'WorkerUI' on port 8080.
23/07/16 21:08:02 INFO WorkerWebUI: Bound WorkerWebUI to 0.0.0.0, and started at http://my-release-spark-worker-0.my-release-spark-headless.default.svc.cluster.local:8080
23/07/16 21:08:02 INFO Worker: Connecting to master my-release-spark-master-svc:7077...
23/07/16 21:08:16 INFO Worker: Retrying connection to master (attempt # 1)
23/07/16 21:08:16 INFO Worker: Connecting to master my-release-spark-master-svc:7077...
23/07/16 21:08:22 WARN TransportClientFactory: DNS resolution failed for my-release-spark-master-svc/<unresolved>:7077 took 20017 ms
23/07/16 21:08:22 WARN Worker: Failed to connect to master my-release-spark-master-svc:7077
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.deploy.worker.Worker$$anon$1.run(Worker.scala:313)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Failed to connect to my-release-spark-master-svc/<unresolved>:7077
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:284)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
	... 4 more
Caused by: java.net.UnknownHostException: my-release-spark-master-svc

**Comment by BenjaminSalah** [comment]
I figured it out, this was more of an issue with kubernetes core DNS needing to be restarted.
