### ISSUE TITLE
I can't create kafka  cluste by bitnami helm document

### ISSUE THREAD

**Issue by wangjc0216** [bitnami/charts#17797]
### Name and Version

bitnamicharts/kafka 23.0.5 

### What architecture are you using?

None

### What steps will reproduce the bug?

I just try to install kafka with helm  quickly ,I saw the kafka cluster deployment document described as `helm install my-release --set replicaCount=3 oci://registry-1.docker.io/bitnamicharts/kafka` 

![image](https://github.com/bitnami/charts/assets/37376634/5fdf05c8-fa73-4f33-b596-7ef62bddc16f)
> doc ref:https://artifacthub.io/packages/helm/bitnami/kafka

But it can't work! and it's log as below:
```
[2023-07-20 10:29:06,372] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-20 10:29:06,461] WARN [RaftManager id=0] Error connecting to node my-release-kafka-1.my-release-kafka-headless.default.svc.cluster.local:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: my-release-kafka-1.my-release-kafka-headless.default.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.scala:107)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendThread.scala:103)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.common.InterBrokerSendThread.sendRequests(InterBrokerSendThread.scala:103)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:77)
        at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:98)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
[2023-07-20 10:29:06,472] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-20 10:29:06,482] WARN [RaftManager id=0] Error connecting to node my-release-kafka-2.my-release-kafka-headless.default.svc.cluster.local:9093 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: my-release-kafka-2.my-release-kafka-headless.default.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.scala:107)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendThread.scala:103)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.common.InterBrokerSendThread.sendRequests(InterBrokerSendThread.scala:103)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:77)
        at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:98)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
[2023-07-20 10:29:06,572] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)

```

### Are you using any custom parameters or values?

 --set replicaCount=3

### What is the expected behavior?

I just want that  kafka（kafka-0,kafka-1,kafka-2） cluster can  work normally

### What do you see instead?

the error log above 

### Additional information

Now I comment the readyProbe and it can be ok , but i want to know whether there be better ways to resolve it .

**Comment by PDVJAM** [comment]
Same here.

**Comment by PDVJAM** [comment]
@wangjc0216 Was just able to create 3 node cluster. Had to change service.headless.publishNotReadyAddresses to true.

**Comment by wangjc0216** [comment]
> @wangjc0216 Was just able to create 3 node cluster. Had to change service.headless.publishNotReadyAddresses to true.

LGTM! I come back to try
