### ISSUE TITLE
Fatal exception: No MetadataVersion with metadata version 11

### ISSUE THREAD

**Issue by mandrean** [bitnami/charts#18004]
### Name and Version

bitnami/kafka 23.0.7

### What architecture are you using?

Linux amd64

### What steps will reproduce the bug?

0. Spin up a simple `kind`  cluster on Linux (amd64)
1. Create a chart where `bitnami/kafka` is a subchart. Tested with both `23.0.5` and `23.0.7` so far.
2. Use the subchart values:
```yaml
kafka:
  fullnameOverride: kafka
  image:
    repository: bitnami/kafka
    tag: 3.4
```
3. Deploy the parent chart with `helm` to the `kind`  cluster

### Are you using any custom parameters or values?

```yaml
  fullnameOverride: kafka
  image:
    repository: bitnami/kafka
    tag: 3.4
```

### What is the expected behavior?

Kafka should start successfully

### What do you see instead?

The `kafka-0` pod crashloops with the following error:

```console
$ kubectl logs kafka-0
kafka 19:52:59.89 
kafka 19:52:59.89 Welcome to the Bitnami kafka container
kafka 19:52:59.89 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 19:52:59.89 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 19:52:59.89 
kafka 19:52:59.89 INFO  ==> ** Starting Kafka setup **
kafka 19:52:59.93 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 19:52:59.93 INFO  ==> Initializing Kafka...
kafka 19:52:59.94 INFO  ==> No injected configuration files found, creating default config files
kafka 19:53:00.28 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
kafka 19:53:00.29 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
kafka 19:53:00.29 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
kafka 19:53:00.29 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 19:53:00.29 INFO  ==> Initializing KRaft...
kafka 19:53:00.30 INFO  ==> Formatting storage directories to add metadata...
kafka 19:53:01.10 INFO  ==> ** Kafka setup finished! **

kafka 19:53:01.11 INFO  ==> ** Starting Kafka **
[2023-07-27 19:53:01,469] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2023-07-27 19:53:01,573] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2023-07-27 19:53:01,613] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.lang.IllegalArgumentException: No MetadataVersion with metadata version 11
	at org.apache.kafka.server.common.MetadataVersion.fromFeatureLevel(MetadataVersion.java:412)
	at org.apache.kafka.metadata.bootstrap.BootstrapMetadata.recordToMetadataVersion(BootstrapMetadata.java:70)
	at org.apache.kafka.metadata.bootstrap.BootstrapMetadata.fromRecords(BootstrapMetadata.java:54)
	at org.apache.kafka.metadata.bootstrap.BootstrapDirectory.readFromBinaryFile(BootstrapDirectory.java:106)
	at org.apache.kafka.metadata.bootstrap.BootstrapDirectory.read(BootstrapDirectory.java:78)
	at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:171)
	at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:56)
	at kafka.Kafka$.buildServer(Kafka.scala:85)
	at kafka.Kafka$.main(Kafka.scala:93)
	at kafka.Kafka.main(Kafka.scala)
```

### Additional information

Emphasis:

> 	at kafka.server.**KafkaRaftServer**$.initializeLogDirs(KafkaRaftServer.scala:171)
	
So I guess something with KRaft and initializing log dirs?
Could it be that some additional setting is needed when running in a `kind` cluster?

**Comment by mandrean** [comment]
Tried deploying it with:

```
kafka:
  fullnameOverride: kafka
  zookeeper:
    enabled: true
  kraft:
    enabled: false
  image:
    repository: bitnami/kafka
    tag: 3.4
```

instead. Now I get this error:

```
[2023-07-27 20:18:51,895] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.RuntimeException: Found unexpected version in loaded `meta.properties`: {cluster.id=kafka_cluster_id_testw, node.id=0, version=1}. Zk-based brokers only support version 0 (which is implicit when the `version` field is missing).
	at kafka.server.KafkaServer.startup(KafkaServer.scala:228)
	at kafka.Kafka$.main(Kafka.scala:115)
	at kafka.Kafka.main(Kafka.scala)
[2023-07-27 20:18:51,896] INFO shutting down (kafka.server.KafkaServer)
[2023-07-27 20:18:51,897] INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient)
[2023-07-27 20:18:52,000] INFO EventThread shut down for session: 0x100067b13f40003 (org.apache.zookeeper.ClientCnxn)
[2023-07-27 20:18:52,000] INFO Session: 0x100067b13f40003 closed (org.apache.zookeeper.ZooKeeper)
[2023-07-27 20:18:52,001] INFO [ZooKeeperClient Kafka server] Closed. (kafka.zookeeper.ZooKeeperClient)
[2023-07-27 20:18:52,003] INFO App info kafka.server for -1 unregistered (org.apache.kafka.common.utils.AppInfoParser)
[2023-07-27 20:18:52,003] INFO shut down completed (kafka.server.KafkaServer)
[2023-07-27 20:18:52,003] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
java.lang.RuntimeException: Found unexpected version in loaded `meta.properties`: {cluster.id=kafka_cluster_id_testw, node.id=0, version=1}. Zk-based brokers only support version 0 (which is implicit when the `version` field is missing).
	at kafka.server.KafkaServer.startup(KafkaServer.scala:228)
	at kafka.Kafka$.main(Kafka.scala:115)
	at kafka.Kafka.main(Kafka.scala)
[2023-07-27 20:18:52,004] INFO shutting down (kafka.server.KafkaServer)
```

So not specifically KRaft...

**Comment by mandrean** [comment]
Oh wow, strange. So running this works:

```
kafka:
  fullnameOverride: kafka
  image:
    repository: bitnami/kafka
    tag: 3.5
``` 

I guess there's some incompatibility between the chart (`v23.0.x`) and the Docker image (`v3.4`) under certain circumstances?

**Comment by carrodher** [comment]
It could be possible. Each Helm chart version is tested with a specific application version, although other combinations can work, it is not guaranteed since there is no tested Helm chart for all combinations.

At https://github.com/bitnami/charts/pull/17354, the Helm chart was bumped to a new major version (23.0.0) because the bundled Kafka container image was updated from 3.4 to 3.5. If you want to use Kafka 3.4, I recommend you use the latest version of 22.x.x that is the latest Helm chart bundling Kafka 3.4, for instance [bitnamicharts/kafka:22.1.6](https://hub.docker.com/layers/bitnamicharts/kafka/22.1.6/images/sha256-e90188b4f471b31ceb01e5991569cbbe4e1bc805e03a36e6ad0e47d00c60f1c4?context=explore)
