### ISSUE TITLE
[bitnami/airflow] UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 128: ordinal not in range(128)

### ISSUE THREAD

**Issue by mustela** [bitnami/charts#1845]
Hey there! Im having a hard time with `logging.info`. Im moving things from a pg db into another pg db using the PostgresHook. And when inserting the record into the second db, Im having the following error: 

```
[2020-01-21 22:49:09,556] {logging_mixin.py:112} WARNING - --- Logging error ---
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING - Traceback (most recent call last):
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/python/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING - UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 128: ordinal not in range(128)
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING - Call stack:
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/bin/airflow", line 37, in <module>
    args.func(args)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 545, in run
    _run(args, dag, ti)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 460, in _run
    run_job.run()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 221, in run
    self._execute()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/jobs/local_task_job.py", line 95, in _execute
    self.task_runner.start()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 80, in _start_by_fork
    args.func(args)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 545, in run
    _run(args, dag, ti)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 465, in _run
    pool=args.pool,
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)
```

As you can see [here](https://github.com/apache/airflow/blob/master/airflow/hooks/dbapi_hook.py#L164), before inserting it tries to logs the query and params. And that's where it's failing, because one of my params  contains this string `"1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN"`

If you try to logging it directly into any dag like `logging.info("1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN")`  you will have the error.

Im wondering if this something around not how these chart containers are being generated (maybe with some missing encoding) or something else. 

You can run a container and run the following 
```
airflow@airflow-web-8bfb4589b-lqcxv:/$ python
Python 3.6.10 (default, Dec 19 2019, 04:04:42) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.info("1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN")
  File "<stdin>", line 0
    
    ^
SyntaxError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)
>>> 
```
If I run `python3 -c 'import sys; print(sys.stdout.encoding)'` I get ANSI_X3.4-1968`, that obviusly does not support those type of characters `é`. 

So if I run that in another python3 default container, I can see that it's set to `UTF-8`

Any clue around how to solve this?

**Comment by mustela** [comment]
Im checking this image https://github.com/puckel/docker-airflow/, which works just fine, and comparing with yours the most visible difference is around locale  https://github.com/puckel/docker-airflow/blob/master/Dockerfile#L21,  Ive set all those vars but still same result.  So maybe something around this https://github.com/puckel/docker-airflow/blob/master/Dockerfile#L53

Any idea?

**Comment by juan131** [comment]
Hi @mustela 

Thanks so much for reporting! I'm closing the issue so we can keep the conversation in the image repository!
