### ISSUE TITLE
Unable to start worker (PermissionError)

### ISSUE THREAD

**Issue by lduparc** [bitnami/charts#1850]
**Which chart**:

* name: airflow
* version: 4.1.2
* appVersion: 1.10.7

**Description**

scheduler and web are running properly. but trying to use KubernetesExecutor I encounter an issue.
I create my own worker because I need to use KubernetesExecutor and an image based on centos6/7
```
Traceback (most recent call last):                                                                                                                          │
│  File "/usr/local/bin/airflow", line 25, in <module>                                                                                                       │
│    from airflow.configuration import conf                                                                                                                  │
│  File "/usr/local/lib/python3.7/site-packages/airflow/__init__.py", line 31, in <module>                                                                   │
│    from airflow.utils.log.logging_mixin import LoggingMixin                                                                                                │
│  File "/usr/local/lib/python3.7/site-packages/airflow/utils/__init__.py", line 24, in <module>                                                             │
│    from .decorators import apply_defaults as _apply_defaults                                                                                               │
│  File "/usr/local/lib/python3.7/site-packages/airflow/utils/decorators.py", line 36, in <module>                                                           │
│    from airflow import settings                                                                                                                            │
│  File "/usr/local/lib/python3.7/site-packages/airflow/settings.py", line 37, in <module>                                                                   │
│    from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG  # NOQA F401                                                                     │
│  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 588, in <module>                                                             │
│    with open(TEST_CONFIG_FILE, 'w') as f:                                                                                                                  │
│PermissionError: [Errno 13] Permission denied: '/opt/bitnami/airflow/unittests.cfg'
```

**Docker file for pod workers**

```
FROM centos:6

RUN yum install -y gcc zlib-devel libffi-devel openssl-devel openssl && yum clean all

RUN mkdir /build && cd /build && \
	curl -O https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz && \
	tar xzf Python-3.6.9.tgz && cd Python-3.6.9 && \
	./configure && \
	make && make install && \
	rm -rf /build

RUN pip3 install --index-url http://pypi.org/simple --trusted-host pypi.org --upgrade pip setuptools
WORKDIR /app

COPY ./requirements.txt /app

RUN yum list installed |grep ssl
RUN pip3 install -r requirements.txt

COPY airflow_local_settings.py /usr/local/lib/python3.6

ENTRYPOINT [ "airflow" ]
```

**Airflow config**

```
airflow.cfg: |-
    [core]
    {{- if .Values.postgresql.enabled }}
    sql_alchemy_conn = postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ template "airflow.fullname" . }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}
    {{- else }}
    sql_alchemy_conn = postgresql://{{ .Values.externalDatabase.user }}:{{ .Values.externalDatabase.password }}@{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }}
    {{- end }}
    executor = KubernetesExecutor
    load_examples = {{ .Values.airflow.loadExamples }}
    dags_are_paused_at_creation = False
    unit_test_mode = False
    fernet_key = {{ .Values.airflow.auth.fernetKey }}

    [webserver]
    rbac = True
    web_server_port = 8080
    dag_default_view = graph

    [smtp]
    smtp_host = localhost
    smtp_starttls = True
    smtp_ssl = False
    smtp_port = 25
    smtp_mail_from = airflow@example.com

    [kubernetes]
    in_cluster = True
    namespace = {{ .Release.Namespace }}
    airflow_configmap = {{ template "airflow.fullname" . }}-configuration
    run_as_user = 1001
    fs_group = 1001
    worker_pods_creation_batch_size = {{ .Values.workerImage.batchSize | int }}
    worker_container_repository = {{ .Values.workerImage.registry }}/{{ .Values.workerImage.repository }}
    worker_container_tag = {{ .Values.workerImage.tag }}
    worker_container_image_pull_policy = {{ .Values.workerImage.pullPolicy }}
    worker_service_account_name = {{ template "airflow.fullname" . }}-service-account
    delete_worker_pods = True
    dags_volume_claim = {{ template "airflow.fullname" . }}-dags-volumeclaim
    logs_volume_claim = {{ template "airflow.fullname" . }}-logs-volumeclaim

    [kubernetes_environment_variables]
    WORKDIR_VOLUMECLAIM = {{ template "airflow.fullname" . }}-workdir-volumeclaim
    AIRFLOW_FERNET_KEY = {{ .Values.airflow.auth.fernetKey }}
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lduparc** [comment]
Issue seems to be related to securityContext, So I updated my pod_mutation_hook with :

```
pod.security_context = {
       "run_as_user": 1001,
       "fs_group": 1001,
    }
```

same issue...

**Comment by juan131** [comment]
Hi @lduparc 

Please note the worker we (Bitnami) provide is a non-root container, and therefore, we set that securityContext to ensure the container is run with a non-root user. However, you can change that in your values.yaml to use a privileged user.

If you take a look to the Dockerfile we use to create the worker (see the link below), you'll see that we set the user to `1000` by default:

```Dockerfile
USER 1001
```

-  https://github.com/bitnami/bitnami-docker-airflow-worker/blob/master/1/debian-9/Dockerfile

Also, the `bitnami-pkg unpack` action (which downloads and unpack the worker code) ensure the permission are fine. You'll need to sth similar.

```Dockerfile
RUN bitnami-pkg unpack airflow-worker-1.10.7-0 --checksum bdeac3be58a9c5ca55cb4e595191244907638acfec6454f6f57095946c061bf8
```
