### ISSUE TITLE
[bitnami/keycloak] Keycloak with KeycloakConfigCli -- everything broken at max

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#18828]
### Name and Version

bitnamicharts/keycloak:16.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Executed this command to install the helm chart.

`helm install demo-keycloak oci://registry-1.docker.io/bitnamicharts/keycloak --values=./values.yaml `

result::

```
root@devops61:~/keycloak/keycloak# helm install demo-keycloak oci://registry-1.docker.io/bitnamicharts/keycloak --values=./values.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
Pulled: registry-1.docker.io/bitnamicharts/keycloak:16.0.5
Digest: sha256:edb093ba06978b29d7fcb78e6f14389b707a1eb2224af1e91c1b8b5d4b8d3212
Error: INSTALLATION FAILED: failed post-install: 1 error occurred:
        * timed out waiting for the condition


```

final result:

```
root@devops61:~/keycloak/keycloak# k get pods
NAME                                              READY   STATUS    RESTARTS      AGE
common.names.fullname-keycloak-config-cli-dzv9h   0/1     Error     0             37m
common.names.fullname-keycloak-config-cli-rfr4g   0/1     Error     0             34m
demo-keycloak-0                                   0/1     Running   1 (31m ago)   37m
demo-keycloak-postgresql-0                        1/1     Running   0             37m
```

Issues:

1: the name of the KeycloakconfigCli Pod is not interpolated by the templates.
2: Keyclok never stays up, container is alway restarting 

```
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       38m                    default-scheduler  Successfully assigned default/demo-keycloak-0 to devops66.ef.com
  Normal   AddedInterface  38m                    multus             Add eth0 [10.42.1.50/32] from k8s-pod-network
  Normal   Pulled          38m                    kubelet            Container image "docker.io/bitnami/keycloak:22.0.1-debian-11-r20" already present on machine
  Normal   Created         38m                    kubelet            Created container keycloak
  Normal   Started         38m                    kubelet            Started container keycloak
  Warning  Unhealthy       35m (x22 over 37m)     kubelet            Readiness probe failed: Get "http://10.42.1.50:8080/iauthrealms/master": dial tcp 10.42.1.50:8080: connect: connection refused
  Warning  Unhealthy       33m                    kubelet            Liveness probe failed: Get "http://10.42.1.50:8080/iauth": dial tcp 10.42.1.50:8080: connect: connection refused
  Warning  Unhealthy       3m28s (x196 over 29m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
```

### Are you using any custom parameters or values?

my values.yaml ( changes only )

```YAML
auth:
  adminUser: admin
  adminPassword: "admin"
httpRelativePath: "/iauth"

extraEnvVars:
    - name:  KEYCLOAK_ADMIN_URL
      value: https://devops67.ef.com/iauth/
    - name:  KEYCLOAK_EXTRA_ARGS
      value: -Dkeycloak.frontendUrl=https://devops67.ef.com/auth/  -Dkeycloak.profile.feature.upload_scripts=enabled
    - name:  KEYCLOAK_FRONTEND_URL
      value: https://devops67.ef.com/iauth/
    - name:  KEYCLOAK_LOGLEVEL
      value: DEBUG
    - name:  KEYCLOAK_PASSWORD
      value: admin
    - name:  KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name:  KEYCLOAK_USER
      value: admin
    - name:  NODE_ENV
      value: development

ingress:
   enabled: false
   pathType: Prefix
   hostname: devops67.ef.com
   annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.org/server-snippets: |
         location / {
           proxy_set_header X-Forwarded-For $host;
           proxy_set_header X-Forwarded-Proto $scheme;
         }
   tls: true
   selfSigned: true

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

keycloakConfigCli:
  enabled: true
  existingConfigmap: "ef-keycloak-realm"


```

### What is the expected behavior?

Keycloak with KeycloakConfigCli should bootstrap the realm. Its doesn't 
Keycloak itself never stays up.

Please note: the same environment, Keycloak version 19.x stays without any issues.

### What do you see instead?

```
root@devops61:~/keycloak/keycloak# k get pods
NAME                                              READY   STATUS    RESTARTS      AGE
common.names.fullname-keycloak-config-cli-dzv9h   0/1     Error     0             40m
common.names.fullname-keycloak-config-cli-rfr4g   0/1     Error     0             37m
demo-keycloak-0                                   0/1     Running   1 (35m ago)   40m
demo-keycloak-postgresql-0                        1/1     Running   0             40m
root@devops61:~/keycloak/keycloak#

```

And

```
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       38m                    default-scheduler  Successfully assigned default/demo-keycloak-0 to devops66.ef.com
  Normal   AddedInterface  38m                    multus             Add eth0 [10.42.1.50/32] from k8s-pod-network
  Normal   Pulled          38m                    kubelet            Container image "docker.io/bitnami/keycloak:22.0.1-debian-11-r20" already present on machine
  Normal   Created         38m                    kubelet            Created container keycloak
  Normal   Started         38m                    kubelet            Started container keycloak
  Warning  Unhealthy       35m (x22 over 37m)     kubelet            Readiness probe failed: Get "http://10.42.1.50:8080/iauthrealms/master": dial tcp 10.42.1.50:8080: connect: connection refused
  Warning  Unhealthy       33m                    kubelet            Liveness probe failed: Get "http://10.42.1.50:8080/iauth": dial tcp 10.42.1.50:8080: connect: connection refused
  Warning  Unhealthy       3m28s (x196 over 29m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
```

### Additional information

Its RKE2 based cluster running.

```
root@devops61:~/keycloak/keycloak# k get nodes -o wide
NAME              STATUS   ROLES                       AGE     VERSION           INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
devops61.ef.com   Ready    control-plane,etcd,master   3d16h   v1.25.12+rke2r1   10.192.168.61   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
devops62.ef.com   Ready    control-plane,etcd,master   3d16h   v1.25.12+rke2r1   10.192.168.62   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
devops63.ef.com   Ready    control-plane,etcd,master   3d16h   v1.25.12+rke2r1   10.192.168.63   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
devops64.ef.com   Ready    <none>                      3d16h   v1.25.12+rke2r1   10.192.168.64   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
devops65.ef.com   Ready    <none>                      3d16h   v1.25.12+rke2r1   10.192.168.65   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
devops66.ef.com   Ready    <none>                      3d16h   v1.25.12+rke2r1   10.192.168.66   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
devops68.ef.com   Ready    <none>                      3d16h   v1.25.12+rke2r1   10.192.168.68   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
devops69.ef.com   Ready    <none>                      3d16h   v1.25.12+rke2r1   10.192.168.69   <none>        Ubuntu 22.04.3 LTS   5.15.0-79-generic   containerd://1.7.1-k3s1
root@devops61:~/keycloak/keycloak#
```

**Comment by juan131** [comment]
Hi @busyboy77 

Could you please share the logs of the `demo-keycloak-0` pod's container and describe it? It seems it was restarted and it's unable to reach the "ready" status.

```console
$ kubectl logs demo-keycloak-0 --previous
$ kubectl describe pod demo-keycloak-0
```

> Use `--previous` flag so we obtain the logs from the container that was restarted before reaching readiness status.

**Comment by busyboy77** [comment]
```

root@devops61:~# kubectl logs demo-keycloak-0 --previous
keycloak 10:33:23.09
keycloak 10:33:23.16 Welcome to the Bitnami keycloak container
keycloak 10:33:23.16 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 10:33:23.18 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 10:33:23.22
keycloak 10:33:23.23 INFO  ==> ** Starting keycloak setup **
keycloak 10:33:23.28 INFO  ==> Validating settings in KEYCLOAK_* env vars...
/opt/bitnami/scripts/libvalidations.sh: line 245: return: : numeric argument required
keycloak 10:33:23.56 INFO  ==> Trying to connect to PostgreSQL server demo-keycloak-postgresql...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
keycloak 10:35:54.06 ERROR ==> Unable to connect to host demo-keycloak-postgresql
root@devops61:~#
```


And


```
root@devops61:~# kubectl describe pod demo-keycloak-0
Name:             demo-keycloak-0
Namespace:        default
Priority:         0
Service Account:  demo-keycloak
Node:             devops66.ef.com/10.192.168.66
Start Time:       Thu, 24 Aug 2023 13:27:49 +0500
Labels:           app.kubernetes.io/component=keycloak
                  app.kubernetes.io/instance=demo-keycloak
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=keycloak
                  controller-revision-hash=demo-keycloak-5c49768699
                  helm.sh/chart=keycloak-16.0.5
                  statefulset.kubernetes.io/pod-name=demo-keycloak-0
Annotations:      checksum/configmap-env-vars: efb719802038afe1aea92ff5a77b793497d92933bc372d2759a61b50b176f529
                  checksum/secrets: bd1b6b1c75a880a3c13b31bd05fea312f9cd78b5a054227885b8eb3eecc796d7
                  cni.projectcalico.org/containerID: 7a2b49364c11c5df9bd5cbf7e33993a83e080fe8386c639ad2d916def7107438
                  cni.projectcalico.org/podIP: 10.42.1.54/32
                  cni.projectcalico.org/podIPs: 10.42.1.54/32
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "multus-cni-network",
                        "ips": [
                            "10.42.1.54"
                        ],
                        "default": true,
                        "dns": {}
                    }]
Status:           Running
IP:               10.42.1.54
IPs:
  IP:           10.42.1.54
Controlled By:  StatefulSet/demo-keycloak
Containers:
  keycloak:
    Container ID:   containerd://a45e788672b9f6abb1eebff9e2705cba06233e9c18f0a0871cb433da4b5a182e
    Image:          docker.io/bitnami/keycloak:22.0.1-debian-11-r20
    Image ID:       docker.io/bitnami/keycloak@sha256:736a672fcd01f9e708902dead31395eedf89160969e0d4ef45f292a667c42a3d
    Ports:          8080/TCP, 7800/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 29 Aug 2023 15:36:20 +0500
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 29 Aug 2023 15:33:22 +0500
      Finished:     Tue, 29 Aug 2023 15:35:54 +0500
    Ready:          False
    Restart Count:  4
    Liveness:       http-get http://:http/iauth delay=300s timeout=5s period=1s #success=1 #failure=3
    Readiness:      http-get http://:http/iauthrealms/master delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      demo-keycloak-env-vars  ConfigMap  Optional: false
    Environment:
      KUBERNETES_NAMESPACE:               default (v1:metadata.namespace)
      BITNAMI_DEBUG:                      false
      KEYCLOAK_ADMIN_PASSWORD:            <set to the key 'admin-password' in secret 'demo-keycloak'>       Optional: false
      KEYCLOAK_DATABASE_PASSWORD:         <set to the key 'password' in secret 'demo-keycloak-postgresql'>  Optional: false
      KEYCLOAK_HTTP_RELATIVE_PATH:        /iauth
      KEYCLOAK_ADMIN_URL:                 https://devops67.ef.com/iauth/
      KEYCLOAK_EXTRA_ARGS:                -Dkeycloak.frontendUrl=https://devops67.ef.com/auth/  -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_FRONTEND_URL:              https://devops67.ef.com/iauth/
      KEYCLOAK_LOGLEVEL:                  DEBUG
      KEYCLOAK_PASSWORD:                  admin
      KEYCLOAK_PROXY_ADDRESS_FORWARDING:  true
      KEYCLOAK_USER:                      admin
      NODE_ENV:                           development
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6bcxm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-6bcxm:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                      From     Message
  ----     ------          ----                     ----     -------
  Warning  Unhealthy       4d16h (x4401 over 5d2h)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 404
  Normal   SandboxChanged  8m17s                    kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   AddedInterface  7m33s                    multus   Add eth0 [10.42.1.54/32] from k8s-pod-network
  Normal   AddedInterface  7m33s                    multus   Add eth0 [10.42.1.54/32] from multus-cni-network
  Warning  BackOff         4m44s (x2 over 4m45s)    kubelet  Back-off restarting failed container
  Normal   Pulled          4m33s (x2 over 7m27s)    kubelet  Container image "docker.io/bitnami/keycloak:22.0.1-debian-11-r20" already present on machine
  Normal   Created         4m33s (x2 over 7m26s)    kubelet  Created container keycloak
  Normal   Started         4m30s (x2 over 7m23s)    kubelet  Started container keycloak
  Warning  Unhealthy       3m14s (x22 over 6m47s)   kubelet  Readiness probe failed: Get "http://10.42.1.54:8080/iauthrealms/master": dial tcp 10.42.1.54:8080: connect: connection refused
```

**Comment by busyboy77** [comment]
did someone check the name of the `keycloak-config-cli` pod, its template is not rendering its properly.

```
root@devops61:~# k get pods
NAME                                              READY   STATUS    RESTARTS        AGE
common.names.fullname-keycloak-config-cli-dzv9h   0/1     Error     0               5d2h
common.names.fullname-keycloak-config-cli-rfr4g   0/1     Error     0               5d2h
demo-keycloak-0                                   0/1     Running   4 (59s ago)     5d2h
demo-keycloak-postgresql-0                        1/1     Running   1 (7m29s ago)   5d2h

```

**Comment by juan131** [comment]
Hi!!

It seems the issue is that Keycloak cannot connect to PostgreSQL, see:

```
keycloak 10:33:23.56 INFO  ==> Trying to connect to PostgreSQL server demo-keycloak-postgresql...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
keycloak 10:35:54.06 ERROR ==> Unable to connect to host demo-keycloak-postgresql
```

Did you remove existing PVC(s) in your cluster from previous deployments? You might have some PostgreSQL data that's not compatible with the credentials created for PostgreSQL in the new installation. Find more information about this kind of issues in the link below:

- https://docs.bitnami.com/kubernetes/faq/troubleshooting/troubleshooting-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases

**Comment by busyboy77** [comment]
the PVCV is bound and just got re-created from scratch, so no previous deployment residuals 

```
root@devops61:~# k get pvc
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-demo-keycloak-postgresql-0   Bound    pvc-0aeb1e26-13ef-41f3-b978-a06d61abf0ae   8Gi        RWO            rook-ceph-block   9m37s
root@devops61:~#
```

**Comment by busyboy77** [comment]
I had a slight mistake in httpRelativePath ( was missing the / after `/iauth`, should be `/iauth/` my bad ) 

now getting this error ( the HELM Chart doesn't automatically generate password for the `bn_keycloak` user)

```
2023-08-29 13:08:37,347 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "bn_keycloak"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
        at org.postgresql.Driver.makeConnection(Driver.java:443)
        at org.postgresql.Driver.connect(Driver.java:297)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

going to re-deploy with random password for the bn_keycloak user under postgresql subchart.

**Comment by busyboy77** [comment]
I have managed to run the Keycloak with below given updates

1: disbled the KeyCLoakconfigCli completely.
2: Added the bn_keycloak user's password to the helm chart.

the stack is working fine now, except the ingress , the adminUI is always loading. 

can  you please comment on the ingress related info, if there is something can help. I'm using RKE2 nginx based ingress controller

**Comment by juan131** [comment]
Hi @busyboy77 

> see the pods logs saying something like `/opt/bitnami/scripts/libvalidations.sh: line 245: return: : numeric argument required`

Thanks for reporting it, this sth to be fixed in the keycloak container, see:

- https://github.com/bitnami/containers/blob/main/bitnami/keycloak/22/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L75
- https://github.com/bitnami/containers/blob/main/bitnami/keycloak/22/debian-11/prebuildfs/opt/bitnami/scripts/libvalidations.sh#L229-L246

I'm glad you were able to solve the installation issues. Could you please open a new issue describing the issues with the ingress configuration and close this one? We should stick to the issue topic to avoid confusion to other issues.
