### ISSUE TITLE
[bitnami/elasticsearch] Failed to resolve publish address, Name or service not known

### ISSUE THREAD

**Issue by ThangTran-77** [bitnami/charts#18992]
### Name and Version

bitnami/elasticsearch 7.17.12-debian-11-r35

### What architecture are you using?

None

### What steps will reproduce the bug?

I deployed the bitnami/elasticsearch on k8s version 1.25.6 and ingress nginx version 1.5.1

### What do you see instead?
```
[38;5;6melasticsearch [38;5;5m16:15:58.00 [0m
[38;5;6melasticsearch [38;5;5m16:15:58.00 [0m[1mWelcome to the Bitnami elasticsearch container[0m
[38;5;6melasticsearch [38;5;5m16:15:58.00 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6melasticsearch [38;5;5m16:15:58.00 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6melasticsearch [38;5;5m16:15:58.01 [0m
[38;5;6melasticsearch [38;5;5m16:15:58.01 [0m[38;5;2mINFO [0m ==> ** Starting Elasticsearch setup **
[38;5;6melasticsearch [38;5;5m16:15:58.05 [0m[38;5;2mINFO [0m ==> Configuring/Initializing Elasticsearch...
[38;5;6melasticsearch [38;5;5m16:15:58.07 [0m[38;5;2mINFO [0m ==> Setting default configuration
[38;5;6melasticsearch [38;5;5m16:15:58.12 [0m[38;5;2mINFO [0m ==> Configuring Elasticsearch cluster settings...
[38;5;6melasticsearch [38;5;5m16:15:59.67 [0m[38;5;2mINFO [0m ==> ** Elasticsearch setup finished! **

[38;5;6melasticsearch [38;5;5m16:15:59.69 [0m[38;5;2mINFO [0m ==> ** Starting Elasticsearch **
[2023-09-03T16:16:03,397][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] version[7.17.12], pid[1], build[default/tar/e3b0c3d3c5c130e1dc6d567d6baef1c73eeb2059/2023-07-20T05:33:33.690180787Z], OS[Linux/5.15.0-25-generic/amd64], JVM[BellSoft/OpenJDK 64-Bit Server VM/17.0.8/17.0.8+7-LTS]
[2023-09-03T16:16:03,399][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] JVM home [/opt/bitnami/java], using bundled JDK [false]
[2023-09-03T16:16:03,400][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-14326601103669895906, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms128m, -Xmx128m, -XX:MaxDirectMemorySize=67108864, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/opt/bitnami/elasticsearch, -Des.path.conf=/opt/bitnami/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=true]
[2023-09-03T16:16:06,583][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [aggs-matrix-stats]
[2023-09-03T16:16:06,583][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [analysis-common]
[2023-09-03T16:16:06,583][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [constant-keyword]
[2023-09-03T16:16:06,583][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [frozen-indices]
[2023-09-03T16:16:06,583][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [ingest-common]
[2023-09-03T16:16:06,584][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [ingest-geoip]
[2023-09-03T16:16:06,584][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [ingest-user-agent]
[2023-09-03T16:16:06,584][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [kibana]
[2023-09-03T16:16:06,584][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [lang-expression]
[2023-09-03T16:16:06,584][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [lang-mustache]
[2023-09-03T16:16:06,584][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [lang-painless]
[2023-09-03T16:16:06,585][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [legacy-geo]
[2023-09-03T16:16:06,585][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [mapper-extras]
[2023-09-03T16:16:06,585][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [mapper-version]
[2023-09-03T16:16:06,585][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [parent-join]
[2023-09-03T16:16:06,585][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [percolator]
[2023-09-03T16:16:06,585][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [rank-eval]
[2023-09-03T16:16:06,586][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [reindex]
[2023-09-03T16:16:06,586][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [repositories-metering-api]
[2023-09-03T16:16:06,586][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [repository-encrypted]
[2023-09-03T16:16:06,586][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [repository-url]
[2023-09-03T16:16:06,586][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [runtime-fields-common]
[2023-09-03T16:16:06,587][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [search-business-rules]
[2023-09-03T16:16:06,587][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [searchable-snapshots]
[2023-09-03T16:16:06,587][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [snapshot-repo-test-kit]
[2023-09-03T16:16:06,587][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [spatial]
[2023-09-03T16:16:06,587][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [transform]
[2023-09-03T16:16:06,587][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [transport-netty4]
[2023-09-03T16:16:06,587][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [unsigned-long]
[2023-09-03T16:16:06,588][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [vector-tile]
[2023-09-03T16:16:06,588][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [vectors]
[2023-09-03T16:16:06,588][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [wildcard]
[2023-09-03T16:16:06,588][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-aggregate-metric]
[2023-09-03T16:16:06,588][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-analytics]
[2023-09-03T16:16:06,588][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-async]
[2023-09-03T16:16:06,589][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-async-search]
[2023-09-03T16:16:06,589][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-autoscaling]
[2023-09-03T16:16:06,589][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-ccr]
[2023-09-03T16:16:06,589][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-core]
[2023-09-03T16:16:06,589][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-data-streams]
[2023-09-03T16:16:06,590][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-deprecation]
[2023-09-03T16:16:06,590][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-enrich]
[2023-09-03T16:16:06,590][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-eql]
[2023-09-03T16:16:06,590][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-fleet]
[2023-09-03T16:16:06,590][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-graph]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-identity-provider]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-ilm]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-logstash]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-ml]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-monitoring]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-ql]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-rollup]
[2023-09-03T16:16:06,591][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-security]
[2023-09-03T16:16:06,592][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-shutdown]
[2023-09-03T16:16:06,592][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-sql]
[2023-09-03T16:16:06,592][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-stack]
[2023-09-03T16:16:06,592][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-text-structure]
[2023-09-03T16:16:06,592][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-voting-only-node]
[2023-09-03T16:16:06,592][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [x-pack-watcher]
[2023-09-03T16:16:06,593][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded plugin [repository-s3]
[2023-09-03T16:16:06,628][INFO ][o.e.e.NodeEnvironment    ] [es-elasticsearch-master-0] using [1] data paths, mounts [[/bitnami/elasticsearch/data (/dev/longhorn/pvc-c6ed94a7-38a4-40dc-a8fc-3e1cddc00141)]], net usable_space [7.7gb], net total_space [7.7gb], types [ext4]
[2023-09-03T16:16:06,629][INFO ][o.e.e.NodeEnvironment    ] [es-elasticsearch-master-0] heap size [128mb], compressed ordinary object pointers [true]
[2023-09-03T16:16:06,649][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] node name [es-elasticsearch-master-0], node ID [vlJtAQvMT--9Ia5dQkDSwg], cluster name [elastic], roles [master]
[2023-09-03T16:16:12,650][INFO ][o.e.i.g.ConfigDatabases  ] [es-elasticsearch-master-0] initialized default databases [[GeoLite2-Country.mmdb, GeoLite2-City.mmdb, GeoLite2-ASN.mmdb]], config databases [[]] and watching [/opt/bitnami/elasticsearch/config/ingest-geoip] for changes
[2023-09-03T16:16:12,652][INFO ][o.e.i.g.DatabaseNodeService] [es-elasticsearch-master-0] initialized database registry, using geoip-databases directory [/tmp/elasticsearch-14326601103669895906/geoip-databases/vlJtAQvMT--9Ia5dQkDSwg]
[2023-09-03T16:16:13,224][INFO ][o.e.t.NettyAllocator     ] [es-elasticsearch-master-0] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=4mb, heap_size=128mb}]
[2023-09-03T16:16:13,258][INFO ][o.e.i.r.RecoverySettings ] [es-elasticsearch-master-0] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
[2023-09-03T16:16:13,312][INFO ][o.e.d.DiscoveryModule    ] [es-elasticsearch-master-0] using discovery type [zen] and seed hosts providers [settings]
[2023-09-03T16:16:13,853][INFO ][o.e.g.DanglingIndicesState] [es-elasticsearch-master-0] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
[2023-09-03T16:16:14,373][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] initialized
[2023-09-03T16:16:14,374][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] starting ...
[2023-09-03T16:16:14,377][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [es-elasticsearch-master-0] deprecation component started
[2023-09-03T16:16:15,575][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-elasticsearch-master-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: BindTransportException[Failed to resolve publish address]; nested: UnknownHostException[es-elasticsearch-master-0.es-elasticsearch-master-hl.elastic.svc.cluster.local: Name or service not known];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:173) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.12.jar:7.17.12]
	at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.12.jar:7.17.12]
Caused by: org.elasticsearch.transport.BindTransportException: Failed to resolve publish address
	at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:484) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:414) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:141) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:318) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.node.Node.start(Node.java:1175) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) ~[elasticsearch-7.17.12.jar:7.17.12]
	... 6 more
Caused by: java.net.UnknownHostException: es-elasticsearch-master-0.es-elasticsearch-master-hl.elastic.svc.cluster.local: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1533) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1385) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1306) ~[?:?]
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:270) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:218) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:170) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:482) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:414) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:141) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:318) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.node.Node.start(Node.java:1175) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.17.12.jar:7.17.12]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) ~[elasticsearch-7.17.12.jar:7.17.12]
	... 6 more
uncaught exception in thread [main]
BindTransportException[Failed to resolve publish address]; nested: UnknownHostException[es-elasticsearch-master-0.es-elasticsearch-master-hl.elastic.svc.cluster.local: Name or service not known];
Likely root cause: java.net.UnknownHostException: es-elasticsearch-master-0.es-elasticsearch-master-hl.elastic.svc.cluster.local: Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:270)
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:218)
	at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:170)
	at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:482)
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:414)
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:141)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:318)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
	at org.elasticsearch.node.Node.start(Node.java:1175)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
For complete error details, refer to the log at /opt/bitnami/elasticsearch/logs/elastic.log
[2023-09-03T16:16:15,587][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] stopping ...
[2023-09-03T16:16:15,596][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] stopped
[2023-09-03T16:16:15,597][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] closing ...
[2023-09-03T16:16:15,615][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] closed
```

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami ES container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
