### ISSUE TITLE
[bitnami/airflow] Worker cannot connect to Redis Sentinel

### ISSUE THREAD

**Issue by bappr** [bitnami/charts#1899]
**Which chart**:

`bitnami/airflow`

**Description**

I am using `bitnami/airflow` with my own version of Postgres and Redis.
Airflow worker cannot connect to Redis Sentinel.
```
[2020-02-10 05:09:33,661: ERROR/MainProcess] consumer: Cannot connect to redis://:**@cs-redis:26379/1: Client sent AUTH, but no password is set.
```

**Steps to reproduce the issue:**

1. Deploy the `bitnami/airflow`
2. Enable Sentinel mode on Redis.
3. Connect to `airflow` to port `26379` of Redis.

**Describe the results you received:**

```
[2020-02-10 05:09:33,661: ERROR/MainProcess] consumer: Cannot connect to redis://:**@cs-redis:26379/1: Client sent AUTH, but no password is set.
```

**Describe the results you expected:**

I should not get an error and the worker should start correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @bappr ,
It seems that Airflow is sending authentication parameter to Redis and you configure it to not use authentication.
You could either set up Redis to use authentication or configure Airflow to not use authentication when connecting to Redis.

**Comment by bappr** [comment]
Hi @miguelaeh ,
So my Redis is configured with authentication.
However, I am trying to connect to the sentinel (port `26379`).
If my understanding is correct, Redis client should initiate the connection without authentication to Sentinel. Since it's not the case, does it mean that airflow does not support Redis HA with sentinel? Or did I miss another config?

FYI, I I try to connect to Redis directly of if I disable authentication, I get another error.

**Comment by miguelaeh** [comment]
Hi @bappr ,
To configure the authentication with sentinel using the sub chart we use the parameter `sentinel.usePassword` at https://github.com/bitnami/charts/tree/master/upstreamed/redis#parameters .
As you are using you own redis I guess you should provide `externalRedis.password`. Could you share how are you deploying the Chart?

**Comment by bappr** [comment]
Hi @miguelaeh 
Sure! I am using the redis-ha helm chart from https://github.com/helm/charts/tree/master/stable/redis-ha

I configured the authentication and I am able to authenticate on any redis node directly using redis-cli.

**Comment by miguelaeh** [comment]
Hi @bappr ,
It should be done setting in the Airflow Chart the `externalRedis.password` to the value that your Redis has at the `redisPassword` key in the secret.
But regarding your log 
```
Client sent AUTH, but no password is set
```
It seems like if Redis has not configured the password and the Airflow chart is sending it.
Could you compare the command that the Airflow chart is using to connect to Redis with the command you tested manually? Are they the same?

**Comment by bappr** [comment]
Hi @miguelaeh 
Yep it's what I have done. Are you sure the bitnami airflow can connect to sentinel? I feel this is the issue here.

> the command that the Airflow chart is using to connect to Redis

What do u mean? It's the worker trying to connect to the redis sentinel. So it's the client driver?

On my end I am just testing using the `redis-cli` and I confirm that the auth is enabled.

**Comment by miguelaeh** [comment]
Hi @bappr ,
I tested it using the `stable/redis-ha` with the options `--set auth=true,redisPassword=password` and then deploying Airflow with `--set externalRedis.password=password,externalRedis.host=<redis-ha service>`
It seems to be working for 10 minutes. Could you share the exact options you are using?

**Comment by bappr** [comment]
@miguelaeh 
Thanks for the help.

```
[2020-02-18 10:01:50,552: INFO/MainProcess] Connected to redis://:**@redis-redis-ha:6379/1
[2020-02-18 10:01:50,577: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 10:01:50,625: CRITICAL/MainProcess] Unrecoverable error: ReadOnlyError("You can't write against a read only replica.",)
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 40, in start
    self.sync(c)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 44, in sync
    replies = self.send_hello(c)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/control.py", line 154, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/control.py", line 106, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/control.py", line 477, in broadcast
    limit, callback, channel=channel,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/pidbox.py", line 352, in _broadcast
    channel=chan)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/pidbox.py", line 391, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/connection.py", line 323, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 381, in get
    ret = self.handle_event(fileno, event)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 363, in handle_event
    return self.on_readable(fileno), self
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 359, in on_readable
    chan.handlers[type]()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 736, in _brpop_read
    **options)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 718, in read_response
    raise response
redis.exceptions.ReadOnlyError: You can't write against a read only replica
```


This is what I am getting using 

```
$ helm install redis  stable/redis-ha --set auth=true,redisPassword=bn_airflow,redis.enabled=false

$ helm  install airflow bitnami/airflow --set externalRedis.password=bn_airflow,externalRedis.host=redis-redis-ha,redis.enabled=false,postgresql.enabled=false,externalDatabase.user=postgres,externalDatabase.password=bn_airflow,externalDatabase.database=bn_airflow,externalDatabase.port=5432,externalDatabase.host=cs-postgres.545734a9-69f7-4d1c-9acd-f52482ab828d
```

**Comment by miguelaeh** [comment]
Hi @bappr ,
It seems it is failing because you are trying to write to a Redis replica that is read-only. I guess it should be solved connecting to the master node. Taking a look to the redis-ha Chart you should find by default 3 `announce` services, try to find the one for the master and is that instead.

**Comment by bappr** [comment]
Hi @miguelaeh 
That's exactly my point actually. And you're right, it's failing because the `redis-ha` service is not configure to target the master node. Instead I should connect to sentinel, and sentinel is gonna give me the master. So we are back to my previous question. Is Airflow supporting Redis sentinel or not? -> https://redis.io/topics/sentinel-clients
Because I truly think the issue is here. If you are not, fine, I will try something with your helm chart.

**Comment by miguelaeh** [comment]
Hi @bappr ,
Thank you for the link, now I understand your point. I took a look to the airflow docs, but searching for sentinel I only found this: https://airflow.apache.org/docs/stable/_api/airflow/models/index.html?highlight=redis%20sentinel#airflow.models.Variable.__NO_DEFAULT_SENTINEL.
Do you know how can be Airflow configured to use Sentinel?
Also, maybe I a wrong, but in the `redis-ha` chart the Sentinel is a sidecar container so maybe the problem could be solved configuring the services correctly to target the master, but that Helm Chart is not our.

**Comment by bappr** [comment]
Hey @miguelaeh 
Unfortunately no I don't know ;)
But it's fine I am gonna try using your helm chart :)
Thanks a lot for your help!

**Comment by miguelaeh** [comment]
No problem @bappr , if you figure out how to do it and you want to share it we will be working on add it or fix whatever is needed. Thanks to you for reporting this!!

**Comment by miguelaeh** [comment]
Hi @bappr ,
I would like to share with you that are working on a new topolog ofr the Redis Helm Chart that will not use sentinel, so this issue should no appear anymore. you can see the PR here: https://github.com/helm/charts/pull/21258
