### ISSUE TITLE
Keycloak JDBC connection not established because of user

### ISSUE THREAD

**Issue by EE1234EE** [bitnami/charts#19314]
### Name and Version

bitnami/keycloak, postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Fresh Minikube Cluster
2. helm repo list: bitnami https://charts.bitnami.com/bitnami
3. helm install keycloak bitnami/keycloak --values path to my values.yaml
4. kubectl get pods CrashLoopBack Keycloak pod. Error in actual behavior.

### Are you using any custom parameters or values?
values.yaml:

```yaml
containerPorts:
  http: 8080

auth:
  adminUser: edwin
  adminPassword: 123abc

service:
  ports:
    http: 8090

postgresql:
  auth:
    postgresPassword: 123abc
    username: edwin
    password: 123abc

externalDatabase:
  user: edwin
  password: 123abc
```

### What is the expected behavior?
A running Keycloak with root User edwin. Probably a rookie mistake. But I can not find a explanation why it's not working.

### What do you see instead?
```
2023-09-17 13:20:20,518 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': FATAL: password authentication failed for user "edwin"
2023-09-17 13:20:20,523 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "edwin"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
        at org.postgresql.Driver.makeConnection(Driver.java:443)
        at org.postgresql.Driver.connect(Driver.java:297)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami keycloak container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
