### ISSUE TITLE
[keycloak 22.0.3] keycloak cli export fail when cache enabled

### ISSUE THREAD

**Issue by CaptainKrby** [bitnami/charts#19464]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Apply any value, but don't forget to activate the cache so that it uses the Kubernetes stack.

Changing the cache options for export and import operations is a bad idea.

### Are you using any custom parameters or values?

````yaml
replicaCount: 2
production: true
proxy: edge
httpRelativePath: "/auth/"

auth:
  adminUser: root
  existingSecret: keycloak

cache:
  enabled: true
  stackName: kubernetes
  stackFile: "/opt/bitnami/keycloak/conf/cache-ispn.xml"

extraEnvVars:
- name: KC_HOSTNAME_URL
  value: https://mykeycloak/auth
- name: KC_HOSTNAME_ADMIN_URL
  value: https://mykeycloak/auth

postgresql:
  enabled: true
  architecture: replication
  auth:
    postgresPassword: ""
    username: keycloak
    password: ""
    database: keycloakdb
    existingSecret: "keycloak-postgresql"
  primary:
    persistence:
      size: 1Gi
  readReplicas:
    replicaCount: 1
    podAntiAffinityPreset: hard
    persistence:
      size: 1Gi
````

### What is the expected behavior?

I should be able to export via `kc.sh` while keeping my cache activated, this problem has been fixed by this PR since Keycloak 22.0.0:

https://github.com/keycloak/keycloak/pull/19645

### What do you see instead?

I have BindException :

````
keycloak@keycloak-valid-0:/opt/bitnami/keycloak/bin$ ./kc.sh export --dir=/var/tmp --realm=antidot-internal --users-per-file=100
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=keycloak-valid-headless.keycloak-valid.svc.k8s-valid.local
2023-09-22 07:59:04,199 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: https://keycloak-valid.corp.net/auth, Hostname: keycloak-valid.corp.net, Strict HTTPS: true, Path: /auth, Strict BackChannel: false, Admin URL: https://keycloak-valid.corp.net/auth, Admin: keycloak-valid.corp.net, Port: -1, Proxied: true
2023-09-22 07:59:06,578 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-09-22 07:59:07,603 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-09-22 07:59:07,769 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-09-22 07:59:08,095 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2023-09-22 07:59:08,098 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: ba17675f-dc75-4c95-8d11-319eaf9b8620, name: keycloak-valid-0-22723
2023-09-22 07:59:08,103 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheException: Unable to start JGroups Channel
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:622)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:489)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:84)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.BindException: No available port to bind to in range [7800 .. 7800]
        at org.jgroups.util.Util.bind(Util.java:4095)
        at org.jgroups.util.Util.createServerSocket(Util.java:4071)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:68)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:43)
        at org.jgroups.protocols.TCP.start(TCP.java:111)
        at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:905)
        at org.jgroups.JChannel.startStack(JChannel.java:921)
        at org.jgroups.JChannel._preConnect(JChannel.java:799)
        at org.jgroups.JChannel.connect(JChannel.java:322)
        at org.jgroups.JChannel.connect(JChannel.java:316)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:620)
        ... 28 more

2023-09-22 07:59:08,149 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2023-09-22 07:59:08,198 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: Unable to start JGroups Channel
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No available port to bind to in range [7800 .. 7800]
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
````

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami keycloak container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by CaptainKrby** [comment]
Thank you for your feedback, but I don't entirely agree. My environment is very basic, I don't have any specific configuration. I think we should dig into Bitnami.

Can you at least confirm that this doesn't happen to you when applying a minimal conf with cache enabled? 
Then a command `kc.sh export --dir /var/tmp/ --users realm_file` on one of the replicas?

**Comment by jruhe-adesso** [comment]
Same here. This is a serious issue, since going back to 22.0.2 is no option.

**Comment by CaptainKrby** [comment]
@jruhe-adesso I opened the issue here : https://github.com/keycloak/keycloak/issues/23595
