### ISSUE TITLE
[bitnami/fluentd] Include more plugins or permit installation of plugins with bitnami's initScripts system

### ISSUE THREAD

**Issue by dionysius** [bitnami/charts#20304]
### Name and Version

bitnami/fluentd

### What is the problem this feature will solve?

I want to configure the aggregator to output in gelf (`@type gelf` instead of `@type stdout`), but the plugin is not installed. Adding it via initScripts fails due to permissions. Neither `sudo` (not installed) nor `su` (already dropped) help.

```yaml
  ## @param aggregator.initScripts Dictionary of init scripts. Evaluated as a template.
  ## ...
  initScripts:
    install_dependencies.sh: |-
      #!/bin/sh
      fluent-gem install 'fluent-plugin-gelf-hs'
```

```
$ kubectl logs -n kube-system fluentd-0 
fluentd 12:22:30.68 
fluentd 12:22:30.68 Welcome to the Bitnami fluentd container
fluentd 12:22:30.69 Subscribe to project updates by watching https://github.com/bitnami/containers
fluentd 12:22:30.69 Submit issues and feature requests at https://github.com/bitnami/containers/issues
fluentd 12:22:30.69 
fluentd 12:22:30.69 INFO  ==> ** Starting Fluentd setup **
fluentd 12:22:30.70 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
#<Thread:0x00007f1241af9038 /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `initialize': Permission denied @ rb_sysopen - /opt/bitnami/fluentd/gelf-3.1.0.gem (Errno::EACCES)
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `open'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `open_file'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:773:in `write_binary'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/remote_fetcher.rb:293:in `cache_update_path'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/remote_fetcher.rb:147:in `download'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/source.rb:208:in `download'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/resolver/specification.rb:113:in `download'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
#<Thread:0x00007f1241af9178 /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `initialize': Permission denied @ rb_sysopen - /opt/bitnami/fluentd/fluent-plugin-gelf-hs-1.0.8.gem (Errno::EACCES)
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `open'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `open_file'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:773:in `write_binary'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/remote_fetcher.rb:293:in `cache_update_path'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/remote_fetcher.rb:147:in `download'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/source.rb:208:in `download'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/resolver/specification.rb:113:in `download'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /opt/bitnami/fluentd/fluent-plugin-gelf-hs-1.0.8.gem
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `initialize'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `open'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:786:in `open_file'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems.rb:773:in `write_binary'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/remote_fetcher.rb:293:in `cache_update_path'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/remote_fetcher.rb:147:in `download'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/source.rb:208:in `download'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/resolver/specification.rb:113:in `download'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
```

### What is the feature you are proposing to solve the problem?

Either include some common used plugins or offer to install them during container creation. I believe the permissions are already dropped when initscripts are handled.

### What alternatives have you considered?

Followup of https://github.com/bitnami/charts/issues/13741

**Comment by juan131** [comment]
Hi @dionysius 

The Fluentd container, for security reasons, is executed as a non-root container and, therefore, the user (UID `1001` by default) doesn't have permissions to install new plugins, see:

- https://github.com/bitnami/charts/blob/main/bitnami/fluentd/values.yaml#L654-L687

We recommend you to extend the Bitnami Fluentd container image adding your custom plugins as it's explained in the link below:

- https://github.com/bitnami/containers/tree/main/bitnami/fluentd#extend-this-image

... Then, you can install the Bitnami Fluentd chart using your custom image.
