### ISSUE TITLE
[bitnami/rabbitmq] pika.exceptions.AMQPHeartbeatTimeout: No activity or too many missed heartbeats in the last 30 seconds

### ISSUE THREAD

**Issue by abdelrhman1410** [bitnami/charts#20577]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi Team,

I hope this message finds you well. I'm currently facing a critical issue with a RabbitMQ cluster deployed on Kubernetes using the bitnami/rabbitmq chart version 10.3.5 and image version 3.10.7-debian-11-r11. The RabbitMQ cluster comprises three nodes, and another application interacts with it by opening connections and reading from RabbitMQ queues.

I've implemented the Classic Mirroring feature to ensure high availability for all queues. The policy has been added as a secret, and the necessary configurations have been made successfully, resulting in mirrored queues.

After enabling the Classic Mirroring, I tried to simulate a failover scenario and I closed one of the three nodes, the queue associated with this node has been mirrored to another node successfully and it is available.

However, a pressing issue has emerged related to the heartbeat timeout. When the application attempts to connect to RabbitMQ, the following error occurs:

`2023-11-01 14:01:17,149 - pika.adapters.blocking_connection - ERROR - Unexpected connection close detected: AMQPHeartbeatTimeout: ('No activity or too many missed heartbeats in the last 30 seconds',)
2023-11-01 14:01:17,150 - mgmtworker - ERROR - Error while reading from RabbitMQ
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/mgmtworker/worker.py", line 394, in main
    worker.consume()
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/cloudify/amqp_client.py", line 216, in consume
    self._pika_connection.process_data_events(0.05)
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(timer.is_ready, common_terminator)
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.AMQPHeartbeatTimeout: No activity or too many missed heartbeats in the last 30 seconds
2023-11-01 14:02:35,261 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
2023-11-01 14:02:35,266 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
2023-11-01 14:02:35,269 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
2023-11-01 14:02:35,273 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
`

This issue is hindering our development activities, and I urgently seek your assistance in resolving it. Your prompt attention to this matter is highly appreciated.

### Are you using any custom parameters or values?

Classic Mirroring for ha policy is configured using a K8s secret.

### What is the expected behavior?

I expect the connection to opened and the reading process done with the queues without any issues.

### What do you see instead?

This what I got instead

`2023-11-01 14:01:17,149 - pika.adapters.blocking_connection - ERROR - Unexpected connection close detected: AMQPHeartbeatTimeout: ('No activity or too many missed heartbeats in the last 30 seconds',)
2023-11-01 14:01:17,150 - mgmtworker - ERROR - Error while reading from RabbitMQ
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/mgmtworker/worker.py", line 394, in main
    worker.consume()
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/cloudify/amqp_client.py", line 216, in consume
    self._pika_connection.process_data_events(0.05)
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(timer.is_ready, common_terminator)
  File "/opt/mgmtworker/env/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.AMQPHeartbeatTimeout: No activity or too many missed heartbeats in the last 30 seconds
2023-11-01 14:02:35,261 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
2023-11-01 14:02:35,266 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
2023-11-01 14:02:35,269 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
2023-11-01 14:02:35,273 - pika.adapters.blocking_connection - ERROR - confirm_delivery: confirmation was already enabled on channel=1
`

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by abdelrhman1410** [comment]
Thank you for response @carrodher.

Would you please clarify more this part of your response: "The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment."

I mentioned that I didn't make extra configuration unless adding the ha policy via a load-definition.

What are the configuration that should be done in my environment to avoid such issue?

Appreciate your support.

**Comment by abdelrhman1410** [comment]
Another question please @carrodher: What should I do if I wanted to increase the Heartbeat Timeout?

**Comment by javsalgar** [comment]
Hi!

Could it be in the rabbitmq.conf file? Probably RabbitMQ devs will know better in this case.
