### ISSUE TITLE
persistant data by mounting nfs volume

### ISSUE THREAD

**Issue by moinologics** [bitnami/charts#20671]
### Name and Version

bitnami/rabbitmq 11.0.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. deploy it with the values.yaml giving below

### Are you using any custom parameters or values?

```yaml
persistence:
  enabled   = false
  mountPath = "/home" #or any other unusable dir
extraVolumes
  - name: "persistence-data"
    nfs:
      server = "<nfs-host>"
      path   = "/"
extraVolumeMounts
  - name      = "persistence-data"
    subPath   = "rabbitmq"
    mountPath = "/bitnami/rabbitmq/mnesia"

```

### What is the expected behavior?

container should start

### What do you see instead?
```
rabbitmq 18:32:44.79 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 18:32:44.80 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 18:32:44.82 INFO  ==> Initializing RabbitMQ...
rabbitmq 18:32:44.90 INFO  ==> Starting RabbitMQ in background...
rabbitmq 18:34:51.01 ERROR ==> Couldn't start RabbitMQ in background.
Stream closed EOF for <namespace>/rabbitmq-0 (rabbitmq)
```

### debug logs
```
rabbitmq 12:36:03.08 
rabbitmq 12:36:03.08 Welcome to the Bitnami rabbitmq container
rabbitmq 12:36:03.08 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 12:36:03.08 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 12:36:03.09 
rabbitmq 12:36:03.09 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 12:36:03.10 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 12:36:03.13 INFO  ==> Initializing RabbitMQ...
rabbitmq 12:36:03.15 DEBUG ==> Creating environment file...
rabbitmq 12:36:03.18 DEBUG ==> Creating enabled_plugins file...
rabbitmq 12:36:03.19 DEBUG ==> Creating Erlang cookie...
rabbitmq 12:36:03.20 DEBUG ==> Ensuring expected directories/files exist...
rabbitmq 12:36:03.22 INFO  ==> Starting RabbitMQ in background...
Waiting for erlang distribution on node 'rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local' while OS process '51' is running
2023-11-08 12:36:08.442914+00:00 [warning] <0.136.0> Failed to write PID file "/bitnami/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local.pid": permission denied
Waiting for applications 'rabbit_and_plugins' to start on node 'rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local'
2023-11-08 12:36:11.484226+00:00 [notice] <0.44.0> Application syslog exited with reason: stopped
2023-11-08 12:36:11.484520+00:00 [notice] <0.239.0> Logging: switching to configured handler(s); following messages may not be visible in this log output
2023-11-08 12:36:11.485251+00:00 [notice] <0.239.0> Logging: configured log handlers are now ACTIVE
2023-11-08 12:36:11.793829+00:00 [info] <0.239.0> ra: starting system quorum_queues
2023-11-08 12:36:11.793929+00:00 [info] <0.239.0> starting Ra system: quorum_queues in directory: /tmp/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local/quorum/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local
2023-11-08 12:36:11.892683+00:00 [info] <0.298.0> ra system 'quorum_queues' running pre init for 0 registered servers
2023-11-08 12:36:11.916991+00:00 [info] <0.299.0> ra: meta data store initialised for system quorum_queues. 0 record(s) recovered
2023-11-08 12:36:11.952957+00:00 [notice] <0.305.0> WAL: ra_log_wal init, open tbls: ra_log_open_mem_tables, closed tbls: ra_log_closed_mem_tables
2023-11-08 12:36:11.962796+00:00 [info] <0.239.0> ra: starting system coordination
2023-11-08 12:36:11.962858+00:00 [info] <0.239.0> starting Ra system: coordination in directory: /tmp/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local/coordination/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local
2023-11-08 12:36:11.964002+00:00 [info] <0.312.0> ra system 'coordination' running pre init for 0 registered servers
2023-11-08 12:36:11.964610+00:00 [info] <0.313.0> ra: meta data store initialised for system coordination. 0 record(s) recovered
2023-11-08 12:36:11.964794+00:00 [notice] <0.318.0> WAL: ra_coordination_log_wal init, open tbls: ra_coordination_log_open_mem_tables, closed tbls: ra_coordination_log_closed_mem_tables
2023-11-08 12:36:11.968123+00:00 [info] <0.239.0> 
2023-11-08 12:36:11.968123+00:00 [info] <0.239.0>  Starting RabbitMQ 3.12.7 on Erlang 26.1.2 [jit]
2023-11-08 12:36:11.968123+00:00 [info] <0.239.0>  Copyright (c) 2007-2023 VMware, Inc. or its affiliates.
2023-11-08 12:36:11.968123+00:00 [info] <0.239.0>  Licensed under the MPL 2.0. Website: https://rabbitmq.com

  ##  ##      RabbitMQ 3.12.7
  ##  ##
  ##########  Copyright (c) 2007-2023 VMware, Inc. or its affiliates.
  ######  ##
  ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com

  Erlang:      26.1.2 [jit]
  TLS Library: OpenSSL - OpenSSL 1.1.1w  11 Sep 2023
  Release series support status: supported

  Doc guides:  https://rabbitmq.com/documentation.html
  Support:     https://rabbitmq.com/contact.html
  Tutorials:   https://rabbitmq.com/getstarted.html
  Monitoring:  https://rabbitmq.com/monitoring.html

  Logs: <stdout>

  Config file(s): /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf

  Starting broker...2023-11-08 12:36:11.969591+00:00 [info] <0.239.0> 
2023-11-08 12:36:11.969591+00:00 [info] <0.239.0>  node           : rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local
2023-11-08 12:36:11.969591+00:00 [info] <0.239.0>  home dir       : /opt/bitnami/rabbitmq/.rabbitmq
2023-11-08 12:36:11.969591+00:00 [info] <0.239.0>  config file(s) : /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
2023-11-08 12:36:11.969591+00:00 [info] <0.239.0>  cookie hash    : HXp2c7GXhwMfOvUWngIJRQ==
2023-11-08 12:36:11.969591+00:00 [info] <0.239.0>  log(s)         : <stdout>
2023-11-08 12:36:11.969591+00:00 [info] <0.239.0>  data dir       : /tmp/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local

BOOT FAILED
===========
Error during startup: {error,
                          {cannot_create_plugins_expand_dir,
                              ["/bitnami/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local-plugins-expand",
                               eacces]}}

2023-11-08 12:36:12.103581+00:00 [notice] <0.44.0> Application mnesia exited with reason: stopped
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0> 
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0> BOOT FAILED
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0> ===========
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0> Error during startup: {error,
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0>                           {cannot_create_plugins_expand_dir,
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0>                               ["/bitnami/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local-plugins-expand",
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0>                                eacces]}}
2023-11-08 12:36:12.103911+00:00 [error] <0.239.0> 
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>   crasher:
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     initial call: application_master:init/4
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     pid: <0.238.0>
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     registered_name: []
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     exception exit: {{cannot_create_plugins_expand_dir,
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>                          ["/bitnami/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local-plugins-expand",
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>                           eacces]},
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>                      {rabbit,start,[normal,[]]}}
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>       in function  application_master:init/4 (application_master.erl, line 142)
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     ancestors: [<0.237.0>]
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     message_queue_len: 1
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     messages: [{'EXIT',<0.239.0>,normal}]
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     links: [<0.237.0>,<0.44.0>]
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     dictionary: []
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     trap_exit: true
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     status: running
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     heap_size: 2586
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     stack_size: 28
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>     reductions: 170
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0>   neighbours:
2023-11-08 12:36:13.105471+00:00 [error] <0.238.0> 
2023-11-08 12:36:13.111941+00:00 [notice] <0.44.0> Application rabbit exited with reason: {{cannot_create_plugins_expand_dir,["/bitnami/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local-plugins-expand",eacces]},{rabbit,start,[normal,[]]}}
Stack trace: 

** (CaseClauseError) no case clause matching: {:badrpc, :nodedown}
    (rabbitmqctl 3.12.1) lib/rabbitmq/cli/core/helpers.ex:105: anonymous fn/2 in RabbitMQ.CLI.Core.Helpers.stream_until_error_parameterised/2
    (elixir 1.15.4) lib/stream.ex:990: Stream.do_transform_user/6
    (elixir 1.15.4) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
    (rabbitmqctl 3.12.1) lib/rabbitmq/cli/core/output.ex:56: RabbitMQ.CLI.Core.Output.print_output_0/3
    (rabbitmqctl 3.12.1) lib/rabbitmq/cli/core/output.ex:31: RabbitMQ.CLI.Core.Output.print_output/3
    (rabbitmqctl 3.12.1) lib/rabbitmqctl.ex:234: RabbitMQCtl.process_output/3
    (rabbitmqctl 3.12.1) lib/rabbitmqctl.ex:642: RabbitMQCtl.maybe_with_distribution/3

{:case_clause, {:badrpc, :nodedown}}

Kernel pid terminated (application_controller) ("{application_start_failure,rabbit,{{cannot_create_plugins_expand_dir,[\"/bitnami/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local-plugins-expand\",eacces]},{rabbit,start,[normal,[]]}}}")

Crash dump is being written to: /opt/bitnami/rabbitmq/var/log/rabbitmq/erl_crash.dump...done
Waiting for erlang distribution on node 'rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local' while OS process '51' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local' while OS process '51' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local' while OS process '51' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local' while OS process '51' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@rabbitmq-0.rabbitmq-headless.third-party-apps.svc.cluster.local' while OS process '51' is running
Error:
process_not_running

```

**Comment by carrodher** [comment]
Could you try adding debug to the container?  
```yaml
image:
  debug: true
```

In that way you can see more info about what's happening

**Comment by moinologics** [comment]
@carrodher i have added debug logs
