### ISSUE TITLE
Can't submit python application to container cluster

### ISSUE THREAD

**Issue by minhhotboy9x** [bitnami/charts#21064]
### Name and Version

bitnami/spark:3.5.0-debian-11-r16

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I used docker-compose to build a multi-spark container on Windows. It has 1 master and 2 workers' containers. When I accessed master and workers and executed some scripts at spark-shell to test, it worked very fine. However, when I tried to submit a Python script from local, it failed.
2. Here are my `docker-compose.yaml` and `spark-example.py` respectively:
```yaml
version: '3'
services:
  spark-master:
    image: bitnami/spark:3.5.0-debian-11-r16
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOSTNAME=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "1" # Adjust as needed
          memory: 1G  # Adjust as needed
    # command: bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:3.5.0-debian-11-r16
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    deploy:
      resources:
        limits:
          cpus: "1" # Adjust as needed
          memory: 1G  # Adjust as needed
    depends_on:
      - spark-master
    # command: bin/spark-class org.apache.spark.deploy.worker.Worker
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:3.5.0-debian-11-r16
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    deploy:
      resources:
        limits:
          cpus: "1" # Adjust as needed
          memory: 1G  # Adjust as needed
    depends_on:
      - spark-master
    # command: bin/spark-class org.apache.spark.deploy.worker.Worker
    networks:
      - spark-network
      
networks:
  spark-network:
    driver: host
```
```python
from pyspark.sql import SparkSession
def main():
    spark = SparkSession.builder \
        .appName("PrintNumbers") \
        .getOrCreate()

    numbers = list(range(1, 21))
    rdd = spark.sparkContext.parallelize(numbers)

    rdd.foreach(print)

    spark.stop()

if __name__ == "__main__":
    main()
```
3. I ran submit script:
``` C:\Spark\spark-3.0.0-bin-hadoop3.2> bin\spark-submit --master spark://192.168.1.13:7077 "D:/spark-k8s tutorial/spark-example.py"
```
and it returned error
```
23/11/21 01:48:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
23/11/21 01:48:25 INFO SparkContext: Running Spark version 3.0.0
23/11/21 01:48:25 INFO ResourceUtils: ==============================================================
23/11/21 01:48:25 INFO ResourceUtils: Resources for spark.driver:

23/11/21 01:48:25 INFO ResourceUtils: ==============================================================
23/11/21 01:48:25 INFO SparkContext: Submitted application: PrintNumbers
23/11/21 01:48:25 INFO SecurityManager: Changing view acls to: ABC
23/11/21 01:48:25 INFO SecurityManager: Changing modify acls to: ABC
23/11/21 01:48:25 INFO SecurityManager: Changing view acls groups to:
23/11/21 01:48:25 INFO SecurityManager: Changing modify acls groups to:
23/11/21 01:48:25 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ABC); groups with view permissions: Set(); users  with modify permissions: Set(ABC); groups with modify permissions: Set()
23/11/21 01:48:26 INFO Utils: Successfully started service 'sparkDriver' on port 62963.
23/11/21 01:48:26 INFO SparkEnv: Registering MapOutputTracker
23/11/21 01:48:26 INFO SparkEnv: Registering BlockManagerMaster
23/11/21 01:48:26 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
23/11/21 01:48:26 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
23/11/21 01:48:26 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
23/11/21 01:48:26 INFO DiskBlockManager: Created local directory at C:\Users\ABC\AppData\Local\Temp\blockmgr-00561954-6406-4770-bb6b-40cfd688c755
23/11/21 01:48:26 INFO MemoryStore: MemoryStore started with capacity 366.3 MiB
23/11/21 01:48:26 INFO SparkEnv: Registering OutputCommitCoordinator
23/11/21 01:48:26 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
23/11/21 01:48:26 INFO Utils: Successfully started service 'SparkUI' on port 4041.
23/11/21 01:48:26 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://MSI.mshome.net:4041
23/11/21 01:48:26 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://192.168.1.13:7077...
23/11/21 01:48:26 INFO TransportClientFactory: Successfully created connection to /192.168.1.13:7077 after 24 ms (0 ms spent in bootstraps)
23/11/21 01:48:46 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://192.168.1.13:7077...
23/11/21 01:49:06 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://192.168.1.13:7077...
23/11/21 01:49:26 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
23/11/21 01:49:26 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
23/11/21 01:49:26 INFO SparkUI: Stopped Spark web UI at http://MSI.mshome.net:4041
23/11/21 01:49:26 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 63023.
23/11/21 01:49:26 INFO NettyBlockTransferService: Server created on MSI.mshome.net:63023
23/11/21 01:49:26 INFO StandaloneSchedulerBackend: Shutting down all executors
23/11/21 01:49:26 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
23/11/21 01:49:26 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
23/11/21 01:49:26 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
23/11/21 01:49:26 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, MSI.mshome.net, 63023, None)
23/11/21 01:49:26 INFO BlockManagerMasterEndpoint: Registering block manager MSI.mshome.net:63023 with 366.3 MiB RAM, BlockManagerId(driver, MSI.mshome.net, 63023, None)
23/11/21 01:49:26 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, MSI.mshome.net, 63023, None)
23/11/21 01:49:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
23/11/21 01:49:26 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, MSI.mshome.net, 63023, None)
23/11/21 01:49:26 INFO MemoryStore: MemoryStore cleared
23/11/21 01:49:26 INFO BlockManager: BlockManager stopped
23/11/21 01:49:26 INFO BlockManagerMaster: BlockManagerMaster stopped
23/11/21 01:49:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
23/11/21 01:49:26 INFO SparkContext: Successfully stopped SparkContext
23/11/21 01:49:26 ERROR SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
        at scala.Predef$.require(Predef.scala:281)
        at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:92)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:565)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
23/11/21 01:49:26 INFO SparkContext: SparkContext already stopped.
Traceback (most recent call last):
  File "D:\spark-k8s tutorial\spark-example.py", line 15, in <module>
    main()
  File "D:\spark-k8s tutorial\spark-example.py", line 5, in main
    .getOrCreate()
  File "C:\Spark\spark-3.0.0-bin-hadoop3.2\python\lib\pyspark.zip\pyspark\sql\session.py", line 186, in getOrCreate
  File "C:\Spark\spark-3.0.0-bin-hadoop3.2\python\lib\pyspark.zip\pyspark\context.py", line 371, in getOrCreate
  File "C:\Spark\spark-3.0.0-bin-hadoop3.2\python\lib\pyspark.zip\pyspark\context.py", line 130, in __init__
  File "C:\Spark\spark-3.0.0-bin-hadoop3.2\python\lib\pyspark.zip\pyspark\context.py", line 193, in _do_init
  File "C:\Spark\spark-3.0.0-bin-hadoop3.2\python\lib\pyspark.zip\pyspark\context.py", line 310, in _initialize_context
  File "C:\Spark\spark-3.0.0-bin-hadoop3.2\python\lib\py4j-0.10.9-src.zip\py4j\java_gateway.py", line 1568, in __call__
  File "C:\Spark\spark-3.0.0-bin-hadoop3.2\python\lib\py4j-0.10.9-src.zip\py4j\protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
        at scala.Predef$.require(Predef.scala:281)
        at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:92)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:565)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)

23/11/21 01:49:26 INFO ShutdownHookManager: Shutdown hook called
23/11/21 01:49:26 INFO ShutdownHookManager: Deleting directory C:\Users\ABC\AppData\Local\Temp\spark-3a7ed786-54a0-4db0-a097-84007aaa8e2c
23/11/21 01:49:26 INFO ShutdownHookManager: Deleting directory C:\Users\ABC\AppData\Local\Temp\spark-df29fa6e-dfb3-4465-9be2-9a3447cc088b
```

### What is the expected behavior?

I expected that it should have worked

### What do you see instead?

Error

**Comment by minhhotboy9x** [comment]
@carrodher I have this issue and I just want sb to help me to solve this. I'm just a beginner in Spark and docker.
