### ISSUE TITLE
listeners are not configured or appended properly when am trying to enable extraListeners

### ISSUE THREAD

**Issue by kalyanibharadwaj** [bitnami/charts#21747]
### Name and Version

bitnami/kafka 24.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

I am deploying three node kafka-kraft version in K8s environment is working fine.
presently require one more listener to access the broker externally, based on the documentation added the extra listeners configuration.
tried 
case-1
```yaml
listeners:
  extraListeners:
    extntls:
      containerPort: 9097
      protocol: PLAINTEXT
      name: EXTLS
      sslClientAuth: ""  
```
case-2
```yaml
listeners:
  extraListeners:
    - name: EXTNTLS
      containerPort: 9097
      protocol: PLAINTEXT
      sslClientAuth: ""  
```
case-3
```yaml
listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT
    name: CLIENT
    sslClientAuth: ""
    
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
    sslClientAuth: ""

  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT
    name: INTERNAL
    sslClientAuth: ""

  extraListeners:
    - name: EXTLS
      containerPort: 9097
      protocol: PLAINTEXT
      sslClientAuth: ""    
```

### Are you using any custom parameters or values?

Custom values mentioned in case

### What is the expected behavior?

`KAFKA_CFG_LISTENERS : INTERNAL://:9094,CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://:9095, EXTNTLS://:9097` with append with extra listener

Client able access the broker externally with those two ports

### What do you see instead?

Formatting storage directories to add metadata...
```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: advertised.listeners listener names must be equal to or a subset of the ones defined in listeners. Found CLIENT,INTERNAL,EXTLS,EXTERNAL. The valid options based on the current configuration are CLIENT,INTERNAL,EXTERNAL,CONTROLLER
	at scala.Predef$.require(Predef.scala:281)
	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2317)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2160)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1568)
	at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:50)
	at scala.Option.flatMap(Option.scala:271)
	at kafka.tools.StorageTool$.main(StorageTool.scala:50)
	at kafka.tools.StorageTool.main(StorageTool.scala)
```
### Additional information

kindly review and suggest, is there any issue with particular version(--version 24.0.4 App version 3.5.1) chart or are we doing anything wrong while configuring extra Listeners and is that possible to expose two ports externally each having different security protocol (PLAINTEXT, SSL)?

**Comment by kalyanibharadwaj** [comment]
Duplicate one
