### ISSUE TITLE
[bitnami/schema-registry] Schema registry will not connect with external kafka in SASL_SSL mode

### ISSUE THREAD

**Issue by Dwijad** [bitnami/charts#22072]
### Name and Version

bitnami/schema-registry 16.2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Configured schema registry with tls encryption.

For tls encryption, generated  JKS truststore and keystore file using cluster CA and with the name `schema-registry.truststore.jks` and `schema-registry-0.keystore.jks`

Created a secret based on the above JKS truststore and keystore file.

`# kubectl create secret generic schema-registry --from-file=schema-registry.truststore.jks --from-file=schema-registry-0.keystore.jks`

Applied the above secret in `auth.tls` section to encrypt communication between schema registry and client.

```
auth:
  tls:    
    enabled: true  
    jksSecret: "schema-registry"
    keystorePassword: "password"
    truststorePassword: "password"
    clientAuthentication: NONE
```
2. Created second secret `kafka-jks-1` from truststore and keystore file which was generated previously for kafka cluster and using the same CA and used it in `auth.kafka` section for encrypting communication between  Schema Registry and External Kafka.

`# kubectl create secret generic kafka-jks-1 --from-file=kafka-broker-0.keystore.jks=./kafka-broker-0.keystore.jks --from-file=kafka-broker-1.keystore.jks=./kafka-broker-1.keystore.jks --from-file=kafka-broker-2.keystore.jks=./kafka-broker-2.keystore.jks --from-file=kafka.truststore.jks=./kafka.truststore.jks`

```
auth:
...
...
  kafka:
    jksSecret: "kafka-jks-1"
    tlsEndpointIdentificationAlgorithm: ""
    keystorePassword: "password"
    truststorePassword: "password"
    saslMechanism: SCRAM-SHA-256
```
3. Configured external kafka configuration 

```
externalKafka:
  brokers:
    - SASL_SSL://test-kafka-broker-0.test-kafka-broker-headless.default.svc.cluster.local:9092
    - SASL_SSL://test-kafka-broker-1.test-kafka-broker-headless.default.svc.cluster.local:9092
    - SASL_SSL://test-kafka-broker-2.test-kafka-broker-headless.default.svc.cluster.local:9092
  listener:
    protocol: SASL_SSL
  sasl:
    user: user
    password: "password"
    existingSecret: "kafka-sr-sasl-password"
```
The installation fails and the schema registry pod goes to error state with the following logs.

```
[2024-01-12 11:14:23,928] ERROR [AdminClient clientId=adminclient-1] Connection to node -1 (test-kafka-broker-0.test-kafka-broker-headless.default.svc.cluster.local/10.244.1.171:9095) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient:899)
[2024-01-12 11:14:23,928] ERROR [AdminClient clientId=adminclient-1] Connection to node -1 (test-kafka-broker-0.test-kafka-broker-headless.default.svc.cluster.local/10.244.1.171:9095) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient:899)
[2024-01-12 11:14:24,005] ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication:79)
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryException: Failed to get Kafka cluster ID
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.kafkaClusterId(KafkaSchemaRegistry.java:1982)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:209)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:101)
	at io.confluent.rest.Application.configureHandler(Application.java:299)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:201)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.kafkaClusterId(KafkaSchemaRegistry.java:1980)
	... 7 more
Caused by: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
```
I know what this error says and it should not be there because i have configured external kafka communication with `auth.kafka.tlsEndpointIdentificationAlgorithm` to none.

### Are you using any custom parameters or values?

```
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0


global:
  imageRegistry: ""
  imagePullSecrets: []

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

image:
  registry: docker.io
  repository: bitnami/schema-registry
  tag: 7.5.3-debian-11-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
command: []
args: []
hostAliases: []
podLabels: {}
configuration: {}
existingConfigmap: ""
log4j: {}
existingLog4jConfigMap: ""
auth:
  tls:
    enabled: true
    jksSecret: "schema-registry"
    keystorePassword: "password"
    truststorePassword: "password"
    clientAuthentication: NONE
  kafka:
    jksSecret: "kafka-jks-1"
    tlsEndpointIdentificationAlgorithm: ""
    keystorePassword: "password"
    truststorePassword: "password"
    saslMechanism: SCRAM-SHA-256
listeners: http://0.0.0.0:8081
avroCompatibilityLevel: backward
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""

replicaCount: 1
updateStrategy:
  type: RollingUpdate
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
podManagementPolicy: OrderedReady
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
priorityClassName: ""
topologySpreadConstraints: {}
schedulerName: ""
terminationGracePeriodSeconds: ""
lifecycleHooks: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
  sysctls: []
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
resources:
  limits: {}
  requests: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
extraVolumes: []
extraVolumeMounts: []
initContainers: []
sidecars: []
pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11
  targetCPU: ""
  targetMemory: ""
  customPodMetrics: []

service:
  type: ClusterIP
  ports:
    http: 8081
  nodePorts:
    http: ""
  clusterIP: ""
  externalTrafficPolicy: Cluster
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
  headless:
    annotations: {}
ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: schema-registry.local
  ingressClassName: ""
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: true

kafka:
  enabled: false
  controller:
    replicaCount: 1
  listeners:
    client:
      protocol: "PLAINTEXT"
  service:
    ports:
      client: 9092
  extraConfig: |-
    offsets.topic.replication.factor=1
  sasl:
    client:
      users:
        - user
      passwords: ""
externalKafka:
  brokers:
    - SASL_SSL://test-kafka-broker-0.test-kafka-broker-headless.default.svc.cluster.local:9092
    - SASL_SSL://test-kafka-broker-1.test-kafka-broker-headless.default.svc.cluster.local:9092
    - SASL_SSL://test-kafka-broker-2.test-kafka-broker-headless.default.svc.cluster.local:9092
  listener:
    protocol: SASL_SSL
  sasl:
    user: user
    password: "password"
    existingSecret: "kafka-sr-sasl-password"

```

### What is the expected behavior?

The schema registry statefulset should be in running state.

### What do you see instead?

```
[2024-01-12 11:14:23,928] ERROR [AdminClient clientId=adminclient-1] Connection to node -1 (test-kafka-broker-0.test-kafka-broker-headless.default.svc.cluster.local/10.244.1.171:9095) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient:899)
[2024-01-12 11:14:23,928] ERROR [AdminClient clientId=adminclient-1] Connection to node -1 (test-kafka-broker-0.test-kafka-broker-headless.default.svc.cluster.local/10.244.1.171:9095) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient:899)
[2024-01-12 11:14:24,005] ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication:79)
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryException: Failed to get Kafka cluster ID
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.kafkaClusterId(KafkaSchemaRegistry.java:1982)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:209)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:101)
	at io.confluent.rest.Application.configureHandler(Application.java:299)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:201)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.kafkaClusterId(KafkaSchemaRegistry.java:1980)
	... 7 more
Caused by: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
```

**Comment by Dwijad** [comment]
The helm chart does not set the schema registry statefulset environment  `tlsEndpointIdentificationAlgorithm `to an empty string.

```
$ k get sts sr-schema-registry -o yaml
...
...
- name: SCHEMA_REGISTRY_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
- name: SCHEMA_REGISTRY_KAFKA_KEYSTORE_PASSWORD
  value: password
...
...
```
 
![Screenshot from 2024-01-13 11-08-34](https://github.com/bitnami/charts/assets/12824049/8dc4c364-095f-4fc6-b532-c4b5ed017cda)

**Comment by Dwijad** [comment]
The certificate issue while connecting to external kafka has gone once i enabled `https` in the listener section which was erroneously set to `http` previously.

Now i have enabled Kafka chart installation in `PLAINTEXT` mode disbaling external kafka and updated the configuration.

```
...
...
listeners: https://0.0.0.0:8081
...
...
auth:
  tls:    
    enabled: true  
    jksSecret: "schema-registry"
    keystorePassword: "password"
    truststorePassword: "password"
    clientAuthentication: NONE
...
...
extraVolumes:
  - name: credentials
    secret:
      secretName: schema-registry
...
...
extraVolumeMounts:
  - name: credentials
    mountPath: /opt/bitnami/schema-registry/certs/
    readOnly: false
...
...
```
But the chart installation with this configuration leads to the following error during schema registry startup even before SSL/SASL settings comes into the picture:

`schema-registry 08:51:03.30 INFO  ==> Validating settings in SCHEMA_REGISTRY_* env vars
schema-registry 08:51:03.33 ERROR ==> In order to configure HTTPS access, you must mount your ssl.keystore.jks (and optionally the ssl.truststore.jks) to the /opt/bitnami/schema-registry/certs directory.`

The issue is more or less similar with this issue #21791

**Comment by kemalgoklensadapay** [comment]
We are observing the exact behavior, looking forward for the fix
