### ISSUE TITLE
Jupyterhub external database config not generated

### ISSUE THREAD

**Issue by DreamingRaven** [bitnami/charts#22703]
### Name and Version

bitnami/jupyterhub 5.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. wrap helm chart in meta / umbrella helm chart to also load postgresql-ha
2. use these values:
```yaml
jupyterhub:
  fullnameOverride: jhub
  hub:
    existingSecret: jhub
    metrics:
      serviceMonitor:
        enabled: true
  proxy:
    service:
      public:
        type: ClusterIP # side note default should probably not be load balancer
  postgresql:
    enabled: false # disable bundled helm chart with jupyterhub (non-ha postgresql)
    externalDatabase:
      host: postgresql-pgpool
      port: 5432
      user: postgres
      existingSecret: postgresql
      existingSecretPasswordKey: password

postgresql-ha:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql-repmgr
    tag: 16.1.0-debian-11-r17
  fullnameOverride: postgres
  postgresql:
    username: postgres
    existingSecret: postgresql
    database: postgres
    replicaCount: 3
    containerPorts:
      postgresql: 5432
  pgpool:
    adminUsername: admin
    existingSecret: pgpool
    replicaCount: 1
    containerPorts:
      postgresql: 5432


```
3. And this meta chart to tie the two together chart:
```yaml
apiVersion: v2
name: jupyterhub
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "4"
dependencies:
- name: jupyterhub
  version: 5.6.0
  repository: "oci://registry-1.docker.io/bitnamicharts"
- name: postgresql-ha
  version: 12.7.0
  repository: "oci://registry-1.docker.io/bitnamicharts"
```
4. see that jupyterhub hub deployment is generated without init container which appears to be what otherwise configures the db:
```yaml
# Source: jupyterhub/charts/jupyterhub/templates/hub/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhub-hub
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/version: 4.0.2
    helm.sh/chart: jupyterhub-5.6.0
    app.kubernetes.io/component: hub
spec:
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: jupyterhub
      app.kubernetes.io/component: hub
  template:
    metadata:
      annotations:
        checksum/hub-config: 1e641480756c6591c6030aba80bba56afc105f3f367f5b6aee8221f96a60fc38
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: jupyterhub
        app.kubernetes.io/version: 4.0.2
        helm.sh/chart: jupyterhub-5.6.0
        app.kubernetes.io/component: hub
        hub.jupyter.org/network-access-proxy-api: "true"
        hub.jupyter.org/network-access-proxy-http: "true"
        hub.jupyter.org/network-access-singleuser: "true"
    spec:
      serviceAccountName: jhub-hub
      
      automountServiceAccountToken: true
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: release-name
                    app.kubernetes.io/name: jupyterhub
                    app.kubernetes.io/component: hub
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      initContainers: # <---- empty init container **********************************************
      containers:
        - name: hub
          image: docker.io/bitnami/jupyterhub:4.0.2-debian-11-r68
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          command:
            - jupyterhub
          args:
            - --config
            - /etc/jupyterhub/jupyterhub_config.py
            - --upgrade-db
          ports:
            - name: http
              containerPort: 8081
          env:
            # and no configuration of the external database makes it through envs either ***********************************
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HELM_RELEASE_NAME
              value: "release-name"
            - name: PROXY_API_SERVICE_PORT
              value: "8001"
            - name: HUB_SERVICE_PORT
              value: "8081"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jhub
                  key: proxy-token
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-externaldb
                  key: db-password
          envFrom:
          resources:
            limits: {}
            requests: {}
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            httpGet:
              path: /hub/health
              port: http
          livenessProbe:
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            httpGet:
              path: /hub/health
              port: http
          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            httpGet:
              path: /hub/health
              port: http
          volumeMounts:
            - mountPath: /etc/jupyterhub/jupyterhub_config.py
              subPath: jupyterhub_config.py
              name: config
            - mountPath: /etc/jupyterhub/z2jh.py
              subPath: z2jh.py
              name: config
            - mountPath: /usr/local/etc/jupyterhub/secret/
              name: secret
      volumes:
        - name: config
          configMap:
            name: jhub-hub
        - name: secret
          secret:
            secretName: jhub
---
```
5. which results in the following logs strangely enough with an sqlite error:
```bash
No config at /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[I 2024-01-24 21:06:44.161 JupyterHub app:2859] Running JupyterHub version 4.0.2
[I 2024-01-24 21:06:44.161 JupyterHub app:2889] Using Authenticator: jupyterhub.auth.PAMAuthenticator-4.0.2
[I 2024-01-24 21:06:44.161 JupyterHub app:2889] Using Spawner: kubespawner.spawner.KubeSpawner-6.2.0
[I 2024-01-24 21:06:44.161 JupyterHub app:2889] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-4.0.2
[E 2024-01-24 21:06:44.222 JupyterHub app:3382]
    Traceback (most recent call last):
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 3379, in launch_instance_async
        await self.initialize(argv)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 2901, in initialize
        self.init_db()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 1835, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/dbutil.py", line 112, in upgrade_if_needed
        orm.check_db_revision(engine)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/orm.py", line 968, in check_db_revision
        current_table_names = set(inspect(engine).get_table_names())
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/inspection.py", line 145, in inspect
        ret = reg(subject)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 303, in _engine_insp
        return Inspector._construct(Inspector._init_engine, bind)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 236, in _construct
        init(self, bind)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 247, in _init_engine
        engine.connect().close()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
        return self._connection_cls(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
        Connection._handle_dbapi_exception_noconnection(
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2430, in _handle_dbapi_exception_noconnection
        raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
        self._dbapi_connection = engine.raw_connection()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
        return self.pool.connect()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 452, in connect
        return _ConnectionFairy._checkout(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
        rec = pool._do_get()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 170, in _do_get
        self._dec_overflow()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
        return self._create_connection()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
        return _ConnectionRecord(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
        self.__connect()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
        pool.logger.debug("Error on connect(): %s", e)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
        self.dbapi_connection = connection = pool._invoke_creator(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 637, in connect
        return dialect.connect(*cargs, **cparams)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 616, in connect
        return self.loaded_dbapi.connect(*cargs, **cparams)
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
    (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Are you using any custom parameters or values?

I am using an umbrella chart which is simply an empty chart (except sealed secrets), that has dependency on jupyterhub and postgresql-ha:
```yaml
jupyterhub:
  fullnameOverride: jhub
  hub:
    existingSecret: jhub
    metrics:
      serviceMonitor:
        enabled: true
  proxy:
    service:
      public:
        type: ClusterIP # side note default should probably not be load balancer
  postgresql:
    enabled: false # disable bundled helm chart with jupyterhub (non-ha postgresql)
    externalDatabase:
      host: postgresql-pgpool
      port: 5432
      user: postgres
      existingSecret: postgresql
      existingSecretPasswordKey: password

postgresql-ha:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql-repmgr
    tag: 16.1.0-debian-11-r17
  fullnameOverride: postgres
  postgresql:
    username: postgres
    existingSecret: postgresql
    database: postgres
    replicaCount: 3
    containerPorts:
      postgresql: 5432
  pgpool:
    adminUsername: admin
    existingSecret: pgpool
    replicaCount: 1
    containerPorts:
      postgresql: 5432
```

### What is the expected behavior?

Init container is generated with the jupyterhub config properly pointing to the external postgresql-ha setup.
Then this is mounted in the normal container via volumemount from init container as normal when postgresql.enabled is true. Unless I have misunderstood how this configuration is given to the jupyter hub deployment.

### What do you see instead?

```bash
No config at /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[I 2024-01-24 21:06:44.161 JupyterHub app:2859] Running JupyterHub version 4.0.2
[I 2024-01-24 21:06:44.161 JupyterHub app:2889] Using Authenticator: jupyterhub.auth.PAMAuthenticator-4.0.2
[I 2024-01-24 21:06:44.161 JupyterHub app:2889] Using Spawner: kubespawner.spawner.KubeSpawner-6.2.0
[I 2024-01-24 21:06:44.161 JupyterHub app:2889] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-4.0.2
[E 2024-01-24 21:06:44.222 JupyterHub app:3382]
    Traceback (most recent call last):
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 3379, in launch_instance_async
        await self.initialize(argv)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 2901, in initialize
        self.init_db()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 1835, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/dbutil.py", line 112, in upgrade_if_needed
        orm.check_db_revision(engine)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/orm.py", line 968, in check_db_revision
        current_table_names = set(inspect(engine).get_table_names())
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/inspection.py", line 145, in inspect
        ret = reg(subject)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 303, in _engine_insp
        return Inspector._construct(Inspector._init_engine, bind)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 236, in _construct
        init(self, bind)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 247, in _init_engine
        engine.connect().close()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
        return self._connection_cls(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
        Connection._handle_dbapi_exception_noconnection(
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2430, in _handle_dbapi_exception_noconnection
        raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
        self._dbapi_connection = engine.raw_connection()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
        return self.pool.connect()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 452, in connect
        return _ConnectionFairy._checkout(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
        rec = pool._do_get()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 170, in _do_get
        self._dec_overflow()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
        return self._create_connection()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
        return _ConnectionRecord(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
        self.__connect()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
        pool.logger.debug("Error on connect(): %s", e)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
        self.dbapi_connection = connection = pool._invoke_creator(self)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 637, in connect
        return dialect.connect(*cargs, **cparams)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 616, in connect
        return self.loaded_dbapi.connect(*cargs, **cparams)
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
    (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Additional information

It appears that the init container which uses the external database variables can never be called, because there is an if condition which blocks execution unless you are using the internal packaged postgresql:
https://github.com/bitnami/charts/blob/e5afe3acfcbeba74482c9ac6c1b2c576b0262623/bitnami/jupyterhub/templates/hub/deployment.yaml#L77-L128

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
