### ISSUE TITLE
[bitnami/airflow] Unable to access the Web-UI of Bitnami/airflow

### ISSUE THREAD

**Issue by mavenzer** [bitnami/charts#22712]
### Name and Version

bitnami/airflow:2.5.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

So we have deployed  Apache  Airflow using Bitnami Helm chart in OC clusters. We have deployed Airflow:2.5.1 almost 7 months ago, it has been a relatively smooth experience for us. But for the past few days we are unable to access Airflow Web-Interface. All the pods are running fine but there are some logs which appears in the Airflow-Webserver-Pod

The logs are as follows
```
100.67.136.2 - - [25/Jan/2024:00:58:58 +0000] "GET /home HTTP/1.1" 500 1611 "https://www.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
[[34m2024-01-25 01:06:15,499[0m] {[34mwebserver_command.py:[0m286} DEBUG[0m - [4 / 4] Starting doing a refresh. Starting 1 workers.[0m
[2024-01-25 01:06:15 +0000] [273] [INFO] Handling signal: ttin
[2024-01-25 01:06:15 +0000] [329] [INFO] Booting worker with pid: 329
[[34m2024-01-25 01:06:16,603[0m] {[34mwebserver_command.py:[0m248} DEBUG[0m - [5 / 5] Killing 1 workers[0m
[2024-01-25 01:06:16 +0000] [273] [INFO] Handling signal: ttou
[2024-01-25 01:06:16 +0000] [325] [INFO] Worker exiting (pid: 325)
[[34m2024-01-25 01:06:16,605[0m] {[34msettings.py:[0m407} DEBUG[0m - Disposing DB connection pool (PID 325)[0m
[2024-01-25 01:06:17 +0000] [273] [WARNING] Worker with pid 325 was terminated due to signal 15
100.67.136.2 - - [25/Jan/2024:01:38:42 +0000] "GET / HTTP/1.1" 302 197 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
[[34m2024-01-25 01:38:43,074[0m] {[34mapp.py:[0m1741} ERROR[0m - Exception on /home [GET][0m
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/auth.py", line 47, in decorated
    from airflow.auth.managers.base_auth_manager import ResourceMethod
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/views.py", line 811, in index
    # find DAGs which have a RUNNING DagRun
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/views.py", line 556, in render_template
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask_appbuilder/baseviews.py", line 322, in render_template
    url,
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/templates/airflow/dags.html", line 44, in top-level template code
    {% elif curr_ordering_direction == 'asc' and request.args.get('sorting_key') == attribute_name %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/templates/airflow/main.html", line 21, in top-level template code
    {% from 'airflow/_messages.html' import show_message %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 42, in top-level template code
    {% block body %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 8, in block 'body'
    {% block navbar %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 10, in block 'navbar'
    {% include 'appbuilder/navbar.html' %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/templates/appbuilder/navbar.html", line 53, in top-level template code
    {% include 'appbuilder/navbar_right.html' %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/templates/appbuilder/navbar_right.html", line 66, in top-level template code
    {% if auth_manager.is_logged_in() %}
  File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'auth_manager' is undefined
100.67.136.2 - - [25/Jan/2024:01:38:43 +0000] "GET /home HTTP/1.1" 500 1611 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
``` 

### Are you using any custom parameters or values?

We have used init containers for adding some python dependencies and also set the fid/gids which are available to our namespace 

### What do you see instead?

So the web-interface of Airflow looks something like this:

<img width="595" alt="airflow-test" src="https://github.com/bitnami/charts/assets/24300927/3ea04838-ece7-4a8c-add8-60e205a848f7">

All the pods are running without any issues(Even the webserver)

<img width="422" alt="airflow-test-2" src="https://github.com/bitnami/charts/assets/24300927/f53aa3c8-8147-425c-aa88-3d6b8d2e4b23">

**Comment by mavenzer** [comment]
Hi @javsalgar   So I have configured the securitycontext as follows
```
          securityContext:
            runAsUser: <user-id-available-in-our-ns> 
```

Also added lifecycle hook to Airflow-webserver, Airflow- Worker, Airflow-Scheduler
```
 containers:
        - name: airflow-web
          image: <custom-image-repo>/airflow:2.5.1
          imagePullPolicy: "IfNotPresent"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "source /opt/bitnami/airflow/venv/bin/activate &&  pip install  --trusted-host artifactory.customrepo.org --index-url=https://artifactory.customrepo.org/artifactory/api/pypi/r-pypi-virtual/simple  pyhdb "]  
```

**Comment by fmulero** [comment]
Hi @mavenzer 

Sorry but I can not reproduce your issue. I tried the chart version 14.0.14, the latests with app version 2.5.1, with the following yaml:
```yaml
web:
  lifecycleHooks: &lifecycleHooks
    postStart:
      exec:
        command: ["/bin/bash", "-c", "source /opt/bitnami/airflow/venv/bin/activate &&  pip install hdbcli"]
  containerSecurityContext: &containerSecurityContext
    runAsUser: 9901
scheduler:
  lifecycleHooks: *lifecycleHooks
  containerSecurityContext: *containerSecurityContext
worker:
  lifecycleHooks: *lifecycleHooks
  containerSecurityContext: *containerSecurityContext
```

Running this command:
```console
$ helm install test oci://registry-1.docker.io/bitnamicharts/airflow --version=14.0.14 -f airflow.yml
NAME: test
LAST DEPLOYED: Tue Jan 30 13:42:33 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: airflow
CHART VERSION: 14.0.14
APP VERSION: 2.5.1

** Please be patient while the chart is being deployed **

Airflow can be accessed via port 8080 on the following DNS name from within your cluster:

    test-airflow.default.svc.cluster.local

To connect to Airflow from outside the cluster, perform the following steps:

1.  Create a port-forward to the service:

    kubectl port-forward --namespace default svc/test-airflow 8080:8080 &
    echo "Airflow URL: http://127.0.0.1:8080"

2. Open a browser and access Airflow using the obtained URL.

3. Get your Airflow login credentials by running:

    export AIRFLOW_PASSWORD=$(kubectl get secret --namespace "default" test-airflow -o jsonpath="{.data.airflow-password}" | base64 -d)
    echo User:     user
    echo Password: $AIRFLOW_PASSWORD
```

In my case, it works as expected.

Could you share more information about the values set? Are you setting any other value in the pod or container security context? How are you pulling your dags? Any information that you think could be useful to diagnose the incident.
