### ISSUE TITLE
[bitnami/redis-cluster] Announce internal DNS hostnames to support in-cluster TLS host certificate SAN validation 

### ISSUE THREAD

**Issue by blulic** [bitnami/charts#23052]
### Name and Version

bitnami/redis-cluster:9.5.0

### What is the problem this feature will solve?

Currently, if the Redis Cluster is not exposed externally, Bitnami Redis Cluster chart doesn't create Redis nodes exposing internal DNS names as the alternate hostnames in the cluster topology:
```
redis-cluster-headless:6379> cluster nodes
a5d70368ce844ac1d63c449bae2bab4de9c1b51a 10.42.0.63:6379@16379 myself,slave cf8a8d8c2182e2c98aa586e38c9f887999b8ceb9 0 1706871203000 2 connected
f13fab288add4dd4e7dcfe05a47180183e92d1e8 10.42.0.60:6379@16379 slave 722ff8de38baa315b369cf808703b9e51dde9655 0 1706871204000 3 connected
eaf514c802d80306267620f3cbf31320aeac76e9 10.42.0.62:6379@16379 slave 7546f93a2d3083fc16949b010fd2d5ca8ef52734 0 1706871205000 1 connected
7546f93a2d3083fc16949b010fd2d5ca8ef52734 10.42.0.48:6379@16379 master - 0 1706871203000 1 connected 0-5460
cf8a8d8c2182e2c98aa586e38c9f887999b8ceb9 10.42.0.61:6379@16379 master - 0 1706871203856 2 connected 5461-10922
722ff8de38baa315b369cf808703b9e51dde9655 10.42.0.49:6379@16379 master - 0 1706871205879 3 connected 10923-16383
```

If the TLS is enabled,  and the certificate contains SANs of the internal DNS cluster nodes, i.e.:
```
X509v3 Subject Alternative Name:
   DNS:redis-cluster-*.redis-cluster-headless, DNS:redis-cluster-headless, DNS:redis-cluster, IP Address:127.0.0.1, DNS:localhost
```
The client cannot verify the hostname against the server certificate as it gets only the IP addresses of the cluster nodes, and they cannot be in the certificate as they are dynamic:
```
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to [rediss://user:**********@redis-cluster-headless:6379]
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) ~[lettuce-core-6.2.7.RELEASE.jar:6.2.7.RELEASE]
....
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 10.42.0.49 found
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:378) ~[?:?]
```
Even if we could add the CIDR of the Kubernetes cluster to the certificate, [RFC2818](https://www.rfc-editor.org/rfc/rfc2818#section-3.1) prevents adding IP addresses with wildcards.

Currently, redis-cluster doesn't have the option to announce internal DNS as the node hostname, as  `cluster-announce-hostname` and `cluster-preferred-endpoint-type hostname` are configured only if the external access is enabled via load balancer IP addresses.

### What is the feature you are proposing to solve the problem?

I am proposing adding new value `cluster.internalAccess.hostMode` which if enabled will do the following (similar as for `.Values.cluster.externalAccess.enabled`) in the `redis-statefulset.yaml` containers args:
- get the pod index 
- create list of ips based on the cluster node names:
```
ips=({{ $count := .Values.cluster.nodes | int }}{{ range $i, $v := until $count }}{{ include "common.names.fullname" $ }}-{{ $i }}.{{ template "common.names.fullname" $ }}-headless {{ end }})
```
 - announce the hostname based on the internal name:
```
export REDIS_CLUSTER_ANNOUNCE_HOSTNAME="${ips[$pod_index]}"
```
- export all redis nodes:
```
export REDIS_NODES="${ips[@]}"
```

and also set the following environment variables:
```yaml
- name: REDIS_CLUSTER_DYNAMIC_IPS
   value: "yes"
 - name: REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE
   value: "hostname"
```

As a result, cluster topology will show announced hostnames for each node besides the IP address:
```
redis-cluster-headless:6379> cluster nodes
7b206618a24c5cb1442cd4232c7d5a4746b83ac6 10.42.0.122:6379@16379,redis-cluster-1.redis-cluster-headless master - 0 1706873049467 2 connected 5461-10922
2a318bc65cbad7048dfac9de98e6e8261bb1a979 10.42.0.108:6379@16379,redis-cluster-0.redis-cluster-headless master - 0 1706873048000 1 connected 0-5460
67c5a3b6e9779f2ad3f5f73db8b9e8b32416d622 10.42.0.124:6379@16379,redis-cluster-4.redis-cluster-headless myself,slave 2a318bc65cbad7048dfac9de98e6e8261bb1a979 0 1706873048000 1 connected
1b964e0bf794b118d9c7c3669814b480d5a9d817 10.42.0.119:6379@16379,redis-cluster-2.redis-cluster-headless master - 0 1706873048454 3 connected 10923-16383
4d09efc47774082c7433c4f12aa8032f7f6dc9a0 10.42.0.125:6379@16379,redis-cluster-3.redis-cluster-headless slave 1b964e0bf794b118d9c7c3669814b480d5a9d817 0 1706873048000 3 connected
2b13331e9170e1da922f71f4b094451ea6f9f387 10.42.0.123:6379@16379,redis-cluster-5.redis-cluster-headless slave 7b206618a24c5cb1442cd4232c7d5a4746b83ac6 0 1706873047000 2 connected
```
And mTLS server certificate hostname validation against the X509 certificate SANs will pass.

### What alternatives have you considered?

I have created a workaround, enabling external access and hostmode, and faking internal DNS AA addresses as the Load balancer IPs:
```yaml
  cluster:
    externalAccess:
      enabled: true
      hostMode: true
      service:
        loadBalancerIP:
         - redis-cluster-0.redis-cluster-headless
         - redis-cluster-1.redis-cluster-headless
         - redis-cluster-2.redis-cluster-headless
         - redis-cluster-3.redis-cluster-headless
         - redis-cluster-4.redis-cluster-headless
         - redis-cluster-5.redis-cluster-headless
    nodes: 6
    replicas: 1
  fullnameOverride: redis-cluster
  nameOverride: redis-cluster
```

This produces the desired result with the warnings:
```
[stderr] W0202 11:28:43.735336   66259 warnings.go:70] spec.loadBalancerIP: IP address was accepted, but will be invalid in a future Kubernetes release: ParseAddr("redis-cluster-1.redis-cluster-headless"): unexpected character (at "redis-cluster-1.redis-cluster-headless")
[stderr] W0202 11:28:43.749889   66259 warnings.go:70] spec.loadBalancerIP: IP address was accepted, but will be invalid in a future Kubernetes release: ParseAddr("redis-cluster-2.redis-cluster-headless"): unexpected character (at "redis-cluster-2.redis-cluster-headless")
[stderr] W0202 11:28:43.812306   66259 warnings.go:70] spec.loadBalancerIP: IP address was accepted, but will be invalid in a future Kubernetes release: ParseAddr("redis-cluster-5.redis-cluster-headless"): unexpected character (at "redis-cluster-5.redis-cluster-headless")
[stderr] W0202 11:28:43.812534   66259 warnings.go:70] spec.loadBalancerIP: IP address was accepted, but will be invalid in a future Kubernetes release: ParseAddr("redis-cluster-3.redis-cluster-headless"): unexpected character (at "redis-cluster-3.redis-cluster-headless")
[stderr] W0202 11:28:43.819030   66259 warnings.go:70] spec.loadBalancerIP: IP address was accepted, but will be invalid in a future Kubernetes release: ParseAddr("redis-cluster-4.redis-cluster-headless"): unexpected character (at "redis-cluster-4.redis-cluster-headless")
[stderr] W0202 11:28:43.869097   66259 warnings.go:70] spec.loadBalancerIP: IP address was accepted, but will be invalid in a future Kubernetes release: ParseAddr("redis-cluster-0.redis-cluster-headless"): unexpected character (at "redis-cluster-0.redis-cluster-headless")
```
```
redis-cluster-headless:6379> cluster nodes
cefcc83254161d49b610d2ff06002f0e4ee7790a 10.42.0.157:6379@16379,redis-cluster-4.redis-cluster-headless slave d450a877147042817bc5010009a16c4d42714a72 0 1706873472835 1 connected
c980fe192886f9c1ad85125437b74b9c7654c423 10.42.0.155:6379@16379,redis-cluster-5.redis-cluster-headless slave 4602bdb9abe6423cd7d0f8976f8eb18a9ef5de48 0 1706873471000 2 connected
7d2a03e5539c006df1c8b076f9afda6a31b322b7 10.42.0.149:6379@16379,redis-cluster-2.redis-cluster-headless master - 0 1706873471000 3 connected 10923-16383
1c056b13f35cb15cd353090792b38905a312c582 10.42.0.154:6379@16379,redis-cluster-3.redis-cluster-headless slave 7d2a03e5539c006df1c8b076f9afda6a31b322b7 0 1706873471819 3 connected
d450a877147042817bc5010009a16c4d42714a72 10.42.0.142:6379@16379,redis-cluster-0.redis-cluster-headless myself,master - 0 1706873472000 1 connected 0-5460
4602bdb9abe6423cd7d0f8976f8eb18a9ef5de48 10.42.0.156:6379@16379,redis-cluster-1.redis-cluster-headless master - 0 1706873469000 2 connected 5461-10922
```

But it also creates unwanted loadbalancer services:
```console
$ kubectl get svc |grep LoadBalancer  |sort
redis-cluster-0-svc      LoadBalancer   10.43.230.121   <pending>       6379:30487/TCP,16379:31914/TCP   77s
redis-cluster-1-svc      LoadBalancer   10.43.77.94     <pending>       6379:31733/TCP,16379:30372/TCP   77s
redis-cluster-2-svc      LoadBalancer   10.43.178.79    192.168.68.14   6379:31905/TCP,16379:32712/TCP   77s
redis-cluster-3-svc      LoadBalancer   10.43.6.127     <pending>       6379:31340/TCP,16379:30088/TCP   77s
redis-cluster-4-svc      LoadBalancer   10.43.127.65    <pending>       6379:32539/TCP,16379:30075/TCP   77s
redis-cluster-5-svc      LoadBalancer   10.43.117.76    <pending>       6379:32101/TCP,16379:31187/TCP   77s
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
