### ISSUE TITLE
[bitnami/keycloak] couldn´t start after helm upgrade 

### ISSUE THREAD

**Issue by anperim** [bitnami/charts#23171]
### Name and Version

bitnami/keycloak:15

### What architecture are you using?

None

### What steps will reproduce the bug?

**In Kubernetes after helm upgrade (version bitnami/keycloak:15 was not modified in command) during startup receive this error:**
```

31m18:08:50,664 FATAL [org.keycloak.services] (ServerService Thread Pool -- 71) Error during startup: java.lang.RuntimeException: Exception invoking method [listUnrunChangeSets] on object [liquibase.Liquibase@2b5685eb], using arguments [null,(),false]
	at org.keycloak.keycloak-common@15.1.1//org.keycloak.common.util.reflections.Reflections.invokeMethod(Reflections.java:386)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.getLiquibaseUnrunChangeSets(LiquibaseJpaUpdaterProvider.java:288)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.validateChangeSet(LiquibaseJpaUpdaterProvider.java:254)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.validate(LiquibaseJpaUpdaterProvider.java:227)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.migration(DefaultJpaConnectionProviderFactory.java:343)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lambda$lazyInit$0(DefaultJpaConnectionProviderFactory.java:211)
	at org.keycloak.keycloak-server-spi-private@15.1.1//org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:753)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:162)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:87)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:65)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:64)
	at org.keycloak.keycloak-model-jpa@15.1.1//org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:40)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.DefaultKeycloakSession.realmLocalStorage(DefaultKeycloakSession.java:228)
	at org.keycloak.keycloak-model-infinispan@15.1.1//org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:149)
	at org.keycloak.keycloak-model-infinispan@15.1.1//org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:411)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.managers.ApplianceBootstrap.isNewInstall(ApplianceBootstrap.java:46)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.resources.KeycloakApplication$3.run(KeycloakApplication.java:195)
	at org.keycloak.keycloak-server-spi-private@15.1.1//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:172)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:136)
	at org.keycloak.keycloak-server-spi-private@15.1.1//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:128)
	at org.keycloak.keycloak-wildfly-extensions@15.1.1//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:36)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2835)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:376)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:288)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:98)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     104 change sets check sum
          META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com was: 9:6f1016664e21e16d26517a4418f5e3df but is now: 7:4e70412f24a3f382c82183742ec79317
          META-INF/db2-jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com was: 9:828775b1596a07d1200ba1d49e5e3941 but is now: 7:cb16724583e9675711801c6875114f28
          META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com was: 9:5f090e44a7d595883c1fb61f4b41fd38 but is now: 7:0310eb8ba07cec616460794d42ade0fa
          META-INF/jpa-changelog-1.1.0.Final.xml::1.1.0.Final::sthorger@redhat.com was: 9:c07e577387a3d2c04d1adc9aaad8730e but is now: 7:5d25857e708c3233ef4439df1f93f012
          META-INF/jpa-changelog-1.2.0.Beta1.xml::1.2.0.Beta1::psilva@redhat.com was: 9:b68ce996c655922dbcd2fe6b6ae72686 but is now: 7:c7a54a1041d58eb3817a4a883b4d4e84
          META-INF/db2-jpa-changelog-1.2.0.Beta1.xml::1.2.0.Beta1::psilva@redhat.com was: 9:543b5c9989f024fe35c6f6c5a97de88e but is now: 7:2e01012df20974c1c2a605ef8afe25b7
          META-INF/jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com was: 9:765afebbe21cf5bbca048e632df38336 but is now: 7:0f08df48468428e0f30ee59a8ec01a41
          META-INF/db2-jpa-changelog-1.2.0.CR1.xml::1.2.0.RC1::bburke@redhat.com was: 9:db4a145ba11a6fdaefb397f6dbf829a1 but is now: 7:a77ea2ad226b345e7d689d366f185c8c
          META-INF/jpa-changelog-1.2.0.Final.xml::1.2.0.Final::keycloak was: 9:9d05c7be10cdb873f8bcb41bc3a8ab23 but is now: 7:a3377a2059aefbf3b90ebb4c4cc8e2ab
          META-INF/jpa-changelog-1.3.0.xml::1.3.0::bburke@redhat.com was: 9:18593702353128d53111f9b1ff0b82b8 but is now: 7:04c1dbedc2aa3e9756d1a1668e003451
          META-INF/jpa-changelog-1.4.0.xml::1.4.0::bburke@redhat.com was: 9:6122efe5f090e41a85c0f1c9e52cbb62 but is now: 7:36ef39ed560ad07062d956db861042ba
          META-INF/db2-jpa-changelog-1.4.0.xml::1.4.0::bburke@redhat.com was: 9:e1ff28bf7568451453f844c5d54bb0b5 but is now: 7:d909180b2530479a716d3f9c9eaea3d7
          META-INF/jpa-changelog-1.5.0.xml::1.5.0::bburke@redhat.com was: 9:7af32cd8957fbc069f796b61217483fd but is now: 7:cf12b04b79bea5152f165eb41f3955f6
          META-INF/jpa-changelog-1.6.1.xml::1.6.1_from15::mposolda@redhat.com was: 9:6005e15e84714cd83226bf7879f54190 but is now: 7:7e32c8f05c755e8675764e7d5f514509
          META-INF/jpa-changelog-1.6.1.xml::1.6.1_from16-pre::mposolda@redhat.com was: 9:bf656f5a2b055d07f314431cae76f06c but is now: 7:980ba23cc0ec39cab731ce903dd01291
          META-INF/jpa-changelog-1.6.1.xml::1.6.1_from16::mposolda@redhat.com was: 9:f8dadc9284440469dcf71e25ca6ab99b but is now: 7:2fa220758991285312eb84f3b4ff5336
          META-INF/jpa-changelog-1.6.1.xml::1.6.1::mposolda@redhat.com was: 9:d41d8cd98f00b204e9800998ecf8427e but is now: 7:d41d8cd98f00b204e9800998ecf8427e
          META-INF/jpa-changelog-1.7.0.xml::1.7.0::bburke@redhat.com was: 9:3368ff0be4c2855ee2dd9ca813b38d8e but is now: 7:91ace540896df890cc00a0490ee52bbc
          META-INF/jpa-changelog-1.8.0.xml::1.8.0::mposolda@redhat.com was: 9:8ac2fb5dd030b24c0570a763ed75ed20 but is now: 7:c31d1646dfa2618a9335c00e07f89f24
          META-INF/jpa-changelog-1.8.0.xml::1.8.0-2::keycloak was: 9:f91ddca9b19743db60e3057679810e6c but is now: 7:df8bc21027a4f7cbbb01f6344e89ce07
          META-INF/db2-jpa-changelog-1.8.0.xml::1.8.0::mposolda@redhat.com was: 9:831e82914316dc8a57dc09d755f23c51 but is now: 7:f987971fe6b37d963bc95fee2b27f8df
          META-INF/db2-jpa-changelog-1.8.0.xml::1.8.0-2::keycloak was: 9:f91ddca9b19743db60e3057679810e6c but is now: 7:df8bc21027a4f7cbbb01f6344e89ce07
          META-INF/jpa-changelog-1.9.0.xml::1.9.0::mposolda@redhat.com was: 9:bc3d0f9e823a69dc21e23e94c7a94bb1 but is now: 7:ed2dc7f799d19ac452cbcda56c929e47
          META-INF/jpa-changelog-1.9.1.xml::1.9.1::keycloak was: 9:c9999da42f543575ab790e76439a2679 but is now: 7:80b5db88a5dda36ece5f235be8757615
          META-INF/db2-jpa-changelog-1.9.1.xml::1.9.1::keycloak was: 9:0d6c65c6f58732d81569e77b10ba301d but is now: 7:1437310ed1305a9b93f8848f301726ce
          META-INF/jpa-changelog-1.9.2.xml::1.9.2::keycloak was: 9:fc576660fc016ae53d2d4778d84d86d0 but is now: 7:b82ffb34850fa0836be16deefc6a87c4

	at org.liquibase//liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:266)
	at org.liquibase//liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.keycloak.keycloak-common@15.1.1//org.keycloak.common.util.reflections.Reflections.invokeMethod(Reflections.java:380)
	... 61 more
```

### What is the expected behavior?

Normal startup

### What do you see instead?

Service is down

**Comment by javsalgar** [comment]
Hi!

From which version you are performing the upgrade?

**Comment by anperim** [comment]
I connect to database and someone tried to update from 15 to 22. I restored the database and works fine.
