### ISSUE TITLE
[bitnami/keycloak] couldn´t reach the keycloak endpoint after upgrade to chart 18.3.4

### ISSUE THREAD

**Issue by epourail** [bitnami/charts#23249]
### Name and Version

bitnami/keycloak 18.3.4

### What architecture are you using?

amd64

### 1. In this environment ...

Azure Kubernetes Service

### 2. With this configuration ...

From the chart version "18.3.3" (app version : 23.0.5) 
with an external mariadb database and behind a Kong gateway

### 3. Run ...

1. the helm upgrade command to apply the 18.3.4 chart version (app version : 23.0.6) 
2. wait the end of the initialisation
3. browse to the keycloak admin page (in my example: "https://my.hostname.com/identity")

### Are you using any custom parameters or values?

```yaml
mariadb:
  auth:
    database: 'keycloak'
    username: 'keycloak'
    existingSecret: '{{ .Release.Name }}-secrets'
  initdbScripts:
    init.sql: "GRANT ALL PRIVILEGES ON *.* TO 'keycloak'@'%';"
  architecture: standalone
  global:
    storageClass: 'managed-premium'
  primary:
    persistence:
      size: 4Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi      

keycloak:
  # Keycloak admin account
  auth:
    adminUser: 'keycloak'
    existingSecret: '{{ .Release.Name }}-secrets'
    passwordSecretKey: kc-admin-password

  # Start Keycloak in production mode
  production: true
  
  # Proxy
  proxy: edge

  # Keycloak extra environment variables
  extraEnvVarsCM: '{{ .Release.Name }}-extra-env-vars'

  # Extra volumes to mount
  extraVolumeMounts:
  - name: provider-config
    mountPath: "/opt/bitnami/keycloak/providers/rightshash-mapper.jar"
    subPath: "rightshash-mapper.jar"
    readOnly: true

  # Extra volumes definition
  extraVolumes:
  - name: provider-config
    configMap:
      name: '{{ .Release.Name }}-mappers'
      items:
      - key: "rightshash-mapper.jar"
        path: "rightshash-mapper.jar"

  httpRelativePath: '/identity'

  ## Keycloak ingress
  ingress:
    enabled: true
    hostname: 'my.hostname.com'
    path: /identity
    pathType: Prefix
    ingressClassName: kong
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      konghq.com/strip-path: "false"

  networkPolicy:
    enabled: false

  # Performance
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  # Database - disable the default postgresql config
  postgresql:
    enabled: false

  # Database - use an external db config
  externalDatabase:
    host: '{{ .Release.Name }}-mariadb'
    port: 3306
    database: 'keycloak'
    user: 'keycloak'
    existingSecret: '{{ .Release.Name }}-secrets'
    existingSecretPasswordKey: 'mariadb-password'

  # Healthcheck probe
  customReadinessProbe:
    httpGet:
      path: /identity/realms/master
      port: 8080
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 5

  # Others
  logging:
    level: "INFO"
```

### What is the expected behavior?

Reach the keycloak endpoint and display the keycloak page.

### What do you see instead?

I receive an error 
with the following message 

> Internal Server Error 
> Error id fd3cf97e-5b3b-47cf-91a1-12e6155a0400-2

with the following pod error logs: 

```logs
2024-02-07 10:04:22,795 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.StringIndexOutOfBoundsException: begin 1, end 1, length 0
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
at java.base/java.lang.String.substring(String.java:2709)
at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.saveUriMatchState(ResteasyReactiveRequestContext.java:692)
at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getMatchedURIs(ResteasyReactiveRequestContext.java:708)
at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getMatchedURIs(UriInfoImpl.java:197)
at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getMatchedURIs(UriInfoImpl.java:187)
at org.jboss.aerogear.keycloak.metrics.ResourceExtractor.getResource(ResourceExtractor.java:42)
at org.jboss.aerogear.keycloak.metrics.MetricsFilter.filter(MetricsFilter.java:49)
at org.jboss.aerogear.keycloak.metrics.MetricsFilterProvider.filter(MetricsFilterProvider.java:26)
at org.jboss.aerogear.keycloak.metrics.MetricsFilterProvider$GeneratedServerResponseFilter$filter.filter(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)
2024-02-07 10:04:23,635 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /identity failed, error id: fd3cf97e-5b3b-47cf-91a1-12e6155a0400-1: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
at java.base/java.util.LinkedList.get(LinkedList.java:480)
at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.saveUriMatchState(ResteasyReactiveRequestContext.java:661)
at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getMatchedURIs(ResteasyReactiveRequestContext.java:708)
at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getMatchedURIs(UriInfoImpl.java:197)
at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getMatchedURIs(UriInfoImpl.java:187)
at org.jboss.aerogear.keycloak.metrics.ResourceExtractor.getResource(ResourceExtractor.java:42)
at org.jboss.aerogear.keycloak.metrics.MetricsFilter.filter(MetricsFilter.java:49)
at org.jboss.aerogear.keycloak.metrics.MetricsFilterProvider.filter(MetricsFilterProvider.java:26)
at org.jboss.aerogear.keycloak.metrics.MetricsFilterProvider$GeneratedServerResponseFilter$filter.filter(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)
```

### Additional information

The helm upgrade command success without error. Here the init logs

```logs
keycloak 09:07:21.79 INFO  ==>
keycloak 09:07:21.79 INFO  ==> Welcome to the Bitnami keycloak container
keycloak 09:07:21.79 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers>
keycloak 09:07:21.79 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues>
keycloak 09:07:21.80 INFO  ==>
keycloak 09:07:21.80 INFO  ==> ** Starting keycloak setup **
keycloak 09:07:21.82 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 09:07:21.84 INFO  ==> Trying to connect to PostgreSQL server demo-core-itg-keycloak-mariadb...
keycloak 09:07:21.85 INFO  ==> Found PostgreSQL server listening at demo-core-itg-keycloak-mariadb:3306
keycloak 09:07:21.85 INFO  ==> Configuring database settings
keycloak 09:07:21.93 INFO  ==> Enabling statistics
keycloak 09:07:21.93 INFO  ==> Enabling health endpoints
keycloak 09:07:21.94 INFO  ==> Configuring http settings
keycloak 09:07:21.96 INFO  ==> Configuring hostname settings
keycloak 09:07:21.96 INFO  ==> Configuring cache count
keycloak 09:07:22.02 INFO  ==> Configuring log level
keycloak 09:07:22.03 INFO  ==> Configuring proxy
keycloak 09:07:22.04 INFO  ==> ** keycloak setup finished! **
keycloak 09:07:22.05 INFO  ==> ** Starting keycloak **
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=demo-core-itg-keycloak-headless.demo-core-itg.svc.cluster.local
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2024-02-07 09:07:38,047 WARN  [org.keycloak.services] (build-18) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
2024-02-07 09:07:38,732 WARN  [org.keycloak.services] (build-18) KC-SERVICES0047: oidc-rights-hash-mapper (myplace.keycloak.tokenmapper.RightsHashMapper) is implementing the internal SPI protocol-mapper. This SPI is internal and may change without notice
2024-02-07 09:07:41,124 WARN  [org.keycloak.services] (build-18) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2024-02-07 09:08:11,594 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 41355ms
Server configuration updated and persisted. Run the following command to review the configuration:
kc.sh show-config
Next time you run the server, just run:
kc.sh start --optimized -cf=/opt/bitnami/keycloak/conf/keycloak.conf --http-enabled=true
```

**Comment by epourail** [comment]
Hello @CeliaGMqrz,
Can you give me any feedback on the issue?
Dis you reproduce it ?

**Comment by epourail** [comment]
Can you give me a feedback ?

**Comment by CeliaGMqrz** [comment]
Hi @epourail

Sorry for my late response.

After some time, I was able to reproduce the env, however, sorry, it seems to work fine for me.

During my tests, I installed version 18.3.3 and then upgraded it to version 18.3.4 as per your instructions, including using the additional values. Although the upgrade process went smoothly without any errors, it's important to confirm if you've followed all the upgrade steps mentioned in the [documentation](https://github.com/bitnami/charts/tree/main/bitnami/keycloak#manage-secrets-and-passwords). 

After the upgrade, I was able to access the Keycloak admin page without any issues. Have you double-checked if all the names are resolved correctly? To ensure we don't miss details, could you please provide a detailed, step-by-step description of how you've installed the chart? This includes additional configurations. Understanding your exact process will help me assist you more effectively.

Thanks for your feedback!

**Comment by epourail** [comment]
Thx for the feedback.
I will perform some new tests.
