### ISSUE TITLE
[bitnami/jenkins] 12.x.x  release is a complete disaster

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#23977]
### Name and Version

bitnami/jenkins:12.10.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deployed multiple versions of the helm chart. 

Looks like there are too many breaking changes  causing this disaster. Have Opened these issues but still no success

https://github.com/bitnami/charts/issues/23965
https://github.com/bitnami/charts/issues/23964
https://github.com/bitnami/charts/issues/23951
https://github.com/bitnami/charts/issues/23945

In addition to these modified versions of values.yaml, deploying the chart with standard values.yaml doesn't even work. 

the behaviour is too volatile and unexpected and it looks to me the release has been delivered in a hurry without verifying the solutions basic tests ran?

However, I had to deploy the production release from Official Jenkins/Jenkins helm repo, which is working fine and looks stable.

### Are you using any custom parameters or values?

standard

### What is the expected behavior?

It doesnot work

### What do you see instead?

It doesnot work

### Additional information

It doesnot work

**Comment by javsalgar** [comment]
Hi!

We're sorry for any inconvenience this is causing. We would like to clarify that all PRs go through  a verification process where we deploy and perform basic testing. Maybe it would make sense to extend this basic testing so issues like the ones you reported are detected (sometimes issues only appear in certain platform due to, for example, certain storage providers). We will work on reproducing these issues and try to understand where the root of the problem is.

**Comment by busyboy77** [comment]
@javsalgar --- Thank you for getting back

You know the problem is that Bitnami is considered as trusted source of all those packages around here in this very Repo and when someone like comes to deploy a production grade deployment from open-source community , our first choice is Bitnami, not because you add something in the original source code to run it faster and stable, but because of the customization offerings that with a little bit knowledge cane achieve and Obviously there are many packages which outperform from their Original counterpart. 

Now coming to my opened Issues, I am deploying Jenkins
I deployed Jenkins:12.9.x , it worked well but the VM corrupted, 
in the meanwhile there was jenkins:12.10.0 which never runs
neither does it creates plugins
nor it does any kubernetes configuration setup ( Cloud + agent )
it didn't ask me to copy past password from the AdminPassword file from inside the Pod and took me straight to the User/Password UI, however, this was not the case previously. Even though you add user via Values.yaml , it was still asking for the password to be copied from inside the pod.

the more irritating probelm, the latest Jenkins:12.10.0 doesn not bother to install Plugins at the time of deployment ( I could see all the plugins are downloaded and installed during chart deployments, ) but when we open the interface it simply doesn't should any of those.

and 

the edge of running on kubernetes -- the kubernetes configuration is something that I dont want to mess up with. In latest release I never does create it, just because no plugins are deployed mentioned in the helm chart values file.

regards,

**Comment by busyboy77** [comment]
and I 'm running the standard deployment on the Ubuntu 22.04,occupiying the whole system for Jenkins only.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay.
  I was able to reproduce the issue.
  It seems located in the chart, I am trying to solve it.

**Comment by rafariossaa** [comment]
I have found that the plugins versions set are causing the first start to abort with this error:
```
kubernetes (3852.v41ea_166a_ed1b_): SECURITY-3075-kubernetes Improper masking of credentials https://www.jenkins.io/security/advisory/2023-04-12/#SECURITY-3075
io.jenkins.tools.pluginmanager.impl.AggregatePluginPrerequisitesNotMetException: Multiple plugin prerequisites not met:
Plugin kubernetes:3852.v41ea_166a_ed1b_ (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin workflow-aggregator:590.v6a_d052e5a_a_b_5 (via pipeline-input-step:491.vb_07d21da_1a_fb_->credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin workflow-aggregator:590.v6a_d052e5a_a_b_5 (via pipeline-model-definition:2.2184.v0b_358b_953e69->git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin git:4.13.0 (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin git:4.13.0 (via git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:240)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:189)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:60)
        Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin kubernetes:3852.v41ea_166a_ed1b_ (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249
                at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1128)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:698)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
                ... 2 more
        Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin workflow-aggregator:590.v6a_d052e5a_a_b_5 (via pipeline-input-step:491.vb_07d21da_1a_fb_->credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249
                at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1128)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:698)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
                ... 2 more
        Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin workflow-aggregator:590.v6a_d052e5a_a_b_5 (via pipeline-model-definition:2.2184.v0b_358b_953e69->git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249
                at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1128)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:698)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
                ... 2 more
        Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin git:4.13.0 (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249
                at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1128)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:698)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
                ... 2 more
        Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin git:4.13.0 (via git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249
                at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1128)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:698)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
                ... 2 more
Multiple plugin prerequisites not met:
Plugin kubernetes:3852.v41ea_166a_ed1b_ (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin workflow-aggregator:590.v6a_d052e5a_a_b_5 (via pipeline-input-step:491.vb_07d21da_1a_fb_->credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin workflow-aggregator:590.v6a_d052e5a_a_b_5 (via pipeline-model-definition:2.2184.v0b_358b_953e69->git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin git:4.13.0 (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249,
Plugin git:4.13.0 (via git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1569.vb_72405b_80249
```
If you enable the debug mode (`image.debug=true') you could see the errors.

I set the plugin block as:
```yaml
plugins:
  - kubernetes:3852.v41ea_166a_ed1b_
  - workflow-aggregator:590.v6a_d052e5a_a_b_5
  - git:4.13.0
  - configuration-as-code:1775.v810dc950b_514
```

and it worked for me, could you give it a try ?
