### ISSUE TITLE
Magento > Failed to open stream: No such file or directory in /bitnami/magento/vendor/composer/autoload_real.php on line 41

### ISSUE THREAD

**Issue by hamadodene** [bitnami/charts#24301]
### Name and Version

bitnami/magento 25.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I installed Magento using the Helm chart through ArgoCD and GitLab. Here is the configuration.

```
apiVersion: v2
name: magento
version: "0.1.0"
dependencies:
  - name: magento
    version: "25.5.0"
    repository: https://charts.bitnami.com/bitnami
```

```
magento:
  global:
    storageClass: nfs-client-magento-dev
  image:
    debug: true
  magentoDeployStaticContent: true  
  fullnameOverride: magento
  namespaces: magento-dev
  magentoHost: magento.local
  magentoUsername: admin
  existingSecret: magento
  magentoEmail: example@example.com
  magentoFirstName: admin
  magentoLastName: admin
  magentoAdminUri: admin
  externalDatabase:
    host: xxxxxxx
    port: 3306
    user: magento
    database: magento
    existingSecret: magento
  elasticsearch:
    enabled: false
  externalElasticsearch:
    host: elasticsearch-magento-dev
    port: 9200
  persistence:
    storageClass: nfs-client-magento-dev
  mariadb:
    enabled: false
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true

  service:
    type: ClusterIP  

  ingress:
    enabled: true
    hostname: xxxxxxxx
    tls: false
    ingressClassName: nginx

```

### Are you using any custom parameters or values?

```
magento:
  global:
    storageClass: nfs-client-magento-dev
  image:
    debug: true
  magentoDeployStaticContent: true  
  fullnameOverride: magento
  namespaces: magento-dev
  magentoHost: magento.local
  magentoUsername: admin
  existingSecret: magento
  magentoEmail: example@example.com
  magentoFirstName: admin
  magentoLastName: admin
  magentoAdminUri: admin
  externalDatabase:
    host: xxxxxxx
    port: 3306
    user: magento
    database: magento
    existingSecret: magento
  elasticsearch:
    enabled: false
  externalElasticsearch:
    host: elasticsearch-magento-dev
    port: 9200
  persistence:
    storageClass: nfs-client-magento-dev
  mariadb:
    enabled: false
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true

  service:
    type: ClusterIP  

  ingress:
    enabled: true
    hostname: xxxxxxxx
    tls: false
    ingressClassName: nginx

```

### What do you see instead?

```
magento 15:32:50.71 INFO  ==> Trying to connect to the database server
magento 15:32:50.71 DEBUG ==> Getting configuration path '/db/connection/default/dbname' from Magento configuration
magento 15:32:50.75 DEBUG ==> Getting configuration path '/db/connection/default/username' from Magento configuration
magento 15:32:50.78 DEBUG ==> Getting configuration path '/db/connection/default/password' from Magento configuration
magento 15:32:50.81 DEBUG ==> Getting configuration path '/db/connection/default/host' from Magento configuration
magento 15:32:50.83 DEBUG ==> Executing SQL command:
SELECT 1
1
magento 15:32:50.86 INFO  ==> Trying to connect to Elasticsearch
magento 15:32:50.86 INFO  ==> Upgrading database schema
[08-Mar-2024 15:32:50 UTC] PHP Warning:  require(/bitnami/magento/vendor/composer/../symfony/polyfill-php80/bootstrap.php): Failed to open stream: No such file or directory in /bitnami/magento/vendor/composer/autoload_real.php on line 41
[08-Mar-2024 15:32:50 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/bitnami/magento/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bitnami/php/lib/php') in /bitnami/magento/vendor/composer/autoload_real.php:41
Stack trace:
#0 /bitnami/magento/vendor/composer/autoload_real.php(45): {closure}()
#1 /bitnami/magento/vendor/autoload.php(25): ComposerAutoloaderInit05b95001e03b74fcfe72321278560811::getLoader()
#2 /bitnami/magento/app/autoload.php(51): include('...')
#3 /bitnami/magento/app/bootstrap.php(44): require_once('...')
#4 /bitnami/magento/bin/magento(14): require('...')
#5 {main}
  thrown in /bitnami/magento/vendor/composer/autoload_real.php on line 41
```

**Comment by hamadodene** [comment]
i fix this problem increasing livenessProbe.initialDelaySeconds to  3600 seconds.
