### ISSUE TITLE
[bitnami/mlflow] GCS Support for MLFlow

### ISSUE THREAD

**Issue by SachinMaharana** [bitnami/charts#24548]
### Name and Version

bitnami/mlflow:0.3.4

### What is the problem this feature will solve?

While configuring S3 for MLFlow artifacts store, i noticed only minio and AWS S3 is supported.
https://github.com/bitnami/charts/tree/main/bitnami/mlflow#external-s3-parameters

Please correct me if i am wrong, is it possible to use GCS as an artifact store with this helm chart?

Since we primarily use GCP, it would be quite helpful if mlflow supports other cloud storage, including GCS and Azure

### What is the feature you are proposing to solve the problem?

Support more cloud storage other than AWS and minio, including GCS and Azure.

### What alternatives have you considered?

Minio is the only other option we have considered. If we get the confirmation that GCS is not supported, we might look into as well for such an integration.

**Comment by javsalgar** [comment]
Hi,

Potentially, it should be possible to use the chart with GCS by using the `args` section setting the necessary parameters for using GCS.

**Comment by SachinMaharana** [comment]
Hi, thanks for the input.  I tried the following, and i get the error.

```
tracking: 
  command: [ "/bin/sh", "-c" ]
  args:
    - >
      mlflow server
      --host=0.0.0.0 --port=5000 --app-name=basic-auth --serve-artifacts
      --artifacts-destination=gs://BUCKET_NAME
      --backend-store-uri=postgresql://bn_mlflow:$(MLFLOW_DATABASE_PASSWORD)@mlfow-platform-postgresql:5432/bitnami_mlflow;
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: SERVICE_ACCOUNT
```


```
024/03/20 13:36:08 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 538, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 951, in _list_artifacts
    artifact_entities = _list_artifacts_for_proxied_run_artifact_root(
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 981, in _list_artifacts_for_proxied_run_artifact_root
    artifact_destination_repo = _get_artifact_repo_mlflow_artifacts()
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 175, in _get_artifact_repo_mlflow_artifacts
    _artifact_repo = get_artifact_repository(os.environ[ARTIFACTS_DESTINATION_ENV_VAR])
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 117, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 74, in get_artifact_repository
    return repository(artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/gcs_artifact_repo.py", line 40, in __init__
    from google.auth.exceptions import DefaultCredentialsError
ModuleNotFoundError: No module named 'google.auth'
2024/03/20 13:36:50 ERROR mlflow.server: Exception on /api/2.0/mlflow-artifacts/artifacts/2/c191a38673dd47d1b57fe84adc75c3e7/artifacts/dataset_info.yaml [PUT]
```


looking at the doc, https://mlflow.org/docs/latest/tracking/artifacts-stores.html#google-cloud-storage
it seems we have to install google-auth into a custom image maybe. 
Do you think that might be the case?

**Comment by javsalgar** [comment]
Just a note updating this ticket. The latest versions of Bitnami MLflow  container contain the proper google cloud python modules, you only need to play with the args section just like this comment

https://github.com/bitnami/charts/issues/24548#issuecomment-2009638033
