### ISSUE TITLE
[bitnami/mlflow] connection to server at "mlflow-postgresql" (10.43.73.67), port 5432 failed: FATAL:  password authentication failed for user "bn_mlflow"

### ISSUE THREAD

**Issue by david-nano** [bitnami/charts#24718]
### Name and Version

bitnami/mlflow 0.11.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install brand new chart (the installation working as expected)
2. Uninstall it and install it again in less then 5 minutes
you will get the error:
```
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3303, in raw_connection
    return self.pool.connect()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/python/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "mlflow-postgresql" (10.43.73.67), port 5432 failed: FATAL:  password authentication failed for user "bn_mlflow"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/bitnami/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/__main__.py", line 4, in <module>
    commands()
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/db/cli.py", line 17, in upgrade
    utils.migrate(engine, revision)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/db/utils.py", line 26, in migrate
    with engine.begin() as conn:
  File "/opt/bitnami/python/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3243, in begin
    with self.connect() as conn:
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3279, in connect
    return self._connection_cls(self)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3303, in raw_connection
    return self.pool.connect()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/python/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/python/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "mlflow-postgresql" (10.43.73.67), port 5432 failed: FATAL:  password authentication failed for user "bn_mlflow"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

* Also by trying to install this chart by ArgoCD give the same error.
* Also fresh install - and try to change image tag.
(or basically every change on current installation can cause that)

### Are you using any custom parameters or values?
```
minio:
  enabled: false
```
### What is the expected behavior?

Not getting error :)

### What do you see instead?

Container `upgrade-db-auth` under mlflow-tracking is back-off restart by error I've attached before.

### Additional information

Here is logs from postgresql:
```
[38;5;6mpostgresql [38;5;5m13:40:23.33 [0m[38;5;2mINFO [0m ==> 
[38;5;6mpostgresql [38;5;5m13:40:23.34 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami postgresql container[0m
[38;5;6mpostgresql [38;5;5m13:40:23.34 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mpostgresql [38;5;5m13:40:23.34 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mpostgresql [38;5;5m13:40:23.34 [0m[38;5;2mINFO [0m ==> 
[38;5;6mpostgresql [38;5;5m13:40:23.36 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL setup **
[38;5;6mpostgresql [38;5;5m13:40:23.39 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_* env vars..
[38;5;6mpostgresql [38;5;5m13:40:23.40 [0m[38;5;2mINFO [0m ==> Loading custom pre-init scripts...
[38;5;6mpostgresql [38;5;5m13:40:23.40 [0m[38;5;2mINFO [0m ==> Initializing PostgreSQL database...
[38;5;6mpostgresql [38;5;5m13:40:23.43 [0m[38;5;2mINFO [0m ==> pg_hba.conf file not detected. Generating it...
[38;5;6mpostgresql [38;5;5m13:40:23.43 [0m[38;5;2mINFO [0m ==> Generating local authentication configuration
[38;5;6mpostgresql [38;5;5m13:40:26.97 [0m[38;5;2mINFO [0m ==> Starting PostgreSQL in background...
[38;5;6mpostgresql [38;5;5m13:40:27.91 [0m[38;5;2mINFO [0m ==> Changing password of postgres
[38;5;6mpostgresql [38;5;5m13:40:27.94 [0m[38;5;2mINFO [0m ==> Creating user bn_mlflow
[38;5;6mpostgresql [38;5;5m13:40:27.96 [0m[38;5;2mINFO [0m ==> Granting access to "bn_mlflow" to the database "bitnami_mlflow"
[38;5;6mpostgresql [38;5;5m13:40:27.99 [0m[38;5;2mINFO [0m ==> Setting ownership for the 'public' schema database "bitnami_mlflow" to "bn_mlflow"
[38;5;6mpostgresql [38;5;5m13:40:28.09 [0m[38;5;2mINFO [0m ==> Configuring replication parameters
[38;5;6mpostgresql [38;5;5m13:40:28.13 [0m[38;5;2mINFO [0m ==> Configuring synchronous_replication
[38;5;6mpostgresql [38;5;5m13:40:28.13 [0m[38;5;2mINFO [0m ==> Configuring fsync
[38;5;6mpostgresql [38;5;5m13:40:28.18 [0m[38;5;2mINFO [0m ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
[38;5;6mpostgresql [38;5;5m13:40:28.49 [0m[38;5;2mINFO [0m ==> Loading custom scripts...
[38;5;6mpostgresql [38;5;5m13:40:28.49 [0m[38;5;2mINFO [0m ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
[38;5;6mpostgresql [38;5;5m13:40:28.50 [0m[38;5;2mINFO [0m ==> Starting PostgreSQL in background...
CREATE DATABASE
GRANT
ALTER DATABASE
[38;5;6mpostgresql [38;5;5m13:40:29.29 [0m[38;5;2mINFO [0m ==> Enabling remote connections
[38;5;6mpostgresql [38;5;5m13:40:29.30 [0m[38;5;2mINFO [0m ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
[38;5;6mpostgresql [38;5;5m13:40:29.61 [0m[38;5;2mINFO [0m ==> ** PostgreSQL setup finished! **

[38;5;6mpostgresql [38;5;5m13:40:29.63 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL **
2024-03-27 13:40:29.654 GMT [1] LOG:  pgaudit extension initialized
2024-03-27 13:40:29.660 GMT [1] LOG:  starting PostgreSQL 16.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-03-27 13:40:29.660 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-03-27 13:40:29.660 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2024-03-27 13:40:29.661 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-03-27 13:40:29.680 GMT [182] LOG:  database system was shut down at 2024-03-27 13:40:29 GMT
2024-03-27 13:40:29.857 GMT [1] LOG:  database system is ready to accept connections
2024-03-27 13:45:29.707 GMT [180] LOG:  checkpoint starting: time
2024-03-27 13:45:56.772 GMT [180] LOG:  checkpoint complete: wrote 272 buffers (1.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=27.001 s, sync=0.040 s, total=27.065 s; sync files=198, longest=0.001 s, average=0.001 s; distance=1259 kB, estimate=1259 kB; lsn=0/1E716C8, redo lsn=0/1E71690
2024-03-27 14:05:30.187 GMT [180] LOG:  checkpoint starting: time
2024-03-27 14:05:31.614 GMT [180] LOG:  checkpoint complete: wrote 15 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.407 s, sync=0.002 s, total=1.428 s; sync files=11, longest=0.002 s, average=0.001 s; distance=2 kB, estimate=1133 kB; lsn=0/1E72248, redo lsn=0/1E72210
2024-03-27 14:20:30.827 GMT [180] LOG:  checkpoint starting: time
2024-03-27 14:20:36.069 GMT [180] LOG:  checkpoint complete: wrote 55 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.221 s, sync=0.002 s, total=5.242 s; sync files=39, longest=0.002 s, average=0.001 s; distance=145 kB, estimate=1035 kB; lsn=0/1E9E168, redo lsn=0/1E968D8
2024-03-27 14:25:03.211 GMT [4133] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:25:03.211 GMT [4133] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:25:05.398 GMT [4134] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:25:05.398 GMT [4134] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:25:23.948 GMT [4165] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:25:23.948 GMT [4165] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:25:30.171 GMT [180] LOG:  checkpoint starting: time
2024-03-27 14:25:34.304 GMT [180] LOG:  checkpoint complete: wrote 42 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.112 s, sync=0.002 s, total=4.133 s; sync files=11, longest=0.002 s, average=0.001 s; distance=350 kB, estimate=966 kB; lsn=0/1EFC1B8, redo lsn=0/1EEE470
2024-03-27 14:25:49.965 GMT [4195] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:25:49.965 GMT [4195] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:26:16.916 GMT [4241] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:26:16.916 GMT [4241] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:26:18.912 GMT [4242] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:26:18.912 GMT [4242] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:26:36.683 GMT [4273] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:26:36.683 GMT [4273] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:27:05.656 GMT [4318] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:27:05.656 GMT [4318] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:27:58.297 GMT [4392] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:27:58.297 GMT [4392] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:29:31.665 GMT [4525] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:29:31.665 GMT [4525] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
2024-03-27 14:30:30.319 GMT [180] LOG:  checkpoint starting: time
2024-03-27 14:30:33.548 GMT [180] LOG:  checkpoint complete: wrote 33 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.211 s, sync=0.001 s, total=3.230 s; sync files=9, longest=0.001 s, average=0.001 s; distance=172 kB, estimate=887 kB; lsn=0/1F19638, redo lsn=0/1F19600
2024-03-27 14:32:23.667 GMT [4790] FATAL:  password authentication failed for user "bn_mlflow"
2024-03-27 14:32:23.667 GMT [4790] DETAIL:  Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"
```

**Comment by javsalgar** [comment]
Hi,

This normally happens because helm uninstall does not remove the PVCs of the postgresql statefulset (that's how helm works by design). Try uninstalling and removing the postgresql PVCs and it should work without issues.

**Comment by david-nano** [comment]
> Hi,
> 
> This normally happens because helm uninstall does not remove the PVCs of the postgresql statefulset (that's how helm works by design). Try uninstalling and removing the postgresql PVCs and it should work without issues.

I did, and got same error.
Also, what is the solution in case of `upgrade`?

**Comment by aoterolorenzo** [comment]
Hey @david-nano,

Could you ensure you are removing PV and PVC traces just in case?

`kubectl delete pvc XXXX`
`kubectl delete pv XXXX`
