### ISSUE TITLE
[bitnami/keycloak] Fail to get theme in version 23+ since chart 20.0.0 is going readonly filesystem

### ISSUE THREAD

**Issue by AlexisDucastel** [bitnami/charts#24938]
### Name and Version

bitnami/keycloak 20.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In several releases of keycloak deployed via Helm with chart "20.0.0", different clusters, different config, we have the template that is not loading, with this error in logs :

```
2024-04-05 08:43:58,179 WARN  [org.keycloak.services] (executor-thread-1) KC-SERVICES0075: Failed to get theme request: java.lang.RuntimeException: Temporary directory /opt/bitnami/keycloak/bin/../data/tmp does not exist and it was not possible to create it.
2024-04-05T10:43:58.180068787+02:00 	at org.keycloak.quarkus.runtime.integration.QuarkusPlatform.getTmpDirectory(QuarkusPlatform.java:152)
2024-04-05T10:43:58.180072936+02:00 	at org.keycloak.encoding.GzipResourceEncodingProviderFactory.initCacheDir(GzipResourceEncodingProviderFactory.java:70)
2024-04-05T10:43:58.180075966+02:00 	at org.keycloak.encoding.GzipResourceEncodingProviderFactory.create(GzipResourceEncodingProviderFactory.java:29)
```

### Are you using any custom parameters or values?

Values example : 
```yaml
        auth:
          <REDACTED>

        postgresql:
          auth:
            <REDACTED>

        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
          certManager: true
          enabled: true
          hostname: <REDACTED>
          ingressClassName: nginx
          pathType: Prefix
          tls: true

        production: true
        proxy: edge
        service:
          type: ClusterIP

        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
```

### What is the expected behavior?

The theme should load properly

### What do you see instead?

The theme is not loaded, leading to 500 HTTP error and unfunctional administration console (hopefully, login interface still works without theme, even if graphically-broken)

Admin :
![image](https://github.com/bitnami/charts/assets/1911945/be6c4b9a-4cd2-470e-9ea7-693006b88efe)

Login:
![image](https://github.com/bitnami/charts/assets/1911945/4dd25911-05a9-4144-a32e-d235891c720a)

Account console:
![image](https://github.com/bitnami/charts/assets/1911945/fb25d70d-8f7d-48f6-82d2-b5d079c86549)

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting, I created this PR which I believe should fixe the issue https://github.com/bitnami/charts/pull/24939
