### ISSUE TITLE
bitnami/jenkins helm chart issue

### ISSUE THREAD

**Issue by jvaidyan** [bitnami/charts#2527]
**Which chart**:
The name (and version) of the affected chart
https://github.com/bitnami/charts/tree/master/bitnami/jenkins

Image : bitnami/jenkins:2.222.3-debian-10-r8
**Describe the bug**
The pod log says:
```
2020-05-05 23:58:36.712+0000 [id=26]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed GrapeHack.hack
java.lang.IllegalArgumentException: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
        at org.apache.ivy.util.Checks.checkAbsolute(Checks.java:57)
        at org.apache.ivy.plugins.resolver.FileSystemResolver.addConfiguredIvy(FileSystemResolver.java:303)
Caused: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ivy.util.Configurator.endCreateChild(Configurator.java:708)
Caused: java.lang.IllegalArgumentException: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
        at org.apache.ivy.util.Configurator.endCreateChild(Configurator.java:712)
        at org.apache.ivy.core.settings.XmlSettingsParser.endElement(XmlSettingsParser.java:596)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
        at org.apache.ivy.core.settings.XmlSettingsParser.doParse(XmlSettingsParser.java:160)
Caused: java.text.ParseException: failed to load settings from jar:file:/bitnami/jenkins/jenkins_home/war/WEB-INF/lib/groovy-all-2.4.12.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
        at org.apache.ivy.core.settings.XmlSettingsParser.doParse(XmlSettingsParser.java:165)
        at org.apache.ivy.core.settings.XmlSettingsParser.parse(XmlSettingsParser.java:150)
        at org.apache.ivy.core.settings.IvySettings.load(IvySettings.java:417)
        at org.apache.ivy.core.settings.IvySettings$load.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at groovy.grape.GrapeIvy.<init>(GrapeIvy.groovy:102)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.jenkinsci.plugins.workflow.cps.global.GrapeHack.hack(GrapeHack.java:60)
Caused: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-05-05 23:58:37.195+0000 [id=26]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2020-05-05 23:58:37.244+0000 [id=26]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2020-05-05 23:58:37.244+0000 [id=26]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
2020-05-05 23:58:37.245+0000 [id=26]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2020-05-05 23:58:37.273+0000 [id=26]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2020-05-05 23:58:37.459+0000 [id=40]    INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Download metadata


2020-05-05 23:58:57.625+0000 [id=40]    INFO    hudson.util.Retrier#start: The attempt #1 to do the action check updates server failed with an allowed exception:
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java
```
**To Reproduce**
https://github.com/bitnami/charts/tree/master/bitnami/jenkins

**Expected behavior**

**Version of Helm and Kubernetes**: helm 3.1, PKS

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by marcosbc** [comment]
Hi @jvaidyan, we were able to reproduce the issue. We'll investigate and get back to you once we have more information.

**Comment by marcosbc** [comment]
Hi @jvaidyan, we found the source of the issue. It is happening because the Java `user.home` property is not set correctly.

If you need fix it temporarily on your side you could enable it like this:

```
--set javaOpts=-Duser.home=/
```

We are working on releasing a new version of the container and chart and expecting to have it released later today.

**Comment by jvaidyan** [comment]
Thank you for the quick turnaround @marcosbc.  For the Socket timeout exception, where is it trying to reach for the updates. Is there a way to bypass that ? Our server is apparently blocking traffic to external .
2020-05-07 13:31:30.452+0000 [id=40]    SEVERE  hudson.PluginManager#doCheckUpdatesServer: Error checking update sites for 1 attempt(s). Last exception was: SocketTimeoutException: connect timed out

**Comment by marcosbc** [comment]
That error looks like a Jenkins-specific issue. I've searched and it seems like it could be this: https://github.com/helm/charts/issues/13559.

Could it be possible you're running behind a proxy? If so, you may consider setting javaOpts like the user put in the post.

**Comment by marcosbc** [comment]
By the way, we already released a new Jenkins container with the fix. You can use the chart version `5.0.10` and container version `2.222.3-debian-10-r11`, both include the fix.

**Comment by jvaidyan** [comment]
Thank you for the update!
