### ISSUE TITLE
[bitnami/kafka] bitnami kafka getting crashloopbackoff 

### ISSUE THREAD

**Issue by Akashs12345** [bitnami/charts#25291]
### Name and Version

bitnami/kafka 3.3.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

in our env, we are using bitnami Kafka 3.3.1 version and we are installing it on Kubernetes using helm charts 
we have Kubernetes setup 3 master and 2 worker nodes in which the 3rd master is also working as a worker.
we have created the external pv and deployed the services and at some points offload Kafka broker pods are getting into a crash loopback off state at all 3 brokers when we rename the log path of the pv and restart the Kafka broker pod it will work for some days and after some five to 6 days the pods will fail 

### Are you using any custom parameters or values?

in our production setup we are useing replication factor : 3
numof.parttions: 2
offset.replication.factor:3

with 3 zookeeper settings

### What do you see instead?
```
[2024-04-12 10:12:06,871] ERROR [KafkaServer id=0] Fatal error during KafkaServer shutdown. (kafka.server.KafkaServer)                                               │
│ java.lang.IllegalStateException: Kafka server is still starting up, cannot shut down!                                                                                │
│     at kafka.server.KafkaServer.shutdown(KafkaServer.scala:708)                                                                                                      │
│     at kafka.Kafka$.$anonfun$main$3(Kafka.scala:100)                                                                                                                 │
│     at kafka.utils.Exit$.$anonfun$addShutdownHook$1(Exit.scala:38)                                                                                                   │
│     at java.base/java.lang.Thread.run(Thread.java:829)                                                                                                               │
│ [2024-04-12 10:12:06,976] ERROR Halting Kafka. (kafka.Kafka$)      
```

**Comment by Akashs12345** [comment]
you cant reproduce the issue as it live issue when i am changing the log path and restarting pod am pod is running fine
