### ISSUE TITLE
Kafka deployment unstable with java.net.UnknownHostException error

### ISSUE THREAD

**Issue by clementrey-dev** [bitnami/charts#25456]
### Name and Version

bitnamicharts/kafka 28.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy a EKS cluster 
2. Kubernetes version is `1.29`
3. Deploy charts with helm

### Are you using any custom parameters or values?

```yaml
USER-SUPPLIED VALUES:
controller:
  nodeSelector:
    team/node: test
  tolerations:
  - effect: NoSchedule
    key: workload
    operator: Equal
    value: test
listeners:
  client:
    protocol: PLAINTEXT
provisioning:
  enabled: true
  nodeSelector:
    team/node: test
  tolerations:
  - effect: NoSchedule
    key: workload
    operator: Equal
    value: test
  topics:
  - name: topic-1
    partitions: 5
    replicationFactor: 1
  - name: topic-2
    partitions: 1
    replicationFactor: 1
  - name: topic-3
    partitions: 1
    replicationFactor: 1

```

### What is the expected behavior?

I am expecting a stable deployment of Kafka

### What do you see instead?

Very often the kafka pods crash with the following error:

```
java.net.UnknownHostException: kafka-cluster-controller-0.kafka-cluster-controller-headless.kafka.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:124)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.resolveAddresses(ClusterConnectionStates.java:536)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:511)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:466)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1050)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:310)
        at org.apache.kafka.server.util.InterBrokerSendThread.sendRequests(InterBrokerSendThread.java:145)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:108)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:136)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:131)

```

also sometimes the kafka cluster get shutdown, I am not sure why:
```
taManager)
[2024-04-30 08:05:59,673] INFO [BrokerLifecycleManager id=0] The broker is in PENDING_CONTROLLED_SHUTDOWN state, still waiting for the active controller. (kafka.server.BrokerLifecycleManager)
[2024-04-30 08:06:01,674] INFO [QuorumController id=0] The request from broker 0 to shut down has been granted since the lowest active offset 124682 is now greater than the broker's controlled shutdown offset 124682. (org.apache.kafka.controller.BrokerHeartbeatManager)
[2024-04-30 08:06:01,674] INFO [QuorumController id=0] Replayed BrokerRegistrationChangeRecord modifying the registration for broker 0: BrokerRegistrationChangeRecord(brokerId=0, brokerEpoch=121979, fenced=1, inControlledShutdown=0, logDirs=[]) (org.apache.kafka.controller.ClusterControlManager)
[2024-04-30 08:06:01,703] INFO [BrokerLifecycleManager id=0] The controller has asked us to exit controlled shutdown. (kafka.server.BrokerLifecycleManager)
[2024-04-30 08:06:01,703] INFO [BrokerLifecycleManager id=0] beginShutdown: shutting down event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:01,703] INFO [BrokerLifecycleManager id=0] Transitioning from PENDING_CONTROLLED_SHUTDOWN to SHUTTING_DOWN. (kafka.server.BrokerLifecycleManager)
[2024-04-30 08:06:01,703] INFO [broker-0-to-controller-heartbeat-channel-manager]: Shutting down (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,704] INFO [broker-0-to-controller-heartbeat-channel-manager]: Stopped (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,704] INFO [broker-0-to-controller-heartbeat-channel-manager]: Shutdown completed (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,704] INFO [SocketServer listenerType=BROKER, nodeId=0] Stopping socket server request processors (kafka.network.SocketServer)
[2024-04-30 08:06:01,708] INFO Node to controller channel manager for heartbeat shutdown (kafka.server.NodeToControllerChannelManagerImpl)
[2024-04-30 08:06:01,715] INFO [SocketServer listenerType=BROKER, nodeId=0] Stopped socket server request processors (kafka.network.SocketServer)
[2024-04-30 08:06:01,716] INFO [data-plane Kafka Request Handler on Broker 0], shutting down (kafka.server.KafkaRequestHandlerPool)
[2024-04-30 08:06:01,717] INFO [data-plane Kafka Request Handler on Broker 0], shut down completely (kafka.server.KafkaRequestHandlerPool)
[2024-04-30 08:06:01,717] INFO [ExpirationReaper-0-AlterAcls]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,718] INFO [ExpirationReaper-0-AlterAcls]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,718] INFO [ExpirationReaper-0-AlterAcls]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,718] INFO [KafkaApi-0] Shutdown complete. (kafka.server.KafkaApis)
[2024-04-30 08:06:01,721] INFO [TransactionCoordinator id=0] Shutting down. (kafka.coordinator.transaction.TransactionCoordinator)
[2024-04-30 08:06:01,721] INFO [Transaction State Manager 0]: Shutdown complete (kafka.coordinator.transaction.TransactionStateManager)
[2024-04-30 08:06:01,721] INFO [TxnMarkerSenderThread-0]: Shutting down (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2024-04-30 08:06:01,721] INFO [TxnMarkerSenderThread-0]: Stopped (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2024-04-30 08:06:01,721] INFO [TxnMarkerSenderThread-0]: Shutdown completed (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2024-04-30 08:06:01,723] INFO [TransactionCoordinator id=0] Shutdown complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2024-04-30 08:06:01,724] INFO [GroupCoordinator 0]: Shutting down. (kafka.coordinator.group.GroupCoordinator)
[2024-04-30 08:06:01,724] INFO [ExpirationReaper-0-Heartbeat]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,724] INFO [ExpirationReaper-0-Heartbeat]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,725] INFO [ExpirationReaper-0-Heartbeat]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,725] INFO [ExpirationReaper-0-Rebalance]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,725] INFO [ExpirationReaper-0-Rebalance]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,725] INFO [ExpirationReaper-0-Rebalance]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,725] INFO [GroupCoordinator 0]: Shutdown complete. (kafka.coordinator.group.GroupCoordinator)
[2024-04-30 08:06:01,726] INFO [AssignmentsManager id=0]KafkaEventQueue#close: shutting down event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:01,726] INFO [broker-0-to-controller-directory-assignments-channel-manager]: Shutting down (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,726] INFO [broker-0-to-controller-directory-assignments-channel-manager]: Stopped (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,726] INFO [broker-0-to-controller-directory-assignments-channel-manager]: Shutdown completed (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,727] INFO Node to controller channel manager for directory-assignments shutdown (kafka.server.NodeToControllerChannelManagerImpl)
[2024-04-30 08:06:01,727] INFO [AssignmentsManager id=0]closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:01,727] INFO [ReplicaManager broker=0] Shutting down (kafka.server.ReplicaManager)
[2024-04-30 08:06:01,728] INFO [LogDirFailureHandler]: Shutting down (kafka.server.ReplicaManager$LogDirFailureHandler)
[2024-04-30 08:06:01,728] INFO [LogDirFailureHandler]: Stopped (kafka.server.ReplicaManager$LogDirFailureHandler)
[2024-04-30 08:06:01,728] INFO [LogDirFailureHandler]: Shutdown completed (kafka.server.ReplicaManager$LogDirFailureHandler)
[2024-04-30 08:06:01,728] INFO [ReplicaFetcherManager on broker 0] shutting down (kafka.server.ReplicaFetcherManager)
[2024-04-30 08:06:01,729] INFO [ReplicaFetcherManager on broker 0] shutdown completed (kafka.server.ReplicaFetcherManager)
[2024-04-30 08:06:01,729] INFO [ReplicaAlterLogDirsManager on broker 0] shutting down (kafka.server.ReplicaAlterLogDirsManager)
[2024-04-30 08:06:01,729] INFO [ReplicaAlterLogDirsManager on broker 0] shutdown completed (kafka.server.ReplicaAlterLogDirsManager)
[2024-04-30 08:06:01,730] INFO [ExpirationReaper-0-Fetch]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,730] INFO [ExpirationReaper-0-Fetch]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,730] INFO [ExpirationReaper-0-Fetch]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,730] INFO [ExpirationReaper-0-RemoteFetch]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,730] INFO [ExpirationReaper-0-RemoteFetch]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,730] INFO [ExpirationReaper-0-RemoteFetch]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,730] INFO [ExpirationReaper-0-Produce]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-Produce]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-Produce]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-DeleteRecords]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-DeleteRecords]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-DeleteRecords]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-ElectLeader]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-ElectLeader]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,743] INFO [ExpirationReaper-0-ElectLeader]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:01,782] INFO [AddPartitionsToTxnSenderThread-0]: Shutting down (kafka.server.AddPartitionsToTxnManager)
[2024-04-30 08:06:01,783] INFO [AddPartitionsToTxnSenderThread-0]: Shutdown completed (kafka.server.AddPartitionsToTxnManager)
[2024-04-30 08:06:01,783] INFO [AddPartitionsToTxnSenderThread-0]: Stopped (kafka.server.AddPartitionsToTxnManager)
[2024-04-30 08:06:01,783] INFO [ReplicaManager broker=0] Shut down completely (kafka.server.ReplicaManager)
[2024-04-30 08:06:01,783] INFO [broker-0-to-controller-alter-partition-channel-manager]: Shutting down (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,783] INFO [broker-0-to-controller-alter-partition-channel-manager]: Stopped (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,783] INFO [broker-0-to-controller-alter-partition-channel-manager]: Shutdown completed (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,784] INFO Node to controller channel manager for alter-partition shutdown (kafka.server.NodeToControllerChannelManagerImpl)
[2024-04-30 08:06:01,784] INFO [broker-0-to-controller-forwarding-channel-manager]: Shutting down (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,784] INFO [broker-0-to-controller-forwarding-channel-manager]: Stopped (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,784] INFO [broker-0-to-controller-forwarding-channel-manager]: Shutdown completed (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:01,784] INFO Node to controller channel manager for forwarding shutdown (kafka.server.NodeToControllerChannelManagerImpl)
[2024-04-30 08:06:01,785] INFO Shutting down. (kafka.log.LogManager)
[2024-04-30 08:06:01,786] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2024-04-30 08:06:01,786] INFO [kafka-log-cleaner-thread-0]: Shutting down (kafka.log.LogCleaner$CleanerThread)
[2024-04-30 08:06:01,786] INFO [kafka-log-cleaner-thread-0]: Stopped (kafka.log.LogCleaner$CleanerThread)
[2024-04-30 08:06:01,787] INFO [kafka-log-cleaner-thread-0]: Shutdown completed (kafka.log.LogCleaner$CleanerThread)
[2024-04-30 08:06:01,828] INFO [ProducerStateManager partition=__consumer_offsets-3] Wrote producer snapshot at offset 2 with 0 producer ids in 3 ms. (org.apache.kafka.storage.internals.log.ProducerStateManager)
[2024-04-30 08:06:01,853] INFO [ProducerStateManager partition=__consumer_offsets-7] Wrote producer snapshot at offset 3 with 0 producer ids in 2 ms. (org.apache.kafka.storage.internals.log.ProducerStateManager)
[2024-04-30 08:06:01,898] INFO Shutdown complete. (kafka.log.LogManager)
[2024-04-30 08:06:01,899] INFO [broker-0-ThrottledChannelReaper-Fetch]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Fetch]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Fetch]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Produce]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Produce]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Produce]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Request]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Request]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-Request]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-ControllerMutation]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-ControllerMutation]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,900] INFO [broker-0-ThrottledChannelReaper-ControllerMutation]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:01,901] INFO [SocketServer listenerType=BROKER, nodeId=0] Shutting down socket server (kafka.network.SocketServer)
[2024-04-30 08:06:01,913] INFO [SocketServer listenerType=BROKER, nodeId=0] Shutdown completed (kafka.network.SocketServer)
[2024-04-30 08:06:01,914] INFO Broker and topic stats closed (kafka.server.BrokerTopicStats)
[2024-04-30 08:06:01,914] INFO [BrokerLifecycleManager id=0] closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:01,915] INFO [BrokerServer id=0] shut down completed (kafka.server.BrokerServer)
[2024-04-30 08:06:01,915] INFO [BrokerServer id=0] Transition from SHUTTING_DOWN to SHUTDOWN (kafka.server.BrokerServer)
[2024-04-30 08:06:01,915] INFO [ControllerServer id=0] shutting down (kafka.server.ControllerServer)
[2024-04-30 08:06:01,916] INFO [raft-expiration-reaper]: Shutting down (kafka.raft.TimingWheelExpirationService$ExpiredOperationReaper)
[2024-04-30 08:06:02,072] INFO [raft-expiration-reaper]: Stopped (kafka.raft.TimingWheelExpirationService$ExpiredOperationReaper)
[2024-04-30 08:06:02,072] INFO [raft-expiration-reaper]: Shutdown completed (kafka.raft.TimingWheelExpirationService$ExpiredOperationReaper)
[2024-04-30 08:06:02,073] INFO [kafka-0-raft-io-thread]: Shutting down (kafka.raft.KafkaRaftManager$RaftIoThread)
[2024-04-30 08:06:02,073] INFO [RaftManager id=0] Beginning graceful shutdown (org.apache.kafka.raft.KafkaRaftClient)
[2024-04-30 08:06:02,074] INFO [RaftManager id=0] Failed to handle fetch from 2 at 124689 due to NOT_LEADER_OR_FOLLOWER (org.apache.kafka.raft.KafkaRaftClient)
[2024-04-30 08:06:02,075] INFO [RaftManager id=0] Failed to handle fetch from 1 at 124689 due to NOT_LEADER_OR_FOLLOWER (org.apache.kafka.raft.KafkaRaftClient)
[2024-04-30 08:06:02,075] INFO [RaftManager id=0] Completed transition to ResignedState(localId=0, epoch=640, voters=[0, 1, 2], electionTimeoutMs=1561, unackedVoters=[1, 2], preferredSuccessors=[1, 2]) from Leader(localId=0, epoch=640, epochStartOffset=122595, highWatermark=Optional[LogOffsetMetadata(offset=124689, metadata=Optional[(segmentBaseOffset=0,relativePositionInSegment=9024299)])], voterStates={0=ReplicaState(nodeId=0, endOffset=Optional[LogOffsetMetadata(offset=124689, metadata=Optional[(segmentBaseOffset=0,relativePositionInSegment=9024299)])], lastFetchTimestamp=-1, lastCaughtUpTimestamp=-1, hasAcknowledgedLeader=true), 1=ReplicaState(nodeId=1, endOffset=Optional[LogOffsetMetadata(offset=124689, metadata=Optional[(segmentBaseOffset=0,relativePositionInSegment=9024299)])], lastFetchTimestamp=1714464361703, lastCaughtUpTimestamp=1714464361703, hasAcknowledgedLeader=true), 2=ReplicaState(nodeId=2, endOffset=Optional[LogOffsetMetadata(offset=124689, metadata=Optional[(segmentBaseOffset=0,relativePositionInSegment=9024299)])], lastFetchTimestamp=1714464361702, lastCaughtUpTimestamp=1714464361702, hasAcknowledgedLeader=true)}) (org.apache.kafka.raft.QuorumState)
[2024-04-30 08:06:02,105] INFO [RaftManager id=0] Completed transition to Unattached(epoch=641, voters=[0, 1, 2], electionTimeoutMs=1679) from ResignedState(localId=0, epoch=640, voters=[0, 1, 2], electionTimeoutMs=1561, unackedVoters=[], preferredSuccessors=[1, 2]) (org.apache.kafka.raft.QuorumState)
[2024-04-30 08:06:02,105] WARN [QuorumController id=0] Renouncing the leadership due to a metadata log event. We were the leader at epoch 640, but in the new epoch 641, the leader is (none). Reverting to last stable offset 124688. (org.apache.kafka.controller.QuorumController)
[2024-04-30 08:06:02,110] INFO [RaftManager id=0] Completed transition to Voted(epoch=641, votedId=1, voters=[0, 1, 2], electionTimeoutMs=1942) from Unattached(epoch=641, voters=[0, 1, 2], electionTimeoutMs=1679) (org.apache.kafka.raft.QuorumState)
[2024-04-30 08:06:02,110] INFO [RaftManager id=0] Vote request VoteRequestData(clusterId='gqk1OFiYycQF2qAOyphls9', topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=641, candidateId=1, lastOffsetEpoch=640, lastOffset=124689)])]) with epoch 641 is granted (org.apache.kafka.raft.KafkaRaftClient)
[2024-04-30 08:06:02,143] INFO [RaftManager id=0] Completed transition to FollowerState(fetchTimeoutMs=2000, epoch=641, leaderId=1, voters=[0, 1, 2], highWatermark=Optional.empty, fetchingSnapshot=Optional.empty) from Voted(epoch=641, votedId=1, voters=[0, 1, 2], electionTimeoutMs=1942) (org.apache.kafka.raft.QuorumState)
[2024-04-30 08:06:02,143] INFO [QuorumController id=0] In the new epoch 641, the leader is 1. (org.apache.kafka.controller.QuorumController)
[2024-04-30 08:06:02,144] INFO [RaftManager id=0] Graceful shutdown completed (org.apache.kafka.raft.KafkaRaftClient)
[2024-04-30 08:06:02,144] INFO [kafka-0-raft-io-thread]: Completed graceful shutdown of RaftClient (kafka.raft.KafkaRaftManager$RaftIoThread)
[2024-04-30 08:06:02,144] INFO [kafka-0-raft-io-thread]: Shutdown completed (kafka.raft.KafkaRaftManager$RaftIoThread)
[2024-04-30 08:06:02,144] INFO [kafka-0-raft-io-thread]: Stopped (kafka.raft.KafkaRaftManager$RaftIoThread)
[2024-04-30 08:06:02,160] INFO [kafka-0-raft-outbound-request-thread]: Shutting down (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2024-04-30 08:06:02,160] INFO [kafka-0-raft-outbound-request-thread]: Stopped (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2024-04-30 08:06:02,160] INFO [kafka-0-raft-outbound-request-thread]: Shutdown completed (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2024-04-30 08:06:02,163] INFO [ProducerStateManager partition=__cluster_metadata-0] Wrote producer snapshot at offset 124689 with 0 producer ids in 2 ms. (org.apache.kafka.storage.internals.log.ProducerStateManager)
[2024-04-30 08:06:02,165] INFO [ControllerRegistrationManager id=0 incarnation=3tjNwpoXTUCmbPuAH5xkjg] beginShutdown: shutting down event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,166] INFO [ControllerRegistrationManager id=0 incarnation=3tjNwpoXTUCmbPuAH5xkjg] shutting down. (kafka.server.ControllerRegistrationManager)
[2024-04-30 08:06:02,166] INFO [controller-0-to-controller-registration-channel-manager]: Shutting down (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:02,166] INFO [controller-0-to-controller-registration-channel-manager]: Stopped (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:02,166] INFO [controller-0-to-controller-registration-channel-manager]: Shutdown completed (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:02,167] INFO Node to controller channel manager for registration shutdown (kafka.server.NodeToControllerChannelManagerImpl)
[2024-04-30 08:06:02,168] INFO [ControllerRegistrationManager id=0 incarnation=3tjNwpoXTUCmbPuAH5xkjg] closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,168] INFO [controller-0-to-controller-registration-channel-manager]: Shutdown completed (kafka.server.NodeToControllerRequestThread)
[2024-04-30 08:06:02,168] WARN [NodeToControllerChannelManager id=0 name=registration] Attempting to close NetworkClient that has already been closed. (org.apache.kafka.clients.NetworkClient)
[2024-04-30 08:06:02,168] INFO Node to controller channel manager for registration shutdown (kafka.server.NodeToControllerChannelManagerImpl)
[2024-04-30 08:06:02,168] INFO [ControllerRegistrationManager id=0 incarnation=3tjNwpoXTUCmbPuAH5xkjg] closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,170] INFO [SocketServer listenerType=CONTROLLER, nodeId=0] Stopping socket server request processors (kafka.network.SocketServer)
[2024-04-30 08:06:02,173] INFO [SocketServer listenerType=CONTROLLER, nodeId=0] Stopped socket server request processors (kafka.network.SocketServer)
[2024-04-30 08:06:02,174] INFO [QuorumController id=0] QuorumController#beginShutdown: shutting down event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,174] INFO [SocketServer listenerType=CONTROLLER, nodeId=0] Shutting down socket server (kafka.network.SocketServer)
[2024-04-30 08:06:02,178] INFO [SocketServer listenerType=CONTROLLER, nodeId=0] Shutdown completed (kafka.network.SocketServer)
[2024-04-30 08:06:02,178] INFO [data-plane Kafka Request Handler on Broker 0], shutting down (kafka.server.KafkaRequestHandlerPool)
[2024-04-30 08:06:02,179] INFO [data-plane Kafka Request Handler on Broker 0], shut down completely (kafka.server.KafkaRequestHandlerPool)
[2024-04-30 08:06:02,179] INFO [ExpirationReaper-0-AlterAcls]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:02,180] INFO [ExpirationReaper-0-AlterAcls]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:02,180] INFO [ExpirationReaper-0-AlterAcls]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2024-04-30 08:06:02,181] INFO [controller-0-ThrottledChannelReaper-Fetch]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,182] INFO [controller-0-ThrottledChannelReaper-Fetch]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,182] INFO [controller-0-ThrottledChannelReaper-Fetch]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,182] INFO [controller-0-ThrottledChannelReaper-Produce]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,182] INFO [controller-0-ThrottledChannelReaper-Produce]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,182] INFO [controller-0-ThrottledChannelReaper-Produce]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,182] INFO [controller-0-ThrottledChannelReaper-Request]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,182] INFO [controller-0-ThrottledChannelReaper-Request]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,183] INFO [controller-0-ThrottledChannelReaper-Request]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,183] INFO [controller-0-ThrottledChannelReaper-ControllerMutation]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,183] INFO [controller-0-ThrottledChannelReaper-ControllerMutation]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,183] INFO [controller-0-ThrottledChannelReaper-ControllerMutation]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2024-04-30 08:06:02,183] INFO [QuorumController id=0] closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,185] INFO [SharedServer id=0] Stopping SharedServer (kafka.server.SharedServer)
[2024-04-30 08:06:02,185] INFO [MetadataLoader id=0] beginShutdown: shutting down event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,185] INFO [SnapshotGenerator id=0] close: shutting down event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,242] INFO [SnapshotGenerator id=0] closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,243] INFO [MetadataLoader id=0] closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,244] INFO [SnapshotGenerator id=0] closed event queue. (org.apache.kafka.queue.KafkaEventQueue)
[2024-04-30 08:06:02,245] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics)
[2024-04-30 08:06:02,245] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics)
[2024-04-30 08:06:02,245] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics)
[2024-04-30 08:06:02,246] INFO App info kafka.server for 0 unregistered (org.apache.kafka.common.utils.AppInfoParser)
[2024-04-30 08:06:02,246] INFO App info kafka.server for 0 unregistered (org.apache.kafka.common.utils.AppInfoParser)
```

Whereas the pod always restarts this creates a lot of disconnection on the client side.

When the cluster is stable, running a debug container I was able to:
* to verify that the name `kafka-cluster-controller-0.kafka-cluster-controller-headless.kafka.svc.cluster.local` is resolvable with `nslookup`
* to verify the topic was correctly created using `kafka-topics --bootstrap-server kafka-cluster.kafka.svc.cluster.local:9092 --list`

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by clementrey-dev** [comment]
Hello, I finally figure out the problem.
I did not pay attention bu the Kafka cluster has been deployed on spot instances. And this why I was seeing this shutdown message everywhere.

I switch to on demand and this works perfectly well
Sorry for the  false positive.

Best Regards
