### ISSUE TITLE
Issues with magento pod

### ISSUE THREAD

**Issue by deton57** [bitnami/charts#2606]
chart: magento-13.0.0 
App version: 2.3.5

Running the following commands: 

` helm install magento bitnami/magento`
`export APP_HOST=$(kubectl get svc --namespace magento magento --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")`
`export APP_PASSWORD=$(kubectl get secret --namespace magento magento -o jsonpath="{.data.magento-password}" | base64 --decode)`
`export APP_DATABASE_PASSWORD=$(kubectl get secret --namespace magento magento-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)`
`helm upgrade magento bitnami/magento     --set magentoHost=$APP_HOST,magentoPassword=$APP_PASSWORD,mariadb.db.password=$APP_DATABASE_PASSWORD
`

kubectl logs magento-fcc56b5b8-m9lsg
```
mysql-c INFO MySQL server listening and working at magento-mariadb:3306
magento INFO Installing Magento...
php TRACE [runProgram] Executing: /opt/bitnami/php/bin/php magento,setup:install,-v,--base-url,http://132.145.228.207/,--backend-frontname,admin,--db-host,magento-mariadb:3306,--db-name,bitnami_magento,--db-user,bn_magento,--db-password,YYR1yXsnMH,--admin-firstname,FirstName,--admin-lastname,LastName,--admin-email,user@example.com,--admin-user,user,--admin-password,tz9VuzP3O7,--language,en_US,--currency,USD,--timezone,America/Los_Angeles,--use-secure,1,--base-url-secure,https://132.145.228.207/,--use-secure-admin,0
Error executing 'postInstallation':
In Mysql.php line 110:

[Zend_Db_Statement_Exception]
SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege an
d binary logging is enabled (you might want to use the less safe log_bin_
trust_function_creators variable), query was: DROP TRIGGER IF EXISTS trg_c atalog_product_entity_after_insert

Exception trace:
at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110
Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:92
Magento\Framework\DB\Statement\Pdo\Mysql->_execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
Zend_Db_Statement->execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
Zend_Db_Adapter_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
Zend_Db_Adapter_Pdo_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:546
Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:613
Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:128
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:3964
Magento\Framework\DB\Adapter\Pdo\Mysql->dropTrigger() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:1233
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->dropTrigger() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View/Subscription.php:124
Magento\Framework\Mview\View\Subscription->create() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View.php:204
Magento\Framework\Mview\View->subscribe() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer.php:291
Magento\Indexer\Model\Indexer->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:192
Magento\Indexer\Model\Indexer\DependencyDecorator->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/google-shopping-ads/Setup/UpgradeData.php:147
Magento\GoogleShoppingAds\Setup\UpgradeData->upgrade() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:1005
Magento\Setup\Model\Installer->handleDBSchemaData() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:890
Magento\Setup\Model\Installer->installDataFixtures() at n/a:n/a
call_user_func_array() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:371
Magento\Setup\Model\Installer->install() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:221
Magento\Setup\Console\Command\InstallCommand->execute() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:255
Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:1001
Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:271
Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:115
Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:147
Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23

In Mysql.php line 91:

[PDOException (HY000)]
SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege an
d binary logging is enabled (you might want to use the less safe log_bin_
trust_function_creators variable)

Exception trace:
at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91
PDOStatement->execute() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91
Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo{closure}() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:107
Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:92
Magento\Framework\DB\Statement\Pdo\Mysql->_execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
Zend_Db_Statement->execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
Zend_Db_Adapter_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
Zend_Db_Adapter_Pdo_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:546
Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:613
Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:128
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:3964
Magento\Framework\DB\Adapter\Pdo\Mysql->dropTrigger() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:1233
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->dropTrigger() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View/Subscription.php:124
Magento\Framework\Mview\View\Subscription->create() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View.php:204
Magento\Framework\Mview\View->subscribe() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer.php:291
Magento\Indexer\Model\Indexer->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:192
Magento\Indexer\Model\Indexer\DependencyDecorator->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/google-shopping-ads/Setup/UpgradeData.php:147
Magento\GoogleShoppingAds\Setup\UpgradeData->upgrade() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:1005
Magento\Setup\Model\Installer->handleDBSchemaData() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:890
Magento\Setup\Model\Installer->installDataFixtures() at n/a:n/a
call_user_func_array() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:371
Magento\Setup\Model\Installer->install() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:221
Magento\Setup\Console\Command\InstallCommand->execute() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:255
Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:1001
Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:271
Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:115
Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:147
Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23

setup:install [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--backend-frontname BACKEND-FRONTNAME] [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retires SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--cache-backend-redis-compress-data CACHE-BACKEND-REDIS-COMPRESS-DATA] [--cache-backend-redis-compression-lib CACHE-BACKEND-REDIS-COMPRESSION-LIB] [--cache-id-prefix CACHE-ID-PREFIX] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-compression-lib PAGE-CACHE-REDIS-COMPRESSION-LIB] [--page-cache-id-prefix PAGE-CACHE-ID-PREFIX] [--lock-provider LOCK-PROVIDER] [--lock-db-prefix LOCK-DB-PREFIX] [--lock-zookeeper-host LOCK-ZOOKEEPER-HOST] [--lock-zookeeper-path LOCK-ZOOKEEPER-PATH] [--lock-file-path LOCK-FILE-PATH] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]

nami TRACE Error: Error executing 'postInstallation':
In Mysql.php line 110:

[Zend_Db_Statement_Exception]
SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege an
d binary logging is enabled (you might want to use the less safe log_bin_
trust_function_creators variable), query was: DROP TRIGGER IF EXISTS trg_c atalog_product_entity_after_insert

Exception trace:
at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110
Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:92
Magento\Framework\DB\Statement\Pdo\Mysql->_execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
Zend_Db_Statement->execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
Zend_Db_Adapter_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
Zend_Db_Adapter_Pdo_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:546
Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:613
Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:128
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:3964
Magento\Framework\DB\Adapter\Pdo\Mysql->dropTrigger() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:1233
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->dropTrigger() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View/Subscription.php:124
Magento\Framework\Mview\View\Subscription->create() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View.php:204
Magento\Framework\Mview\View->subscribe() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer.php:291
Magento\Indexer\Model\Indexer->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:192
Magento\Indexer\Model\Indexer\DependencyDecorator->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/google-shopping-ads/Setup/UpgradeData.php:147
Magento\GoogleShoppingAds\Setup\UpgradeData->upgrade() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:1005
Magento\Setup\Model\Installer->handleDBSchemaData() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:890
Magento\Setup\Model\Installer->installDataFixtures() at n/a:n/a
call_user_func_array() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:371
Magento\Setup\Model\Installer->install() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:221
Magento\Setup\Console\Command\InstallCommand->execute() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:255
Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:1001
Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:271
Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:115
Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:147
Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23

In Mysql.php line 91:

[PDOException (HY000)]
SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege an
d binary logging is enabled (you might want to use the less safe log_bin_
trust_function_creators variable)

Exception trace:
at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91
PDOStatement->execute() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91
Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo{closure}() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:107
Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:92
Magento\Framework\DB\Statement\Pdo\Mysql->_execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
Zend_Db_Statement->execute() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
Zend_Db_Adapter_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
Zend_Db_Adapter_Pdo_Abstract->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:546
Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:613
Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:128
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query() at /opt/bitnami/magento/htdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:3964
Magento\Framework\DB\Adapter\Pdo\Mysql->dropTrigger() at /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:1233
Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->dropTrigger() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View/Subscription.php:124
Magento\Framework\Mview\View\Subscription->create() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Mview/View.php:204
Magento\Framework\Mview\View->subscribe() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer.php:291
Magento\Indexer\Model\Indexer->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:192
Magento\Indexer\Model\Indexer\DependencyDecorator->setScheduled() at /opt/bitnami/magento/htdocs/vendor/magento/google-shopping-ads/Setup/UpgradeData.php:147
Magento\GoogleShoppingAds\Setup\UpgradeData->upgrade() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:1005
Magento\Setup\Model\Installer->handleDBSchemaData() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:890
Magento\Setup\Model\Installer->installDataFixtures() at n/a:n/a
call_user_func_array() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:371
Magento\Setup\Model\Installer->install() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:221
Magento\Setup\Console\Command\InstallCommand->execute() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:255
Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:1001
Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:271
Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:115
Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:147
Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23

setup:install [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--backend-frontname BACKEND-FRONTNAME] [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retires SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--cache-backend-redis-compress-data CACHE-BACKEND-REDIS-COMPRESS-DATA] [--cache-backend-redis-compression-lib CACHE-BACKEND-REDIS-COMPRESSION-LIB] [--cache-id-prefix CACHE-ID-PREFIX] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-compression-lib PAGE-CACHE-REDIS-COMPRESSION-LIB] [--page-cache-id-prefix PAGE-CACHE-ID-PREFIX] [--lock-provider LOCK-PROVIDER] [--lock-db-prefix LOCK-DB-PREFIX] [--lock-zookeeper-host LOCK-ZOOKEEPER-HOST] [--lock-zookeeper-path LOCK-ZOOKEEPER-PATH] [--lock-file-path LOCK-FILE-PATH] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]

at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.php/helpers.js:69:14)
at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
at Object.$app.helpers.magentoCli (/root/.nami/components/com.bitnami.magento/helpers.js:37:7)
at Component.$app.postInstallation (/root/.nami/components/com.bitnami.magento/main.js:89:18)
at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
```

**Comment by rafariossaa** [comment]
Hi,
  Did you get a notice when installing the chart that way? You should have got something like:
```
$  helm install magento bitnami/magento
NAME: magento
LAST DEPLOYED: Tue May 19 06:49:38 2020
NAMESPACE: rafael
STATUS: deployed
REVISION: 1
NOTES:
###############################################################################
### ERROR: You did not provide an external host in your 'helm install' call ###
###############################################################################

This deployment will be incomplete until you configure Magento with a resolvable
host. To configure Magento with the URL of your service:
...

```
 You have instructions about this at the end of the parameter list [here](https://github.com/bitnami/charts/tree/master/bitnami/magento#user-content-parameters).
