### ISSUE TITLE
Discourse container fails to start with discourse-ai plugin specified

### ISSUE THREAD

**Issue by lazyfatcot** [bitnami/charts#26565]
### Name and Version

bitnami/discourse 13.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Add the discourse-ai plugin to the plugins section in values.yaml

### Are you using any custom parameters or values?
```yaml
discourse:
  persistPlugins: false
  plugins:
    - https://github.com/discourse/discourse-ai.git
```

### What is the expected behavior?

discourse-ai plugin successfully installed and the discourse container is started

### What do you see instead?

Infinite container restart with the following error in logs:
```
Defaulted container "discourse" out of: discourse, sidekiq
Cloning into '/opt/bitnami/discourse/plugins/discourse-ai'...
checking out compatible discourse-ai version: a65c4076a63104b61d213534db7f89aa3c8acd9e
HEAD is now at a65c407 SECURITY: Place a SSRF protection when calling services from the plugin. (#485)
discourse 10:43:19.99 INFO  ==> 
discourse 10:43:20.00 INFO  ==> Welcome to the Bitnami discourse container
discourse 10:43:20.00 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 10:43:20.01 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 10:43:20.01 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse 10:43:20.01 INFO  ==> 
###
gem install tokenizers -v 0.4.2 -i /opt/bitnami/discourse/plugins/discourse-ai/gems/3.2.4 --no-document --ignore-dependencies --no-user-install
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/bitnami/discourse/plugins/discourse-ai/gems directory.
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:356:in `rescue in install'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:305:in `install'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/resolver/specification.rb:105:in `install'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/request_set.rb:281:in `block in install_into'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/request_set.rb:273:in `each'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/request_set.rb:273:in `install_into'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/request_set.rb:148:in `install'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:207:in `install_gem'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:216:in `each'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:216:in `install_gems'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:162:in `execute'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:326:in `invoke_with_build_args'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:255:in `invoke_command'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:194:in `process_args'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:152:in `run'
	/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:56:in `run'
	/opt/bitnami/ruby/bin/gem:12:in `<main>'

You are specifying the gem tokenizers in /opt/bitnami/discourse/plugins/discourse-ai/plugin.rb, however it does not exist!
Looked for: 
- /opt/bitnami/discourse/plugins/discourse-ai/gems/3.2.4/specifications/tokenizers-0.4.2.gemspec
- /opt/bitnami/discourse/plugins/discourse-ai/gems/3.2.4/specifications/tokenizers-0.4.2-x86_64-linux.gemspec
- /opt/bitnami/discourse/plugins/discourse-ai/gems/3.2.4/specifications/tokenizers-0.4.2-x86_64-linux.gemspec
```

**Comment by lazyfatcot** [comment]
Seems that I found the root of the problem.
The **root** user performs a git clone of the plugin, so he becomes the directory owner.

```
root@discourse-test-7df6cfbc64-vjn8m:/opt/bitnami/discourse/plugins/discourse-ai# ls -la
total 12
drwxr-xr-x 3 root      root 4096 May 30 11:16 .
```

No wonder that in such a condition 

> gem install tokenizers -v 0.4.2 -i /opt/bitnami/discourse/plugins/discourse-ai/gems/3.2.4 --no-document --ignore-dependencies --no-user-install

 fired by the **discourse** user fails.

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by MahendraRaja** [comment]
I am stuck with this issue.  How to adjust the ownership? Can we do it through values.yaml?
