### ISSUE TITLE
[bitnami/spark] Submit example not working

### ISSUE THREAD

**Issue by JWDobken** [bitnami/charts#2669]
Deploy the [spark chart](https://github.com/bitnami/charts/tree/master/bitnami/spark) version 1.2.21 without any changes to the settings; no problems here, having one master and two worker pods runnings.

After installation with Helm, [the following lines](https://github.com/bitnami/charts/blob/0b43bcaf762f853b6d156342f018bf777cf0ae35/bitnami/spark/templates/NOTES.txt#L30) are suggested to run an example application (when the stack is deployed in a namespace, the namespace flag is not included):

```cmd
2. Submit an application to the cluster:

  To submit an application to the cluster the spark-submit script must be used. That script can be
  obtained at https://github.com/apache/spark/tree/master/bin. Also you can use kubectl run.

  kubectl exec -ti spark-worker-0 -- spark-submit --master spark://spark-master-svc:7077 \
    --class org.apache.spark.examples.SparkPi \
    examples/jars/spark-examples_2.11-2.4.4.jar 5
```

But this returns the following error:
```cmd
$ kubectl exec -ti spark-worker-0 -- spark-submit --master spark://spark-master-svc:7077 \
    --class org.apache.spark.examples.SparkPi \
    examples/jars/spark-examples_2.11-2.4.4.jar 5
20/05/26 17:21:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/05/26 17:21:07 WARN DependencyUtils: Local jar /opt/bitnami/spark/examples/jars/spark-examples_2.11-2.4.4.jar does not exist, skipping.
20/05/26 17:21:07 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.examples.SparkPi.
java.lang.ClassNotFoundException: org.apache.spark.examples.SparkPi
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:806)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/05/26 17:21:07 INFO ShutdownHookManager: Shutdown hook called
20/05/26 17:21:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-6cdeed5d-e98d-4504-90c5-a32ee95e7978
command terminated with exit code 101
```

- Kube client: "v1.18.2"
- GKE server: "v1.15.11-gke.5"

**Comment by dani8art** [comment]
Hi @JWDobken yes you are right there are two issues here, 

- one of them is with the `.jar` path that we need to use the full path instead of relative, please append.

```console
/opt/bitnami/spark/...
```

- the second one is with the `.jar` version that we need to use `2.4.5` instead.

**Comment by JWDobken** [comment]
I confirm that this works indeed:
```cmd
kubectl exec -ti spark-worker-0 -- spark-submit --master spark://spark-master-svc:7077 \
  --class org.apache.spark.examples.SparkPi \
  /opt/bitnami/spark/examples/jars/spark-examples_2.11-2.4.5.jar 5
```

**Comment by dani8art** [comment]
Yes, we have opened an internal task to try to find a solution that doesn't depend on the `jar` version. Thank you so much for the feedback!
