### ISSUE TITLE
Cannot deploy MLFlow helm chart with `tracking.auth` enabled

### ISSUE THREAD

**Issue by aaj-synth** [bitnami/charts#26928]
### Name and Version

bitnami/mlflow 1.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to create authentication for MLFlow tracking server using the `tracking.auth.enabled` configuration. The mlflow server was already deployed and was running. The helm chart is unable to create the authentication component and continuously fails, stating some alembic migrations as culprit. I am using the same database for both tracking server and authentication, which means that i have the same value for `externalDatabase.database` and `externalDatabase.authDatabase`.

### Are you using any custom parameters or values?

```yaml
externalDatabase:
  authDatabase: mlflowbackend
  database: mlflowbackend
  existingSecret: mlflow-db-auth
  existingSecretPasswordKey: db_password
  host: <redacted>
  user: mlflow_backend_user
tracking:
  auth:
    enabled: true
    existingSecret: mlflow-db-auth
    existingSecretPasswordKey: db_password
    existingSecretUserKey: username
```

### What is the expected behavior?

MLFlow instance should get auth.

### What do you see instead?

MLFlow is in a `CrashLoopBackOff` state with the following logs:

```bash
 k get pods -n mlflow -w
NAME                               READY   STATUS                  RESTARTS      AGE
mlflow-tracking-857779dc67-msgrm   0/1     Init:CrashLoopBackOff   2 (18s ago)   39s

# This shows up in the pod logs:
k logs mlflow-tracking-5848565f6-4bgs8 -c upgrade-db-auth -n mlflow                                                                                                                                                 
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 251, in _catch_revision_errors
    yield
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 459, in _upgrade_revs
    for script in reversed(list(revs))
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 813, in iterate_revisions
    revisions, heads = fn(
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 1466, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 566, in get_revisions
    return tuple(
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 567, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 638, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '5b0e9adcef9c'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/bitnami/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/__main__.py", line 4, in <module>
    commands()
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bitnami/python/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/db/cli.py", line 17, in upgrade
    utils.migrate(engine, revision)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/db/utils.py", line 28, in migrate
    upgrade(alembic_cfg, revision)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/db/migrations/env.py", line 76, in <module>
    run_migrations_online()
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/auth/db/migrations/env.py", line 70, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/command.py", line 392, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 447, in _upgrade_revs
    with self._catch_revision_errors(
  File "/opt/bitnami/python/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '5b0e9adcef9c'
```

### Additional information

I tried turning on authentication on an existing mlflow server as well as created a new mlflow server with authentication already configured as `enabled`. 
- On a running mlflow server, i got the error that i have posted above, which was coming from `upgrade-db-auth` container.
- On a completely new DB and MLFlow server, i got the same error, but not from `upgrade-db-auth` rather from `mlflow` container.
```bash
>> k logs mlflow-tracking-6f665b7b87-hvmwk -c upgrade-db-auth -n mlflow
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 8606fa83a998, initial_migration

>> k logs mlflow-tracking-6f665b7b87-hvmwk -c mlflow -n mlflow
Defaulted container "mlflow" out of: mlflow, wait-for-database (init), get-default-auth-conf (init), render-auth-conf (init), upgrade-db-auth (init)
2024/06/06 15:32:01 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2024/06/06 15:32:01 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
2024/06/06 15:32:01 ERROR mlflow.cli: Error initializing backend store
2024/06/06 15:32:01 ERROR mlflow.cli: Can't locate revision identified by '8606fa83a998'
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 251, in _catch_revision_errors
    yield
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 459, in _upgrade_revs
    for script in reversed(list(revs))
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 813, in iterate_revisions
    revisions, heads = fn(
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 1466, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 566, in get_revisions
    return tuple(
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 567, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/revision.py", line 638, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '8606fa83a998'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/cli.py", line 425, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 306, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 283, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 42, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 52, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 137, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 170, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 98, in _initialize_tables
    _upgrade_db(engine)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 223, in _upgrade_db
    command.upgrade(config, "heads")
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/command.py", line 392, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 447, in _upgrade_revs
    with self._catch_revision_errors(
  File "/opt/bitnami/python/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/bitnami/python/lib/python3.10/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '8606fa83a998'
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by KyriosGN0** [comment]
i ran into the same problem, you need a sperate DB for auth

**Comment by KyriosGN0** [comment]
if you create a second database instance in the same machine and set `authDatabase` to point to it (assuming the have the same username and password) it should work
