### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function init_set()

### ISSUE THREAD

**Issue by spuny** [bitnami/charts#27836]
### Name and Version

bitnami/wordpress 22.4.18

### What architecture are you using?

None

### What steps will reproduce the bug?

Installed the fresh new chart with already initialized db. Using flux. But that should not matter.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The pod should start up normally without any problems

### What do you see instead?

Debug log with the error:
```
wordpress-dev-7bfc5858cd-g8rnq wordpress wordpress 09:35:37.20 DEBUG ==> Setting WP_AUTO_UPDATE_CORE to 'false' in WordPress configuration (literal: yes)
wordpress-dev-7bfc5858cd-g8rnq wordpress Success: Added the constant 'WP_AUTO_UPDATE_CORE' to the 'wp-config.php' file with the raw value 'false'.
wordpress-dev-7bfc5858cd-g8rnq wordpress wordpress 09:35:37.30 INFO  ==> An already initialized WordPress database was provided, configuration will be skipped
wordpress-dev-7bfc5858cd-g8rnq wordpress [08-Jul-2024 09:35:37 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function init_set() in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1334) : eval()'d code:102
wordpress-dev-7bfc5858cd-g8rnq wordpress Stack trace:
wordpress-dev-7bfc5858cd-g8rnq wordpress #0 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1334): eval()
wordpress-dev-7bfc5858cd-g8rnq wordpress #1 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1293): WP_CLI\Runner->load_wordpress()
wordpress-dev-7bfc5858cd-g8rnq wordpress #2 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
wordpress-dev-7bfc5858cd-g8rnq wordpress #3 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
wordpress-dev-7bfc5858cd-g8rnq wordpress #4 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
wordpress-dev-7bfc5858cd-g8rnq wordpress #5 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/php/boot-phar.php(20): include('...')
wordpress-dev-7bfc5858cd-g8rnq wordpress #6 /opt/bitnami/wp-cli/bin/wp-cli.phar(4): include('...')
wordpress-dev-7bfc5858cd-g8rnq wordpress #7 {main}
wordpress-dev-7bfc5858cd-g8rnq wordpress   thrown in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1334) : eval()'d code on line 102
```

**Comment by spuny** [comment]
Just FYI, I've backuped the db to restore it later and I'm trying to install it as a new chart in a new namespace. Still the same error

**Comment by spuny** [comment]
I'm closing this, it was my bad configuration probably. I've tested whole new install from helm chart directly and it was running.
After disabling following in values.yaml file it started working:
```
    wordpressExtraConfigContent: |
      @init_set( 'post_max_size', '1024M');
      @init_set( 'memory_limit', '300M');
      @init_set( 'upload_max_filesize', '200M');
      @init_set( 'max_execution_time', '360');
      @init_set( 'max_input_time', '360');
```
