### ISSUE TITLE
[bitnami/elasticsearch] Error message for adding elastiknn plugin ，Hope foundation bitnami/elasticsearch: 8.14.x image using Java 22+

### ISSUE THREAD

**Issue by liuxin638507** [bitnami/charts#27942]
### Name and Version

bitnami/elasticsearch:8.14.2

### What architecture are you using?

None

### What steps will reproduce the bug?

~~~bash
elasticsearch 17:47:14.11 INFO  ==> 
elasticsearch 17:47:14.12 INFO  ==> Welcome to the Bitnami elasticsearch container
elasticsearch 17:47:14.12 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
elasticsearch 17:47:14.13 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
elasticsearch 17:47:14.14 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
elasticsearch 17:47:14.14 INFO  ==> 
elasticsearch 17:47:14.26 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 17:47:14.34 WARN  ==> Setting ELASTICSEARCH_IS_DEDICATED_NODE is disabled.
elasticsearch 17:47:14.35 WARN  ==> ELASTICSEARCH_NODE_ROLES will be ignored and Elasticsearch will asume all different roles.
elasticsearch 17:47:14.36 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 17:47:14.43 INFO  ==> Setting default configuration
elasticsearch 17:47:14.52 INFO  ==> Configuring Elasticsearch cluster settings...
warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
elasticsearch 17:47:19.22 INFO  ==> ** Elasticsearch setup finished! **

elasticsearch 17:47:19.27 INFO  ==> ** Starting Elasticsearch **
warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
[2024-07-12T09:47:27,161][INFO ][o.e.n.NativeAccess       ] [5b4ca87cffcc] Using [jna] native provider and native methods for [Linux]
[2024-07-12T09:47:28,750][INFO ][o.e.n.Node               ] [5b4ca87cffcc] version[8.14.2], pid[315], build[tar/2afe7caceec8a26ff53817e5ed88235e90592a1b/2024-07-01T22:06:58.515911606Z], OS[Linux/5.4.3-1.el7.elrepo.x86_64/amd64], JVM[BellSoft/OpenJDK 64-Bit Server VM/17.0.11/17.0.11+12-LTS]
[2024-07-12T09:47:28,750][INFO ][o.e.n.Node               ] [5b4ca87cffcc] JVM home [/opt/bitnami/java], using bundled JDK [false]
[2024-07-12T09:47:28,751][INFO ][o.e.n.Node               ] [5b4ca87cffcc] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=org.elasticsearch.preallocate, --add-opens=org.apache.lucene.core/org.apache.lucene.store=org.elasticsearch.vec, -XX:ReplayDataFile=logs/replay_pid%p.log, -Djava.library.path=/opt/bitnami/elasticsearch/lib/platform/linux-x64:/opt/bitnami/elasticsearch/jdk/lib:/opt/bitnami/elasticsearch/jdk/lib/server::/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib, -Djna.library.path=/opt/bitnami/elasticsearch/lib/platform/linux-x64:/opt/bitnami/elasticsearch/jdk/lib:/opt/bitnami/elasticsearch/jdk/lib/server::/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib, -Des.distribution.type=tar, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-10592032835620624227, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,level,pid,tags:filecount=32,filesize=64m, -Xms1024m, -Xmx1024m, -XX:MaxDirectMemorySize=536870912, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, --module-path=/opt/bitnami/elasticsearch/lib, --add-modules=jdk.net, --add-modules=ALL-MODULE-PATH, -Djdk.module.main=org.elasticsearch.server]
[2024-07-12T09:47:28,751][INFO ][o.e.n.Node               ] [5b4ca87cffcc] Default Locale [en_US]
[2024-07-12T09:47:28,846][ERROR][o.e.b.Elasticsearch      ] [5b4ca87cffcc] fatal exception while booting Elasticsearch java.lang.IllegalStateException: plugin elastiknn requires Java 21:, your system: 17.0.11+12-LTS
	at org.elasticsearch.base@8.14.2/org.elasticsearch.jdk.JarHell.checkJavaVersion(JarHell.java:280)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.plugins.PluginDescriptor.readJavaVersion(PluginDescriptor.java:320)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.plugins.PluginDescriptor.readerInternalDescriptor(PluginDescriptor.java:266)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:251)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.plugins.PluginsUtils.readPluginBundle(PluginsUtils.java:255)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.plugins.PluginsUtils.findBundles(PluginsUtils.java:236)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.plugins.PluginsUtils.getPluginBundles(PluginsUtils.java:218)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:156)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.node.NodeServiceProvider.newPluginService(NodeServiceProvider.java:54)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.node.NodeConstruction.createEnvironment(NodeConstruction.java:451)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.node.NodeConstruction.prepareConstruction(NodeConstruction.java:252)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.node.Node.<init>(Node.java:192)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:240)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:240)
	at org.elasticsearch.server@8.14.2/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)

ERROR: Elasticsearch did not exit normally - check the logs at /opt/bitnami/elasticsearch/logs/elasticsearch.log

ERROR: Elasticsearch died while starting up, with exit code 1
~~~

### What do you see instead?

Hope foundation bitnami/elasticsearch: 8.14.x image using Java 22+

**Comment by javsalgar** [comment]
Hi!

I'm afraid this is because we are using Java 17 in the Elasticsearch image and we don't have short-term plans to update it. As an alternative, you can create your own fork where you replace the Java image. 

https://github.com/bitnami/containers/blob/main/bitnami/elasticsearch/8/debian-12/Dockerfile

**Comment by liuxin638507** [comment]
> Hi!
> 
> I'm afraid this is because we are using Java 17 in the Elasticsearch image and we don't have short-term plans to update it. As an alternative, you can create your own fork where you replace the Java image.
> 
> https://github.com/bitnami/containers/blob/main/bitnami/elasticsearch/8/debian-12/Dockerfile

Thank you. At present, I have manually replaced the java version and it works normally
