### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nirberko** [bitnami/charts#28651]
### Name and Version

bitnami/supabase:5.3.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. just install this helm chart on EKS

### Are you using any custom parameters or values?
```yaml
postgresql:
  enabled: false

externalDatabase:
  host: ....
  user: root
  password: .....
  database: postgres
  port: 5432
```
### What do you see instead?

I'm getting `CrashLoopBackOff` in `supabase-auth` pod.

this is the logs:
```
Defaulted container "gotrue" out of: gotrue, wait-for-db (init)
{"level":"info","msg":"Go runtime metrics collection started","time":"2024-08-04T14:26:37Z"}
{"level":"info","msg":"received graceful shutdown signal","time":"2024-08-04T14:26:37Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x60fbce]

goroutine 1 [running]:
net/url.(*URL).Query(0xc00004c017?)
	/opt/bitnami/go/src/net/url/url.go:1122 +0xe
github.com/supabase/auth/cmd.migrate(0xc00021bb80?, {0x0?, 0x0?, 0x0?})
	/bitnami/blacksmith-sandox/gotrue-2.155.6/src/github.com/supabase/auth/cmd/migrate_cmd.go:55 +0x227
github.com/supabase/auth/cmd.init.func3(0x1b3f180, {0x1bbc060?, 0x4?, 0x1184c9c?})
	/bitnami/blacksmith-sandox/gotrue-2.155.6/src/github.com/supabase/auth/cmd/root_cmd.go:17 +0x1d
github.com/spf13/cobra.(*Command).execute(0x1b3f180, {0xc00011e050, 0x0, 0x0})
	/bitnami/blacksmith-sandox/gotrue-2.155.6/src/github.com/supabase/auth/vendor/github.com/spf13/cobra/command.go:920 +0x867
github.com/spf13/cobra.(*Command).ExecuteC(0x1b3f180)
	/bitnami/blacksmith-sandox/gotrue-2.155.6/src/github.com/supabase/auth/vendor/github.com/spf13/cobra/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/bitnami/blacksmith-sandox/gotrue-2.155.6/src/github.com/supabase/auth/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(0x1347b30?, {0x1347cb8?, 0xc000268f00?})
	/bitnami/blacksmith-sandox/gotrue-2.155.6/src/github.com/supabase/auth/vendor/github.com/spf13/cobra/command.go:961 +0x47
main.main()
	/bitnami/blacksmith-sandox/gotrue-2.155.6/src/github.com/supabase/auth/main.go:31 +0xf9
```

### Additional information

this is my terraform eks configuration:

```
data "aws_ssm_parameter" "eks_ami_release_version" {
  name = "/aws/service/eks/optimized-ami/1.28/amazon-linux-2/recommended/release_version"
}

data "aws_iam_role" "terraform-cloud-web-identity" {
  name = "terraform-cloud"
  depends_on = [module.terraform_cloud]
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.0"

  depends_on = [module.vpc, module.terraform_cloud]

  cluster_name    = "${var.environment}-${var.eks.cluster_name}"
  cluster_version = var.eks.cluster_version

  #create_cluster_security_group = true
  cluster_endpoint_public_access = true

  enable_cluster_creator_admin_permissions = true

  cluster_addons = {
    aws-ebs-csi-driver = {
      most_recent = true
    }
    coredns = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
  }

  vpc_id     = module.vpc.vpc_id
  subnet_ids = flatten([module.vpc.private_subnets, module.vpc.public_subnets])

  eks_managed_node_group_defaults = {
    instance_types = ["t3.medium"]
  }

  # TODO - node group for the platform, and node group for the test runners
  eks_managed_node_groups = {
    nodes = {
      instance_types      = ["t3.medium"]
      ami_release_version = nonsensitive(data.aws_ssm_parameter.eks_ami_release_version.value)

      min_size     = 1
      max_size     = 50
      desired_size = 1

      capacity_type = "SPOT"
    }
  }

#  kms_key_owners = [
#    data.aws_iam_role.terraform-cloud-web-identity.arn
#  ]
}

module "eks-auth" {
  source  = "terraform-aws-modules/eks/aws//modules/aws-auth"
  version = "~> 20.0"

  depends_on = [module.eks]

  manage_aws_auth_configmap = true

  aws_auth_roles = [
    {
      rolearn  = aws_iam_role.k8s-admin-role.arn
      username = aws_iam_role.k8s-admin-role.name
      groups   = ["system:masters"]
    },
    {
      rolearn  = module.terraform_cloud.role_arn
      username = data.aws_iam_role.terraform-cloud-web-identity.name,
      groups   = ["system:masters"]
    }
  ]

  aws_auth_accounts = [
    local.account_id
  ]
}

module "kubernetes-addons" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "~> 1.0"

  depends_on = [module.eks]

  cluster_name      = module.eks.cluster_name
  cluster_endpoint  = module.eks.cluster_endpoint
  cluster_version   = module.eks.cluster_version
  oidc_provider_arn = module.eks.oidc_provider_arn

  enable_aws_load_balancer_controller = true
  enable_cluster_autoscaler           = true

  aws_load_balancer_controller = {
    set = [
      {
        name  = "vpcId"
        value = module.vpc.vpc_id
      },
      {
        name  = "podDisruptionBudget.maxUnavailable"
        value = 1
      },
    ]
  }
}

module "iam_eks_role" {
  source    = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  role_name = "${module.eks.cluster_name}-default-eks-role"

  depends_on = [module.eks]

  role_policy_arns = {
    AmazonRDSFullAccess = "arn:aws:iam::aws:policy/AmazonRDSFullAccess",
    AmazonSQSFullAccess = "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
  }

  oidc_providers = {
    nodes = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["default:default", "platform:default", "supabase:default"]
    }
  }
}

resource "kubernetes_default_service_account" "platform" {
  depends_on = [module.eks]
  metadata {
    namespace   = "platform"
    annotations = {
      "eks.amazonaws.com/role-arn" = module.iam_eks_role.iam_role_arn
    }
  }
}

data "aws_eks_cluster" "this" {
  name = module.eks.cluster_name
}

data "aws_eks_cluster_auth" "this" {
  depends_on = [module.eks]
  name = module.eks.cluster_name
}
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by nirberko** [comment]
I manage to make it run but now I'm getting cors error for `kong` and I'm wondering if there is any configuration i need to configure for the ingress. because i didn't found any cors configuration in any of the charts
