### ISSUE TITLE
[bitnami/keycloak] How do I add my custom provider?

### ISSUE THREAD

**Issue by chominnn** [bitnami/charts#28795]
### Name and Version
bitnami/keycloak

#values.yaml
```yaml
extraVolumes:
    - name: keycloak-spi-pv
      persistentVolumeClaim:
        claimName: keycloak-spi-pvc
extraVolumeMounts:
    - name: keycloak-spi-pv
      mountPath: /mydir
```
This is my first time using Keycloak. And I am not good at English. I ask for your understanding

When the pod starts, I can see the directory in /mydir

To custom user providers apply, 
The file must be placed in /opt/bitnami/keycloak

If i edit the additional volume mount path to [/opt/bitnami/keycloak]

The keycloak install scripts(?) are not working It seems to have been overwritten by the persistent volume

I used the container below 
```yaml
    - Name: init-spi
      Image: busybox
      imagePullPolicy: Always
      Command: ["/bin/sh"]
      args: [-c], cp -R /mydir/* /opt/bitnami / keycloak /"]
      Mount Volume:
      - name : keycloak-spi- pv
        mountPath: /mydir
      Security Context:
        Run as user: 1001
        RunAsGroup: 1001
```
But again, it didn't work

Unable to create cp: '/opt/bitnami/keycloak' directory, no such file or directory

The directory cannot be created because the main container (keycloak installation scripts) has not started

How do I apply for a custom user provider??

Or is there a way to restart Keycloak without deleting the pod?
If possible, I would like to copy the file directly to the directory after the Keycloak pod is executed.

Or if there is a good way, please advise.

Thank you.

**Comment by chominnn** [comment]
and also can see when tried kc.sh start-dev
i need to find how to reload keycloak instead delete pod
keycloak@keycloak-0:/opt/bitnami/keycloak$ kc.sh start-dev
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local
Updating the configuration and installing your custom providers, if any. Please wait.
2024-08-09 01:25:40,317 WARN  [org.keycloak.services] (build-16) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
2024-08-09 01:25:41,064 WARN  [org.keycloak.services] (build-16) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2024-08-09 01:25:54,120 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 18001ms
2024-08-09 01:25:57,766 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2024-08-09 01:26:01,743 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2024-08-09 01:26:03,769 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2024-08-09 01:26:04,082 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-08-09 01:26:04,865 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2024-08-09 01:26:04,870 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 1e83113a-4081-40b6-8043-1251f37464b1, name: keycloak-0-8505
2024-08-09 01:26:04,877 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheException: Unable to start JGroups Channel
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:610)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:481)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:63)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:49)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:43)
        at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:78)
        at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:70)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.BindException: No available port to bind to in range [7800 .. 7800]
        at org.jgroups.util.Util.bind(Util.java:4095)
        at org.jgroups.util.Util.createServerSocket(Util.java:4071)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:68)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:43)
        at org.jgroups.protocols.TCP.start(TCP.java:111)
        at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:905)
        at org.jgroups.JChannel.startStack(JChannel.java:921)
        at org.jgroups.JChannel._preConnect(JChannel.java:799)
        at org.jgroups.JChannel.connect(JChannel.java:322)
        at org.jgroups.JChannel.connect(JChannel.java:316)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:608)
        ... 28 more

2024-08-09 01:26:04,994 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-08-09 01:26:04,994 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
2024-08-09 01:26:04,995 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: Unable to start JGroups Channel
2024-08-09 01:26:04,995 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2024-08-09 01:26:04,996 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2024-08-09 01:26:04,997 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No available port to bind to in range [7800 .. 7800]
2024-08-09 01:26:04,998 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

**Comment by javsalgar** [comment]
Hi,

Looking at the init script, you are copying data to /opt/bitnami/keycloak, but this would disappear if not stored in a volume. At the same time, mounting a volume in /opt/bitnami/keycloak would make its original contents disappear. So you would need to add an extra volume and do something like this:

```bash

cp -rf /opt/bitnami/keycloak/* /my-new-vol
cp -rf /mydir /my-new-vol
```

And then mount the new volume in the main container at /opt/bitnami/keycloak.

**Comment by chominnn** [comment]
> 안녕,
> 
> init 스크립트를 보면, /opt/bitnami/keycloak에 데이터를 복사하고 있지만, 볼륨에 저장하지 않으면 사라집니다. 동시에, /opt/bitnami/keycloak에 볼륨을 마운트하면 원래 내용이 사라집니다. 따라서 여분의 볼륨을 추가하고 다음과 같이 해야 합니다.
> 
> ```shell
> cp -rf /opt/bitnami/keycloak/* /my-new-vol
> cp -rf /mydir /my-new-vol
> ```
> 
> 그런 다음 /opt/bitnami/keycloak의 기본 컨테이너에 새 볼륨을 마운트합니다.

thx to reply but it didn't work T-T



I've been thinking about it for a few days
I think I need the kc.sh restart(or stop) command.

There is no way to transfer custom files before the main container runs
Even if you build kc.sh after adding files to the directory after the main container runs, providers do not seem to apply.
* Theme seems to have been applied.

Even if the same version was performed in a docker environment, it is not applicable to build alone
When I started [kc.sh start] finishing the process, I was able to confirm that the provider came up normally.

**Comment by bork91** [comment]
This commit https://github.com/bitnami/charts/commit/9de041c92e2788a108631052aa5401a9469e3592 has made it possible to add your providers with at initContainer.

```
initContainers: |
    - name: keycloak-plugin
      image: my-plugin
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying module..."
          cp -r /module/* /emptydir/app-providers-dir
      volumeMounts:
        - name: empty-dir
          mountPath: /emptydir
```
