### ISSUE TITLE
[bitnami/kafka] Split brain situation when scaling out kafka

### ISSUE THREAD

**Issue by MikeNikolayev** [bitnami/charts#29167]
### Name and Version

bitnami/kafka 29.3.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install kafka helm chart on 1 node k3s cluster
2. add 2 more nodes to k3s
3.  perform 
helm upgrade --install kafka   ... to apply cluster values and have 3 pods instead of 1

the problem occurs in 50% of the cases but on all Openstack labs in all geo locations - Asia, America, Europe

### Are you using any custom parameters or values?

yes. we use kafka orig chart as dependency of our own chart with our version and customize kafka.
In addition we use linkerd service mesh , so that each kafka pod (and other pods in our cluster) has linkerd sidecar
Example:
helm upgrade --install kafka   /tmp/kafka-<version>.tgz   --wait --timeout 10m   -f /tmp/helm-values/kafka/cluster.values.yaml   -f /tmp/kafka/linkerd.values.yml

default values of our chart:
cat values.yaml
```
kafka:
  metrics:
    kafka:
      enabled: false
  enabled: true
  networkPolicy:
    enabled: true
    egressRules:
      customRules: []
  fullnameOverride: "kafka"
  nameOverride: "kafka"
  image:
    registry: localhost
    repository: bitnami/kafka
  containerSecurityContext:
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  persistence:
    size: 1Gi
  controller:
    resources:
      limits:
        cpu: "1"
        memory: 2.5Gi
      requests:
        cpu: 200m
        memory: 100Mi
    replicaCount: 1
    heapOpts: -Xms256m -Xmx2048m
    podAnnotations:
      linkerd.io/inject: "enabled"
      kubectl.kubernetes.io/default-container: "kafka"
      config.linkerd.io/image-pull-policy: "Never"
      config.linkerd.io/proxy-cpu-request: 50m
      config.linkerd.io/proxy-cpu-limit: 500m
      config.linkerd.io/proxy-memory-request: 48Mi
      config.linkerd.io/proxy-memory-limit: 512Mi
      config.linkerd.io/proxy-outbound-connect-timeout: 5000ms
  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
      name: CLIENT
      sslClientAuth: ""
    controller:
      name: CONTROLLER
      containerPort: 9093
      protocol: PLAINTEXT
      sslClientAuth: ""
    interbroker:
      containerPort: 9094
      protocol: PLAINTEXT
      name: INTERNAL
      sslClientAuth: ""
    external:
      containerPort: 9095
      protocol: PLAINTEXT
      name: EXTERNAL
      sslClientAuth: ""
  extraConfig: |
    num.partitions=10
    num.network.threads=3
    num.io.threads=8
    min.insync.replicas=1
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/bitnami/kafka/data
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.flush.interval.messages=10000
    log.flush.interval.ms=1000
    log.retention.hours=1
    log.roll.hours=3
    log.retention.bytes=250000000
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    allow.everyone.if.no.acl.found=true
    auto.create.topics.enable=true
    default.replication.factor=1
    max.partition.fetch.bytes=1048576
    max.request.size=1048576
    message.max.bytes=20000000
```

while cluster values are overwriting some of them:
```
kafka:
  controller:
    replicaCount: 3
  extraConfig: |
    num.partitions=10
    num.network.threads=3
    num.io.threads=8
    min.insync.replicas=1
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/bitnami/kafka/data
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=1
    log.flush.interval.messages=10000
    log.flush.interval.ms=1000
    log.retention.hours=1
    log.roll.hours=3
    log.retention.bytes=250000000
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    allow.everyone.if.no.acl.found=true
    auto.create.topics.enable=true
    default.replication.factor=3
    max.partition.fetch.bytes=1048576
    max.request.size=1048576
    message.max.bytes=20000000
```
and linkerd:
```
kafka:
  controller:
    podAnnotations:
      linkerd-version: "stable-2.13.7"
```

### What is the expected behavior?

the expected behavior is to see all 3 brokers working together as a cluster.
I verify it by
/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka-controller-headless:9092

### What do you see instead?

while instead we have a split brain issue.
 
broker-0 (restarted after upgrade) sees itself only
 brokers 1 and 2 "see" all

and on top of all that, kafka partitions reassignment job fails due to that.  

### Additional information

some more info from the logs:
kafka log(most often the problem is with orig pod that is being replaced):
```
 ERROR Encountered fatal fault: Unable to apply TopicRecord record at offset 163 on standby controller, from the batch with baseOffset 163 (org.apache.kafka.server.fault.ProcessTerminatingFaultHandler)
java.lang.RuntimeException: Found duplicate TopicRecord for __consumer_offsets with a different ID than before. Previous ID was 9Fnh47gNRKanoaLan949VQ and new ID is FF6E2w2aQkmXxoJI18fOqw
        at org.apache.kafka.controller.ReplicationControlManager.replay(ReplicationControlManager.java:443)
        at org.apache.kafka.controller.QuorumController.replay(QuorumController.java:1500)
        at org.apache.kafka.controller.QuorumController.access$1600(QuorumController.java:179)
        at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$handleCommit$0(QuorumController.java:1088)
        at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$appendRaftEvent$3(QuorumController.java:1197)
        at org.apache.kafka.controller.QuorumController$ControllerEvent.run(QuorumController.java:580)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:127)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:210)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:181)
        at java.base/java.lang.Thread.run(Thread.java:840)
[2024-09-03 08:24:33,693] ERROR Encountered fatal fault: Error loading metadata log record from offset 1351 (org.apache.kafka.server.fault.ProcessTerminatingFaultHandler)
java.lang.IllegalStateException: Tried to change broker 2, but that broker was not registered.
        at org.apache.kafka.image.ClusterDelta.getBrokerOrThrow(ClusterDelta.java:102)
        at org.apache.kafka.image.ClusterDelta.replay(ClusterDelta.java:133)
        at org.apache.kafka.image.MetadataDelta.replay(MetadataDelta.java:325)
        at org.apache.kafka.image.MetadataDelta.replay(MetadataDelta.java:230)
        at org.apache.kafka.image.loader.MetadataBatchLoader.replay(MetadataBatchLoader.java:257)
        at org.apache.kafka.image.loader.MetadataBatchLoader.loadBatch(MetadataBatchLoader.java:135)
        at org.apache.kafka.image.loader.MetadataLoader.lambda$handleCommit$1(MetadataLoader.java:361)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:127)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:210)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:181)
        at java.base/java.lang.Thread.run(Thread.java:840)


kafka partition reassignment log:
this message is repeated
Creating reassignment JSON for existing partitions of topic: xc-cm-onboard-finished
Error: Unknown broker id 1
org.apache.kafka.server.common.AdminCommandFailedException: Unknown broker id 1
        at org.apache.kafka.tools.reassign.ReassignPartitionsCommand.verifyBrokerIds(ReassignPartitionsCommand.java:887)
        at org.apache.kafka.tools.reassign.ReassignPartitionsCommand.executeAssignment(ReassignPartitionsCommand.java:747)
        at org.apache.kafka.tools.reassign.ReassignPartitionsCommand.handleAction(ReassignPartitionsCommand.java:172)
        at org.apache.kafka.tools.reassign.ReassignPartitionsCommand.main(ReassignPartitionsCommand.java:14
```

**Comment by MikeNikolayev** [comment]
adding more logs from latest test. this error is seen exactly once the problematic pod-0 is replaced by a new pod-0
[2024-09-04 10:52:27,447] INFO [QuorumController id=0] registerBroker: event failed with NotControllerException in 79 microseconds. Exception message: The active controller appears to be node 0. (org.apache.kafka.controller.QuorumController)
[2024-09-04 10:52:27,447] INFO [QuorumController id=0] createTopics: event failed with NotControllerException in 33 microseconds. Exception message: The active controller appears to be node 0. (org.apache.kafka.controller.QuorumController)
[2024-09-04 10:52:27,448] INFO [QuorumController id=0] registerController: event failed with NotControllerException in 30 microseconds. Exception message: The active controller appears to be node 0. (org.apache.kafka.controller.QuorumController)
[2024-09-04 10:52:27,448] INFO [NodeToControllerChannelManager id=0 name=heartbeat] Client requested disconnect from node 0 (org.apache.kafka.clients.NetworkClient)
[2024-09-04 10:52:27,448] INFO [broker-0-to-controller-heartbeat-channel-manager]: Recorded new KRaft controller, from now on will use node kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9093 (id: 0 rack: null) (kafka.server.NodeToControllerRequestThread)
[2024-09-04 10:52:27,451] ERROR [ControllerApis nodeId=0] Unexpected error handling request RequestHeader(apiKey=CONTROLLER_REGISTRATION, apiVersion=0, clientId=0, correlationId=0, headerVersion=2) -- ControllerRegistrationRequestData(controllerId=0, incarnationId=xD6xok2URHqlhn5j-ozshQ, zkMigrationReady=false, listeners=[Listener(name='CONTROLLER', host='kafka-controller-0.kafka-controller-headless.default.svc.cluster.local', port=9093, securityProtocol=0)], features=[Feature(name='metadata.version', minSupportedVersion=1, maxSupportedVersion=19)]) with context RequestContext(header=RequestHeader(apiKey=CONTROLLER_REGISTRATION, apiVersion=0, clientId=0, correlationId=0, headerVersion=2), connectionId='100.76.0.63:9093-100.76.0.63:53842-3', clientAddress=/100.76.0.63, principal=User:ANONYMOUS, listenerName=ListenerName(CONTROLLER), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=apache-kafka-java, softwareVersion=3.7.1), fromPrivilegedListener=false, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@3a345c1d]) (kafka.server.ControllerApis)
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.NotControllerException: The active controller appears to be node 0.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at org.apache.kafka.controller.QuorumController$ControllerWriteEvent.complete(QuorumController.java:880)
        at org.apache.kafka.controller.QuorumController$ControllerWriteEvent.handleException(QuorumController.java:871)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.completeWithException(KafkaEventQueue.java:148)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:137)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:210)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:181)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.kafka.common.errors.NotControllerException: The active controller appears to be node 0.


and in next minute
[2024-09-04 10:53:34,927] INFO [QuorumController id=0] alterPartitionReassignments: event failed with NotControllerException in 71 microseconds. Exception message: The active controller appears to be node 2. (org.apache.kafka.controller.QuorumController)
[2024-09-04 10:53:34,928] ERROR [ControllerApis nodeId=0] Unexpected error handling request Forwarded request: RequestContext(header=RequestHeader(apiKey=ENVELOPE, apiVersion=0, clientId=2, correlationId=4469, headerVersion=2), connectionId='100.76.0.63:9093-100.76.0.63:56166-5', clientAddress=/100.76.0.63, principal=User:ANONYMOUS, listenerName=ListenerName(CONTROLLER), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=apache-kafka-java, softwareVersion=3.7.1), fromPrivilegedListener=false, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@7ec38d3]) RequestHeader(apiKey=ALTER_PARTITION_REASSIGNMENTS, apiVersion=0, clientId=reassign-partitions-tool, correlationId=6, headerVersion=2) -- AlterPartitionReassignmentsRequestData(timeoutMs=30000, topics=[ReassignableTopic(name='CMFinalizeUpgrade', partitions=[ReassignablePartition(partitionIndex=0, replicas=[0, 1, 2]), ReassignablePartition(partitionIndex=1, replicas=[0, 1, 2]), ReassignablePartition(partitionIndex=2, replicas=[0, 1, 2])])]) with context RequestContext(header=RequestHeader(apiKey=ALTER_PARTITION_REASSIGNMENTS, apiVersion=0, clientId=reassign-partitions-tool, correlationId=6, headerVersion=2), connectionId='100.76.0.63:9093-100.76.0.63:56166-5', clientAddress=/100.76.1.12, principal=User:ANONYMOUS, listenerName=ListenerName(CONTROLLER), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=unknown, softwareVersion=unknown), fromPrivilegedListener=false, principalSerde=Optional.empty) (kafka.server.ControllerApis)
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.NotControllerException: The active controller appears to be node 2.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at kafka.server.ControllerApis.handleAlterPartitionReassignments(ControllerApis.scala:876)
        at kafka.server.ControllerApis.handle(ControllerApis.scala:112)
        at kafka.server.ControllerApis.$anonfun$handleEnvelopeRequest$1(ControllerApis.scala:166)
        at kafka.server.ControllerApis.$anonfun$handleEnvelopeRequest$1$adapted(ControllerApis.scala:166)
        at kafka.server.EnvelopeUtils$.handleEnvelopeRequest(EnvelopeUtils.scala:66)
        at kafka.server.ControllerApis.handleEnvelopeRequest(ControllerApis.scala:166)
        at kafka.server.ControllerApis.handle(ControllerApis.scala:118)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:160)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.kafka.common.errors.NotControllerException: The active controller appears to be node 2.

**Comment by dgomezleon** [comment]
Hi @MikeNikolayev,

I could not reproduce the issue on GKE (unfortunately, I'm unfamiliar with k3s).

I would like to know if the issue also happens if all the nodes are already created and you install Kafka and then upgrade it since I don't see the connection. Do you see any difference depending on the node where the pod is running?

**Comment by MikeNikolayev** [comment]
thank you for your answer, David.
I think the key issue is that once I upgrade from 1 to 3 pods, I have 1 minute timeout and then I start running the partition reassignment script job. It could be, that I should wait more. 
if I request anything while brokers are still not in full healthy quorum - that causes a split brain and it is never fixed  without manual intervention.
I wonder what is your opinion?

**Comment by MikeNikolayev** [comment]
That's a good question.
When system is not serving any traffic, a reasonable timeout would help probably.

But do you know what is the best production practice for partitions reassignment in case of high loads of traffic? 
Should the script be ran as post helm upgrade or should it be ran separately, maybe even manually not to stuck the whole product ?

**Comment by dgomezleon** [comment]
Hi @MikeNikolayev 
I would suggest do not run partition reassignment automatically as part of Helm upgrades. It could overwhelm the system, leading to potential outages or degraded performance. It’s better to decouple this from Helm upgrades.

 I consider running the partition reassignment as a separate manual or orchestrated process during off-peak hours is better.
