### ISSUE TITLE
[bitnami/opensearch] Can't install plugins

### ISSUE THREAD

**Issue by hnc-lcy9104** [bitnami/charts#29498]
### Name and Version

bitnami/opensearch 1.2.10

### What architecture are you using?

None

### What steps will reproduce the bug?

1. In this environment: aws eks v1.30. 
2. With this config: plugins: repository-s3

### Are you using any custom parameters or values?
```
values = [
  <<-EOT
    ......
    plugins: repository-s3
    ......
  EOT
]
```
### What is the expected behavior?

Install plugins.

### What do you see instead?

I added plugins: repository-s3 to the values.yaml that was working fine, but a new pod is not being created. After removing plugins: repository-s3 from values.yaml and running opensearch-plugin install repository-s3 by executing into the pod with exec bash, I got the following result:
opensearch-plugin install repository-s3
```
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
[=================================================] 100%??
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission config#plus read
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.NetPermission setDefaultAuthenticator
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission aws.configFile read,write
* java.util.PropertyPermission aws.sharedCredentialsFile read,write
* java.util.PropertyPermission opensearch.allow_insecure_settings read,write
* java.util.PropertyPermission opensearch.path.conf read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/opensearch/config/repository-s3: Operation not permitted
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:277)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:299)
    at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2167)
    at org.opensearch.plugins.InstallPluginCommand.setFileAttributes(InstallPluginCommand.java:1022)
    at org.opensearch.plugins.InstallPluginCommand.installConfig(InstallPluginCommand.java:977)
    at org.opensearch.plugins.InstallPluginSupportFiles(InstallPluginCommand.java:913)
    at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:889)
    at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:276)
    at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)
    at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
    at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
    at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
    at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
    at org.opensearch.cli.Command.main(Command.java:101)
    at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

Also, according to [this link](https://github.com/bitnami/containers/blob/main/bitnami/opensearch/README.md#plugins), it says, "The Bitnami OpenSearch Docker image comes with the S3 Repository plugin installed by default," so shouldn’t the repository-s3 plugin already be installed?

However, when I run the opensearch-plugin list command, it is not listed.

**Comment by juan131** [comment]
Hi @hnc-lcy9104 

I was able to reproduce the issue with that particular plugin, but I was able to install other plugins (e.g. `analysis-icu`). It looks like the issue you're facing is related to filesystem permissions, under investigation.

> Also, according to [this link](https://github.com/bitnami/containers/blob/main/bitnami/opensearch/README.md#plugins), it says, "The Bitnami OpenSearch Docker image comes with the S3 Repository plugin installed by default," so shouldn’t the repository-s3 plugin already be installed?

This looks like a copy-paste error given OpenSearch's README was based on ElasticSearch one. As you can see in the logs below, if you try to install that plugin using ElasticSearch you find a warning saying it's already packaged:

```console
elasticsearch 11:15:18.74 DEBUG ==> Installing plugin: repository-s3
-> Installing repository-s3
[repository-s3] is no longer a plugin but instead a module packaged with this distribution of Elasticsearch
-> Please restart Elasticsearch to activate any plugins installed
```

I'll send a PR to amend it.

**Comment by juan131** [comment]
Hi @hnc-lcy9104 

It seems the issue is that this plugin's installation tries to change the permission for `/opt/bitnami/opensearch/config` (where we mount an emptyDir sub-folder to have write permissions, see https://github.com/bitnami/charts/blob/main/bitnami/opensearch/templates/master/statefulset.yaml#L263-L265) from `777` to `775`. However, this is not permitted given the restrictions in the default container security context:

```console
$ ls -la /opt/bitnami/opensearch/config
total 88
drwxrwsrwx 10 root 1001  4096 Sep 24 06:04 .
(...)
$ chmod 775 /opt/bitnami/opensearch/config
chmod: changing permissions of '/opt/bitnami/opensearch/config': Operation not permitted
```

Trying to figure out a workaround.

**Comment by juan131** [comment]
I just sent a PR that addresses the issue @hnc-lcy9104

**Comment by hnc-lcy9104** [comment]
I deployed using chart version 1.3.4, but the same error is still occurring.

**Comment by juan131** [comment]
Hi @hnc-lcy9104 

Could you please provide the chart parameters (provided via `values.yaml` or using the `--set` flag) you used to install your Helm release? Please exclusively provide the parameters you customized avoiding the ones with default values.

> Note: you can easily obtain the above parameters using `helm get values RELEASE_NAME`

Also, did you install Discourse on a "clean" environment (with no PVCs from previous releases)?

**Comment by hnc-lcy9104** [comment]
I was operating well with the following values.yaml configuration, and after adding only plugins: repository-s3 and deploying, it doesn't work.


extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: custom-roles
      namespace: {{ include "common.names.namespace" . | quote }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
    data:
      roles.yml: |-
        # Add custom content to the /opt/bitnami/opensearch/config.default/opensearch-security/roles.yml file.
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: custom-roles-mapping
      namespace: {{ include "common.names.namespace" . | quote }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
    data:
      roles_mapping.yml: |-
        # Add custom content to the /opt/bitnami/opensearch/config.default/opensearch-security/roles_mapping.ymlfile.
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: custom-tenants
      namespace: {{ include "common.names.namespace" . | quote }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
    data:
      tenants.yml: |-
        # Add custom content to the /opt/bitnami/opensearch/config.default/opensearch-security/tenants.yml file.

  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: custom-security-config
      namespace: {{ include "common.names.namespace" . | quote }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
    data:
      config.yml: |-
        # Add custom content to the /opt/bitnami/opensearch/config.default/opensearch-security/config.yml file.
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: custom-dashboard
      namespace: {{ include "common.names.namespace" . | quote }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
    data:
      opensearch_dashboards.yml: |-
        # Add custom content to the /opt/bitnami/opensearch-dashboards/config/opensearch_dashboards.yml file.

clusterName: opensearch
extraConfig:
  plugins:
    security:
      restapi:
        roles_enabled: ["all_access", "security_rest_api_access"]
extraEnvVars:
  - name: TZ
    value: Asia/Seoul
  - name: KIBANA_PASSWORD
    value: xxxxxxxxxx
useIstioLabels: false
ingress:
  enabled: true
  # ......

security:
  enabled: true
  adminPassword: xxxxxxxxxx
  tls:
    restEncryption: true
master:
  pdb:
    minAvailable: 1
  resources:
    requests:
      cpu: 256m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 4Gi
  heapSize: 2048m
  persistence:
    storageClass: gp3
    size: 50Gi
  networkPolicy:
    enabled: false
  extraVolumeMounts:
    - name: custom-security-config
      mountPath: /opt/bitnami/opensearch/config.default/opensearch-security/config.yml
      subPath: config.yml
    - name: custom-roles
      mountPath: /opt/bitnami/opensearch/config.default/opensearch-security/roles.yml
      subPath: roles.yml
    - name: custom-roles-mapping
      mountPath: /opt/bitnami/opensearch/config.default/opensearch-security/roles_mapping.yml
      subPath: roles_mapping.yml
    - name: custom-tenants
      mountPath: /opt/bitnami/opensearch/config.default/opensearch-security/tenants.yml
      subPath: tenants.yml
  extraVolumes:
    - name: custom-security-config
      configMap:
        name: custom-security-config
    - name: custom-roles
      configMap:
        name: custom-roles
    - name: custom-roles-mapping
      configMap:
        name: custom-roles-mapping
    - name: custom-tenants
      configMap:
        name: custom-tenants
data:
  replicaCount: 3
  pdb:
    minAvailable: 1
  resources:
    requests:
      cpu: 256m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 4Gi
  heapSize: 2048m
  persistence:
    storageClass: gp3
    size: 500Gi
  networkPolicy:
    enabled: false

coordinating:
  pdb:
    minAvailable: 1
  resources:
    requests:
      cpu: 256m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 4Gi
  heapSize: 2048m
  networkPolicy:
    enabled: false

ingest:
  enabled: false

sysctlImage:
  enabled: true

dashboards:
  enabled: true
  password: xxxxxxxxxx
  ingress:
    enabled: true
    # ......
  replicaCount: 2
  pdb:
    minAvailable: 1
  resources:
    requests:
      cpu: 128m
      memory: 256Mi
    limits:
      cpu: 512m
      memory: 1024Mi
  heapSize: 256m
  extraEnvVars:
    - name: TZ
      value: Asia/Seoul
  extraVolumeMounts:
    - name: custom-dashboard
      mountPath: /opt/bitnami/opensearch-dashboards/config/opensearch_dashboards.yml
      subPath: opensearch_dashboards.yml
  extraVolumes:
    - name: custom-dashboard
      configMap:
        name: custom-dashboard
  persistence:
    enabled: true
    storageClass: efs
  networkPolicy:
    enabled: false

**Comment by juan131** [comment]
Thanks @hnc-lcy9104 !

Could you install OpenSearch setting the parameter `image.debug` to `true` (this will increase the container logs verbosity) and share the container logs on failing pods?

**Comment by hnc-lcy9104** [comment]
Here are the logs after applying the requested configuration.
```
opensearch 14:57:18.93 INFO  ==> 
opensearch 14:57:18.93 INFO  ==> Welcome to the Bitnami opensearch container
opensearch 14:57:18.93 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
opensearch 14:57:18.93 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
opensearch 14:57:18.94 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
opensearch 14:57:18.94 INFO  ==> 
opensearch 14:57:18.94 DEBUG ==> Copying files from /opt/bitnami/opensearch/config.default to /opt/bitnami/opensearch/config
opensearch 14:57:18.95 DEBUG ==> Copying plugins from /opt/bitnami/opensearch/plugins.default to /opt/bitnami/opensearch/plugins
opensearch 14:57:18.99 INFO  ==> ** Starting Opensearch setup **
opensearch 14:57:19.01 DEBUG ==> Ensuring expected directories/files exist...
opensearch 14:57:19.02 DEBUG ==> Validating settings in DB_* env vars...
opensearch 14:57:19.03 INFO  ==> Configuring/Initializing Opensearch...
opensearch 14:57:19.04 DEBUG ==> Ensuring expected directories/files exist...
opensearch 14:57:19.06 DEBUG ==> Using specified values for Xmx and Xms heap options...
opensearch 14:57:19.06 DEBUG ==> Setting '-Xmx2048m -Xms2048m' heap options...
opensearch 14:57:19.06 INFO  ==> Setting default configuration
opensearch 14:57:19.09 INFO  ==> Configuring Opensearch cluster settings...
opensearch 14:57:19.20 DEBUG ==> Configure Opensearch Node roles...
opensearch 14:57:19.21 INFO  ==> Adding custom configuration
opensearch 14:57:19.22 INFO  ==> Configuring Opensearch security plugin
opensearch 14:57:19.27 INFO  ==> Configuring OPENSEARCH HTTP TLS settings...
opensearch 14:57:19.28 DEBUG ==> Configuring REST API TLS settings using PEM certificates...
opensearch 14:57:19.31 INFO  ==> Configuring Opensearch Transport TLS settings...
opensearch 14:57:19.33 DEBUG ==> Configuring Transport Layer TLS settings using PEM certificates...
opensearch 14:57:19.36 INFO  ==> Configuring Opensearch security users and roles...
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
opensearch 14:57:23.92 DEBUG ==> Validating Kernel settings...
opensearch 14:57:23.93 DEBUG ==> Custom index.store.type found in the config file. Skipping kernel validation...
opensearch 14:57:23.93 DEBUG ==> Custom node.store.allow_mmap found in the config file. Skipping kernel validation...
opensearch 14:57:23.94 DEBUG ==> Installing plugins: repository-s3
opensearch 14:57:23.95 DEBUG ==> Installing plugin: repository-s3
-> Installing repository-s3
Checking if url exists: https://artifacts.opensearch.org/releases/plugins/repository-s3/2.17.0/repository-s3-linux-x64-2.17.0.zip
-> Downloading repository-s3 from opensearch
Retrieving zip from https://artifacts.opensearch.org/releases/plugins/repository-s3/2.17.0/repository-s3-2.17.0.zip
- Plugin information:
Name: repository-s3
Description: The S3 repository plugin adds S3 repositories
Version: 2.17.0
OpenSearch Version: 2.17.0
Java Version: 11
Native Controller: false
Extended Plugins: []
 * Classname: org.opensearch.repositories.s3.S3RepositoryPlugin
Folder name: 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission config#plus read
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.NetPermission setDefaultAuthenticator
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission aws.configFile read,write
* java.util.PropertyPermission aws.sharedCredentialsFile read,write
* java.util.PropertyPermission opensearch.allow_insecure_settings read,write
* java.util.PropertyPermission opensearch.path.conf read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/opensearch/config/repository-s3: Operation not permitted
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:277)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:299)
    at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2167)
    at org.opensearch.plugins.InstallPluginCommand.setFileAttributes(InstallPluginCommand.java:1022)
    at org.opensearch.plugins.InstallPluginCommand.installConfig(InstallPluginCommand.java:977)
    at org.opensearch.plugins.InstallPluginCommand.installPluginSupportFiles(InstallPluginCommand.java:913)
    at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:889)
    at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:276)
    at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)
    at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
    at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
    at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
    at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
    at org.opensearch.cli.Command.main(Command.java:101)
    at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

**Comment by juan131** [comment]
Hm.. It looks like the permissions issue still there. Could you do a `kubectl describe` of that same pod and share the output? Thanks

**Comment by hnc-lcy9104** [comment]
```
# .......
Init Containers:
  sysctl:
    Container ID:  containerd://cb589c125d5dba4f8d4efe9d88acfbcb05f20ff59ceced03be637a482e605183
    Image:         docker.io/bitnami/os-shell:12-debian-12-r30
    Image ID:      docker.io/bitnami/os-shell@sha256:196fd17303203b1d838572472e0dd6820a019db659fa7cdae4b8af809a0c8390
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -ec
      CURRENT=`sysctl -n vm.max_map_count`;
      DESIRED="262144";
      if [ "$DESIRED" -gt "$CURRENT" ]; then
          sysctl -w vm.max_map_count=262144;
      fi;
      CURRENT=`sysctl -n fs.file-max`;
      DESIRED="65536";
      if [ "$DESIRED" -gt "$CURRENT" ]; then
          sysctl -w fs.file-max=65536;
      fi;
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 25 Sep 2024 15:38:34 +0900
      Finished:     Wed, 25 Sep 2024 15:38:34 +0900
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:                150m
      ephemeral-storage:  2Gi
      memory:             192Mi
    Requests:
      cpu:                100m
      ephemeral-storage:  50Mi
      memory:             128Mi
    Environment:          <none>
    Mounts:               <none>
  copy-default-plugins:
    Container ID:  containerd://be4eb7a839cb314d7c1360f0bbb9e40c30a2d663b9d1524be663cf8b6e3d8b77
    Image:         docker.io/bitnami/opensearch:2.17.0-debian-12-r1
    Image ID:      docker.io/bitnami/opensearch@sha256:095232e39b069416084facc946d285b1524de1c0ea4bb2402312921bdc284f60
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
    Args:
      -ec
      . /opt/bitnami/scripts/liblog.sh
      . /opt/bitnami/scripts/libfs.sh
      . /opt/bitnami/scripts/opensearch-env.sh
      
      mkdir -p /emptydir/app-conf-dir /emptydir/app-plugins-dir
      info "Copying directories to empty dir"
      # In order to not break plugins installation we need to make the conf directory
      # writable, so we need to copy it to an empty dir volume
      cp -r --preserve=mode /opt/bitnami/opensearch/config /emptydir/app-conf-dir
      
      if ! is_dir_empty "$DB_DEFAULT_PLUGINS_DIR"; then
          info "Copying default plugins"
          cp -nr "$DB_DEFAULT_PLUGINS_DIR"/* /emptydir/app-plugins-dir
      fi
      
      chown -R 1001:1001 /emptydir/app-conf-dir /emptydir/app-plugins-dir
      
      info "Copy operation completed"
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 25 Sep 2024 15:38:35 +0900
      Finished:     Wed, 25 Sep 2024 15:38:36 +0900
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  4Gi
    Requests:
      cpu:        256m
      memory:     2Gi
    Environment:  <none>
    Mounts:
      /emptydir from empty-dir (rw)
Containers:
  opensearch:
    Container ID:    containerd://05a79fda89242526370799b76684288381e53644d3dfb450eded8fa8e35d49c8
    Image:           docker.io/bitnami/opensearch:2.17.0-debian-12-r1
    Image ID:        docker.io/bitnami/opensearch@sha256:095232e39b069416084facc946d285b1524de1c0ea4bb2402312921bdc284f60
    Ports:           9200/TCP, 9300/TCP
    Host Ports:      0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    Command:
      bash
      -ec
      if [[ "$MY_POD_NAME" =~ -0$ ]]; then
        export OPENSEARCH_SECURITY_BOOTSTRAP=true
        # Opensearch securityadmin.sh requires the admin.key to be in PKCS8 format
        openssl pkcs8 -topk8 -nocrypt -in "/opt/bitnami/opensearch/config/certs/admin.key" > "/opt/bitnami/opensearch/config/admin.key"
        export OPENSEARCH_SECURITY_ADMIN_KEY_LOCATION="/opt/bitnami/opensearch/config/admin.key"
      fi
      /opt/bitnami/scripts/opensearch/entrypoint.sh /opt/bitnami/scripts/opensearch/run.sh
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 25 Sep 2024 15:39:19 +0900
      Finished:     Wed, 25 Sep 2024 15:39:28 +0900
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     1
      memory:  4Gi
    Requests:
      cpu:      256m
      memory:   2Gi
    Liveness:   tcp-socket :rest-api delay=90s timeout=5s period=10s #success=1 #failure=5
    Readiness:  exec [/opt/bitnami/scripts/opensearch/healthcheck.sh] delay=90s timeout=5s period=10s #success=1 #failure=5
    Environment:
      BITNAMI_DEBUG:                     true
      MY_POD_NAME:                       opensearch-master-1 (v1:metadata.name)
      OPENSEARCH_IS_DEDICATED_NODE:      yes
      OPENSEARCH_NODE_ROLES:             master
      OPENSEARCH_TRANSPORT_PORT_NUMBER:  9300
      OPENSEARCH_HTTP_PORT_NUMBER:       9200
      OPENSEARCH_CLUSTER_NAME:           opensearch
      OPENSEARCH_CLUSTER_HOSTS:          opensearch-master-hl.log-stack.svc.cluster.local,opensearch-coordinating-hl.log-stack.svc.cluster.local,opensearch-data-hl.log-stack.svc.cluster.local,
      OPENSEARCH_TOTAL_NODES:            5
      OPENSEARCH_CLUSTER_MASTER_HOSTS:   opensearch-master-0 opensearch-master-1
      OPENSEARCH_MINIMUM_MASTER_NODES:   2
      OPENSEARCH_ADVERTISED_HOSTNAME:    $(MY_POD_NAME).opensearch-master-hl.log-stack.svc.cluster.local
      OPENSEARCH_PLUGINS:                repository-s3
      OPENSEARCH_HEAP_SIZE:              2048m
      OPENSEARCH_SECURITY_NODES_DN:      CN=opensearch-master;CN=opensearch-data;CN=opensearch-coordinating
      OPENSEARCH_SECURITY_ADMIN_DN:      CN=admin;CN=admin
      OPENSEARCH_ENABLE_SECURITY:        true
      OPENSEARCH_PASSWORD:               <set to the key 'opensearch-password' in secret 'opensearch'>             Optional: false
      OPENSEARCH_DASHBOARDS_PASSWORD:    <set to the key 'opensearch-dashboards-password' in secret 'opensearch'>  Optional: false
      LOGSTASH_PASSWORD:                 <set to the key 'logstash-password' in secret 'opensearch'>               Optional: false
      OPENSEARCH_ENABLE_FIPS_MODE:       false
      OPENSEARCH_TLS_VERIFICATION_MODE:  full
      OPENSEARCH_ENABLE_REST_TLS:        true
      OPENSEARCH_TLS_USE_PEM:            true
      TZ:                                Asia/Seoul
      KIBANA_PASSWORD:                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Mounts:
      /bitnami/opensearch/data from data (rw)
      /opt/bitnami/opensearch/config from empty-dir (rw,path="app-conf-dir")
      /opt/bitnami/opensearch/config.default/opensearch-security/config.yml from custom-security-config (rw,path="config.yml")
      /opt/bitnami/opensearch/config.default/opensearch-security/roles.yml from custom-roles (rw,path="roles.yml")
      /opt/bitnami/opensearch/config.default/opensearch-security/roles_mapping.yml from custom-roles-mapping (rw,path="roles_mapping.yml")
      /opt/bitnami/opensearch/config.default/opensearch-security/tenants.yml from custom-tenants (rw,path="tenants.yml")
      /opt/bitnami/opensearch/config/certs from opensearch-certificates (ro)
      /opt/bitnami/opensearch/config/my_opensearch.yml from config (rw,path="my_opensearch.yml")
      /opt/bitnami/opensearch/config/repository-s3 from empty-dir (rw,path="repository-s3")
      /opt/bitnami/opensearch/logs from empty-dir (rw,path="app-logs-dir")
      /opt/bitnami/opensearch/plugins from empty-dir (rw,path="app-plugins-dir")
      /opt/bitnami/opensearch/tmp from empty-dir (rw,path="app-tmp-dir")
      /tmp from empty-dir (rw,path="tmp-dir")
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-opensearch-master-1
    ReadOnly:   false
  empty-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      opensearch
    Optional:  false
  opensearch-certificates:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          opensearch-master-crt
    SecretOptionalName:  <nil>
    SecretName:          opensearch-admin-crt
    SecretOptionalName:  <nil>
  custom-security-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      custom-security-config
    Optional:  false
  custom-roles:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      custom-roles
    Optional:  false
  custom-roles-mapping:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      custom-roles-mapping
    Optional:  false
  custom-tenants:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        custom-tenants
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```

**Comment by juan131** [comment]
Hi @hnc-lcy9104 

It seems you're mounting an empty-dir volume at `/opt/bitnami/opensearch/config/repository-s3`:

```console
    Mounts:
      (...)
      /opt/bitnami/opensearch/config/repository-s3 from empty-dir (rw,path="repository-s3")
```

Is this a customization you added via `extraVolumeMounts` parameter or similar? I'd expect you to have the mount below instead:

```
    Mounts:
      (...)
      /opt/bitnami/opensearch/config from empty-dir (rw,path="app-conf-dir")
```

**Comment by hnc-lcy9104** [comment]
I apologize. I had previously tried various things when the plugin installation didn't work, and some settings were left behind. It is now working properly. Thank you so much!

**Comment by hnc-lcy9104** [comment]
It’s not working after the commit https://github.com/bitnami/charts/commit/bc87c424bd5584e4735e7b4539a542f9e59aa0dc.

**Comment by ShivakumarAmbigiTR** [comment]
Could you please let me know what change worked finally for you?
