### ISSUE TITLE
Deployment Hangs because Postgresql Database Security Options do not perform as expected

### ISSUE THREAD

**Issue by Malachyiii** [bitnami/charts#30301]
### Name and Version

bitnami/jupyterhub

### What architecture are you using?

-Deployed from gitlab using ArgoCD GUI

### What steps will reproduce the bug?

Part 1
1. Deploy the app with  no `postgresql` settings and a Persistent Volume Claim
2. Update the app and sync it
3. App attempts to use the old generated Secret but expects the new secret

Part 2
1. Create a kubernetes secret in the namespace
2. Add the new secret to the values.yaml file under 
```
  postgresql:
    enabled: true
    auth:
      username: bn_jupyterhub
      existingSecret: "secretname"
```
3. update app

Part 3
1. Add a username and password to values.yaml under
```
 postgresql:
    enabled: true
    auth:
      username: bn_jupyterhub
      password: "password"
```
2. update app

### Are you using any custom parameters or values?

Given that the following is hardcoded in the config 

```
def _load_config():
    """Load the Helm chart configuration used to render the Helm templates of
    the chart from a mounted k8s Secret, and merge in values from an optionally
    mounted secret (hub.existingSecret)."""

    cfg = {}
    for source in ("secret/values.yaml", "existing-secret/values.yaml"):
        path = f"/usr/local/etc/jupyterhub/{source}"
        if os.path.exists(path):
            print(f"Loading {path}")
            with open(path) as f:
                values = yaml.safe_load(f)
            cfg = _merge_dictionaries(cfg, values)
        else:
            print(f"No config at {path}")
    return cfg
```

The following might be relevant (this is REQUIRED by our setup)

```
extraEnvVars:     
      - name: HOME
        value: "/tmp"
      - name: JUPYTER_RUNTIME_DIR
        value: "/tmp/jupyter/runtime"
      - name: JUPYTER_DATA_DIR
        value: "/tmp/jupyter/data"
      - name: JUPYTER_CONFIG_DIR
        value: "/tmp/jupyter/config"
      - name: IPYTHONDIR
        value: "/tmp/ipython"
```

### What is the expected behavior?

1. Changes to the app update successfully and do not cause it to stop.
2. Secret specified in the values.yaml is used by the app
3. User name and password specified in the values.yaml file used in the app

### What do you see instead?

For part 1:
Hub pod hangs as it tries repeatedly and unsuccessfully to log in to postgresql pod with the wrong credentials

For parts 2 and 3:

```
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[I 2024-11-07 12:40:33.957 JupyterHub app:2885] Running JupyterHub version 4.1.6
[I 2024-11-07 12:40:33.957 JupyterHub app:2915] Using Authenticator: nativeauthenticator.nativeauthenticator.NativeAuthenticator
[I 2024-11-07 12:40:33.957 JupyterHub app:2915] Using Spawner: kubespawner.spawner.KubeSpawner-6.2.0
[I 2024-11-07 12:40:33.958 JupyterHub app:2915] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-4.1.6
[E 2024-11-07 12:40:33.976 JupyterHub app:3408]
    Traceback (most recent call last):
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/app.py", line 3405, in launch_instance_async
        await self.initialize(argv)
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/app.py", line 2927, in initialize
        self.init_db()
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/app.py", line 1854, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/dbutil.py", line 113, in upgrade_if_needed
        orm.check_db_revision(engine)
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/orm.py", line 981, in check_db_revision
        current_table_names = set(inspect(engine).get_table_names())
                                  ^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/inspection.py", line 140, in inspect
        ret = reg(subject)
              ^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 312, in _engine_insp
        return Inspector._construct(Inspector._init_engine, bind)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 245, in _construct
        init(self, bind)
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 256, in _init_engine
        engine.connect().close()
        ^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
        return self._connection_cls(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
        Connection._handle_dbapi_exception_noconnection(
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2442, in _handle_dbapi_exception_noconnection
        raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
        self._dbapi_connection = engine.raw_connection()
                                 ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
        return self.pool.connect()
               ^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
        return _ConnectionFairy._checkout(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
        rec = pool._do_get()
              ^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
        with util.safe_reraise():
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
        return self._create_connection()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
        return _ConnectionRecord(self)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
        self.__connect()
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
        with util.safe_reraise():
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
        self.dbapi_connection = connection = pool._invoke_creator(self)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
        return dialect.connect(*cargs, **cparams)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
        return self.loaded_dbapi.connect(*cargs, **cparams)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
    (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Additional information

Documentation is extremely unclear for someone who is just starting out. Behavior is very unexpected. Why does the setup default to failure and not default to something stable with updates? Extremely unclear how to remedy the issue. Extremely unclear logs. 

The [troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues) specified only tells us how to solve the for a single time (roll back and get the old credentials or delete the PVC and start again) **but does not specify how to permanently fix the issue**

**Comment by Malachyiii** [comment]
For people who are wondering, the answer is not in the jupyterhub repo, it is in the postgresql repo.

You need to specify the key names for the secret specifically (it does not recognize them automatically)

`  postgresql:
    auth:
        postgresPassword: "password"
        username: "bn_jupyterhub"
        password: "other password"
        existingSecret: "secretname"
        database: bitnami_jupyterhub
        secretKeys:
          adminPasswordKey: "postgres-password"
          userPasswordKey: "password"`
