### ISSUE TITLE
[bitnami/discourse] - Permission Denied when accessing /var/run/secrets/eks.amazonaws.com/serviceaccount/token

### ISSUE THREAD

**Issue by stevejr** [bitnami/charts#30825]
### Name and Version

bitnami/discourse:15.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Need an EKS cluster with an [IAM Roles For Service Accounts (IRSA)](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) created for the `discourse` Service Account
2. Optionally create an S3 bucket - not concerned with getting an error indicating it is missing as that would at least prove that Discourse has accessed AWS successfully
3. Deploy a new instance of discourse with chart version 15.0.5 but do not create the Service Account - use the one from step 1 above.
4. Add the env var `DISCOURSE_EXTRA_CONF_CONTENT` with the string `s3_use_iam_profile = true` which instructs Discourse to use an IAM profile when accessing S3
5. Add all other Discourse values for accessing S3 i.e `s3_bucket` etc 
6. Use the default Security Context values for the Containers and Pods

### What is the expected behavior?

Discourse should start and be able to access the defined S3 bucket

### What do you see instead?

Discourse fails to start and logs the following error:

```
Errno::EACCES: Permission denied @ rb_sysopen - /var/run/secrets/eks.amazonaws.com/serviceaccount/token (Errno::EACCES)
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:90:in `read'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:90:in `_token_from_file'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:74:in `refresh'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/refreshing_credentials.rb:28:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:64:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:152:in `new'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:152:in `assume_role_web_identity_credentials'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:13:in `block in resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/plugins/credentials_configuration.rb:73:in `block in <class:CredentialsConfiguration>'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:72:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:215:in `block in resolve_defaults'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:59:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:59:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:214:in `resolve_defaults'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:207:in `value_at'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:191:in `block in resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:191:in `resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:179:in `apply_defaults'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:152:in `build!'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/base.rb:65:in `build_config'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/base.rb:22:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.143.0/lib/aws-sdk-s3/client.rb:481:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/base.rb:102:in `new'
/opt/bitnami/discourse/lib/s3_helper.rb:392:in `init_aws_s3_client'
/opt/bitnami/discourse/lib/s3_helper.rb:285:in `s3_client'
/opt/bitnami/discourse/lib/s3_helper.rb:434:in `s3_resource'
/opt/bitnami/discourse/lib/s3_helper.rb:440:in `s3_bucket'
/opt/bitnami/discourse/lib/s3_helper.rb:70:in `upload'
/opt/bitnami/discourse/lib/file_store/s3_store.rb:118:in `store_file'
/opt/bitnami/discourse/lib/file_store/s3_store.rb:68:in `store_optimized_image'
/opt/bitnami/discourse/app/models/optimized_image.rb:120:in `block (2 levels) in create_for'
/opt/bitnami/discourse/app/models/optimized_image.rb:119:in `open'
/opt/bitnami/discourse/app/models/optimized_image.rb:119:in `block in create_for'
/opt/bitnami/discourse/app/models/optimized_image.rb:19:in `block (2 levels) in lock'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/app/models/optimized_image.rb:19:in `block in lock'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/app/models/optimized_image.rb:18:in `lock'
/opt/bitnami/discourse/app/models/optimized_image.rb:73:in `create_for'
/opt/bitnami/discourse/lib/site_icon_manager.rb:74:in `block in ensure_optimized!'
/opt/bitnami/discourse/lib/site_icon_manager.rb:70:in `each'
/opt/bitnami/discourse/lib/site_icon_manager.rb:70:in `ensure_optimized!'
/opt/bitnami/discourse/lib/tasks/db.rake:272:in `block (2 levels) in <main>'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/lib/tasks/db.rake:234:in `block in <main>'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:25:in `load'
/opt/bitnami/ruby/bin/bundle:25:in `<main>'
```

When accessing the Sidekiq container in the pod the default user is `root` which can read the file. If you `su - discourse` then you get the permission error.

### Additional information

Previous versions of Discourse are able to use an IAM Profile because they do not enforce a Security Context.

I have tried setting the Pod SecurityContext to have the `fsGroup` value set to `65534` but this still does not resolve the issue.

Please advise what the correct SecurityContext should be at both the Pod and Container level to allow the `discourse` user to be able to access the file.

**Comment by stevejr** [comment]
Is there any thoughts on how the permission error can be resolved as I assume we do need to use the Security Context.

We want to keep using the IAM Role but unless this can be fixed we will have to switch to a dedicated IAM User for Discourse which we really don't want to do.

**Comment by stevejr** [comment]
Is it possible to get an update on this issue? Thanks.

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

If you have any questions about the application, customizing its content, or using technology and infrastructure, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by jabinara** [comment]
Was this ever fixed? I am in the same boat.  I am using the eks cluster and started the discourse pod using root user(long story, I had to do this due to a bug in the container).  The pod's security context is root, hence the projected volume is mounted as root.  Unfortunately the backup runs as bn_discourse user and is not able to access `/var/run/secrets/eks.amazonaws.com/serviceaccount`. I cannot change the pod security context to this user.  If this doesn't work, I will have to do my own backups which will be sad :(

**Comment by powerpower2005** [comment]
Any Update for this issue?

**Comment by powerpower2005** [comment]
@jabinara 
I search the user of system of discourse and I found discourse user id 999

I update some values below

```yaml
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: OnRootMismatch
  sysctls: []
  supplementalGroups: []
  fsGroup: 999
```

And it works.
