### ISSUE TITLE
[bitnami/zookeeper] Replace liveliness and test probes with a proper zookeeper command

### ISSUE THREAD

**Issue by ddcprg** [bitnami/charts#3168]
**Which chart**:
bitnami/zookeeper

**Describe the bug**
Too many exception due to pod probes.

**To Reproduce**
Let the pods run for a bit and check the logs
```
<date> [myid:1] - WARN  [NIOWorkerThread-1:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /<IP>:<port>, session = 0x0
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**
No logs due to HC tests

**Version of Helm and Kubernetes**:
zookeeper-5.17.3

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
References:
- https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#testing-for-liveness
- https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#testing-for-readiness
- https://github.com/confluentinc/cp-docker-images/issues/358

**Comment by ddcprg** [comment]
We will be happy to contribute the patch if this is accepted

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input! Sounds good to me doing this change. Feel free to provide a PR and we will review it :)

**Comment by ddcprg** [comment]
thanks @javsalgar I'll try to push the patch today with some additional notes about deployment
