### ISSUE TITLE
Celery Task Timeout Error on worker for dynamic dags 

### ISSUE THREAD

**Issue by aditiagarwal30nov** [bitnami/charts#3181]
Setup:
Running Bitnami Debian 1.10.10 image on Azure Kubernetes Service
Using redis helm chart for celery executor
Connecting to Azure PostgresSQL basic tier database

Issue:
We are configuring a dag template which generates multiple dags based on python environment variable. The dags come up correctly, however, on triggering a new dag, the worker reports the following error:

```
[2020-07-17 09:28:29,544] {base_hook.py:84} INFO - Using connection to: id: phdh_mongo. Host: phdh-cosmos-db-uat.documents.azure.com, Port: 10255, Schema: phdh-uat, Login: phdh-cosmos-db-uat, Password: XXXXXXXX, extra: XXXXXXXX
[2020-07-17 09:28:29,803] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: hisg_temp_non_pii_dag.decompress_files_in_blob 2020-07-17T09:23:51.761685+00:00 [running]> release-name-airflow-worker-1.release-name-airflow-headless.default.svc.cluster.local
[2020-07-17 09:28:30,406] {base_hook.py:84} INFO - Using connection to: id: phdh_mongo. Host: phdh-cosmos-db-uat.documents.azure.com, Port: 10255, Schema: phdh-uat, Login: phdh-cosmos-db-uat, Password: XXXXXXXX, extra: XXXXXXXX
[2020-07-17 09:28:33,563] {timeout.py:42} ERROR - Process timed out, PID: 417
[2020-07-17 09:28:33,564] {dagbag.py:246} ERROR - Failed to import: /opt/bitnami/airflow/dags/multi_producer_dags.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/opt/bitnami/airflow/venv/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/multi_producer_dags.py", line 41, in <module>
    import_dynamic_dags()
  File "/opt/bitnami/airflow/dags/multi_producer_dags.py", line 37, in import_dynamic_dags
    schedule_interval=config["non_pii"]["schedule"],
  File "/opt/bitnami/airflow/dags/../dags/producer_dag_template.py", line 43, in create_producer_dag
    mongo_conn_id="phdh_mongo",
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/decorators.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/opt/bitnami/airflow/dags/../dags/operators/cosmos_db_get_ingestion_metadata_operator.py", line 19, in __init__
    self.mongo_hook = MongoHook(conn_id=mongo_conn_id)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/contrib/hooks/mongo_hook.py", line 44, in __init__
    self.connection = self.get_connection(conn_id)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 53, in _get_connections_from_db
    .filter(Connection.conn_id == conn_id)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3244, in all
    return list(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3403, in __iter__
    return self._execute_and_instances(context)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3425, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3440, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3418, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1133, in connection
    execution_options=execution_options,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1139, in _connection_for_bind
    engine, execution_options
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 432, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2251, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/timeout.py", line 43, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 417
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 37, in <module>
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 523, in run
    dag = get_dag(args)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 149, in get_dag
    'parse.'.format(args.dag_id))
airflow.exceptions.AirflowException: dag_id could not be found: spt_non_pii_dag. Either the dag did not exist or it failed to parse.
[2020-07-17 09:28:34,196: ERROR/ForkPoolWorker-15] execute_command encountered a CalledProcessError
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 67, in execute_command
    close_fds=True, env=env)
  File "/opt/bitnami/python/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['airflow', 'run', 'spt_non_pii_dag', 'read_ingest_config_push_to_xcom', '2020-07-17T09:27:43.904482+00:00', '--local', '--pool', 'default_pool', '-sd', '/opt/bitnami/airflow/dags/multi_producer_dags.py']' returned non-zero exit status 1.
[2020-07-17 09:28:34,199: ERROR/ForkPoolWorker-15] None
[2020-07-17 09:28:34,239: ERROR/ForkPoolWorker-15] Task airflow.executors.celery_executor.execute_command[53f35578-78ac-4a35-8f9b-30d6d603295d] raised unexpected: AirflowException('Celery command failed',)
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 67, in execute_command
    close_fds=True, env=env)
  File "/opt/bitnami/python/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['airflow', 'run', 'spt_non_pii_dag', 'read_ingest_config_push_to_xcom', '2020-07-17T09:27:43.904482+00:00', '--local', '--pool', 'default_pool', '-sd', '/opt/bitnami/airflow/dags/multi_producer_dags.py']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 72, in execute_command
    raise AirflowException('Celery command failed')
airflow.exceptions.AirflowException: Celery command failed
[2020-07-17 09:28:37,035] {decompress_files_operator.py:65} INFO - [DecompressFilesOperator][hisg][2020-07-16][092351761685] Searching for zip files at: hisg/uploads/2020-07-16, using blob: sstphdhuatsftpdata and container: sftp
[2020-07-17 09:28:37,100] {decompress_files_operator.py:91} INFO - [DecompressFilesOperator][hisg][2020-07-16][092351761685] No zip files found to decompress. Skipping stage...
{"asctime": "2020-07-17 09:28:42,044", "filename": "logging_mixin.py", "lineno": 112, "levelname": "INFO", "message": "[2020-07-17 09:28:42,044] {local_task_job.py:103} INFO - Task exited with return code 0", "dag_id": "hisg_temp_non_pii_dag", "task_id": "decompress_files_in_blob", "execution_date": "2020_07_17T09_23_51_761685", "try_number": "1"}
[2020-07-17 09:28:44,150: INFO/ForkPoolWorker-16] Task airflow.executors.celery_executor.execute_command[03a9c3ea-14dd-41d9-a8d6-aa86dfa35122] succeeded in 45.85219061298994s: None
[2020-07-17 09:38:09,619: INFO/MainProcess] Received task: airflow.executors.celery_executor.execute_command[1ba81df5-c16c-46f1-867d-fa0945b83c13]
[2020-07-17 09:38:09,621: INFO/ForkPoolWorker-15] Executing command in Celery: ['airflow', 'run', 'hisg_temp_non_pii_dag', 'update_ingest_config', '2020-07-17T09:23:51.761685+00:00', '--local', '--pool', 'default_pool', '-sd', '/opt/bitnami/airflow/dags/hisg_non_pii_dag.py']
end_of_log[2020-07-17 09:38:12,145] {settings.py:254} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=521
[2020-07-17 09:38:16,470] {__init__.py:51} INFO - Using executor CeleryExecutor
[2020-07-17 09:38:16,472] {dagbag.py:403} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/hisg_non_pii_dag.py
[2020-07-17 09:38:21,780] {base_hook.py:84} INFO - Using connection to: id: phdh_mongo. Host: phdh-cosmos-db-uat.documents.azure.com, Port: 10255, Schema: phdh-uat, Login: phdh-cosmos-db-uat, Password: XXXXXXXX, extra: XXXXXXXX
[2020-07-17 09:38:25,073] {base_hook.py:84} INFO - Using connection to: id: phdh_mongo. Host: phdh-cosmos-db-uat.documents.azure.com, Port: 10255, Schema: phdh-uat, Login: phdh-cosmos-db-uat, Password: XXXXXXXX, extra: XXXXXXXX
Running %s on host %s <TaskInstance: hisg_temp_non_pii_dag.update_ingest_config 2020-07-17T09:23:51.761685+00:00 [queued]> release-name-airflow-worker-1.release-name-airflow-headless.default.svc.cluster.local
{"asctime": "2020-07-17 09:38:32,184", "filename": "taskinstance.py", "lineno": 655, "levelname": "INFO", "message": "Dependencies all met for <TaskInstance: hisg_temp_non_pii_dag.update_ingest_config 2020-07-17T09:23:51.761685+00:00 [queued]>", "dag_id": "hisg_temp_non_pii_dag", "task_id": "update_ingest_config", "execution_date": "2020_07_17T09_23_51_761685", "try_number": "1"}
{"asctime": "2020-07-17 09:38:33,892", "filename": "taskinstance.py", "lineno": 655, "levelname": "INFO", "message": "Dependencies all met for <TaskInstance: hisg_temp_non_pii_dag.update_ingest_config 2020-07-17T09:23:51.761685+00:00 [queued]>", "dag_id": "hisg_temp_non_pii_dag", "task_id": "update_ingest_config", "execution_date": "2020_07_17T09_23_51_761685", "try_number": "1"}
{"asctime": "2020-07-17 09:38:33,893", "filename": "taskinstance.py", "lineno": 866, "levelname": "INFO", "message": "\n--------------------------------------------------------------------------------", "dag_id": "hisg_temp_non_pii_dag", "task_id": "update_ingest_config", "execution_date": "2020_07_17T09_23_51_761685", "try_number": "1"}
{"asctime": "2020-07-17 09:38:33,893", "filename": "taskinstance.py", "lineno": 867, "levelname": "INFO", "message": "Starting attempt 1 of 1", "dag_id": "hisg_temp_non_pii_dag", "task_id": "update_ingest_config", "execution_date": "2020_07_17T09_23_51_761685", "try_number": "1"}
{"asctime": "2020-07-17 09:38:33,893", "filename": "taskinstance.py", "lineno": 868, "levelname": "INFO", "message": "\n--------------------------------------------------------------------------------", "dag_id": "hisg_temp_non_pii_dag", "task_id": "update_ingest_config", "execution_date": "2020_07_17T09_23_51_761685", "try_number": "1"}
{"asctime": "2020-07-17 09:38:35,312", "filename": "taskinstance.py", "lineno": 887, "levelname": "INFO", "message": "Executing <Task(CosmosDBUpdateIngestionMetadataOperator): update_ingest_config> on 2020-07-17T09:23:51.761685+00:00", "dag_id": "hisg_temp_non_pii_dag", "task_id": "update_ingest_config", "execution_date": "2020_07_17T09_23_51_761685", "try_number": "1"}
```

**Comment by andresbono** [comment]
Hi @aditiagarwal30nov, the logs say:

```
Failed to import: /opt/bitnami/airflow/dags/multi_producer_dags.py
```

Does the file exist in the worker container?

**Comment by aditiagarwal30nov** [comment]
Thank you for your response. We found the issue was related to the `dag_import_timeout` which was set to 30 seconds. If the dag did not get imported in that much time the task was being killed.
