### ISSUE TITLE
Airflow worker failed to start due to error OSError(12, 'Cannot allocate memory'

### ISSUE THREAD

**Issue by BigFatDog** [bitnami/charts#3392]
**Which chart**:
the latest bitnami/airflow

**Describe the bug**
airflow worker cannot start due to OSError: [Errno 12] Cannot allocate memory

**To Reproduce**
1. deploy airflow to k8s
2. use external redis and postgresql
3.  Only the worker statefulset fails to start. I can see it connects to redis and postgresql.
4. I see the error message:

```
/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is

absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=1001 euid=1001 gid=0 egid=0

uid=uid, euid=euid, gid=gid, egid=egid,

[2020-08-11 20:31:11,637: CRITICAL/MainProcess] Unrecoverable error: OSError(12, 'Cannot allocate memory')

Traceback (most recent call last):

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 208, in start

self.blueprint.start(self)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start

step.start(parent)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start

return self.obj.start()

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/concurrency/base.py", line 132, in start

self.on_start()

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 117, in on_start

**self.options)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 486, in __init__

super(AsynPool, self).__init__(processes, *args, **kwargs)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/billiard/pool.py", line 1046, in __init__

self._create_worker_process(i)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 503, in _create_worker_process

return super(AsynPool, self)._create_worker_process(i)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/billiard/pool.py", line 1158, in _create_worker_process

w.start()

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/billiard/process.py", line 124, in start

self._popen = self._Popen(self)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen

return Popen(process_obj)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__

self._launch(process_obj)

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/billiard/popen_fork.py", line 72, in _launch

self.pid = os.fork()

OSError: [Errno 12] Cannot allocate memory

-------------- celery@airflow-worker-0 v4.4.6 (cliffs)

--- ***** -----

-- ******* ---- Linux-4.15.0-55-generic-x86_64-with-debian-10.5 2020-08-11 20:31:01

- *** --- * ---

- ** ---------- [config]

- ** ---------- .> app: airflow.executors.celery_executor:0x7f9feff84400

- ** ---------- .> transport: redis://:**@redis-master:6379/1

- ** ---------- .> results: postgresql://airflow:**@postgresql:5432/airflow

- *** --- * --- .> concurrency: 16 (prefork)

-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
```

**Expected behavior**
Worker can start

**Version of Helm and Kubernetes**:

-  Helm version:
helm 2.14.3

**Comment by carrodher** [comment]
Hi, it seems the node where you are running this chart doesn't have enough resources to run the pods and the processes executed by the pods. 
Can you try increasing those resources in the infrastructure or configuring the resources at the pod level? You can specify resource limits/requests for the [worker](https://github.com/bitnami/charts/blob/master/bitnami/airflow/values.yaml#L225), [web](https://github.com/bitnami/charts/blob/master/bitnami/airflow/values.yaml#L261), and [scheduler](https://github.com/bitnami/charts/blob/master/bitnami/airflow/values.yaml#L297). [Here](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) you can find more information about how to manage resources in k8s

**Comment by BigFatDog** [comment]
Thank you so much for your input! It resolves my problem and deepens my knowledge of k8s.
`Worker` works well after I raise its RAM limit to 1.5GB

One more question. What's the best practice to specify RAM limit for worker?
I mean, is there anything special for `Worker` so that I need to monitor its runtime and raise its memory limit again when it gets heavy workload in future ?

**Comment by carrodher** [comment]
I am glad you were able to fix the issue. It depends on several things like the number of actions executed by each pod, the frequency of those actions, etc; that is why it's difficult to set a default value for those parameters as it is something that depends on each use case rather than a general configuration.

Here you can find another post with very interesting information about this topic: https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

There is also `metrics-server` (https://github.com/bitnami/charts/tree/master/bitnami/metrics-server you can find the bitnami chart) that is used to collect resource usage data, so you can see how are used the resources and then set the limits/requests based on that data. Another useful thing is check the recommendations from the application developers, just in case they recommend some minimum or maximum for running the application.

**Comment by BigFatDog** [comment]
Thank you for your detailed explanation!

**Comment by dailingling** [comment]
I'm not in K8S.just only in centos 7.but I also has this issues.
----
Traceback (most recent call last):
  File "/data/.local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/data/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "/data/.local/lib/python3.7/site-packages/airflow/bin/cli.py", line 579, in run
    _run(args, dag, ti)
  File "/data/.local/lib/python3.7/site-packages/airflow/bin/cli.py", line 475, in _run
    run_job.run()
  File "/data/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 218, in run
    self._execute()
  File "/data/.local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 94, in _execute
    self.task_runner.start()
  File "/data/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 43, in start
    self.process = self._start_by_fork()
  File "/data/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 52, in _start_by_fork
    pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
---------
I update swap like this page:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-centos-7

my swap is :
 swapon -s
Filename				Type		Size	Used	Priority
/swapfile                              	file	4194300	264	-1

add the swap can't fix my issue.
How can I do?

**Comment by carrodher** [comment]
Hi, in this repository we provide support for the Bitnami Helm Charts. In order to keep issues in order and provide better support, if you are running a Bitnami Airflow Docker image without Helm, can you create an issue in the container repository (https://github.com/bitnami/bitnami-docker-airflow)?

On the other hand, Bitnami is not providing Centos 7 Docker Images at this moment as part of the Bitnami Community Catalog, our images are based on Debian 10, can you check if you are using a Bitnami image? In that case, feel free to create the issue in the above repository, if not I recommend you to reach the Airflow support page

**Comment by fizaashraf37** [comment]
I was having the exact same issue. I was using docker-compose to run the containers. I simply had to add resources tag under my worker tag in docker-compose.yml file. And this worked for me. 

worker:
        image: "airflow-worker:local-1.0.0"
        restart: always
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        environment:
            - EXECUTOR=Celery
            - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
        command: celery_worker
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2000M
                reservations:
                    cpus: '0.2'
                    memory: 500M
