### ISSUE TITLE
Kafka auth enable error

### ISSUE THREAD

**Issue by maurya-m** [bitnami/charts#3499]
**Which chart**:
kafka : values.yaml - https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml

**Describe the bug**
I am trying to enable Kafka authentication using the values.yaml parameters (customized) configured as below : 

 ```
auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  saslMechanisms: plain,scram-sha-256,scram-sha-512
  saslInterBrokerMechanism: plain
  jaas:
    clientUsers:
    - user1
    clientPasswords: [password1]
    interBrokerUser: admin
    interBrokerPassword: ""
    zookeeperUser: zk_user
    zookeeperPassword: zk_pwd123

```
But the kafka pod is CrashloopOff with the above custom parameters configured, i want to avoid jks in general, want only authenication enable for topic creation , pushing message to this created topic.
 
NAME                                   READY   STATUS             RESTARTS   AGE
kafka-auth-0                           1/2     CrashLoopBackOff   6          5m4s
kafka-auth-client                      1/1     Running            0          171m
kafka-auth-exporter-7967855bbf-5gvmm   0/1     CrashLoopBackOff   5          5m4s
kafka-auth-zookeeper-0                 1/1     Running            0          5m4s

Logs on the pod "kafka-auth-0" is reporting there is 

 ```
11:13:40.79
 11:13:40.79 Welcome to the Bitnami kafka container
 11:13:40.79 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 11:13:40.79 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 11:13:40.79
 11:13:40.80 INFO  ==> ** Starting Kafka setup **
 11:13:40.87 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
 11:13:40.88 INFO  ==> Initializing Kafka...
 11:13:40.88 INFO  ==> No injected configuration files found, creating default config files
 11:13:41.11 INFO  ==> Configuring Kafka for inter-broker communications with SASL_PLAINTEXT authentication.
 11:13:41.12 INFO  ==> Configuring Kafka for client communications with SASL_PLAINTEXT authentication.
 11:13:41.14 INFO  ==> Generating JAAS authentication file
 11:13:41.16 INFO  ==> Creating users in Zookeeper
Creating user user1 in zookeeper
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
[2020-08-24 11:13:42,941] ERROR SASL authentication failed using login context 'Client' with exception: {} (org.apache.zookeeper.client.ZooKeeperSaslClient)
javax.security.sasl.SaslException: Error in authenticating with a Zookeeper Quorum member: the quorum member's saslToken is null.
        at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslToken(ZooKeeperSaslClient.java:312)
        at org.apache.zookeeper.client.ZooKeeperSaslClient.respondToServer(ZooKeeperSaslClient.java:275)
        at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:882)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:101)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2020-08-24 11:13:42,952] ERROR [ZooKeeperClient] Auth failed. (kafka.zookeeper.ZooKeeperClient)
Error while executing config command with args '--zookeeper kafka-auth-zookeeper --alter --add-config SCRAM-SHA-256=[iterations=8192,password=password1],SCRAM-SHA-512=[password=password1] --entity-type users --entity-name user1'
org.apache.zookeeper.KeeperException$AuthFailedException: KeeperErrorCode = AuthFailed for /config/users/user1
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:130)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:557)
        at kafka.zk.KafkaZkClient.getEntityConfigs(KafkaZkClient.scala:338)
        at kafka.zk.AdminZkClient.fetchEntityConfig(AdminZkClient.scala:396)
        at kafka.admin.ConfigCommand$.alterConfigWithZk(ConfigCommand.scala:157)
        at kafka.admin.ConfigCommand$.processCommandWithZk(ConfigCommand.scala:118)
        at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:92)
        at kafka.admin.ConfigCommand.main(ConfigCommand.scala)

```

**To Reproduce**

**Expected behavior**
Want to enable ACL access to Brokers 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by maurya-m** [comment]
got passed the pod error , but facing this error when testing with the kafka:
 ```
ERROR [Producer clientId=console-producer] Connection to node -2 (kafka-auth-1.kafka-auth-headless.kafka-auth.svc.cluster.local/10.42.240.21:9092) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient)
[2020-08-24 12:06:20,578] WARN [Producer clientId=console-producer] Bootstrap broker kafka-auth-1.kafka-auth-headless.kafka-auth.svc.cluster.local:9092 (id: -2 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2020-08-24 12:06:20,762] ERROR [Producer clientId=console-producer] Connection to node -1 (kafka-auth-0.kafka-auth-headless.kafka-auth.svc.cluster.local/10.42.64.10:9092) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient)
```

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure of what you need to run.
  If you want to run consumer / producer you should follow the instructions returned by `helm install kafka bitnami/kafka ...` command.
  To run `kafka-topics.sh` you should do it from a kafka node.
  The password in `values.yaml` should look like this:
```
...
    clientUsers:
      - user1

    ## Kafka client passwords. This is mandatory if more than one user is specified in clientUsers.
    ##
    ## clientPasswords:
    ##   - password1
    ##   - password2"
    ##
    clientPasswords:
      - password1
...
```

  Could you give this a try?

**Comment by maurya-m** [comment]
@rafariossaa , thanks for responding back here.

i did try the change you suggested with :

```
 jaas:
    ## Kafka client user list
    ##
    ## clientUsers:
    ##   - user1
    ##   - user2
    ##
    clientUsers:
      - user1

    ## Kafka client passwords. This is mandatory if more than one user is specified in clientUsers.
    ##
    ## clientPasswords:
    ##   - password1
    ##   - password2"
    ##
    clientPasswords:
      - password1
```

but the issue with running the sample given when helm install is still throwing configurtion error, is there any configration i am clearly missing ?

```
NAME                                   READY   STATUS    RESTARTS   AGE
kafka-auth-0                           2/2     Running   1          2m55s
kafka-auth-client                      1/1     Running   0          4s
kafka-auth-exporter-7967855bbf-nh7wx   1/1     Running   4          2m55s
kafka-auth-zookeeper-0                 1/1     Running   0          2m55s
[@maurya kafka]$ kubectl cp --namespace kafka-auth client.properties kafka-auth-client:/tmp/client.properties
[@maurya kafka]$     kubectl cp --namespace kafka-auth kafka_jaas.conf kafka-auth-client:/tmp/kafka_jaas.conf
[@maurya kafka]$ kubectl exec --tty -i kafka-auth-client --namespace kafka-auth -- bash
I have no name!@kafka-auth-client:/$ export KAFKA_OPTS="-Djava.security.auth.login.config=/tmp/kafka_jaas.conf"
I have no name!@kafka-auth-client:/$ kafka-console-producer.sh \
>             --producer.config /tmp/client.properties \
>             --broker-list kafka-auth-0.kafka-auth-headless.kafka-auth.svc.cluster.local:9092 \
>             --topic test
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:441)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:301)
        at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:45)
        at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
Caused by: java.lang.SecurityException: java.io.IOException: Configuration Error:
        Line 5: expected [option key]
        at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
        at java.base/sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:255)
        at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:246)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.login.Configuration.getConfiguration(Configuration.java:245)
        at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:114)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:98)
        at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:134)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:73)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:449)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:430)
        ... 3 more
Caused by: java.io.IOException: Configuration Error:
        Line 5: expected [option key]
        at java.base/sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:665)
        at java.base/sun.security.provider.ConfigFile$Spi.match(ConfigFile.java:561)
        at java.base/sun.security.provider.ConfigFile$Spi.parseLoginEntry(ConfigFile.java:476)
        at java.base/sun.security.provider.ConfigFile$Spi.readConfig(ConfigFile.java:426)
        at java.base/sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:329)
        at java.base/sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:271)
        at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
        ... 21 more
I have no name!@kafka-auth-client:/$
```

my kafka_jaas.conf  & client properties : 

`- kafka_jaas.conf:

        KafkaClient {
            org.apache.kafka.common.security.scram.ScramLoginModule required
            username="user1"
            password="password1"
        };

    - client.properties:

        security.protocol=SASL_PLAINTEXT
        sasl.mechanism=SCRAM-SHA-256`

**Comment by rafariossaa** [comment]
Hi,
  You need a `;` in the last line of the file `kafka_jass.conf`:
  When running helm you will get something like this:
```    - kafka_jaas.conf:

        KafkaClient {
            org.apache.kafka.common.security.scram.ScramLoginModule required
            username="user1"
            password="$(kubectl get secret mykafka-jaas -n default -o jsonpath='{.data.client-passwords}' | base64 --decode | cut -d , -f 1)";
        };
```
You can get the rendered text with:
```
$ echo "KafkaClient {
            org.apache.kafka.common.security.scram.ScramLoginModule required
            username="user1"
            password="$(kubectl get secret mykafka-jaas -n default -o jsonpath='{.data.client-passwords}' | base64 --decode | cut -d , -f 1)";
        };
" > kafka_jaas.conf

$ cat ./kafka_jaas.conf 
KafkaClient {
            org.apache.kafka.common.security.scram.ScramLoginModule required
            username=user1
            password=password1;
        };
```
  Could you give this a try ?

**Comment by maurya-m** [comment]
@rafariossaa , 
Thanks for pointing to the missing semi-colon ";" , was able to get past the earlier error. Cheers!
