### ISSUE TITLE
[bitnami/prestashop] postInstallation script fails

### ISSUE THREAD

**Issue by Ghyron** [bitnami/charts#3786]
**Which chart**:
bitnami/prestashop

**Describe the bug**
Prestashop container CrashLoopBackOff every time while trying to execute the script install/index_cli.php after fresh Kubernetes installation se below trace for more information.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Log (with trace=true)

```mysql-c TRACE [canConnect] Connection with '<censored>' user is successful
mysql-c INFO  MySQL server listening and working at presta-demo-mariadb:3306
prestas INFO  Configuring PrestaShop...
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php install/index_cli.php,--db_user=niu_presto,--db_password=<censored>,--db_server=presta-demo-mariadb:3306,--db_name=<censored>,--domain=localhost,--firstname=<censored>,--lastname=<censored>,--password=<censored>,--email=<censored>,--timezone=PST8PDT,--country=es,--language=en,--newsletter=0
Error executing 'postInstallation': Program exited with exit code 1
nami    TRACE Error: Error executing 'postInstallation': Program exited with exit code 1
    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.php/helpers.js:69:14)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.prestashop/main.js:49:9)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)```

**Comment by Ghyron** [comment]
Solved was a problem with the MySQL password length. 
I've seen the error adding the follow env vars to container:
```
kubectl set env deployment/<deployment> NAMI_DEBUG=true
kubectl set env deployment/presta-demo-prestashop NAMI_LOG_LEVEL=trace8
```

**Comment by miguelaeh** [comment]
Thanks for sharing your solution with other users!
