### ISSUE TITLE
[bitnami/wordpress] The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable

### ISSUE THREAD

**Issue by wereldbolt** [bitnami/charts#4365]
After following the troubleshoot guide I thought, MariaDb should work out of the Bitnami box, I'll post the bug.

The chart: bitnami/wordpress
Several version used: 9.9.3, 9.9.2, 9.4.3

The Wordpress pod is not able to connect with de database in de Mariadb pod, caused by missing env values. The log said `my.cnf` is not writable:

``` 
app-entrypoint.sh 21:36:50.15 
app-entrypoint.sh 21:36:50.15 Welcome to the Bitnami wordpress container
app-entrypoint.sh 21:36:50.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
app-entrypoint.sh 21:36:50.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
app-entrypoint.sh 21:36:50.16 
app-entrypoint.sh 21:36:50.17 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing Varnish environment
wordpre DEBUG Deleting the Varnish example configuration file
wordpre INFO  ==> Preparing Apache environment
wordpre DEBUG Creating the Apache configuration vhost file
wordpre DEBUG Creating the Apache configuration https vhost file
wordpre INFO  ==> Preparing PHP environment
mysql-c INFO  Trying to connect to MySQL server
nami    TRACE Error: Error executing 'postInstallation': Failed to connect to webshop-mariadb:3306 after 36 tries
    at Object.waitForService (/.nami/components/com.bitnami.mysql-client/lib/network.js:77:23)
    at Object.checkConnection (/.nami/components/com.bitnami.mysql-client/lib/databases/mysql/index.js:584:22)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at MysqlHandler.checkConnection (/.nami/components/com.bitnami.wordpress/lib/handlers/databases/mysql/index.js:109:15)
    at Component.$app.postInstallation (/.nami/components/com.bitnami.wordpress/main.js:71:21)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
Error executing 'postInstallation': Failed to connect to webshop-mariadb:3306 after 36 tries
```

**Describe the bug**
The user of the container or the process has not permissions to write the file to `/opt/bitnami/mariadb/conf/my.cnf`.

**To Reproduce**

scenario A: default values  
scenario B: minimal values

scenario A
1. Install the chart: `helm install webshop bitnami/wordpress --version 9.9.2`
2. Enter pod, through dashboard or `kubectl logs webshop-mariadb-0`

scenario B
1. The file `values.yaml` contains (in question format):
```
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 5.4.2-debian-10-r32

  pullPolicy: IfNotPresent
  debug: true

clusterDomain: cluster.local

commonLabels: {}

commonAnnotations: {}

wordpressUsername: bitnami
wordpressPassword: sGdk2mSqjM
wordpressEmail: webshop@gmail.com
wordpressFirstName: web
wordpressLastName: web
wordpressBlogName: website

wordpressTablePrefix: wp_

wordpressScheme: http

wordpressSkipInstall: false

wordpressExtraConfigContent: ""

allowEmptyPassword: true

allowOverrideNone: false

htaccessPersistenceEnabled: false

customHTAccessCM:

command: []
args: []

updateStrategy:
  type: RollingUpdate

replicaCount: 1

extraEnv: []

extraVolumeMounts: []

extraVolumes: []

resources:
  limits: {}

  requests:
    memory: 512Mi
    cpu: 300m

affinity: {}

nodeSelector: {}

tolerations: {}

podLabels: {}

podAnnotations: {}

securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

healthcheckHttps: false

customLivenessProbe: {}
customReadinessProbe: {}

livenessProbeHeaders: {}
readinessProbeHeaders: {}

service:
  type: ClusterIP
  port: 80
  httpsPort: 443
  httpsTargetPort: https
  
  metricsPort: 9117
  
  nodePorts:
    http: ""
    https: ""
    metrics: ""
  
  externalTrafficPolicy: Cluster
  annotations: {}
  
  loadBalancerSourceRanges: []
  
ingress:
  
  enabled: true

  certManager: false
  hostname: web.nl

  annotations: {
  }


  tls: false


  secrets: []

persistence:
  enabled: false

  accessMode: ReadWriteOnce
  size: 10Gi

mariadb:

  enabled: true

  replication:
    enabled: false

  db:
    name: bitnami_wordpress
    user: bn_wordpress

    password: Ges1Lud3FRyE

  rootUser:
    password: Tyc4B6xha9bs

  master:
    persistence:
      enabled: false

      accessModes:
        - ReadWriteOnce
      size: 8Gi

externalDatabase:
  host: localhost
  user: bn_wordpress
  password: "RrDz02VNJX"
  database: bitnami_wordpress
  port: 3306

metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.8.0-debian-10-r167
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"

  resources:
    limits: {}
    requests: {}

  serviceMonitor:
    enabled: false
    interval: 30s
    honorLabels: false
    additionalLabels: {}
sidecars: {}

initContainers: {}

```

**Expected behavior**
I expect that:  
1. the user of the securitycontext (1001) should have permissions to write to `/opt/bitnami/mariadb/conf/my.cnf`  
2. Mariadb should be able to write the receive env variables to `my.cnf`  
3. Wordpress should be able to connect to the database with de database user

**Version of Helm and Kubernetes**:
- Helm version:  
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

If more context is needed, let me know. Kind regards, Ernst

**Comment by marcosbc** [comment]
Hi @wereldbolt, I can see these options in your values.yaml file:

```
externalDatabase:
  host: localhost
  user: bn_wordpress
  password: "RrDz02VNJX"
  database: bitnami_wordpress
  port: 3306
```

Note that with that configuration, the scripts will think that the MariaDB service is running in the same container as WordPress, which is not the case for Bitnami containers.

Also, note that the Kubernetes pod will **not** be able to connect to your local computer via `externalDatabase`. That option is meant for services such as RDS or Azure Database.

**Comment by ernstbolt** [comment]
@marcosbc Thanks for your response. After commenting the section in the values.yaml, I got the same error.

**Comment by ernstbolt** [comment]
@marcosbc Changing the securityuser to www-data prevents mariadb to stop. The error is still in the log.

**Comment by marcosbc** [comment]
Hi @ernstbolt, just to clarify, do you want to deploy with `externalDatabase` or to deploy a new MariaDB server?

In any case, this line is just a warning, not an error, so nothing happens if it's there (apart from environment variables not having any effect on the mounted configuration file):

```
mariadb 21:26:24.43 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
```

That is because the chart mounts the configuration file. If you want to hide that warning just make the chart not to mount the config file by setting `mariadb.primary.configuration=` (i.e. set it to empty value).

**Comment by wereldbolt** [comment]
Hi @marcosbc , thanks for you clarifaction and for pointing me in the right direction.
