### ISSUE TITLE
redis WRONGPASS invalid username-password pair (default setting)

### ISSUE THREAD

**Issue by KimKiHyuk** [bitnami/charts#4435]
**Which chart**:
airflow-6.7.1

**Describe the bug**
![image](https://user-images.githubusercontent.com/32787543/99694238-8bfad300-2acf-11eb-85ef-35b52373f409.png)

worker cannot connect to redis and logs said WRONGPASS invalid username-password pair.
```
[2020-11-19 15:24:31,458: INFO/MainProcess] celery@key-airflow-worker-0 ready.
[2020-11-19 15:29:32,594: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 688, in _receive
    ret.append(self._receive_one(c))
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 698, in _receive_one
    response = c.parse_response()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2020-11-19 15:29:36,683: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: Error 111 connecting to key-redis-master:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2020-11-19 15:29:39,691: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: Error 111 connecting to key-redis-master:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2020-11-19 15:29:44,715: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: Error 111 connecting to key-redis-master:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2020-11-19 15:29:51,726: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: Error 111 connecting to key-redis-master:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2020-11-19 15:31:14,911: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: WRONGPASS invalid username-password pair.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 15:31:34,938: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: WRONGPASS invalid username-password pair.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 15:31:56,962: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: WRONGPASS invalid username-password pair.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 15:32:20,990: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: WRONGPASS invalid username-password pair.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 15:32:47,023: ERROR/MainProcess] consumer: Cannot connect to redis://:**@key-redis-master:6379/1: WRONGPASS invalid username-password pair.
Trying again in 28.00 seconds... (14/100)
```
**To Reproduce**
I followed under instructions
https://docs.bitnami.com/tutorials/deploy-apache-airflow-kubernetes-helm/
1. helm install key bitnami/airflow 
--set airflow.cloneDagFilesFromGit.enabled=true 
--set airflow.cloneDagFilesFromGit.repository=https://github.com/KimKiHyuk/airflow-dags
--set airflow.cloneDagFilesFromGit.branch=master 
--set airflow.baseUrl=http://127.0.0.1:8080 

I can access to web UI and see my dags list.
but when i tried to trigger dags, it does not work.
and web said my scheduler has a problem.
![image](https://user-images.githubusercontent.com/32787543/99693377-a2545f00-2ace-11eb-874e-1d3a02fc384e.png)

**Expected behavior**
When clicked trigger button, 
![image](https://user-images.githubusercontent.com/32787543/99693612-ea738180-2ace-11eb-8046-d0af12d37c04.png)
dag should be executed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by KimKiHyuk** [comment]
I don't know why, but remove k8s cluster and install again, it works.
 thank you.

**Comment by tanisha41** [comment]
> I don't know why, but remove k8s cluster and install again, it works. thank you.

done that not working

NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472771a450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
 

socket.gaierror: [Errno -3] Temporary failure in name resolution
redis.exceptions.ConnectionError: Error -3 connecting to airflow-redis:6379. Temporary failure in name resolution
