### ISSUE TITLE
No such file or directory: /opt/bitnami/scripts/schema-registry/entrypoint.sh when auth.tls.enabled=true

### ISSUE THREAD

**Issue by lokeshkumarprakashkumar** [bitnami/charts#4678]
**Which chart**:
bitnami/keycloak 1.1.0

**Describe the bug**
When tested for the x509 keycloak authentication using bitnami/keycloak 1.1.0 charts, I faced a issue that there is "No such file or directory: /opt/bitnami/scripts/schema-registry/entrypoint.sh" when the pod is starting up.

**To Reproduce**

1. Install Helm chart using the following settings
helm install my-release --set proxyAddressForwarding=true --set auth.adminUser=<admin> --set auth.adminPassword=<password> --set auth.tls.enabled=true --set auth.tls.jksSecret=<secretName> --set auth.tls.keystorePassword=<keystorepassword> --set auth.tls.truststorePassword=<truststorepassword> bitnami/keycloak
2. The truststore and keystore is available in the secrets and the secretName is used to reference it 
3. The keyclock pod goes to error/crashloopback state
4. Check the logs to see the error
"/bin/bash: line 9: /opt/bitnami/scripts/schema-registry/entrypoint.sh: No such file or directory"

**Expected behavior**
Keycloak pod should be in running state

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
This happens only when the auth.tls.enabled=true as it is trying to execute the command,
exec /opt/bitnami/scripts/schema-registry/entrypoint.sh /opt/bitnami/scripts/schema-registry/run.sh when tls is enabled.

**Comment by marcosbc** [comment]
Hi @lokeshkumarprakashkumar, thanks for reporting this! You were right, there was a typo in the StatefulSet template, which I've sent a PR at #4697 to fix it.

**Comment by travisghansen** [comment]
There are still several problems with this I think:

- the configmap has the ENV vars pointing to the wrong directory (configmap has `secrets` instead of `certs`

```
ls -l /opt/bitnami/keycloak/certs/
total 8
-r--r----- 1 root root 3266 Jan 11 09:21 keycloak.keystore.jks
-r--r----- 1 root root 3266 Jan 11 09:21 keycloak.truststore.jks
```

This snippet fails to run with the default security contexts

```
          if [[ -f "/certs/keycloak.truststore.jks" ]] && [[ -f "/certs/keycloak-${ID}.keystore.jks" ]]; then
              mkdir -p /opt/bitnami/keycloak/certs
              cp "/certs/keycloak.truststore.jks" "/opt/bitnami/keycloak/certs/keycloak.truststore.jks"
              cp "/certs/keycloak-${ID}.keystore.jks" "/opt/bitnami/keycloak/certs/keycloak.keystore.jks"
          else
              echo "Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled."
              exit 1
          fi
```

And even with correcting all of the above I still get this in my logs...

```
09:22:31,251 WARN  [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (default task-1) TruststoreProvider is disabled
```

**Comment by marcosbc** [comment]
> the configmap has the ENV vars pointing to the wrong directory (configmap has secrets instead of certs

You seem to be right. Would you be open to sending a PR fixing this typo?

>This snippet fails to run with the default security contexts (pukes on the mkdir saying it doesn't have permission)

I guess that once the previous item is fixed, this will work since the directory would exist (and hence `mkdir -p` would not fail).

>And even with correcting all of the above I still get this in my logs...
>```
>09:22:31,251 WARN  [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (default task-1) TruststoreProvider is disabled
>```

What version of the Keycloak container are you using? We recently fixed some errors in Keycloak's configuration in [`11.0.3-debian-10-r63`](https://github.com/bitnami/bitnami-docker-keycloak/commit/41c8a87191302be3d375edd91dea70300f2ce0c9). If you are using an older version, could you confirm it is fixed in the new release?

**Comment by travisghansen** [comment]
I deployed with this:

```
keycloak                   	bn-keycloak         	7       	2021-01-11 02:10:11.418849585 -0700 MST	deployed	keycloak-1.2.0               	11.0.3
```

Associate image is:

```
image: docker.io/bitnami/keycloak:11.0.3-debian-10-r59
```

Is there a newer chart version which uses the updated image? Does the updated image need a new chart or can I just update override the image and test it with chart version 1.2.0?

**Comment by travisghansen** [comment]
OK, so I deployed with the new image and things are better but still unable to truly test due to permissions problems. I fix the path in the configmaps and then I still get this:

```
14:59:18,284 FATAL [org.keycloak.services] (ServerService Thread Pool -- 65) Error during startup: java.lang.RuntimeException: Failed to initialize TruststoreProviderFactory: /opt/bitnami/keycloak/certs/keycloak.truststore.jks
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.truststore.FileTruststoreProviderFactory.init(FileTruststoreProviderFactory.java:83)
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.services.DefaultKeycloakSessionFactory.loadFactories(DefaultKeycloakSessionFactory.java:251)
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:84)
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.services.resources.KeycloakApplication.createSessionFactory(KeycloakApplication.java:260)
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:124)
	at org.keycloak.keycloak-wildfly-extensions@11.0.3//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:29)
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2811)
	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:371)
	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:283)
	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:93)
	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)
	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:585)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.io.FileNotFoundException: /opt/bitnami/keycloak/certs/keycloak.truststore.jks (Permission denied)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.truststore.FileTruststoreProviderFactory.loadStore(FileTruststoreProviderFactory.java:103)
	at org.keycloak.keycloak-services@11.0.3//org.keycloak.truststore.FileTruststoreProviderFactory.init(FileTruststoreProviderFactory.java:81)
	... 42 more
```

I'm not sure how that can happen since I have this:

```
podSecurityContext:
  enabled: true
  fsGroup: 0

containerSecurityContext:
  enabled: true
  runAsUser: 0
  runAsNonRoot: false
```

If you update the image without fixing the configmap options the pod will puke (if tls is enabled) so you'll want to make sure all of the above is cleaned up before pushing the updated image to a new chart release.

**Comment by travisghansen** [comment]
I can't catch a break, if I try to hack the chart locally to update the ENV vars and install from that I get this:

```
Error: found in Chart.yaml, but missing in charts/ directory: common, postgresql
```

Also if I remove the root user config options I'm back to:

```
mkdir: cannot create directory '/opt/bitnami/keycloak/certs': Permission denied
```

**Comment by marcosbc** [comment]
@travisghansen For the `missing in charts/` error, try running "helm dep update".

Note that the `mkdir -p` option will not fail if the directory exists, even if you don't have permissions to write to it. Could you verify that this is the case? Maybe there's something else that needs to be changed for certs to be mounted on that directory.

NOTE: For debugging purposes, you may find it useful to specify `command` and `args` option to the chart, i.e. `command[0]=sleep` and `args[0]=infinity` to be able to `kubectl exec -ti` into the pods and debug within the containerized environment.

**Comment by travisghansen** [comment]
OK, here are the details...

# without any funny *securityContext* settings

```
ls -l /certs/
total 0
lrwxrwxrwx 1 root root 30 Jan 16 17:53 keycloak-0.keystore.jks -> ..data/keycloak-0.keystore.jks
lrwxrwxrwx 1 root root 30 Jan 16 17:53 keycloak.truststore.jks -> ..data/keycloak.truststore.jks

I have no name!@keycloak-0:/$ ls -l /opt/bitnami/
total 0
drwxr-xr-x  1 root root  33 Sep 29 19:10 common
drwxr-xr-x 10 root root 141 Nov 18 16:09 java
drwxr-xr-x  1 root root  59 Nov 24 19:47 keycloak
drwxrwxr-x  2 root root  26 Jan  9 09:21 licenses
drwxrwxr-x  1 root root  67 Jan  9 09:21 scripts

I have no name!@keycloak-0:/$ ls -l /opt/bitnami/keycloak/
total 500
-rw-r--r-- 1 root root  11358 Nov 24 12:22 LICENSE.txt
drwxr-xr-x 3 root root   4096 Nov 24 19:47 bin
drwxr-xr-x 7 root root     92 Nov 24 19:47 docs
drwxr-xr-x 1 root root     38 Nov 24 19:47 domain
-rw-r--r-- 1 root root 489102 Nov 24 12:22 jboss-modules.jar
drwxr-xr-x 2 root root     33 Nov 24 19:47 licenses
drwxr-xr-x 3 root root     39 Nov 24 19:47 modules
drwxr-xr-x 1 root root     80 Jan  9 09:22 standalone
drwxr-xr-x 5 root root     76 Nov 24 19:47 themes
-rw-r--r-- 1 root root     26 Nov 24 12:22 version.txt
drwxr-xr-x 2 root root     42 Nov 24 19:47 welcome-content

I have no name!@keycloak-0:/$ whoami 
whoami: cannot find name for user ID 1001
```

# adding an emptyDir volume/mount

```
...
        volumeMounts:
        - mountPath: /certs
          name: certificates
          readOnly: true
        - mountPath: /opt/bitnami/keycloak/certs
          name: bitnami-certs
...
      volumes:
      - name: certificates
        secret:
          defaultMode: 256
          secretName: keystore
      - emptyDir: {}
        name: bitnami-certs
```

Results in this:

```
ls -l /opt/bitnami/keycloak/
...
drwxrwsrwx 2 root 1001      6 Jan 16 18:06 certs
```

And during startup I get this:

```
18:10:49,376 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore /opt/bitnami/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/bitnami/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-12.0.3.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

And trying to invoke the 'Logout All' endpoint.

```
18:12:58,819 WARN  [org.keycloak.services] (default task-1) KC-SERVICES0057: Logout for client 'eas' failed: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

My truststore has a single self-signed CA which **is not** the cert used in the endpoint so from what I can tell adding the `emptyDir` worked. Now what I'd really like is to have java trust the system certs since my endpoint has a cert issued by letsencrypt...any tips on how to make that happen? If I can figure that out then I should be able to test the feature end-to-end.

**Comment by marcosbc** [comment]
Hi @travisghansen, I can see you added this volumeMount:

```yaml
        - mountPath: /opt/bitnami/keycloak/certs
          name: bitnami-certs
```

So then a folder will be mounted into /opt/bitnami/keycloak, and any `cp` command will fail since Kubernetes mounts as read-only usually. Does the same happen if you try without it?

I know that we recently fixed some issues with Keycloak container for SSL support, mentioning in case your issue could be related: https://github.com/bitnami/bitnami-docker-keycloak/issues/2

**Comment by travisghansen** [comment]
@marcosbc it's actually the opposite, doing an `emptyDir` volume mount is the only thing that actually makes it work. You can see in my comment what the permissions are on the dir. So basically the `emptyDir` is needed.

To summarize:

- I have to update the image tag to the version you mentioned
- I have to add the volume/mount manually

At this point everything works...except my truststore doesn't include all standard certificates and I'm not familiar enough to know an easy way to make java trust all the standard system certs...is that possible/easy? What's the easiest way to get java to trust everything `/etc/certs` for example or `/etc/ca-certificates`? Would that 'just work' if the image actually included that package?

**Comment by marcosbc** [comment]
I see, in any case it looks like the "certs" directory is a typo and should really be "secrets".

>except my truststore doesn't include all standard certificates and I'm not familiar enough to know an easy way to make java trust all the standard system certs...is that possible/easy?

It should be possible yes, although it would require to execute some extra commands.

>What's the easiest way to get java to trust everything /etc/certs for example or /etc/ca-certificates? Would that 'just work' if the image actually included that package?

Unfortunately including that package would not be enough. To add root certificates to the truststore you could follow these steps: https://docs.oracle.com/cd/E19906-01/820-4916/geygn/index.html

**Comment by travisghansen** [comment]
OK, well I'm getting closer (and indeed may have everything from a chart/image perspective ironed out), but still don't have the actual feature working. At this point I simply get a failure in the UI and nothing logged on the server/pod side. But here are the requirements:

- add the volume/volume mounts
- bump the image version
- edit the `command` to use `/opt/bitnami/keycloak/secrets` instead of `/opt/bitnami/keycloak/secrets`

To create the keystore file my distro (arch) already has a (seemingly up to date) keystore for java which includes all my system certs located at `/etc/ssl/certs/java/cacerts`. I copied that in place and stored it in k8s using the secret as explained in `values.yaml`. 

The error I get in the UI is:

```
Error! Failed to logout users under: <https endpoint>. Verify availability of failed hosts and try again
```

I assume the truststore is properly working because if I have an empty password (which technically should work IMO in this case) or the wrong password and invoke the same actions I get this in the server-side logs:

```
15:49:02,538 WARN  [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (default task-3) TruststoreProvider is disabled
```

**Comment by travisghansen** [comment]
Does anyone happen to know the proper way to enable debug logging from the app via the chart?

**Comment by rafariossaa** [comment]
Hi,
  Currently there is no values that you can set to change the log level, but the container image provide an environment variable to set it. You can check it [here](https://github.com/bitnami/bitnami-docker-keycloak/blob/b59ce3ecf17b4a2a6ead0d080c9ccd6bac80c185/11/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh#L272) . So, you should be able to set it in the `statefulset.yaml` and get the desired effect.

**Comment by travisghansen** [comment]
OK, that worked! Thanks for the pointer! So after turning on `ALL` logging I was able to figure out what needs to happen at the application level and have corrected it to move on to next steps (nothing related to the image/chart). At this point I can confirm that all the steps above work nicely to make it work end-to-end (at least for my use-case). When fixes land in the chart/images I can retest without any funny business on my side to make sure it works without any 'hacks'. Just let me know when they've landed and I'll give it a go.

**Comment by rafariossaa** [comment]
Hi,
  Sorry, I am missing something. I am not sure about the fixes that need to be landed ? Is there a PR ongoing that I am not aware of ?.

**Comment by travisghansen** [comment]
No PR no. I've just put my findings here. These are the items that are required to get it working for me:

- bump the image to at least `-r63` to include whatever fixes are necessary there
- update the `command` of the container and replace `certs` with `secrets` (see below)
- add the `emptyDir` `volume` (see below)
- add the above as a `volumeMount` (see below)
- given the volumeMount...it's probably fine to remove the `mkdir -p` from the `command` block

# command fix

```
        containers:
        - command:
          - /bin/bash
          - -ec
          - |
            ID="${MY_POD_NAME#"keycloak-"}"
            if [[ -f "/certs/keycloak.truststore.jks" ]] && [[ -f "/certs/keycloak-${ID}.keystore.jks" ]]; then
                mkdir -p /opt/bitnami/keycloak/secrets
                cp "/certs/keycloak.truststore.jks" "/opt/bitnami/keycloak/secrets/keycloak.truststore.jks"
                cp "/certs/keycloak-${ID}.keystore.jks" "/opt/bitnami/keycloak/secrets/keycloak.keystore.jks"
            else
                echo "Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled."
                exit 1
            fi
            exec /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh
```

# volume / volumeMounts

```
          volumeMounts:
          - mountPath: /certs
            name: certificates
            readOnly: true
          - mountPath: /opt/bitnami/keycloak/secrets
            name: bitnami-secrets

        volumes:
        - name: certificates
          secret:
            defaultMode: 256
            secretName: keystore
        - emptyDir: {}
          name: bitnami-secrets
```

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing your findings !. 
  Would you like to send a PR? , that would be great !.
  We will be glad to review and merge it.

**Comment by travisghansen** [comment]
Ugh, apparently the chart has already been fixed since I started this dialog and has the fixes mentioned above. Sorry for the noise :(

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the feedback. I am happy this is solved now.
  Don't hesitate to open a new issue in the case something is not working properly.
