### ISSUE TITLE
overwriting ilm policy is disabled.

### ISSUE THREAD

**Issue by oleglutskyi** [bitnami/charts#4749]
After bitnami installation, I'm try to add Windows server logs. 
On the last step (setup) I've received this error in powershell: 
"overwriting ilm policy is disabled. set setup.ilm.overwrite true for enabling
Index setup finished.
Loaded dashboards
"

**Comment by FraPazGal** [comment]
Hello @oleglutskyi!

Could you provide more information? I'm not sure which chart you are installing nor the kubernetes cluster provider you are using.

**Comment by oleglutskyi** [comment]
> Hello @oleglutskyi!
> 
> Could you provide more information? I'm not sure which chart you are installing nor the kubernetes cluster provider you are using.

Thanks for you answer. Sure, I followed this article: https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-installation-configuration.html
And seems I resolved the error that I provided and now setup completed. Last command showed me the next: 
"Index setup finished
Loading dashboards (Kibana must be running and reachable)
Loaded dashboards."

But Kibana Discovery Page provide me another error: 
"Could not locate that index-pattern-field (id: @timestamp)" 
Full error:
"Error: Could not locate that index-pattern-field (id: @timestamp)
    at FieldParamType._this.deserialize (http://host/36063/bundles/plugin/data/data.plugin.js:1:749327)
    at http://host/36063/bundles/plugin/data/data.plugin.js:1:500490
    at Array.forEach (<anonymous>)
    at AggConfig.setParams (http://host/36063/bundles/plugin/data/data.plugin.js:1:499912)
    at AggConfig.set (http://host/36063/bundles/plugin/data/data.plugin.js:1:506846)
    at AggConfig.setType (http://host/36063/bundles/plugin/data/data.plugin.js:1:506209)
    at new AggConfig (http://host/36063/bundles/plugin/data/data.plugin.js:1:499641)
    at AggConfigs.createAggConfig (http://host/36063/bundles/plugin/data/data.plugin.js:1:258575)
    at http://host36063/bundles/plugin/data/data.plugin.js:1:258964
    at Array.forEach (<anonymous>)"

**Comment by FraPazGal** [comment]
Hi @oleglutskyi,

Sorry for asking almost the same, but I'm not sure yet about which chart are you using. Are you deploying our kibana and/or elasticsearch one? In the article you provided it seems the stack installation is done on Windows with installers.
