### ISSUE TITLE
bitnami/discourse How to upgrade Discourse?

### ISSUE THREAD

**Issue by timothydowney** [bitnami/charts#5168]
How do I perform a Discourse upgrade using the `bitnami/discourse` chart?  I'm running an instance of the chart inside 
of my Kubernetes cluster and having issues when attempting an upgrade.

Firstly, thanks for this chart!  It's well done and has saved me a lot of time.

This is part of a process of migration out of an EC2 instance into Kubernetes.  The steps I've followed are:

- Install `bitnami/discourse` chart into my cluster using 2.2.4 of the discourse docker image to match my existing discourse running in EC2.
- Restore a backup from my EC2 discourse into my new cluster installation.
- Perform a `helm upgrade` to move from 2.2.4 to 2.6.0.

I'm able to repeatedly perform the first steps to get a copy of my existing EC2 instance up and running with all content inside of my k8s cluster, but when I attempt to upgrade to 2.6.0 I'm faced with issues at pod startup.

Here is the error that I am seeing:

```
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Migrating database...
Error executing 'postInstallation': `enabled_site_setting_filter` is deprecated
rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'email_private_messages' for UserOption.
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.3/lib/active_model/attribute_assignment.rb:52:in `_assign_attribute'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.3/lib/active_model/attribute_assignment.rb:43:in `block in _assign_attributes'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.3/lib/active_model/attribute_assignment.rb:42:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.3/lib/active_model/attribute_assignment.rb:42:in `_assign_attributes'
```

I am using version 2.1.2 of the `bitnami/discourse` chart.

Has anyone been able to perform an upgrade?  Am I missing a step that is required before attempting to upgrade the discourse container tag?

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. How was the backup/restore done? Was it using the Discourse interface? Could it be that you had extensions/plugins in your initial installation that were not transferred to the new instance? Does the issue happen when upgrading to an intermediate version, such as 2.3.0 or 2.4.0 (this is important for us to isolate the issue)

**Comment by timothydowney** [comment]
Hi @javsalgar  -- This is a good lead.  I have two plugins from the initial install that I have not been able to migrate.  To answer your other question I grabbed a tarball of a backup from my original instance and I'm using the built-in restore capability on my new k8s instance to restore it.

As for the plugins -- On my existing EC2 instance, I have three plugins installed:

* ldap
* [discourse-solved](https://github.com/discourse/discourse-solved)
* [discourse-voting](https://github.com/discourse/discourse-voting)

I'm using the install plugin method defined in [4624](https://github.com/bitnami/charts/issues/4624), i.e.

```
RAILS_ENV=production bundle exec rake plugin:install repo=https://github.com/jonmbake/discourse-ldap-auth
RAILS_ENV=production bundle exec rake assets:precompile
```

This works for discourse-ldap-auth, but is failing on the precompile for both discourse-solved and discourse-voting.  I'm getting errors like:

```
root@discourse-75c4684f67-xsrrc:/opt/bitnami/discourse# RAILS_ENV=production bundle exec rake assets:precompile
rake aborted!
NoMethodError: undefined method `redis' for Discourse:Module
/opt/bitnami/discourse/plugins/discourse-solved/plugin.rb:34:in `block in activate!'
/opt/bitnami/discourse/lib/plugin/instance.rb:320:in `block in notify_after_initialize'
/opt/bitnami/discourse/lib/plugin/instance.rb:318:in `each'
/opt/bitnami/discourse/lib/plugin/instance.rb:318:in `notify_after_initialize'
/opt/bitnami/discourse/config/application.rb:275:in `each'
/opt/bitnami/discourse/config/application.rb:275:in `block in <class:Application>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control
```

I'm not really clear why `redis` wouldn't be available.  The chart has installed and is running the redis pod, but I'm not really sure how to tell if Discourse is using it.  I'm assuming that there is something in the environment setup that isn't bringing in the right deps.  Either way, I'm unable to install those two plugins which could be leading to the original reported problem since my install & restore is not like-for-like.

I've also tried a suggestion from [elsewhere](https://github.com/swrobel/discourse-heroku/issues/4) suggesting to try adding `config.assets.initialize_on_precompile = false` to `production.rb`.  It appears to have no helpful effect.

Any advice on how to get the plugins installed?

**Comment by javsalgar** [comment]
Hi,

I tried installing the latest version of the chart and found no issues when installing the plugin .

![image](https://user-images.githubusercontent.com/1133777/105472829-ace0cf80-5c9c-11eb-8a35-6555a0b2d0c3.png)


I'm curious if the latest discourse admin can import backups from previous versions. Did you try that?
