### ISSUE TITLE
[bitnami/mongodb] Unable to connect to a single node replicaset, replicaset experiencing poor performance

### ISSUE THREAD

**Issue by ccarv** [bitnami/charts#5441]
**Which chart**:
bitnami/mongodb (latest)

**Describe the bug**
I am having two issues:
1. Terrible performance with replicaset at 3 nodes, standalone performs **significantly** better
2. replicaCount set to 1 does not allow me to write to that single node, only read (error below)

It is my understanding that replicaset should not degrade performance when dealing with very large IO. At least, it should perform no worse then a standalone installation. But from what I'm experiencing, replicaset is much slower then a standalone install.

Since I require replicaset (some of the applications are tailing the updates in Mongo), I cannot use a standalone installation. So I tried reducing my replicaCount down to 1 and get the following error:

```
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=REPLICA_SET, servers=[{address=mongo-0.mongo-headless.default.svc.cluster.local:27017, type=REPLICA_SET_SECONDARY, roundTripTime=1.8 ms, state=CONNECTED}]
        at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:377) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.binding.ClusterBinding.getWriteConnectionSource(ClusterBinding.java:68) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:411) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.Mongo.execute(Mongo.java:845) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.Mongo$2.execute(Mongo.java:828) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:342) ~[mongo-java-driver-3.4.0.jar:na]
        at com.mongodb.DBCollection.update(DBCollection.java:567) ~[mongo-java-driver-3.4.0.jar:na]
        at org.mongodb.morphia.DatastoreImpl.saveDocument(DatastoreImpl.java:1299) ~[morphia-1.3.2.jar:na]
        at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1289) ~[morphia-1.3.2.jar:na]
        at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1121) ~[morphia-1.3.2.jar:na]
        at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1116) ~[morphia-1.3.2.jar:na]
        at design.unstructured.plno.platform.datastore.MorphiaStorage.save(MorphiaStorage.java:49) ~[platform-datastore-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at design.unstructured.plno.platform.datastore.MongoStorage.save(MongoStorage.java:57) ~[platform-datastore-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at design.unstructured.plno.reader.core.io.adapters.StorageAdapter.lambda$process$1(StorageAdapter.java:51) ~[correlator-core-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:1.8.0_282]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_282]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[na:1.8.0_282]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_282]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:1.8.0_282]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_282]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_282]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_282]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_282]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[na:1.8.0_282]
```

**Expected behavior**
I should be able to connect to a single node replicaset. I was able to achieve this with a previous, now deprecated, version of the Bitnami MongoDB chart.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:07:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
My Java application was originally designed to use MongoDB 3.x.x. I've upgraded my drivers to use `3.12.7` and don't believe (I could be wrong) there are any compatibility issues. I am using simple read / write operations. Nothing fancy.

Enabling replica set allows applications to tail MongoDB IO log. Some of the applications are using this feature and disabling it would prevent them from being able to function. This means a standalone install will not work.

After upgrading my MongoDB java driver to 3.12.7, the formatting of the error of a single node replicaset changed. Perhaps this might provide more context:

```
com.mongodb.MongoNotPrimaryException: Command failed with error 10107 (NotWritablePrimary): 'not master' on server mongo-0.mongo-headless.default.svc.cluster.local:27017. The full response is {"errorLabels": ["RetryableWriteError"], "topologyVersion": {"processId": {"$oid": "60232574755386ed69133619"}, "counter": {"$numberLong": "3"}}, "operationTime": {"$timestamp": {"t": 1612902024, "i": 1}}, "ok": 0.0, "errmsg": "not master", "code": 10107, "codeName": "NotWritablePrimary", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1612902024, "i": 1}}, "signature": {"hash": {"$binary": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "$type": "00"}, "keyId": {"$numberLong": "0"}}}}
```

Here is my helm configuration:
```
fullnameOverride: mongo
architecture: replicaset
replicaCount: 3
persistence:
  size: 500Gi
auth:
 enabled: false
 ```

**Comment by javsalgar** [comment]
Hi,

Thank you for the input. My question would be about the persistence volume technology you are using. Could it be that you are using a very slow volume type and that could potentially explain the performance drop? Which is the cluster you are using as well? How many Kubernetes nodes it has?

**Comment by ccarv** [comment]
@javsalgar I deployed in AWS EKS with t3.2xlarger servers. It could very well be the storage but wouldn't standalone installation exhibit similar behavior? Using GP2.

**Comment by ccarv** [comment]
Looks like I solved my second issue. I was running a `helm uninstall` and subsequently tried to run `helm install`. When the mongo pod came back online, it continued to look for the other nodes in the previous replicaset. Purging the entire installation and setting replicaCount to 1 fixed it.

This begs the question of scaling up and down a replicaset. If one of the primary members was removed, why doesn't one of the secondary nodes become primary? 

My first issue with performance is still a problem.

**Comment by javsalgar** [comment]
https://github.com/bitnami/charts/issues/5441#issuecomment-776715491

It may exhibit a similar behavior but if there's a blocking dependency between the nodes (such as a synchronous write or similar), the limitations between the different node storages may become worse. One way to test if it is an issue with the storage is to deploy with persistence disabled and see if the performance is still there. If the performance issue disappears, then the issue is with slow PVCs and we would need to use a different PVC technology. 

About the secondary node becoming primary, did you check the secondary nodes logs to see if they changed? Also, if the primary gets back, then the initial topology would get restored.
