### ISSUE TITLE
[bitnami/kafka] pure IPV6 cluster and metrics exporter causes InvalidReceiveException 

### ISSUE THREAD

**Issue by mtenrero** [bitnami/charts#5447]
**Which chart**:
kafka (2.7.5)

**Describe the bug**
When the kafka chart is deployed in a pure IPV6 cluster, the kafka pods receives some connections from the sidecar jmx-exporter which are not expected and gets refused. This issue can't get reproduced in a IPV4 cluster.

jmx-exporter container: 

```
SEVERE: JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
... 23 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:607)
at java.net.Socket.connect(Socket.java:556)
at java.net.Socket.<init>(Socket.java:452)
at java.net.Socket.<init>(Socket.java:229)
at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
```
kafka container:

```
[2021-02-10 14:22:32,000] WARN [SocketServer brokerId=1002] Unexpected error from /0:0:0:0:0:0:0:1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
at kafka.network.Processor.poll(SocketServer.scala:923)
at kafka.network.Processor.run(SocketServer.scala:826)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**

Deploy the chart with the following configuration in a pure IPV6 cluster which it doesn't have any IPV4 address.

```yaml
kafka:
  nameOverride: kafka
  fullnameOverride: kafka
  global:
    storageClass: kafka
    imagePullSecrets: []
  ipFamily: IPv6
  image:
    repository: bitnami/kafka
    tag: 2.7.0-debian-10-r35
  replicaCount: 1
  numPartitions: 100
  ## Default replication factors for automatically created topics
  defaultReplicationFactor: 1
  ## The replication factor for the offsets topic
  offsetsTopicReplicationFactor: 1
  ## The replication factor for the transaction topic
  transactionStateLogReplicationFactor: 1
  ## Node selector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  #nodeSelector:
  #  topology.sm.com/zone.kafka: "true"
  zookeeperConnectionTimeoutMs: 6000
  persistence:
    enable: true
    size: 500Gi
  metrics:
    kafka:
      enabled: true
      image:
        repository: bitnami/kafka-exporter
        tag: 1.2.0-debian-10-r346
      service:
        annotations:
          prometheus/scrape: "true"
    jmx:
      enabled: true
      image:
        repository: bitnami/jmx-exporter
        tag: 0.15.0-debian-10-r1
      service:
        annotations:
          prometheus/scrape: "true"
      whitelistObjectNames:
        - kafka.controller:*
        - kafka.server:*
        - java.lang:*
        - kafka.network:*
  zookeeper:
    enabled: false
  externalZookeeper:
    servers: zookeeper
  minBrokerId: 1001
  extraEnvVars:
    - name: KAFKA_CFG_RESERVED_BROKER_MAX_ID
      value: "2000"
```

**Expected behavior**
All conections should be undestanable by kafka in both cluster IP Families

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:11:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
For some reason, we lost the tracking of this issue until today the stale bot added the comment. Sorry for that @mtenrero  

Honestly, I don't know if the JMX exporter (based on [this project](https://github.com/prometheus/jmx_exporter)) is compatible with IPv6. This line below suggests me it's not:

- https://github.com/prometheus/jmx_exporter/blob/master/jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/TestJavaAgent.java#L67

**Comment by mtenrero** [comment]
I think it's supported because some lines underneath you can find some tests for IPV6 handling: 
[https://github.com/prometheus/jmx_exporter/blob/8a2a794b16bb706158b8585f52c27b7a4d984d32/jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/TestJavaAgent.java#L83](https://github.com/prometheus/jmx_exporter/blob/8a2a794b16bb706158b8585f52c27b7a4d984d32/jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/TestJavaAgent.java#L83)

**Comment by miguelaeh** [comment]
Hi @mtenrero ,
It seems those tests you shared are for windows, could that be related?

**Comment by mtenrero** [comment]
@miguelaeh Hi Miguel, I don't think so, but it's true IPV6 tests are only present on tests based on Windows hosts...

**Comment by javsalgar** [comment]
Hi,

I think that the best option would be asking the jmx_exporter devs directly. They can confirm whether there's support or not.
