### ISSUE TITLE
[bitnami/airflow] Fail to run a DAGs

### ISSUE THREAD

**Issue by iAshishHere** [bitnami/charts#5471]
**Which chart**:
```
Chart - bitnami/airflow
version - 8.0.3
```
**Describe the bug**
After deploying, I was testing some example DAGs to test their execution, and I noticed that DAG's are failing. And after some time, I am not able to access the Webserver.

![image](https://user-images.githubusercontent.com/29349091/107739095-2153df00-6d2e-11eb-9ecc-41c0e5b880fa.png)

**To Reproduce**

helm repo add bitnami https://charts.bitnami.com/bitnami

helm install my-release airflow

Below mentioned is the configuration I am using in my Helm chart.

```
executor: 'CeleryExecutor'

web:

  image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 2.0.1-debian-10-r0
       
scheduler:

  image:
    registry: docker.io
    repository: bitnami/airflow-scheduler
    tag: 2.0.0-debian-10-r19

worker:

  image:
    registry: docker.io
    repository: bitnami/airflow-worker
    tag: 2.0.0-debian-10-r20
```
Apart from this, I am using `Azure FileShare` where I am mounting my DAGs, Plugins, Logs 
Change in `scheduler.deployment.yaml`, `worker.statefulset.yaml`, `web.deployment.yaml `

```
volumeMounts:
          {{- if .Values.airflow.externalmount.azurefileshare }}
            - name: azurefileshare-dag
              mountPath: /opt/bitnami/airflow/dags
            - name: azurefileshare-plugin
              mountPath: /opt/bitnami/airflow/plugin
            - name: azurefileshare-test
              mountPath: /opt/bitnami/airflow/test
            - name: azurefileshare-logs
              mountPath: /opt/bitnami/airflow/logs
            - name: azurefileshare-requirement
              mountPath: /bitnami/python/
          {{- end }}
```
```
volumes:
      {{- if .Values.airflow.externalmount.azurefileshare }}
        - name: azurefileshare-dag
          azureFile:
            secretName: {{ .Values.airflow.storageaccount.secret }}
            shareName: {{ .Values.airflow.azurefileshare.dags }}
            readOnly: false
        - name: azurefileshare-plugin
          azureFile:
            secretName: {{ .Values.airflow.storageaccount.secret }}
            shareName: {{ .Values.airflow.azurefileshare.plugins }}
            readOnly: false
        - name: azurefileshare-test
          azureFile:
            secretName: {{ .Values.airflow.storageaccount.secret }}
            shareName: {{ .Values.airflow.azurefileshare.test }}
            readOnly: false
        - name: azurefileshare-logs
          azureFile:
            secretName: {{ .Values.airflow.storageaccount.secret }}
            shareName: {{ .Values.airflow.azurefileshare.logs }}
            readOnly: false
        - name: azurefileshare-requirement
          azureFile:
            secretName: {{ .Values.airflow.storageaccount.secret }}
            shareName: {{ .Values.airflow.azurefileshare.requirement }}
            readOnly: false
        
      {{- end }}
```
In value.yaml

```
airflow: 

  storageaccount:
    secret: "sa-secret"
  externalmount:
    azurefileshare: true

  azurefileshare:
    dags: airflow-dag
    plugins: airflow-plugins
    logs: airflow-logs
    test: airflow-tests
    requirement: requirement
```
    

**See error**

Below are the logs of a **worker-pod**

```
[2021-02-11 15:41:42,502] {_internal.py:113} INFO -  * Running on http://0.0.0.0:8793/ (Press CTRL+C to quit)/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/platforms.py:800 RuntimeWarning: You're running the worker with superuser privileges: this isabsolutely not recommended!Please specify a different user using the --uid option.User information: uid=1001 euid=1001 gid=0 egid=0

[2021-02-11 15:41:47,003: INFO/MainProcess] Connected to redis://:**@airflow-latest-redis-master:6379/1

[2021-02-11 15:41:47,019: INFO/MainProcess] mingle: searching for neighbors

[2021-02-11 15:41:48,110: INFO/MainProcess] mingle: all alone

[2021-02-11 15:41:48,129: INFO/MainProcess] celery@airflow-latest-worker-0 ready.
[2021-02-12 00:00:00,142: INFO/MainProcess] Received task: airflow.executors.celery_executor.execute_command[cef6c140-d04c-4814-bea7-55d18b9d8921]  
[2021-02-12 00:00:00,194: INFO/ForkPoolWorker-7] Executing command in Celery: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2021-02-11T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/opt/bitnami/airflow/dags/tutorial.py']
[2021-02-12 00:00:00,296: INFO/ForkPoolWorker-7] Filling up the DagBag from /opt/bitnami/airflow/dags/tutorial.py
[2021-02-12 00:00:01,331: ERROR/ForkPoolWorker-7] Failed to execute task [Errno 1] Operation not permitted: '/opt/bitnami/airflow/logs/tutorial/print_date/2021-02-11T00:00:00+00:00/1.log'.
[2021-02-12 00:00:01,348: ERROR/ForkPoolWorker-7] Task airflow.executors.celery_executor.execute_command[cef6c140-d04c-4814-bea7-55d18b9d8921] raised unexpected: AirflowException('Celery command failed on host: airflow-latest-worker-0.airflow-latest-worker-headless.airflow-dev.svc.cluster.local')Traceback (most recent call last): 
 File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task    
     R = retval = fun(*args, **kwargs)  
 File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__    
     return self.run(*args, **kwargs)  
 File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 87, in execute_command    
     _execute_in_fork(command_to_exec)  
 File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 98, in _execute_in_fork    
     raise AirflowException('Celery command failed on host: ' + get_hostname())
 airflow.exceptions.AirflowException: Celery command failed on host: airflow-latest-worker-0.airflow-latest-worker-headless.airflow-dev.svc.cluster.local
```
Below is the **scheduler logs**, I have attached only the small portion, but it is filled with the same Warning.

```
[2021-02-12 06:44:24,676] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:24,715] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:25,075] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:25,119] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:25,464] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:25,469] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:25,880] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:26,220] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:26,222] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:26,644] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:26,666] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:27,048] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:27,053] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:27,443] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:27,486] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:27,789] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:27,855] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:44:28,151] {file_processor_handler.py:129} WARNING - OSError while attempting to symlink the latest log directory

```

Below is the **Web server logs**

```
[2021-02-12 06:54:26 +0000] [67] [INFO] Handling signal: ttou
[2021-02-12 06:54:28 +0000] [6768] [INFO] Worker exiting (pid: 6768)
[2021-02-12 06:54:49 +0000] [67] [INFO] Handling signal: ttin
[2021-02-12 06:54:49 +0000] [6783] [INFO] Booting worker with pid: 6783
[2021-02-12 06:54:52,170] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.compute_ssh.ComputeEngineSSHHook' from 'apache-airflow-providers-google' package: cannot import name 'ImportSshPublicKeyResponse' from 'google.cloud.oslogin_v1' (/opt/bitnami/airflow/venv/lib/python3.8/site-packages/google/cloud/oslogin_v1/__init__.py)
[2021-02-12 06:54:52,515] {opentelemetry_tracing.py:28} INFO - This service is instrumented using OpenTelemetry. OpenTelemetry could not be imported; please add opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data.
[2021-02-12 06:54:53,042] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.wasb.WasbHook' from 'apache-airflow-providers-microsoft-azure' package: No module named 'azure.storage.blob'
[2021-02-12 06:54:53,318] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.compute_ssh.ComputeEngineSSHHook' from 'apache-airflow-providers-google' package: cannot import name 'ImportSshPublicKeyResponse' from 'google.cloud.oslogin_v1' (/opt/bitnami/airflow/venv/lib/python3.8/site-packages/google/cloud/oslogin_v1/__init__.py)
[2021-02-12 06:54:53,319] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.wasb.WasbHook' from 'apache-airflow-providers-microsoft-azure' package: No module named 'azure.storage.blob'
[2021-02-12 06:54:53,400] {file_processor_handler.py:128} WARNING - OSError while attempting to symlink the latest log directory
[2021-02-12 06:54:55,091] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.compute_ssh.ComputeEngineSSHHook' from 'apache-airflow-providers-google' package: cannot import name 'ImportSshPublicKeyResponse' from 'google.cloud.oslogin_v1' (/opt/bitnami/airflow/venv/lib/python3.8/site-packages/google/cloud/oslogin_v1/__init__.py)
[2021-02-12 06:54:55,093] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.wasb.WasbHook' from 'apache-airflow-providers-microsoft-azure' package: No module named 'azure.storage.blob'
[2021-02-12 06:54:55,265] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.compute_ssh.ComputeEngineSSHHook' from 'apache-airflow-providers-google' package: cannot import name 'ImportSshPublicKeyResponse' from 'google.cloud.oslogin_v1' (/opt/bitnami/airflow/venv/lib/python3.8/site-packages/google/cloud/oslogin_v1/__init__.py)
[2021-02-12 06:54:55,267] {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.wasb.WasbHook' from 'apache-airflow-providers-microsoft-azure' package: No module named 'azure.storage.blob'
```

**Expected behavior**
At least sample test DAGs shouldn't fail and the web UI which was appearing before should appear properly.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.4.2
```

- Output of `kubectl version`:

```
v1.16.10
```

**Additional context**
Web UI was appearing at first. After running the DAG and around 4-5 hours later when I checked the UI, it was showing as below
![image](https://user-images.githubusercontent.com/29349091/107739081-1436f000-6d2e-11eb-9ce7-2d33781d3a9f.png)

**Comment by javsalgar** [comment]
Hi,

I found something weird when testing the dags. I'm triggering a new build that should update the current helm chart. Let's see if the issues disappear after that.

**Comment by iAshishHere** [comment]
When I am not using VolumeMounts, then it's working fine and all the example DAGs are not failing. 
But when I am using Mounts then it fails, even though the DAG files are syncing properly.

**Comment by iAshishHere** [comment]
Closing this issue.
After analyzing it thoroughly, I found the problem is in the mounting of LOGs folder with external volume on Azure FileShare.
Raised another issue - #5487

**Comment by iAshishHere** [comment]
Closing this issue.
After analyzing it thoroughly, I found the problem is in the mounting of LOGs folder with external volume on Azure FileShare.
Raised another issue - #5487
