### ISSUE TITLE
[Bitnami/Airflow] : PIP install not working in worker pods

### ISSUE THREAD

**Issue by ashishmgofficial** [bitnami/charts#5539]
I have mounted the requirements.txt . I can see pip dependencies getting installed in the scheduler logs . But in the Worker pods im getting ```module not found error```

**Comment by rafariossaa** [comment]
Hi,
  Could you provide instructions on how did you deploy and mount the file ? Also, could you send the logs ?

**Comment by ashishmgofficial** [comment]
@juan131 

I have mounted using ```worker.extraVolumes``` and ```worker.extraVolumeMounts``` as below in my deploy.yaml under worker section :  

```
  extraVolumeMounts:
    - name: airflow-pip-requirements
      mountPath: /bitnami/python    
  extraVolumes:        
    - name: airflow-pip-requirements
      persistentVolumeClaim:
         claimName: airflow-pip-requirements-claim
```


now if I try to import lets say pyspark in my DAG , I get the following error :

```
[2021-02-21 14:39:00,908] {dagbag.py:440} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/git-dags/ge_test.py
[2021-02-21 14:39:00,927] {dagbag.py:297} ERROR - Failed to import: /opt/bitnami/airflow/dags/git-dags/ge_test.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 294, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/git-dags/ge_test.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 216, in task_run
    dag = get_dag(args.subdir, args.dag_id)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 187, in get_dag
    raise AirflowException(
airflow.exceptions.AirflowException: dag_id could not be found: spark_app_sa_jenkins-ge. Either the dag did not exist or it failed to parse.

```

**Comment by juan131** [comment]
@ashishmgofficial we're duplicating conversations. Please let's continue at https://github.com/bitnami/charts/issues/3533
