### ISSUE TITLE
[bitnami/postgresql] Cannot import large dump through initdbScripts

### ISSUE THREAD

**Issue by joel-schaal** [bitnami/charts#5570]
**Which chart**:

postgresql      10.2.4  (as a subchart for [Sentry](https://github.com/sentry-kubernetes/charts))

**Describe the bug**

I am trying to import a 1.8GB sql dump in a fresh database.
I wanted to use `initdbScript` and `initdbScriptsConfigMap` for that but I have discovered it is [difficult to create a ConfigMap over 1MB](https://kubernetes.io/docs/concepts/configuration/configmap/#:~:text=A%20ConfigMap%20is%20not%20designed,separate%20database%20or%20file%20service.)

I am thinking to develop a hook on my own to do that but I wanted to be sure I'm not doing it wrong. 

**To Reproduce**

1. Get your hand on a large dump
2. Try to create a configmap out of it (ex: `kubectl create configmap db-dump --from-file=/tmp/2GB.dump`)
3. `fatal error: runtime: out of memory`

**Expected behavior**

The dump would be imported in the database 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:07:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi,
  Could you post the log where you got the error ? 
  If you got the "out of memory" error when creating the configmap, I think you meed to increase the resources of your cluster.
   Instead of using a configmap, maybe you can use the initscripts feature to pull the dump into the pod and then import it into the database.

**Comment by joel-schaal** [comment]
> Could you post the log where you got the error ?

Here it is:
```
[ec2-user@ip-10-1-215-159 hooks]$ kubectl create configmap db-dump --from-file=/tmp/9.1.2.dump
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1b0eec5, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc004000000, 0x70000000, 0x2e1e898)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x2e06000, 0x6ee8c000, 0x7ffd63989df0, 0x7f407986cc10)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x2e06000, 0x37746, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x2e06000, 0x37746, 0x2e1e8a8, 0x41de15)
        /usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x2e06000, 0x37746, 0x7f4077440101, 0x7f407744a6c0)
        /usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x2e06000, 0x37746, 0x7f4077010101, 0x7f40775ee098)
        /usr/local/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x6ee8a390, 0x18b0101, 0x18b5c80)
        /usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x45b4a4)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc00062b490 sp=0xc00062b488 pc=0x45b5a0
runtime.mallocgc(0x6ee8a390, 0x1854620, 0x437701, 0xc000000180)
        /usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc00062b530 sp=0xc00062b490 pc=0x40c755
runtime.makeslice(0x1854620, 0x6ee8a390, 0x6ee8a390, 0x200000003)
        /usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc00062b560 sp=0xc00062b530 pc=0x445d9c
bytes.makeSlice(0x6ee8a390, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:229 +0x77 fp=0xc00062b5c8 sp=0xc00062b560 pc=0x503a37
bytes.(*Buffer).grow(0xc00062b680, 0x6ee8a390, 0x4ca430)
        /usr/local/go/src/bytes/buffer.go:142 +0x15b fp=0xc00062b618 sp=0xc00062b5c8 pc=0x50337b
bytes.(*Buffer).Grow(...)
        /usr/local/go/src/bytes/buffer.go:161
io/ioutil.readAll(0x1d94260, 0xc0000c6fc8, 0x6ee8a390, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:34 +0xc0 fp=0xc00062b6b8 sp=0xc00062b618 pc=0x5fce30
io/ioutil.ReadFile(0xc000360a30, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:73 +0x117 fp=0xc00062b758 sp=0xc00062b6b8 pc=0x5fd057
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.addKeyFromFileToConfigMap(0xc0004bab40, 0xc000360a35, 0xa, 0xc000360a30, 0xf, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned/configmap.go:257 +0x3f fp=0xc00062b7c8 sp=0xc00062b758 pc=0x1477cbf
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.handleConfigMapFromFileSources(0xc0004bab40, 0xc0002b2190, 0x1, 0x1, 0xc0002b2190, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned/configmap.go:224 +0x4b1 fp=0xc00062b8f8 sp=0xc00062b7c8 pc=0x1477701
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.ConfigMapGeneratorV1.StructuredGenerate(0x7ffd6398a6e8, 0x7, 0x0, 0x0, 0xc0002b2190, 0x1, 0x1, 0x2e1c968, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned/configmap.go:137 +0x3e5 fp=0xc00062b9c8 sp=0xc00062b8f8 pc=0x1476ec5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.(*ConfigMapGeneratorV1).StructuredGenerate(0xc0001e0c40, 0x0, 0x0, 0x135fe00, 0xc000369ad0)
        <autogenerated>:1 +0xa8 fp=0xc00062bac8 sp=0xc00062b9c8 pc=0x148a458
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create.(*CreateSubcommandOptions).Run(0xc0000b8f20, 0x0, 0x1bdb0a8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create/create.go:420 +0x4c fp=0xc00062bc88 sp=0xc00062bac8 pc=0x14ab66c
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create.(*ConfigMapOpts).Run(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create/create_configmap.go:122
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create.NewCmdCreateConfigMap.func1(0xc0004d3b80, 0xc000386de0, 0x1, 0x2)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create/create_configmap.go:80 +0xa3 fp=0xc00062bce8 sp=0xc00062bc88 pc=0x14be6f3
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004d3b80, 0xc000386dc0, 0x2, 0x2, 0xc0004d3b80, 0xc000386dc0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x2aa fp=0xc00062bdc0 sp=0xc00062bce8 pc=0x798c0a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000644000, 0xc00007e180, 0xc00003a050, 0x5)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb fp=0xc00062be98 sp=0xc00062bdc0 pc=0x79980b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1f9 fp=0xc00062bf60 sp=0xc00062be98 pc=0x174c6a9
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x206 fp=0xc00062bfe0 sp=0xc00062bf60 pc=0x430b96
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00062bfe8 sp=0xc00062bfe0 pc=0x45d4f1

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x2dff2c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:411 +0xd6

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 20 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bdaff0, 0x1d92800, 0xc0004a4000, 0x1, 0xc00008a0c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bdaff0, 0x12a05f200, 0x0, 0x1, 0xc00008a0c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bdaff0, 0x12a05f200, 0xc00008a0c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
```



> maybe you can use the initscripts feature to pull the dump into the pod

I considered this but then was not so liking to setup credentials in the script for pulling out the data


I actually used a Helm hook to mount the file as a `hostPath` and connect to the DB to import it. 
While that works and solves my issue, I find it a bit hacky (needing to set some nodeAffinity), and I hoped other people used the initdbscript feature for such use case.

**Comment by Mauraza** [comment]
Hi @joel-schaal, 

I'm glad you solve the issue using a Helm hook.
