### ISSUE TITLE
[airflow helm chart]: LDAP error: NameError: name 'no' is not defined

### ISSUE THREAD

**Issue by AyadiAmen** [bitnami/charts#5892]
**Which chart**:

airflow 
version 8.1.0

**Describe the bug**

When i try to deploy the airflow helm chart with ldap enabled, i can't pass the password in ldap.bindpw i get the error : `Error: Deployment.apps "fadi-airflow-web" is invalid: spec.template.spec.containers[0].env[19].valueFrom: Invalid value: "": may not be specified when `value` is not empty` , but when i remove the line 109 ` value: {{ .Values.ldap.bindpw }}` from the  `./templates/web/deployment.yaml` file in the section:
```
        108   - name: AIRFLOW_LDAP_BIND_PASSWORD
        109     value: {{ .Values.ldap.bindpw }}
        110       valueFrom:
        111          secretKeyRef:
        112            name: {{ include "airflow.ldapSecretName" . }}
        113             key: bind-password
```
the password passes correctly as an env variable, but still only the `redis-master` and `airflow-scheduler` pods run correctly whereas the pods `airflow-web` and `airflow-worker` keep on crashing, when i check the `airflow-web` logs here's what i get:

```
nami    INFO  Initializing airflow
airflow INFO  ==> No injected configuration files found. Creating default config file...
airflow INFO  ==> Setting Airflow base URL...
airflow INFO  ==> Enabling Webserver authentication...
airflow INFO  ==> Enabling LDAP authentication...
airflow INFO  ==> Disabling examples...
airflow INFO  ==> Configuring Airflow database...
airflow INFO  ==> Setting Airflow Fernet key...
airflow INFO  ==> Configuring Airflow Celery Executor...
airflow INFO  ==> Deploying Airflow from scratch...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at test-postgresql:5432
postgre ERROR [canConnect] Connection with 'admin' user is unsuccessful
postgre INFO  PostgreSQL server listening and working at test-postgresql:5432
airflow INFO  ==> Populating Airflow database...
airflow INFO  ==> Creating Airflow user...
Error executing 'postInstallation': Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/user_command.py", line 47, in users_create
    appbuilder = cached_app().appbuilder  # pylint: disable=no-member
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/www/app.py", line 135, in cached_app
    app = create_app(config=config, testing=testing)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/www/app.py", line 74, in create_app
    flask_app.config.from_pyfile(settings.WEBSERVER_CONFIG, silent=True)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask/config.py", line 132, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "/opt/bitnami/airflow/webserver_config.py", line 136, in <module>
    AUTH_LDAP_USE_TLS=no
NameError: name 'no' is not defined
```

**To Reproduce**

deploy the airflow helm chart with the following configuration in the `values.yaml` file:

```
  postgresql:
    enabled: false
  externalDatabase:
    database: postgres
    host: test-postgresql
    password: xxxxxxx
    port: 5432
    user: admin
  service:
    type: NodePort
    port: 8080
  ldap:
    enabled: true
    uri: 'ldap://test-openldap:389'
    base: 'dc=example,dc=com'
    binddn: 'cn=admin,dc=example,dc=com'
    bindpw: 'xxxxxxxx'
    uidField: 'cn'
  ingress:
    enabled: false
```
**Expected behavior**

I expected helm chart to run normally and to be able to authenticate using my **ldap** credentials.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:23:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
When i disable `ldap` and run the helm chart with the following configuration:

```
  auth:
    forcePassword: false ( tried both true and false )
    username: admin
    password: xxxxxxx
    fernetKey: _WJG5F2fIZ6q5LH03MQE45stfYpuLpeqzYcqOIxvCbs=
    existingSecret:
  ldap:
    enabled: false
```

 i still get an error at `airflow INFO  ==> Creating Airflow user...` step with a different error message:

```
nami    INFO  Initializing airflow
airflow INFO  ==> No injected configuration files found. Creating default config file...
airflow INFO  ==> Setting Airflow base URL...
airflow INFO  ==> Enabling Webserver authentication...
airflow INFO  ==> Disabling examples...
airflow INFO  ==> Configuring Airflow database...
airflow INFO  ==> Setting Airflow Fernet key...
airflow INFO  ==> Configuring Airflow Celery Executor...
airflow INFO  ==> Deploying Airflow from scratch...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at test-postgresql:5432
postgre INFO  PostgreSQL server listening and working at test-postgresql:5432
airflow INFO  ==> Populating Airflow database...
airflow INFO  ==> Creating Airflow user...
Error executing 'postInstallation': Failed to create user
```

**Comment by javsalgar** [comment]
Hi,

@miguelaeh is working on a major change in the Airflow container. Adding him to the ticket so he can ensure that this error does not appear in the new version of the container.

**Comment by AyadiAmen** [comment]
thank you @javsalgar !

**Comment by mailtobash** [comment]
Is there a temporary fix that you can recommend for this?

**Comment by miguelaeh** [comment]
Hi guys,
The new versions of the airflow images have been released, could give them a try?
