### ISSUE TITLE
Java heap space error when provisioning topics

### ISSUE THREAD

**Issue by SeanM96** [bitnami/charts#5917]
```
Error while executing topic command : Call(callName=createTopics, deadlineMs=1616759256372, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
[2021-03-26 11:46:37,525] ERROR org.apache.kafka.common.errors.TimeoutException: Call(callName=createTopics, deadlineMs=1616759256372, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited. Call: createTopics
 (kafka.admin.TopicCommand$)
[2021-03-26 11:46:37,636] ERROR Uncaught exception in thread 'kafka-admin-client-thread | adminclient-1': (org.apache.kafka.common.utils.KafkaThread)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:61)
	at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:348)
	at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:113)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1329)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1260)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This is when trying to create a single topic with:

```
  provisioning:
    enabled: true
    topics: 
      - name: topicname
        partitions: 1
        replicationFactor: 1
```

Searches have led me to believe this is possibly because I have no plaintext listeners, and this is not configured to work via SSL, this is more so a misleading error for an SSL handshake failure. Currently, there is no option to pass a secret location for the relevant jks, which I need to be pointed to in the --comand-config argument, pointing to a file with the file locations in. Can this be done?

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. What version of the chart are you using `helm ls`? Apart from the above code block related to the provisioning, are you adding any other customized parameters?

**Comment by SeanM96** [comment]
I am using it as a dependency chart, using version 12.12.3.

I have kafka set up to not use plaintext listeners, purely using SSL/SASL. It may be that the heap error is masking an SSL handshake failure, due to no SSL config being passed to the topic provisioning job as shell parameters.

**Comment by javsalgar** [comment]
Hi,

If I understand correctly, the JKS secret that you provide mounts the certificates in `/certs`, according to the chart yaml. Then, if you need to provide an extra flag you could set the KAFKA_EXTRA_FLAGS variable using the extraEnvVars value. Would that work for your case?
