### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  too many connections for role "bn_airflow"

### ISSUE THREAD

**Issue by Jagadeepkosuri** [bitnami/charts#6148]
**Which chart**:
charts/airflow

**Describe the bug**
When i trigger a DAG, the DAG tasks doesn't run. They stay in queued state for long time and move to up for retry. By looking into logs of web and scheduler pods, I found that scheduler is not able to connect Postgres database. See the error in below logs of web pod 

```
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/backends/database/__init__.py", line 51, in _inner
    return fun(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/backends/database/__init__.py", line 154, in _get_task_meta_for
    session = self.ResultSession()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/backends/database/__init__.py", line 113, in ResultSession
    **self.engine_options)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/backends/database/session.py", line 61, in session_factory
    self.prepare_models(engine)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/backends/database/session.py", line 56, in prepare_models
    ResultModelBase.metadata.create_all(engine)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4554, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2094, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/opt/bitnami/python/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2086, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  too many connections for role "bn_airflow"

(Background on this error at: http://sqlalche.me/e/13/e3q8)

```

**To Reproduce**
I just run the helm chart with one web replica, one scheduler replica and 1 database replica. Using Celery executor. 

**Expected behavior**

**Version of Helm and Kubernetes**:
  
- Output of `helm version`:

`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}`

- Output of `kubectl version`:
  
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+k3s1", GitCommit:"355fff3017b06cde44dbd879408a3a6826fa7125", GitTreeState:"clean", BuildDate:"2021-03-31T06:21:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+k3s1", GitCommit:"355fff3017b06cde44dbd879408a3a6826fa7125", GitTreeState:"clean", BuildDate:"2021-03-31T06:21:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by carrodher** [comment]
Hi, are you able to reproduce the issue by using the default parameters? The error `too many connections for role "bn_airflow"` doesn't seem an issue related to wrong credentials when reaching the database but Airflow trying to access it in a very intensive way.

Apart from changing the number of replicas, did you modify any other parameter? Once deployed the chart, what are the steps you followed before seeing the error?

**Comment by Jagadeepkosuri** [comment]
Yes, I'm using custom docker images for web, scheduler and worker. I have  added below two steps to Dockerfile to create custom images

RUN install_packages build-essential gcc unixodbc-dev
RUN /opt/bitnami/airflow/venv/bin/pip3 install pyodbc


Once chart is deployed,  I try to upload some sample dag and run it.

**Comment by Jagadeepkosuri** [comment]
> Hi, are you able to reproduce the issue by using the default parameters? The error `too many connections for role "bn_airflow"` doesn't seem an issue related to wrong credentials when reaching the database but Airflow trying to access it in a very intensive way.
> 
> Apart from changing the number of replicas, did you modify any other parameter? Once deployed the chart, what are the steps you followed before seeing the error?

@carrodher 
Yes, I'm using custom docker images for web, scheduler and worker. I have added below two steps to Dockerfile to create custom images

RUN install_packages build-essential gcc unixodbc-dev
RUN /opt/bitnami/airflow/venv/bin/pip3 install pyodbc

Once chart is deployed, I try to upload some sample dag and run it.

**Comment by Jagadeepkosuri** [comment]
Once Airflow is deployed , webserver logs look like below

```
[2021-04-20 12:23:34,811] {file_processor_handler.py:126} WARNING - OSError while attempting to symlink the latest log directory
[2021-04-20 12:23:36,414] {__init__.py:50} INFO - Using executor CeleryExecutor
[2021-04-20 12:23:36,425] {dagbag.py:417} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags
[2021-04-20 12:23:38,346] {security.py:477} INFO - Start syncing user roles.
[2021-04-20 12:23:38,665] {security.py:387} INFO - Fetching a set of all permission, view_menu from FAB meta-table
[2021-04-20 12:23:39,185] {security.py:330} INFO - Cleaning faulty perms
[2021-04-20 12:23:39 +0000] [69] [INFO] Handling signal: ttou
[2021-04-20 12:23:39 +0000] [103] [INFO] Worker exiting (pid: 103)
```

After opening webserver, if i try to trigger a DAG, logs look like below

```
 File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  too many connections for role "bn_airflow"

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-04-20 12:25:15 +0000] [117] [INFO] Worker exiting (pid: 117)
[2021-04-20 12:25:15 +0000] [109] [INFO] Worker exiting (pid: 109)[2021-04-20 12:25:15 +0000] [111] [INFO] Worker exiting (pid: 111)
[2021-04-20 12:25:15 +0000] [113] [INFO] Worker exiting (pid: 113)
[2021-04-20 12:25:15 +0000] [115] [INFO] Worker exiting (pid: 115)

[2021-04-20 12:25:17,268] {cli.py:990} ERROR - [0 / 0] Some workers seem to have died and gunicorn did not restart them as expected
[2021-04-20 12:25:17 +0000] [69] [INFO] Shutting down: Master
[2021-04-20 12:25:17 +0000] [69] [INFO] Reason: Worker failed to boot.
[2021-04-20 12:25:28,278] {cli.py:990} ERROR - [0 / 0] Some workers seem to have died and gunicorn did not restart them as expected
[2021-04-20 12:25:39,283] {cli.py:990} ERROR - [0 / 0] Some workers seem to have died and gunicorn did not restart them as expected
[2021-04-20 12:25:50,303] {cli.py:990} ERROR - [0 / 0] Some workers seem to have died and gunicorn did not restart them as expected
[2021-04-20 12:26:01,316] {cli.py:990} ERROR - [0 / 0] Some workers seem to have died and gunicorn did not restart them as expected
```

**Comment by carrodher** [comment]
Hi, it's difficult for me to try to reproduce the issue, just to discard it is not an issue related to resources, is the issue solved by increasing the number of replicas?

**Comment by Jagadeepkosuri** [comment]
It was solved after increasing the postgresqlDbUserConnectionLimit and postgresqlPostgresConnectionLimit to 200.
