### ISSUE TITLE
[bitnami/kafka] problem when increasing size of  socket.send.buffer.bytes and  socket.recieve.buffer.bytes

### ISSUE THREAD

**Issue by nervouscat** [bitnami/charts#6164]
Hello,

I am currently having trouble setting the following settings into the values.yaml file:

```
socketReceiveBufferBytes:1048576  #was 102400
socketSendBufferBytes: 1048576 #was 102400

```
When i run the helm chart, the brokers encounter the following error:

```
[2021-04-19 19:50:12,297] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2021-04-19 19:50:12,803] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value 1.048576e+06 for configuration socket.send.buffer.bytes: Not a number of type INT
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:727)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:475)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1309)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1312)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1260)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29)
        at kafka.Kafka$.main(Kafka.scala:68)
        at kafka.Kafka.main(Kafka.scala)
```

Is there any way to resolve this issue?

Thank you in advance!

- Output of `helm version`: 
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

**Comment by miguelaeh** [comment]
Hi @nervouscat ,
Maybe the value you provided is too high, could you give a try to a smaller value?

**Comment by nervouscat** [comment]
Hi @miguelaeh ,

Am not sure thats the problem, since the error claims that its not an integer:
`Invalid value 1.048576e+06 for configuration socket.send.buffer.bytes: Not a number of type INT`

I checked other configurations online, which used the same number, perhaps helm or yaml cannot accept the number?
I also noticed in the values.yaml that some of the longer int values are preceded with a '_' to turn them into strings:

`socketRequestMaxBytes: _104857600`

in my case maybe the same needs to be applied to the helm chart for send and receive bytes?

Thank you in advance!

**Comment by miguelaeh** [comment]
Hi @nervouscat 
I am not familiar with the `_` approach. Does it work in your case? I though that maybe the number is too big to fit into an integer

**Comment by bogdanro** [comment]
Hi, any solution for this? Thanks.

**Comment by bogdanro** [comment]
just add values in ""
socketReceiveBufferBytes: "1048576"
socketSendBufferBytes: "1048576"
