### ISSUE TITLE
[bitnami/keycloak] unable to deploy keycloak next to an older keycloak release

### ISSUE THREAD

**Issue by hichamuntitled** [bitnami/charts#6240]
**Which chart**:
keycloak

**Describe the bug**
in my kubernetes cluster, I have two namespaces A and B.
in namesapce A, I have keycloak (chart 1.0.3) installed and its release name is `a`.
in namesapce B, I want to deploy a newer version of keycloak (chart 2.3.0) and its release name is `b`.
when keycloak b (in my namesapce B) is starting I have the following warnings/erreors

```
13:10:37,833 WARN  [org.infinispan.topology.ClusterTopologyManagerImpl] (thread-12,ejb,B-keycloak-0) ISPN000329: Unable to read rebalancing status from coordinator A-keycloak-0: java.util.concurrent.CompletionException: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from A-keycloak-0, see cause for remote stack trace
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.AbstractRequest.completeExceptionally(AbstractRequest.java:74)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:47)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:52)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1402)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1305)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:131)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1445)
	at org.jgroups@4.2.5.Final//org.jgroups.JChannel.up(JChannel.java:784)
	at org.jgroups@4.2.5.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
	at org.jgroups@4.2.5.Final//org.jgroups.stack.Protocol.up(Protocol.java:306)
	at org.jgroups@4.2.5.Final//org.jgroups.protocols.FORK.up(FORK.java:142)

.
.
.
13:14:37,637 WARN  [org.jgroups.protocols.UDP] (mcast-receiver-4,ejb,B-keycloak-0) JGRP000010: packet from 10.133.120.3:55200 has different version (4.0.13) than ours (4.2.5); packet is discarded
.
.
13:14:39,053 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 63) MSC000001: Failed to start service org.wildfly.clustering.infinispan.cache.ejb.http-remoting-connector: org.jboss.msc.service.StartException in service org.wildfly.clustering.infinispan.cache.ejb.http-remoting-connector: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.statetransfer.StateTransferManager
	at org.wildfly.clustering.service@21.0.2.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:66)
	at org.wildfly.clustering.service@21.0.2.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.statetransfer.StateTransferManager
	at org.infinispan@11.0.4.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:560)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:775)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:341)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:237)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:210)
	at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:1008)
	at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDelegatingCache.java:512)
	at org.infinispan@11.0.4.Final//org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:697)
	at org.infinispan@11.0.4.Final//org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:643)
	at org.infinispan@11.0.4.Final//org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:532)
	at org.infinispan@11.0.4.Final//org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:510)
	at org.jboss.as.clustering.infinispan@21.0.2.Final//org.jboss.as.clustering.infinispan.DefaultCacheContainer.getCache(DefaultCacheContainer.java:92)
	at org.wildfly.clustering.infinispan.spi@21.0.2.Final//org.wildfly.clustering.infinispan.spi.service.CacheServiceConfigurator.get(CacheServiceConfigurator.java:77)
	at org.wildfly.clustering.infinispan.spi@21.0.2.Final//org.wildfly.clustering.infinispan.spi.service.CacheServiceConfigurator.get(CacheServiceConfigurator.java:55)
	at org.wildfly.clustering.service@21.0.2.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:63)
	... 7 more
Caused by: java.util.concurrent.CompletionException: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from A-keycloak-0, see cause for remote stack trace
	at org.infinispan@11.0.4.Final//org.infinispan.util.concurrent.CompletionStages.join(CompletionStages.java:82)
	at org.infinispan@11.0.4.Final//org.infinispan.statetransfer.StateTransferManagerImpl.start(StateTransferManagerImpl.java:132)
	at org.infinispan@11.0.4.Final//org.infinispan.statetransfer.CorePackageImpl$2.start(CorePackageImpl.java:103)
	at org.infinispan@11.0.4.Final//org.infinispan.statetransfer.CorePackageImpl$2.start(CorePackageImpl.java:82)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:592)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:583)
	at org.infinispan@11.0.4.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:552)
	... 22 more
Caused by: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from A-keycloak-0, see cause for remote stack trace
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.ResponseCollectors.wrapRemoteException(ResponseCollectors.java:25)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.ValidSingleResponseCollector.withException(ValidSingleResponseCollector.java:37)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.ValidSingleResponseCollector.addResponse(ValidSingleResponseCollector.java:21)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.addResponse(SingleTargetRequest.java:73)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:43)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:52)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1402)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1305)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:131)
	at org.infinispan@11.0.4.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1445)

```

**Expected behavior**
install new version separately from the older one, as they are in different namespaces and have different release name 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
v1.17.9
```

**Comment by carrodher** [comment]
Hi, it seems you are using a different product, the latest version available in the Bitnami Helm Chart repository is `2.4.6`:
```console
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo bitnami/keycloak -l
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/keycloak	2.4.6        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.4.3        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.4.2        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.4.1        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.4.0        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.3.0        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.2.4        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.2.3        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.2.2        	12.0.4     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.2.1        	12.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.1.2        	12.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.1.1        	12.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.1.0        	12.0.2     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.0.1        	12.0.2     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	2.0.0        	12.0.2     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.4.3        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.4.2        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.4.0        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.3.1        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.2.1        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.2.0        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.1.7        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.1.5        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.1.4        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.1.3        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.1.1        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.1.0        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.0.5        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.0.4        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.0.3        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.0.2        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	1.0.1        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	0.1.2        	11.0.3     	Keycloak is a high performance Java-based ident...
bitnami/keycloak	0.1.0        	11.0.2     	Keycloak is a high performance Java-based ident...
```

**Comment by hichamuntitled** [comment]
Hi,
It's what I've got in logs.
But I'am using bitnami charts.
Here are the output of `kubectl -n a get sts a-keycloak -o yaml` (the old instance)
```
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: a
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-1.0.3
```
And the same output of the new instance in the namespace B
```
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: b
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-2.3.0
```
(I'll update the original post)

**Comment by carrodher** [comment]
I was not able to reproduce the issue, those are the steps I followed
- Old version:
```console
$ kubectl create namespace carlosrha
namespace/carlosrha created

$ helm install a bitnami/keycloak --version 1.0.3 --namespace carlosrha

$ helm ls --namespace carlosrha
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
a   	carlosrha	1       	2021-04-30 09:31:25.539732059 +0000 UTC	deployed	keycloak-1.0.3	11.0.3

$ kubectl get pods --namespace carlosrha
NAME             READY   STATUS    RESTARTS   AGE
a-keycloak-0     1/1     Running   0          3m40s
a-postgresql-0   1/1     Running   0          3m40s
```
- New version, different namespace:
```console
$ kubectl create namespace carlosrhb
namespace/carlosrhb created

$ helm install b bitnami/keycloak --version 2.3.0 --namespace carlosrhb

$ helm ls --namespace carlosrhb
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
b   	carlosrhb	1       	2021-04-30 09:35:57.842086278 +0000 UTC	deployed	keycloak-2.3.0	12.0.4

$ kubectl get pods --namespace carlosrhb
NAME             READY   STATUS    RESTARTS   AGE
b-keycloak-0     1/1     Running   0          4m46s
b-postgresql-0   1/1     Running   0          4m46s
```

Taking a look at the logs with `kubectl logs -f a-keycloak-0 --namespace carlosrha` or `kubectl logs -f b-keycloak-0 --namespace carlosrhb` I am not able to see any error, everything seems to be working as expected. Maybe the second deployment fails in your case because the cluster is running out of resources, can be?

**Comment by hichamuntitled** [comment]
The cluster is not runnning out of resources.
When reading logs, I understand that keycloak-B is trying to join keycloak-A even if it's in a different namespace.

**Comment by carrodher** [comment]
I'm sorry but still not able to reproduce the issue, can you follow the same process I described in the previous comment? This process is installing the old version in a specific namespace and the new version in a different namespace, without setting anything else and it seems everything is working as expected.
Are you doing other customizations?
