### ISSUE TITLE
[bitnami/airflow] Google OAuth integration debugging

### ISSUE THREAD

**Issue by dontspamterry** [bitnami/charts#6336]
**Which chart**:
airflow 10.0.1

**Describe the bug**
I am trying to integrate Google OAuth for Airflow 2.0.2. I have a `webserver_config.py` with OAuth enabled for Google as prescribed by [FAB OAuth Authentication](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth) that I have created a ConfigMap for which is mounted to the `airflow-web` container via the `web.configMap` setting.

Here's my `webserver_config.py`:
```python
import os

from flask_appbuilder.security.manager import AUTH_OAUTH

basedir = os.path.abspath(os.path.dirname(__file__))

# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = True

# ----------------------------------------------------
# AUTHENTICATION CONFIG
# ----------------------------------------------------
# For details on how to set up each of the following authentication, see
# http://flask-appbuilder.readthedocs.io/en/latest/security.html# authentication-methods
# for details.

# The authentication type
# AUTH_OID : Is for OpenID
# AUTH_DB : Is for database
# AUTH_LDAP : Is for LDAP
# AUTH_REMOTE_USER : Is for using REMOTE_USER from web server
# AUTH_OAUTH : Is for OAuth
AUTH_TYPE = AUTH_OAUTH

# Will allow user self registration
AUTH_USER_REGISTRATION = True

# The default user self registration role
AUTH_USER_REGISTRATION_ROLE = "Public"

# When using OAuth Auth, uncomment to setup provider(s) info
# Google OAuth example:
OAUTH_PROVIDERS = [{
  'name':'google',
    'token_key':'access_token',
    'icon':'fa-google',
        'remote_app': {
            'api_base_url':'https://www.googleapis.com/oauth2/v2/',
            'client_kwargs':{
                'scope': 'email profile'
            },
            'access_token_url':'https://accounts.google.com/o/oauth2/token',
            'authorize_url':'https://accounts.google.com/o/oauth2/auth',
            'request_token_url': None,
            'client_id': '<redacted>.apps.googleusercontent.com',
            'client_secret': '<redacted>'
        }
}]
```
I also have the environment variables set for logging:
```bash
extraEnvVars:
  - name: AIRFLOW__LOGGING__LOGGING_LEVEL
    value: "DEBUG"
  - name: AIRFLOW__LOGGING__FAB_LOGGING_LEVEL
    value: "DEBUG"
```
to see what logs would show up to help debug. However, after deploying, the web pod replica continues in a Running, Error, CrashLoopBackOff cycle. Looking at the logs of the `airflow-web` container in the web pod, all I see is:

```
│ airflow-web airflow 22:22:25.21                                                                                                                                 │
│ airflow-web airflow 22:22:25.21 Welcome to the Bitnami airflow container                                                                                        │
│ airflow-web airflow 22:22:25.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow                                      │
│ airflow-web airflow 22:22:25.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues                                  │
│ airflow-web airflow 22:22:25.21                                                                                                                                 │
│ airflow-web airflow 22:22:25.22 INFO  ==> Enabling non-root system user with nss_wrapper                                                                        │
│ airflow-web airflow 22:22:25.23 INFO  ==> ** Starting Airflow setup **                                                                                          │
│ airflow-web airflow 22:22:25.25 INFO  ==> Initializing Airflow ...                                                                                              │
│ airflow-web airflow 22:22:25.26 INFO  ==> No injected configuration file found. Creating default config file                                                    │
│ airflow-web airflow 22:22:25.90 INFO  ==> Configuring Airflow webserver authentication                                                                          │
│ airflow-web airflow 22:22:25.93 INFO  ==> Configuring Airflow database                                                                                          │
│ airflow-web airflow 22:22:25.97 INFO  ==> Waiting for PostgreSQL to be available at tsiu-airflow-postgresql:5432...                                             │
│ airflow-web airflow 22:22:30.21 INFO  ==> Creating Airflow admin user     
```
There are no debug messages and nothing else to help track down what is failing. Eventually, the scheduler pods will error out  waiting to connect to the web pod. If I revert the `AUTH_TYPE` back to `AUTH_DB` in `webserver_config.py`, the web pod recovers.

I'm looking for some guidance on how I can further debug what is going on as I cannot log in to the short-lived pod to even poke around on what might be wrong. Additionally, I logged in to the EC2 node where the pod is running on and checked the corresponding container log under `/var/log/containers`, but found the same output as noted above. Help?!

**To Reproduce**

1. Access to Google Console to create a client id and secret per https://support.google.com/googleapi/answer/6158849?hl=en
2. Update the `webserver_config.py` above with your client id and secret
3. Create a ConfigMap in the same Kubernetes namespace as your Airflow deploy with the `webserver_config.py` file above
4. Create a `values.yaml` override file with `web.configMap` setting pointing to the ConfigMap created in (1) and the additional logging settings noted above.
5. Deploy the Airflow 10.0.1 Chart with the `values.yaml` override

**Expected behavior**
Don't know. Was hoping to at least see some error logs as to why the web server pod could not start up

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
none

**Comment by alvneiayu** [comment]
hi @dontspamterry

To enable extra logs for example in web:
- Modify inside the values.yaml web.image.debug to true or install airflow doing --set web.image.debug=true. Doing that you will see the env var BITNAMI_DEBUG changed to true (if you want to verify that you are enabling the logs).
- Include inside extra variables the var BITNAMI_LOG_LEVEL with the value trace8.
```
extraEnvVars:
  - name: AIRFLOW__LOGGING__LOGGING_LEVEL
    value: "DEBUG"
  - name: AIRFLOW__LOGGING__FAB_LOGGING_LEVEL
    value: "DEBUG"
  - name: BITNAMI_LOG_LEVEL
    value: "trace8"
```
Doing this, you should see more logs. I am not an expert with Airflow but share here the logs and I am going to try to help you to discover what's going on.

Thanks 

Álvaro

**Comment by dontspamterry** [comment]
thanks @alvneiayu ! I'll give that a try and see what I can find. I'll post the extra logs if I get stuck.

**Comment by dontspamterry** [comment]
hi @alvneiayu , I updated the `values.yaml` per your pointers above and sadly, I don't much more to help me figure out what's going on. Here's the logs from the web container after applying those debug logging changes:

```
│ airflow-web airflow 16:51:13.23                                                                                                                                 │
│ airflow-web airflow 16:51:13.23 Welcome to the Bitnami airflow container                                                                                        │
│ airflow-web airflow 16:51:13.24 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow                                      │
│ airflow-web airflow 16:51:13.24 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues                                  │
│ airflow-web airflow 16:51:13.24                                                                                                                                 │
│ airflow-web airflow 16:51:13.24 INFO  ==> Enabling non-root system user with nss_wrapper                                                                        │
│ airflow-web airflow 16:51:13.25 INFO  ==> ** Starting Airflow setup **                                                                                          │
│ airflow-web airflow 16:51:13.27 INFO  ==> Initializing Airflow ...                                                                                              │
│ airflow-web airflow 16:51:13.29 INFO  ==> No injected configuration file found. Creating default config file                                                    │
│ airflow-web airflow 16:51:13.29 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow version                                                               │
│ airflow-web /opt/bitnami/scripts/libos.sh: line 253: 1: command not found                                                                                       │
│ airflow-web airflow 16:51:13.96 INFO  ==> Configuring Airflow webserver authentication                                                                          │
│ airflow-web airflow 16:51:13.98 INFO  ==> Configuring Airflow database                                                                                          │
│ airflow-web airflow 16:51:14.00 INFO  ==> Waiting for PostgreSQL to be available at tsiu-airflow-postgresql:5432...                                             │
│ airflow-web airflow 16:51:14.01 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow db init                                                               │
│ airflow-web /opt/bitnami/scripts/libos.sh: line 253: 1: command not found                                                                                       │
│ airflow-web airflow 16:51:18.37 INFO  ==> Creating Airflow admin user                                                                                           │
│ airflow-web airflow 16:51:18.38 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow users create -r Admin -u user -e user@example.com -p JbUnKH6UEH -f Fi │
│ airflow-web /opt/bitnami/scripts/libos.sh: line 253: 1: command not found 
```

and the corresponding env vars for the web container:

```
│       BITNAMI_DEBUG:                                       1  
│       BITNAMI_LOG_LEVEL:                                   trace8 
```
 I would have expected a lot of new logs to be outputted. Any thoughts?

**Comment by dontspamterry** [comment]
I think the reason why I don't see a whole bunch of logs is because something is failing in the various shell scripts being executed before the actual web server is started. If I swap out my `webserver_config.py` with the default one, the web pod comes up fine and that's when all the DEBUG logs start appearing from the webserver. how to debug the scripts to figure out what's bombing is the next question...

**Comment by alvneiayu** [comment]
hi @dontspamterry 

Share with me your values.yaml, please. I will try to reproduce the problem.

Thanks

Álvaro

**Comment by dontspamterry** [comment]
hi @alvneiayu , my `values.yaml` with sensitive info removed:

```
executor: KubernetesExecutor
redis:
  enabled: false
rbac:
  create: true
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: <irsa role ARN>

auth:
  existingSecret: tsiu-airflow
postgresql:
  enabled: true
  existingSecret: tsiu-airflow

externalDatabase:
  database: airflow_db
  existingSecret: tsiu-airflow
  existingSecretPasswordKey: postgresql-password
  host: <host name>
  port: 5432
  user: airflow_user

loadExamples: false

scheduler:
  replicaCount: 2

extraEnvVars:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: "<some bucket location>
  - name: AIRFLOW__LOGGING__ENCRYPT_S3_LOGS
    value: "True"
  - name: AIRFLOW__LOGGING__LOGGING_LEVEL
    value: "DEBUG"
  - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
    value: "True"
  - name: AIRFLOW__LOGGING__FAB_LOGGING_LEVEL
    value: "DEBUG"
  - name: BITNAMI_LOG_LEVEL
    value: "trace8"

web:
  baseUrl: <some base url>
  extraEnvVars:
  - name: AIRFLOW__WEBSERVER__SECRET_KEY
    value: <some secret>
  replicaCount: 1 
  configMap: tsiu-webserver-config
  image:
    debug: true


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/success-codes: 200,302
    alb.ingress.kubernetes.io/group.name: tsiu-airflow-group
    alb.ingress.kubernetes.io/inbound-cidrs: <cidr list>
  hosts:
    - name: "<some host>"
      path: "/*"
service:
  type: NodePort
```

And this is the `webserver_config.py` that I have created a ConfigMap called `tsiu-webserver-config` and mounted to the web pod in the `values.yaml` above.

```python
import os

from flask_appbuilder.security.manager import AUTH_OAUTH

basedir = os.path.abspath(os.path.dirname(__file__))

# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = True

AUTH_TYPE = AUTH_OAUTH

AUTH_ROLE_ADMIN = "Admin"
AUTH_ROLE_PUBLIC = "Viewer"

# Will allow user self registration
AUTH_USER_REGISTRATION = True

# The default user self registration role
AUTH_USER_REGISTRATION_ROLE = "Admin"

# When using OAuth Auth, uncomment to setup provider(s) info
# Google OAuth example:
OAUTH_PROVIDERS = [{
  'name':'google',
    'token_key':'access_token',
    'icon':'fa-google',
        'remote_app': {
            'api_base_url':'https://www.googleapis.com/oauth2/v2/',
            'client_kwargs':{
                'scope': 'email profile'
            },
            'access_token_url':'https://accounts.google.com/o/oauth2/token',
            'authorize_url':'https://accounts.google.com/o/oauth2/auth',
            'request_token_url': None,
            'client_id': os.environ["GOOGLE_CLIENT_ID"],
            'client_secret': os.environ["GOOGLE_CLIENT_SECRET"],
        }
}]


# ----------------------------------------------------
# Theme CONFIG
# ----------------------------------------------------
# Flask App Builder comes up with a number of predefined themes
# that you can use for Apache Airflow.
# http://flask-appbuilder.readthedocs.io/en/latest/customizing.html#changing-themes
# Please make sure to remove "navbar_color" configuration from airflow.cfg
# in order to fully utilize the theme. (or use that property in conjunction with theme)
# APP_THEME = "bootstrap-theme.css"  # default bootstrap
# APP_THEME = "amelia.css"
# APP_THEME = "cerulean.css"
# APP_THEME = "cosmo.css"
# APP_THEME = "cyborg.css"
# APP_THEME = "darkly.css"
# APP_THEME = "flatly.css"
# APP_THEME = "journal.css"
# APP_THEME = "lumen.css"
APP_THEME = "paper.css"
# APP_THEME = "readable.css"
# APP_THEME = "sandstone.css"
# APP_THEME = "simplex.css"
# APP_THEME = "slate.css"
# APP_THEME = "solar.css"
# APP_THEME = "spacelab.css"
# APP_THEME = "superhero.css"
# APP_THEME = "united.css"
# APP_THEME = "yeti.css"
```

**Comment by eduardchai** [comment]
I experienced the same issue and this is what works for me:
```
    """Default configuration for the Airflow webserver"""
    import os

    from flask_appbuilder.security.manager import AUTH_DB

    # from flask_appbuilder.security.manager import AUTH_LDAP
    from flask_appbuilder.security.manager import AUTH_OAUTH
    # from flask_appbuilder.security.manager import AUTH_OID
    # from flask_appbuilder.security.manager import AUTH_REMOTE_USER


    basedir = os.path.abspath(os.path.dirname(__file__))

    # Flask-WTF flag for CSRF
    WTF_CSRF_ENABLED = True

    # ----------------------------------------------------
    # AUTHENTICATION CONFIG
    # ----------------------------------------------------
    # For details on how to set up each of the following authentication, see
    # http://flask-appbuilder.readthedocs.io/en/latest/security.html# authentication-methods
    # for details.

    # The authentication type
    # AUTH_OID : Is for OpenID
    # AUTH_DB : Is for database
    # AUTH_LDAP : Is for LDAP
    # AUTH_REMOTE_USER : Is for using REMOTE_USER from web server
    # AUTH_OAUTH : Is for OAuth
    AUTH_TYPE = AUTH_OAUTH

    # Uncomment to setup Full admin role name
    # AUTH_ROLE_ADMIN = 'Admin'

    # Uncomment to setup Public role name, no authentication needed
    # AUTH_ROLE_PUBLIC = 'Public'

    # Will allow user self registration
    AUTH_USER_REGISTRATION = True

    # The default user self registration role
    AUTH_USER_REGISTRATION_ROLE = "Viewer"

    # When using OAuth Auth, uncomment to setup provider(s) info
    # Google OAuth example:
    OAUTH_PROVIDERS = [{
      'name':'google',
        'token_key':'access_token',
        'icon':'fa-google',
            'remote_app': {
                'api_base_url':'https://www.googleapis.com/oauth2/v2/',
                'client_kwargs':{
                    'scope': 'email profile'
                },
                'access_token_url':'https://accounts.google.com/o/oauth2/token',
                'authorize_url':'https://accounts.google.com/o/oauth2/auth',
                'request_token_url': None,
                'client_id': 'GOOGLE_CLIENT_ID',
                'client_secret': 'GOOGLE_CLIENT_SECRET',
            }
    }]
    
    # When using LDAP Auth, setup the ldap server
    # AUTH_LDAP_SERVER = "ldap://ldapserver.new"

    # When using OpenID Auth, uncomment to setup OpenID providers.
    # example for OpenID authentication
    # OPENID_PROVIDERS = [
    #    { 'name': 'Yahoo', 'url': 'https://me.yahoo.com' },
    #    { 'name': 'AOL', 'url': 'http://openid.aol.com/<username>' },
    #    { 'name': 'Flickr', 'url': 'http://www.flickr.com/<username>' },
    #    { 'name': 'MyOpenID', 'url': 'https://www.myopenid.com' }]

    # ----------------------------------------------------
    # Theme CONFIG
    # ----------------------------------------------------
    # Flask App Builder comes up with a number of predefined themes
    # that you can use for Apache Airflow.
    # http://flask-appbuilder.readthedocs.io/en/latest/customizing.html#changing-themes
    # Please make sure to remove "navbar_color" configuration from airflow.cfg
    # in order to fully utilize the theme. (or use that property in conjunction with theme)
    # APP_THEME = "bootstrap-theme.css"  # default bootstrap
    # APP_THEME = "amelia.css"
    # APP_THEME = "cerulean.css"
    # APP_THEME = "cosmo.css"
    # APP_THEME = "cyborg.css"
    # APP_THEME = "darkly.css"
    # APP_THEME = "flatly.css"
    # APP_THEME = "journal.css"
    # APP_THEME = "lumen.css"
    # APP_THEME = "paper.css"
    # APP_THEME = "readable.css"
    # APP_THEME = "sandstone.css"
    # APP_THEME = "simplex.css"
    # APP_THEME = "slate.css"
    # APP_THEME = "solar.css"
    # APP_THEME = "spacelab.css"
    # APP_THEME = "superhero.css"
    # APP_THEME = "united.css"
    # APP_THEME = "yeti.css"
```
Make sure that `AUTH_USER_REGISTRATION_ROLE` is not `Public`. Not sure why but it did not work for me when it is set to `Public`. It worked for the other pre-defined roles though e.g. `Admin`, `Viewer`, `User`, or `Op`.

For the web image itself, you need to create your own image with `authlib` installed:
```
FROM bitnami/airflow:2.0.2

USER root
RUN . /opt/bitnami/airflow/venv/bin/activate && pip install authlib

USER 1001
```

Hope it helps! Cheers.

**Comment by dontspamterry** [comment]
Thanks, @eduardchai !! I was about to post an update after I got it working. I, literally, went down a rabbit hole trying to figure out what was wrong and it turns out that I was missing the `AuthLib` module. Unfortunately, the web pod logs did not show any errors on startup indicating the problem so what I did was use `docker-compose` at https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html to stand up local instances, mounted my `webserver_config.py`, and when the web container did not start up, ran `docker logs` against the web container to uncover:

```bash
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-05-17 15:10:24,556] {dagbag.py:451} INFO - Filling up the DagBag from /dev/null
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/webserver_command.py", line 360, in webserver
    app = cached_app(None)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/app.py", line 145, in cached_app
    app = create_app(config=config, testing=testing)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/app.py", line 123, in create_app
    init_appbuilder(flask_app)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/extensions/init_appbuilder.py", line 51, in init_appbuilder
    update_perms=conf.getboolean('webserver', 'UPDATE_FAB_PERMS'),
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 148, in __init__
    self.init_app(app, session)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 202, in init_app
    self.sm = self.security_manager_class(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/security.py", line 161, in __init__
    super().__init__(appbuilder)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_appbuilder/security/sqla/manager.py", line 51, in __init__
    super(SecurityManager, self).__init__(appbuilder)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 256, in __init__
    from authlib.integrations.flask_client import OAuth
ModuleNotFoundError: No module named 'authlib'
```

The above error did not get logged with Bitnami's web pod  :cry:   Also, I should have read through https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth more thoroughly and seen the `WARNING` note about having to install `AuthLib`.

I did not have to create my own custom image with `AuthLib` installed as the Bitnami Helm Chart supports `worker.extraVolumes` and `worker.extraVolumeMounts` to inject a custom `requirements.txt`. I simply created a ConfigMap out of my `requirements.txt` and then set the following in my `values.yaml` override:

```yaml
worker:
  extraVolumeMounts:
  - name: requirements
    mountPath: /bitnami/python/
  extraVolumes:
  - name: requirements
    configMap:
      name: <name of my ConfigMap>
```

On container startup, the worker pod will look for the presence of `/bitnami/python/requirements.txt` and install the additional packages if present

**Comment by eduardchai** [comment]
Glad to hear that. I prefer to install the library in the image because i am using `KubernetesExecutor` and I want to avoid additional overhead of installing the library.
