### ISSUE TITLE
[zookeeper] kubectl rollout restart sts fails to start zookeeper when quorumListenOnAllIPs=true

### ISSUE THREAD

**Issue by samene** [bitnami/charts#6942]
**Which chart**:
bitnami/zookeeper 6.0.1 (zookeeper 3.6.2)

**Describe the bug**
I have deployed zookeeper with 3 replicas with istio injection enabled. As per istio docs I configured ```quorumListenOnAllIPs=true```.
Everything is working fine. Today I upgraded istio control plane to 1.10.2 and to upgrade the data plane I did a 
```kubectl rollout restart sts zookeeper -n mynamespace```
After that the pods were restarted in reverse order: 3,2 and 1. Before the rollout, node-2 was the leader and 1 and 3 were followers. All readiness probes are good but none of the nodes zookeeper is running and all are full of only the following log statement. 
**Thousands of them, almost every 1/2 second.**

```
2021-07-13 07:36:47,004 [myid:3] - WARN  [NIOWorkerThread-1:NIOServerCnxn@373] - Close of session 0x0
java.io.IOException: ZooKeeperServer not running
        at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:544)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:332)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
When I delete all the pods at the same time using kubectl delete, then all of them come up properly and zookeeper is running on all three.

**Version of Helm and Kubernetes**:
Helm v3.4.1
Kubernetes v1.20.6

**Comment by alemorcuq** [comment]
Hi, @samene. I will try to reproduce the issue and get back to you.

**Comment by alemorcuq** [comment]
Sorry for the delay. I wasn't able to reproduce your issue. I installed the chart with `replicaCount=3` and `quorumListenOnAllIPs=true` and did a rollout restart, but I'm not seeing any errors in the logs.

**Comment by samene** [comment]
> Sorry for the delay. I wasn't able to reproduce your issue. I installed the chart with `replicaCount=3` and `quorumListenOnAllIPs=true` and did a rollout restart, but I'm not seeing any errors in the logs.

Was this with istio 1.10.2?

**Comment by alemorcuq** [comment]
No. Unfortunately we don't support Istio at the moment so we don't test with Istio. It's something that is on our roadmap but we have limited resources to work on this. 

This doesn't mean that our charts don't work with Istio, it means we don't know whether they work or not.
