### ISSUE TITLE
[bitnami/spark] /etc/hosts cannot be edited on spark worker nodes

### ISSUE THREAD

**Issue by soullover** [bitnami/charts#7085]
**Which chart**:
[bitnami/spark]

**Describe the bug**

I want to use pyspark to read kafka event and handle the data, but the driver transfers the the server hostname of kafka to worker nodes. The worker nodes cannot connect to kafka server because the hostname and the ip mapping are not existing in the /etc/hosts on worker nodes and the pyspark program fails. I want to edit the /ect/hosts file on worker node but this is non-root container so I meet the permission denied issue. Is there any way to do that without generating a root worker image? 

Below is the log/stderr from one of the worker nodes. p69-253 is the hostname of kafka server and the worker node cannot connect to it without obtaining the IP address of it.

spark-kafka-source-aaf767f4-9870-4e9c-ac52-16a06eac9446-1167290343-executor] Error connecting to node p69-253:9092 (id: 0 rack: null)
java.net.UnknownHostException: p69-253: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:111)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:512)

**To Reproduce**

1. Setup bitnami spark on k8s;
2. Setup kafka server;
3. Use pyspark script to read kafka message and handle it;
4. Driver reports timeout from worker nodes.

**Expected behavior**
/etc/hosts file can be edited on spark worker node.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by soullover** [comment]
I have found a solution for this issue so close it.
