### ISSUE TITLE
[spark] spark-submit from outside k8s cluster

### ISSUE THREAD

**Issue by zpol95** [bitnami/charts#7195]
We have deployed bitnami/spark chart version 5.7.1 and are trying to perform a spark-submit from outside the cluster and inside a Jupyter notebook.  
Thus far we have been unable to successfully connect and have a job run to completion using a spark:// or a k8s:// master URL.  

Ingress and Service Configuration for Spark helm chart: 

    service:
        type: NodePort
        clusterPort: 7077
        webPort: 80
        nodePorts:
            cluster: 30000
            web: 32767
    ingress:
        enabled: true
        certManager: false
        pathType: ImplementationSpecific
        apiVersion: ""
        hostname: CLUSTER_IP
        path: /
        annotations: {
            traefik.ingress.kubernetes.io/router.entrypoints: websecure,
            traefik.ingress.kubernetes.io/router.tls: 'true'}
            
Pyspark Configuration in Jupyter notebook:

    sparkconf = SparkConf().setAppName(appname)
    sparkconf.setMaster("spark://<CLUSTER_IP>:<nodePort.cluster in values.yml>")
    sparkconf.set("spark.kubernetes.container.image", "<IMAGE_URL>")
    sparkconf.set("spark.kubernetes.authenticate.driver.serviceAccountName", "spark")

Using above configuration results in the following:

- Inside the Spark UI, we can see the job has been registered.
    
- From the Jupyter notebook logs

        WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources

- We get this log printing out from the master pod

        Launching executor app-20210811181322-0000/0 on worker worker-20210810181101

- Inside the worker pod, we get a log showing it is launching -

        INFO ExecutorRunner: Launch command

Following the print out of the above logs, nothing additional ever happens. The notebook will just periodically continue to warn about the resources.  
<br>
Our current theory is that it possibly has something to do with the driver being unable to connect back to the Spark cluster to kick off the job. If this is the case, we would very much appreciate some guidance in how to go about resolving the connection issue.
<br>  
Additionally, setting the master as k8s://https://<CLUSTER_IP>:6443 in efforts to use the k8s scheduler in Spark results in this error:

    org.apache.spark.SparkException: External scheduler cannot be instantiated
        at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2961)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:557)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:832)
    Caused by: io.fabric8.kubernetes.client.KubernetesClientException: JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency. To use support for EC Keys you must explicitly add this dependency to classpath.
        at io.fabric8.kubernetes.client.internal.CertUtils.handleECKey(CertUtils.java:163)
        at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:133)
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:113)
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:245)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:124)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:67)
        at org.apache.spark.deploy.k8s.SparkKubernetesClientFactory$.createKubernetesClient(SparkKubernetesClientFactory.scala:100)
        at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterManager.createSchedulerBackend(KubernetesClusterManager.scala:86)
        at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2955)
        ... 14 more

**Comment by javsalgar** [comment]
Hi, 

I'm not a Spark expert, but does the client need access to all the worker nodes in order to work or only the master is enough? That would explain the fact that inside the cluster it works and not outside cluster.

**Comment by chudyandrej** [comment]
I have the same problem.

**Comment by javsalgar** [comment]
Hi,

Could you check this?

> I'm not a Spark expert, but does the client need access to all the worker nodes in order to work or only the master is enough? That would explain the fact that inside the cluster it works and not outside cluster.

**Comment by madhavajay** [comment]
Did anyone figure this out, it seems like a pretty big issue given this is the most popular way to deploy it?

**Comment by RichardPinter** [comment]
What happened?
