### ISSUE TITLE
[bitnami/airflow] dag_id could not be found with dagConfigMap and Kubernetes executor

### ISSUE THREAD

**Issue by junaidnasir-ps** [bitnami/charts#7308]
**Which chart**:
Bitnami/airflow 10.2.8 (Kubernetes executor)

**Describe the bug**
When using dagConfigMap with kubernetes executor the dag fails most of the time (some time it works fine) after a few seconds with the following error.

```bash
airflow-worker 09:28:47.62
airflow-worker 09:28:47.63 Welcome to the Bitnami airflow-worker container
airflow-worker 09:28:47.63 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-worker
airflow-worker 09:28:47.63 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-worker/issues
airflow-worker 09:28:47.63
airflow-worker 09:28:47.63 INFO  ==> Enabling non-root system user with nss_wrapper

[2021-08-24 09:28:49,631] {dagbag.py:496} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/external/..2021_08_23_13_22_47.097678951/billing-models-run-and-push-to-pubsub.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 220, in task_run
    dag = get_dag(args.subdir, args.dag_id)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 191, in get_dag
    raise AirflowException(
airflow.exceptions.AirflowException: dag_id could not be found: billing-models-run-and-push-to-pubsub. Either the dag did not exist or it failed to parse.
```
dagConfigMap is working and available in the cluster. I can also see all the dags on the UI. 
on successful runs the dagbag is filled from `/opt/bitnami/airflow/dags/external/..data/` instead

**To Reproduce**

1. deploy helm with kubernetes executor and dagConfigmap
2. create a dagConfigmap `kubectl create configmap dags-cm --from-file dags/ `
3. run the dag through airflow web ui

**Expected behavior**
All dags should be available in worker pods when using configmap and Kubernetes executor

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.900", GitCommit:"28ab8501be88ea42e897ca8514d7cd0b436253d9", GitTreeState:"clean", BuildDate:"2021-06-30T09:23:36Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Additional context**
```yaml
# values.yaml
web:
  image:
    debug: true
    tag: 2.1.2-debian-10-r20
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-python-requirements-cm
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt
      subPath: requirements.txt

worker:
  image:
    debug: true
    tag: 2.1.2-debian-10-r19

scheduler:
  image:
    tag: 2.1.2-debian-10-r20
```

**Comment by randradas** [comment]
Hello @junaidnasir-ps I need to create an internal task in our backlog to continue helping with it, we will be back with questions, fixes or ideas.

Meanwhile I found some examples here: https://airflow.apache.org/docs/apache-airflow/stable/executor/kubernetes.html that could help. did you take a look at them?

**Comment by junaidnasir-ps** [comment]
not stale

**Comment by randradas** [comment]
The internal task is created, we are looking for a fix.

**Comment by randradas** [comment]
Hello @junaidnasir-ps I would like to ask you something just to clarify. did you find the dags in every worker?. Recently I fixed another issue and I found that the DAGs need to be available not just in the worker but also in the web and the scheduler container in order to avoid problems of dag availability.

**Comment by junaidnasir-ps** [comment]
@randradas Yes i can see them in both web and scheduler.
I have set `name = "AIRFLOW__CORE__DAGS_FOLDER", value = "/opt/bitnami/airflow/dags/external/..data/" ` for the meanwhile as workaround

**Comment by randradas** [comment]
@junaidnasir-ps I think I found the root problem to fix. Basically the metadata stored in the database about the dag contains the path of the dag in the airflow-web container, the scheduler and the worker use this path which does not exist in they respectives file systems. When the worker try to run a task fails becauase the dag's path does not exist.

dag discovery is made by the ariflow-web container.

The fix requires to relocate the dags into a consistent path between container before the airflow initialization, probably a new initContainer is required to do that. Stay tuned.

dag location in containers:
```
➜  ~ kubectl exec -it airflow-worker-0 -- ls -al /opt/bitnami/airflow/dags/external/
total 12
drwxrwsrwx 3 root 1001 4096 Sep 23 19:32 .
drwxrwxr-x 1 root root 4096 Sep 23 19:32 ..
drwxr-sr-x 2 root 1001 4096 Sep 23 19:32 ..2021_09_23_19_32_01.256869848
lrwxrwxrwx 1 root 1001   29 Sep 23 19:32 bitnami-example-dag.py -> ..data/bitnami-example-dag.py
lrwxrwxrwx 1 root 1001   31 Sep 23 19:32 ..data -> ..2021_09_23_19_32_01.256869848
➜  ~ kubectl exec -it airflow-scheduler-758b448557-vcx6l -- ls -al /opt/bitnami/airflow/dags/external/
total 12
drwxrwsrwx 3 root 1001 4096 Sep 23 19:31 .
drwxrwxr-x 1 root root 4096 Sep 23 19:31 ..
drwxr-sr-x 2 root 1001 4096 Sep 23 19:31 ..2021_09_23_19_31_40.191857515
lrwxrwxrwx 1 root 1001   31 Sep 23 19:31 ..data -> ..2021_09_23_19_31_40.191857515
lrwxrwxrwx 1 root 1001   29 Sep 23 19:31 bitnami-example-dag.py -> ..data/bitnami-example-dag.py
➜  ~ kubectl exec -it airflow-web-99dd65f4d-gkjhd -- ls -al /opt/bitnami/airflow/dags/external/
total 12
drwxrwsrwx 3 root 1001 4096 Sep 23 19:31 .
drwxrwxr-x 1 root root 4096 Sep 23 19:31 ..
drwxr-sr-x 2 root 1001 4096 Sep 23 19:31 ..2021_09_23_19_31_40.124100924
lrwxrwxrwx 1 root 1001   29 Sep 23 19:31 bitnami-example-dag.py -> ..data/bitnami-example-dag.py
lrwxrwxrwx 1 root 1001   31 Sep 23 19:31 ..data -> ..2021_09_23_19_31_40.124100924
```

Wrong path during the worker execution:
```
➜  ~ kubectl logs airflow-worker-0 | grep "Executing command in Celery" | head -n 10
[2021-09-23 19:32:58,185: INFO/ForkPoolWorker-15] Executing command in Celery: ['airflow', 'tasks', 'run', 'bitnami_example_dag', 'print_date', '2015-06-01T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/opt/bitnami/airflow/dags/external/..2021_09_23_19_31_40.191857515/bitnami-example-dag.py']
```

Which leads to the error:
`[2021-09-23 21:35:23,131: ERROR/ForkPoolWorker-16] Failed to execute task dag_id could not be found: bitnami_example_dag. Either the dag did not exist or it failed to parse..`
