### ISSUE TITLE
Fluentd Forwarder & Aggregator change default configFiles

### ISSUE THREAD

**Issue by amin224** [bitnami/charts#7367]
**Which chart**:
The name (and version) of the affected chart
chart: fluentd-4.1.3
version: 1.13.3

**Describe the bug**

I am trying to install fluent d helm chart in order to get logs from my Kubernetes pods and send them to bitnami/Elasticsearch. I want to be able to use my own forwarder and aggregator config files using these parameters `forwarder.configFile` and `aggregator.configFile `but when i run the helm chart it is not using my config files in the Kubernetes cluster, thus my fluent d pods are crashing due to cannot find config file in the /opt/bitnami/fluentd/conf directory

**To Reproduce**

1. sudo mkdir /opt/bitnami/fluentd/conf
2. create 2 config files fluentdaggregator-configmap.yml  fluentdforwarder-configmap.yml

Samples:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-test-forwarder-cm
data:
  fluent.conf: |-
    ################################################################
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>
...
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-test-aggregator-cm
data:
  fluent.conf: |-
    ################################################################
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>
...
```

3. helm install fluentd-test bitnami/fluentd --set forwarder.nodeSelector.amin=testing --set aggregator.nodeSelector.amin=testing --set forwarder.configFile="fluentdforwarder-configmap.yml" --set aggregator.configFile="fluentdaggregator-configmap.yml"

4. 
```
kubectl logs -f fluentd-test-0
fluentd 09:47:48.35 
fluentd 09:47:48.36 Welcome to the Bitnami fluentd container
fluentd 09:47:48.36 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-fluentd
fluentd 09:47:48.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-fluentd/issues
fluentd 09:47:48.37 
fluentd 09:47:48.37 INFO  ==> ** Starting Fluentd setup **
fluentd 09:47:48.40 INFO  ==> ** Fluentd setup finished! **

fluentd 09:47:48.42 INFO  ==> ** Starting Fluentd **
/opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/config.rb:31:in `initialize': No such file or directory @ rb_sysopen - /opt/bitnami/fluentd/conf/fluentdaggregator-configmap.yml (Errno::ENOENT)
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/config.rb:31:in `open'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/config.rb:31:in `build'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:742:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/command/fluentd.rb:343:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

**Expected behavior**

I want to run my fluent d helm chart with my forwarder and aggregator config files (that I made) so that it will work for my environment

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e5a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: v1.18.9-eks
Server Version: v1.20.9
```

**Additional context**

```
fluentd-test-0                                        0/1     Error              1          11s
fluentd-test-qr6w2                                    0/1     CrashLoopBackOff   1          11s
fluentd-test-rl9nj                                    0/1     Error              1          11s

```

**Comment by carrodher** [comment]
I'm trying to reproduce the issue on my side, I will update this issue with more info.

In the meantime, can you add the `BITNAMI_DEBUG=true` environment variable to the container? In this way, you can see more information in the logs

**Comment by amin224** [comment]
Hello @carrodher ,

Sorry for the delayed response, I was trying to solve my issue today. kindly check below with `BITNAMI_DEBUG=true` for both my containers (forwarder and aggregator):

Steps:

1.  I created 2 config files:

`fluentdforwarder-configmap.yml:`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-test-forwarder-cm
data:
  fluent.conf: |-
    ################################################################
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    @include pods-kind-fluent.conf
    @include aggregator-output.conf
  pods-kind-fluent.conf: |-
    <source>
      @type tail
      # read from the beginning of the file
      read_from_head true
      tag kubernetes.*
      path /var/log/containers/counter_default_count-e119ecb78c7caea8be20bacbfce3044e7415a8f208645bbc09105f0969585ef2.log
      # exclude fluentd logs
      pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
        @type regexp
        #https://regex101.com/r/ZkOBTI/1
        expression ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.[^Z]*Z)\s(?<stream>[^\s]+)\s(?<character>[^\s])\s(?<message>.*)$
        #time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
  aggregator-output.conf: |-
     # Forward all logs to the aggregators
     <match **>
       @type forward
       <server>
         host fluentd-test-0.fluentd-test-headless.default.svc.cluster.local
         port 24224
       </server>
       <buffer>
         @type file
         path /opt/bitnami/fluentd/logs/buffers/logs.buffer
         flush_thread_count 2
         flush_interval 5s
        </buffer>
     </match>
```
`fluentdaggregator-configmap.yml:`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-test-aggregator-cm
data:
  fluent.conf: |-
    ################################################################
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    @include fluentd-inputs.conf
    @include fluentd-output.conf

  fluentd-inputs.conf: |-
     # TCP input to receive logs from
     <source>
       @type forward
       bind 0.0.0.0
       port 24224
     </source>
     <filter kubernetes.**>
       @type kubernetes_metadata
       @id filter_kube_metadata
       kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
       verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
       ca_file "#{ENV['KUBERNETES_CA_FILE']}"
       skip_labels "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_LABELS'] || 'false'}"
       skip_container_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_CONTAINER_METADATA'] || 'false'}"
       skip_master_url "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_MASTER_URL'] || 'false'}"
       skip_namespace_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_NAMESPACE_METADATA'] || 'false'}"
     </filter>

  fluentd-output.conf: |-
    <match **>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch-coordinating'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      index_name fluentd-k8s
      type_name fluentd
    </match>
```

2. Deployed both files using:
`kubectl create -f fluentdaggregator-configmap.yml  fluentdforwarder-configmap.yml`

3. `helm install fluentd-test bitnami/fluentd --set forwarder.nodeSelector.amin=testing --set aggregator.nodeSelector.amin=testing --set aggregator.configMap=fluentd-test-aggregator-cm --set forwarder.configMap=fluentd-test-forwarder-cm`

4. Edited my fluentd-forwarder daemonset and set `BITNAMI_DEBUG=true` in the environment, in addition edited my fluentd-aggregator statefulset and set `BITNAMI_DEBUG=true` in the environment

5. Restarted my daemonset and statefulset to get new pods

6. Result  for both forwarder and aggregator new pods:

```
kubectl logs -f fluentd-test-s4pr8 
fluentd 13:51:51.54 
fluentd 13:51:51.54 Welcome to the Bitnami fluentd container
fluentd 13:51:51.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-fluentd
fluentd 13:51:51.55 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-fluentd/issues
fluentd 13:51:51.55 
fluentd 13:51:51.55 INFO  ==> ** Starting Fluentd setup **
fluentd 13:51:51.56 INFO  ==> ** Fluentd setup finished! **

fluentd 13:51:51.57 INFO  ==> ** Starting Fluentd **
/opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/config.rb:31:in `initialize': No such file or directory @ rb_sysopen - /opt/bitnami/fluentd/conf/fluentd.conf (Errno::ENOENT)
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/config.rb:31:in `open'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/config.rb:31:in `build'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:742:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/lib/fluent/command/fluentd.rb:343:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.13.3/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

Please note that I also found a useful step by step documentation here [bitnami-logging](https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/) and as you can see I followed the same steps but did not work.

**Comment by carrodher** [comment]
I was able to reproduce your issue when using the same configmaps pasted above:

```console
$ kubectl get cm
NAME                                       DATA   AGE
aggregator-cm                              3      23s
forwarder-cm                               3      26s

$ helm install fluentd-test bitnami/fluentd --set aggregator.configMap=aggregator-cm,forwarder.configMap=forwarder-cm,image.debug=true
kubectl get pods
NAME: fluentd-test2
LAST DEPLOYED: Fri Sep  3 07:43:28 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

  To verify that Fluentd has started, run:

    kubectl get all -l "app.kubernetes.io/name=fluentd,app.kubernetes.io/instance=fluentd-test2"

$ helm ls
NAME                             	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART                       	APP VERSION
fluentd-test                     	default  	1       	2021-09-03 07:26:09.048052537 +0000 UTC 	deployed	fluentd-4.1.6               	1.14.0

$ kubectl get pods
NAME                           READY   STATUS             RESTARTS   AGE
fluentd-test-0                 0/1     CrashLoopBackOff   7          15m

$ kubectl logs -f fluentd-test-0
fluentd 07:42:57.34
fluentd 07:42:57.35 Welcome to the Bitnami fluentd container
fluentd 07:42:57.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-fluentd
fluentd 07:42:57.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-fluentd/issues
fluentd 07:42:57.35
fluentd 07:42:57.35 INFO  ==> ** Starting Fluentd setup **
fluentd 07:42:57.37 INFO  ==> ** Fluentd setup finished! **

fluentd 07:42:57.39 INFO  ==> ** Starting Fluentd **
/opt/bitnami/fluentd/gems/fluentd-1.14.0/lib/fluent/config.rb:31:in `initialize': No such file or directory @ rb_sysopen - /opt/bitnami/fluentd/conf/fluentd.conf (Errno::ENOENT)
	from /opt/bitnami/fluentd/gems/fluentd-1.14.0/lib/fluent/config.rb:31:in `open'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.0/lib/fluent/config.rb:31:in `build'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.0/lib/fluent/supervisor.rb:744:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.0/lib/fluent/command/fluentd.rb:351:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.0/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

On the other hand, when using a different configmap (for example the ones that appear at https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/#step-3-configure-and-deploy-fluentd) the above error is not present. In this case, I am facing other errors because I didn't deploy previously Elasticsearch nor followed the guide, just fluentd.

By using a different configmap the pod is not in crashloopbackoff status (although it is not fully ready since I am not doing the whole configuration process):
```console
$ kubectl get pods
NAME                           READY   STATUS             RESTARTS   AGE
fluentd-test3-0                0/1     Running            1          3m48s
```

In the same way, I'm able to see the custom configmap content rendered as the fluentd config file, see
```console
$ kubectl exec -it fluentd-test3-0 -- cat /opt/bitnami/fluentd/conf/fluentd.conf

# Ignore fluentd own events
<match fluent.**>
  @type null
</match>

# TCP input to receive logs from the forwarders
<source>
  @type forward
  bind 0.0.0.0
  port 24224
</source>

# HTTP input for the liveness and readiness probes
<source>
  @type http
  bind 0.0.0.0
  port 9880
</source>

# Throw the healthcheck to the standard output instead of forwarding it
<match fluentd.healthcheck>
  @type stdout
</match>

# Send the logs to the standard output
<match **>
  @type elasticsearch
  include_tag_key true
  host "#{ENV['ELASTICSEARCH_HOST']}"
  port "#{ENV['ELASTICSEARCH_PORT']}"
  logstash_format true
  <buffer>
    @type file
    path /opt/bitnami/fluentd/logs/buffers/logs.buffer
    flush_thread_count 2
    flush_interval 5s
  </buffer>
</match>
```

Can you double-check the configuration used in the configmaps or try with a very basic configuration just to ensure it works? If everything works with a basic config file then you can work on adding a more advanced config, but at least we can check if the issue is related to the config file or the chart logic...

**Comment by amin224** [comment]
Thank you for the clarification, I am confused why my fluentd configs would cause an error it is fairly similar to the default one by bitnami. I only removed metrics.server parameters and added an Elasticsearch as my output alongside some filtering for my logs to add Kubernetes information. Nonetheless I will follow your advice and troubleshoot with a simpler config and will share my output here as soon as possible.

**Comment by chtourou-youssef** [comment]
@amin224 are you resolve your problem ?

**Comment by amin224** [comment]
@chtourou-youssef Not yet, will share my solution once I have the time. Probably by Monday

**Comment by s0mb3x** [comment]
I'm facing the same issue. 
Aggregator is not loading the configMap provided in helm chart values file.
Forwarder loads the configMap just fine.

**Comment by carrodher** [comment]
Can you please share more info about the version of the chart you are using, how are you passing the ConfigMaps, etc. In order to reproduce your issue, it would be useful to have the CMs values you're using in the _values.yaml_
