### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by samuda2019** [bitnami/charts#7742]
**Which chart**:
The name (and version) of the affected chart
airflow

**Describe the bug**

Gateway Timeout
Server error - server 20.69.209.220 is unreachable at this moment.

Please retry the request or contact your administrator.
**To Reproduce**

After configuring Airflow successfully and trying to open the Airflow UI in browser. I'm getting a gateway timeout error.

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by samuda2019** [comment]
sudo kubectl logs aks-cluster-airflow-web-546bff7889-rpztg
airflow 20:17:03.60
airflow 20:17:03.60 Welcome to the Bitnami airflow container
airflow 20:17:03.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow
airflow 20:17:03.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues
airflow 20:17:03.61
airflow 20:17:03.61 INFO  ==> Enabling non-root system user with nss_wrapper
airflow 20:17:03.62 INFO  ==> ** Starting Airflow setup **
airflow 20:17:03.64 INFO  ==> Initializing Airflow ...
airflow 20:17:03.66 INFO  ==> No injected configuration file found. Creating default config file
airflow 20:17:03.66 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow version
2.1.4
airflow 20:17:04.31 INFO  ==> Configuring Airflow webserver authentication
airflow 20:17:04.34 INFO  ==> Configuring Airflow database
airflow 20:17:04.39 INFO  ==> Configuring Celery Executor
airflow 20:17:04.43 INFO  ==> Waiting for PostgreSQL to be available at srbitnami.postgres.database.azure.com:5432...
airflow 20:17:04.51 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow db init
DB: postgresql+psycopg2://user%40srbitnami:***@srbitnami.postgres.database.azure.com:5432/airflow
[2021-10-08 20:17:05,685] {db.py:702} INFO - Creating tables
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "user"
FATAL:  password authentication failed for user "user"

sudo kubectl logs aks-cluster-airflow-scheduler-5554b664d-fjsgg
airflow-scheduler 20:18:50.66
airflow-scheduler 20:18:50.67 Welcome to the Bitnami airflow-scheduler container
airflow-scheduler 20:18:50.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-scheduler
airflow-scheduler 20:18:50.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-scheduler/issues
airflow-scheduler 20:18:50.68
airflow-scheduler 20:18:50.69 INFO  ==> Enabling non-root system user with nss_wrapper
airflow-scheduler 20:18:50.72 INFO  ==> ** Starting Airflow setup **
airflow-scheduler 20:18:50.81 INFO  ==> No injected configuration file found. Creating default config file
airflow-scheduler 20:18:51.61 INFO  ==> Configuring Airflow database
airflow-scheduler 20:18:51.68 INFO  ==> Configuring Celery Executor
airflow-scheduler 20:18:51.72 INFO  ==> Waiting for PostgreSQL to be available at aks-cluster-postgresql:5432...
airflow-scheduler 20:19:15.31 INFO  ==> Persisting Airflow installation
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"

sudo kubectl logs aks-cluster-airflow-worker-0
airflow-worker 20:16:30.50
airflow-worker 20:16:30.50 Welcome to the Bitnami airflow-worker container
airflow-worker 20:16:30.50 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-worker
airflow-worker 20:16:30.50 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-worker/issues
airflow-worker 20:16:30.50
airflow-worker 20:16:30.51 INFO  ==> Enabling non-root system user with nss_wrapper
airflow-worker 20:16:30.51 INFO  ==> ** Starting Airflow setup **
airflow-worker 20:16:30.56 INFO  ==> No injected configuration file found. Creating default config file
airflow-worker 20:16:30.56 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow version
2.1.4
airflow-worker 20:16:31.22 INFO  ==> Configuring Airflow database
airflow-worker 20:16:31.31 INFO  ==> Configuring Celery Executor
airflow-worker 20:16:31.34 INFO  ==> Waiting for PostgreSQL to be available at srbitnami.postgres.database.azure.com:5432...
airflow-worker 20:16:31.43 INFO  ==> Persisting Airflow installation
airflow-worker 20:16:31.47 INFO  ==> Waiting for Airflow Webserser to be up
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"

**Comment by samuda2019** [comment]
@randradas           Thank you. Deleting the PVCs fixed it but when I try to use my own PostgreSQL I’m still getting error FATAL: password authentication failed for user "bn_airflow". Can I not use any user by passing externalDatabase.user option? It works fine if I let it use the PostgreSQL using a container created with my AKS cluster.
