### ISSUE TITLE
Subchart issue with the helm upgrade

### ISSUE THREAD

**Issue by banicr** [bitnami/charts#7746]
**Describe the bug**
I am using bitnami/geode as one of the subcharts in my dataplatforms blueprint. The issue I am facing is, whenever I try to deploy the chart using "helm install" command  it works fine. But, When I update the other subchart and do  a "helm upgrade", one of the geode server/locator pods  goes into "CrashLoopBackOff" state. 

In the container logs I see the below error:
```
(1) Executing - start locator --dir=/bitnami/geode/data --classpath=/opt/bitnami/geode/extensions --force --J=-Dgemfire.log-file=/opt/bitnami/geode/logs/locator.log --properties-file=/opt/bitnami/geode/config/gemfire.properties --security-properties-file=******** --name=bp3-geode-locator-1 --locators=bp3-geode-locator-0.bp3-geode-locator-hl.ge.svc.cluster.local[10334],bp3-geode-locator-1.bp3-geode-locator-hl.ge.svc.cluster.local[10334] --hostname-for-clients=bp3-geode-locator-1.bp3-geode-locator-hl.ge.svc.cluster.local --J=-Dprometheus.metrics.port=9915 --port=10334

The Locator process terminated unexpectedly with exit status 1. Please refer to the log file in /bitnami/geode/data for full details.

Exception in thread "main" org.apache.geode.security.GemFireSecurityException: Security check failed. Authentication error. Please check your credentials.

	at org.apache.geode.distributed.internal.DistributionImpl.start(DistributionImpl.java:181)

	at org.apache.geode.distributed.internal.DistributionImpl.createDistribution(DistributionImpl.java:222)

	at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:464)

	at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:497)

	at org.apache.geode.distributed.internal.ClusterDistributionManager.create(ClusterDistributionManager.java:326)

	at org.apache.geode.distributed.internal.InternalDistributedSystem.initialize(InternalDistributedSystem.java:779)

	at org.apache.geode.distributed.internal.InternalDistributedSystem.access$200(InternalDistributedSystem.java:135)

	at org.apache.geode.distributed.internal.InternalDistributedSystem$Builder.build(InternalDistributedSystem.java:3034)

	at org.apache.geode.distributed.internal.InternalDistributedSystem.connectInternal(InternalDistributedSystem.java:290)

	at org.apache.geode.distributed.internal.InternalLocator.startDistributedSystem(InternalLocator.java:746)

	at org.apache.geode.distributed.internal.InternalLocator.startLocator(InternalLocator.java:392)

	at org.apache.geode.distributed.LocatorLauncher.start(LocatorLauncher.java:716)

	at org.apache.geode.distributed.LocatorLauncher.run(LocatorLauncher.java:623)

	at org.apache.geode.distributed.LocatorLauncher.main(LocatorLauncher.java:217)

Caused by: java.lang.SecurityException: Security check failed. Authentication error. Please check your credentials.

	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.attemptToJoin(GMSJoinLeave.java:504)

	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.join(GMSJoinLeave.java:363)

	at org.apache.geode.distributed.internal.membership.gms.GMSMembership.join(GMSMembership.java:533)

	at org.apache.geode.distributed.internal.membership.gms.GMSMembership.access$1200(GMSMembership.java:72)

	at org.apache.geode.distributed.internal.membership.gms.GMSMembership$ManagerImpl.joinDistributedSystem(GMSMembership.java:1752)

	at org.apache.geode.distributed.internal.membership.gms.Services.start(Services.java:242)

	at org.apache.geode.distributed.internal.membership.gms.GMSMembership.start(GMSMembership.java:1642)

	at org.apache.geode.distributed.internal.DistributionImpl.start(DistributionImpl.java:171)

	... 13 more
```

**To Reproduce**

1. Deploy the dataplatforms blueprint using the below command
```
helm install bp3 dataplatform-bp3 \
    --set geode.metrics.enabled=true \                                                                                          
    --set postgresql-ha.metrics.enabled=true
```
2. Change the postgresql-ha replicas in values.yaml file
3. Upgrade the chart using the below command
```
helm upgrade bp3 -f values2.yaml --set postgresql-ha.postgresql.password=$POSTGRESQL_PASSWORD --set postgresql-ha.postgresql.repmgrPassword=$REPMGR_PASSWORD --set postgresql-ha.pgpool.adminPassword=$ADMIN_PASSWORD --set geode.auth.password=$PASSWORD dataplatform-bp3
```

**Expected behavior**
Geode pods should be running fine without going to  "CrashLoopBackOff" state. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+vmware.1", GitCommit:"f4553304874c3b89584280a5ac1b005d57c725a8", GitTreeState:"clean", BuildDate:"2021-03-22T17:07:14Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9+vmware.1", GitCommit:"7131318a3deb1893fcf6493d8f6ed25c8f5c2ecb", GitTreeState:"clean", BuildDate:"2021-07-25T19:11:13Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

Also, Please help me understand the below  queries:
1. How can we upgrade one particular subchart in Helm.
2. If I am trying to update one of the subcharts via helm upgrade, why all the other subcharts gets updated.

**Comment by yilmi** [comment]
Hi @banicr,

You're referring to a chart that doesn't exist in our catalog, therefore I can't really help if I don't have the chart details.

Thanks,
Yass
