### ISSUE TITLE
[bitnami/kafka] Set headless service to publishNotReadyAddresses

### ISSUE THREAD

**Issue by philschleier** [bitnami/charts#7846]
**Which chart**:
kafka-14.2.1

**Describe the bug**
When doing a `kubectl rollout restart sts` on the kafka statefulset produced by this chart, a producer using Shopify/sarama would produce a lot of errors like `Request was for a topic or partition that does not exist on this broker` or `In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes`. 

The brokers themselves would produce errors as well:

```
[2021-10-18 15:28:40,942] WARN [Controller id=0, targetBrokerId=2] Error connecting to node kafka-2.kafka-headless.kafka.svc.cluster.local:9093 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: druid-kafka-2.druid-kafka-headless.druid.svc.cluster.local
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:111)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:513)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:172)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:985)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:292)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:246)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
```

In a statefulset rollout, a node is restarted as soon as the previous one is ready. If `publishNotReadyAddresses` is not enabled on the headless service, then the previous node's hostname is published at the same time as this next node shuts down, which as far as I can tell leads to some kind of race condition and temporarily messes with the availability of the cluster.

**To Reproduce**

1. Deploy cluster
2. Run `kubectl rollout restart sts ...`

**Expected behavior**
A clean, error-free restart of all nodes in order. It looks to me like adding `publishNotReadyAddresses: true` to the headless service achieves this. The brokers have no issues looking up the other hostnames and the producers seem happy as well.

**Comment by juan131** [comment]
Hi @philschleier 

I'd say that these errors are expected during a rollout.. I mean, if you include in your produce a broker hostname, it's normal that the producer complains while the broker is down.

> A clean, error-free restart of all nodes in order. It looks to me like adding publishNotReadyAddresses: true to the headless service achieves this. The brokers have no issues looking up the other hostnames and the producers seem happy as well.

IMHO, that would be very risky since you'll be promoting access to backend pods that are NOT ready (Kafka isn't initialized yet). I mean, you'll be substituting an error complaining about an "Unknown host" with an error complaining about an "unresponsive" broker.
