### ISSUE TITLE
bitnami/spark worker nodes are unable to communicate with each other

### ISSUE THREAD

**Issue by banicr** [bitnami/charts#8006]
**Which chart**:
spark version 5.7.9

**Describe the bug**
I have deployed spark helm chart and integrated with TSM(Tanzu service mesh). When I trigger spark application, the spark worker nodes are unable to communicate with each other(The driver is not able to talk to the executor).

**To Reproduce**
1. deploy helm chart
2. Integrate with TSM
3. Trigger spark application

**Expected behavior**
Spark worker nodes should be able to communicate with each other

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+vmware.1", GitCommit:"f4553304874c3b89584280a5ac1b005d57c725a8", GitTreeState:"clean", BuildDate:"2021-03-22T17:07:14Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+87cc9a4", GitCommit:"87cc9a4ade7ebee64def2489b78c9d8ae5d6fdf9", GitTreeState:"clean", BuildDate:"2021-06-19T03:11:54Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Could you share the logs with the errors? Does the issue happen before integrating with TSM? We would like to understand when the issue takes place.

**Comment by banicr** [comment]
Hi @javsalgar , issue happens only after integrating with TSM, here are the logs:
```
21/11/02 11:54:33 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
21/11/02 11:54:34 INFO TransportClientFactory: Successfully created connection to dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909 after 69 ms (0 ms spent in bootstraps)
21/11/02 11:54:34 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909 is closed
21/11/02 11:54:34 INFO TransportClientFactory: Found inactive connection to dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909, creating a new one.
21/11/02 11:54:34 INFO TransportClientFactory: Successfully created connection to dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909 after 1 ms (0 ms spent in bootstraps)
21/11/02 11:54:34 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909 is closed
21/11/02 11:54:34 INFO TransportClientFactory: Found inactive connection to dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909, creating a new one.
21/11/02 11:54:34 INFO TransportClientFactory: Successfully created connection to dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909 after 1 ms (0 ms spent in bootstraps)
21/11/02 11:54:34 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909 is closed
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1748)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:393)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:382)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:413)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:411)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	... 4 more
Caused by: java.io.IOException: Connection from dp-spark-worker-0.dp-spark-headless.dp.svc.cluster.local/192.168.248.107:42909 closed
	at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
	at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:117)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:225)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
Also, I tried I tried creating a headless service with fixed ports to spark worker, block and driver. but spark driver port always tries to connect to the next available port and it fails. For example I specified port 9600 nad it tries to connect to 9601 port and fails.
```
  ports:
  - name: tcp-driver
    port: 9600
    protocol: TCP
    targetPort: driver
  - name: tcp-block
    port: 9900
    protocol: TCP
    targetPort: block
  - name: tcp-worker
    port: 9700
    protocol: TCP
    targetPort: worker
```

**Comment by javsalgar** [comment]
Hi,

Do you have Istio enabled in TSM? It could be that the istio sidecar is closing the connection for some reason.
