### ISSUE TITLE
Unable to bring back kafka server and getting Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /brokers/ids

### ISSUE THREAD

**Issue by cah-nitin-janavekar** [bitnami/charts#8080]
**Which chart**:
Kafka helm chart using Community Edition version 5.5.1

**Describe the bug**
Hi All, I am renewing my kafka certificate on my GKE (Google Kubernetes cluster) platform. When I try to deploy new certificate on my old PVCs then getting below error but I am going to use fresh PVC, didnt see any error.
```bash
[2021-10-27 21:38:37,249] INFO channel is connected: [id: 0x9b50d380, L:/10.58.39.61:60794 - R:ent-stg-cp-zookeeper/10.58.54.53:2281] (org.apache.zookeeper.ClientCnxnSocketNetty)
[2021-10-27 21:38:37,560] INFO Session establishment complete on server stg-cp-zookeeper/10.50.34.35:2281, sessionid = 0x304f94c37990008, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2021-10-27 21:38:37,563] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2021-10-27 21:38:37,623] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /brokers/ids
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:120)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at kafka.zookeeper.AsyncResponse.maybeThrow(ZooKeeperClient.scala:569)
        at kafka.zk.KafkaZkClient.createRecursive(KafkaZkClient.scala:1644)
        at kafka.zk.KafkaZkClient.makeSurePersistentPathExists(KafkaZkClient.scala:1566)
        at kafka.zk.KafkaZkClient.$anonfun$createTopLevelPaths$1(KafkaZkClient.scala:1558)
        at kafka.zk.KafkaZkClient.$anonfun$createTopLevelPaths$1$adapted(KafkaZkClient.scala:1558)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at kafka.zk.KafkaZkClient.createTopLevelPaths(KafkaZkClient.scala:1558)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:425)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:231)
        at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:114)
        at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)
[2021-10-27 21:38:37,625] INFO shutting down (kafka.server.KafkaServer)
[2021-10-27 21:38:37,628] INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient)
[2021-10-27 21:38:37,633] INFO channel is told closing (org.apache.zookeeper.ClientCnxnSocketNetty)
[2021-10-27 21:38:37,635] INFO channel is disconnected: [id: 0x9b50d380, L:/10.58.39.61:60794 ! R:ent-stg-cp-zookeeper/10.58.54.53:2281] (org.apache.zookeeper.ClientCnxnSocketNetty)
[2021-10-27 21:38:37,635] INFO channel is told closing (org.apache.zookeeper.ClientCnxnSocketNetty)
[2021-10-27 21:38:37,635] INFO Session: 0x304f94c37990008 closed (org.apache.zookeeper.ZooKeeper)
[2021-10-27 21:38:37,635] INFO EventThread shut down for session: 0x304f94c37990008 (org.apache.zookeeper.ClientCnxn)
[2021-10-27 21:38:37,637] INFO [ZooKeeperClient Kafka server] Closed. (kafka.zookeeper.ZooKeeperClient)
[2021-10-27 21:38:37,640] INFO shut down completed (kafka.server.KafkaServer)
[2021-10-27 21:38:37,641] INFO Shutting down SupportedServerStartable (io.confluent.support.metrics.SupportedServerStartable)
[2021-10-27 21:38:37,641] INFO Closing BaseMetricsReporter (io.confluent.support.metrics.BaseMetricsReporter)
[2021-10-27 21:38:37,641] INFO Waiting for metrics thread to exit (io.confluent.support.metrics.SupportedServerStartable)
[2021-10-27 21:38:37,641] INFO Shutting down KafkaServer (io.confluent.support.metrics.SupportedServerStartable)
[2021-10-27 21:38:37,641] INFO shutting down (kafka.server.KafkaServer)
```
current configuration ::-
```bash
## Zookeeper Configuration
tickTime: 2000
syncLimit: 5
initLimit: 10
maxClientCnxns: 300
autoPurgeSnapRetainCount: 3
autoPurgePurgeInterval: 24
configurationOverrides:
  #enable SSL between zookeeper and other Kafka components
  "secure.Client.Port" : 2281 
  "client.secure" : true  
  "server.cnxn.factory" : org.apache.zookeeper.server.NettyServerCnxnFactory
  "auth.provider.x509" : org.apache.zookeeper.server.auth.X509AuthenticationProvider
  "ssl.keyStore.location" : kafka.stg.server.keystore.jks
  "ssl.trustStore.location" : kafka.stg.server.truststore.jks
  "ssl.truststore.type" : JKS
  "ssl.client.Auth" : need
  "ssl.endpoint.identification.algorithm": ''

**** Broker configurations **********
configurationOverrides:
  "offsets.topic.replication.factor": "3"
  "default.replication.factor": "3"
  "min.insync.replicas": 2
  "auto.create.topics.enable": true  ## Cannnot be set to False as schema registry and rest proxy will not work
    "security.inter.broker.protocol": SSL
  "advertised.listeners": |-
   SSL://stg-cp-kafka-${KAFKA_BROKER_ID}:9093,EXTERNAL://kafka.brk${KAFKA_BROKER_ID}.stg.com:9094,ISTIO://brk${KAFKA_BROKER_ID}.kafka.stg.gcp.cahcloud.net:31400
  "listener.security.protocol.map": |- 
   PLAINTEXT:PLAINTEXT,SSL:SSL,EXTERNAL:SSL,ISTIO:SSL
  "authorizer.class.name" : "kafka.security.authorizer.AclAuthorizer"
   super.users" : User:CN=Kafka-stg.net,O=ABC,L=London,ST=London,C=GB
  "allow.everyone.if.no.acl.found": "false"
  "ssl.truststore.location" : kafka.stg.server.truststore.jks
  "ssl.keystore.location" : kafka.stg.server.keystore.jks
  "ssl.endpoint.identification.algorithm": ''
  "ssl.client.auth": required
  
  ## mTLS-to-ZooKeeper

  zookeeper.connect : stg-cp-zookeeper:2281  ## Zookeeper LoadBalancer
  zookeeper.connection.timeout.ms : 30000
  zookeeper.sync.time.ms : 30000
  zookeeper.ssl.client.enable : true
  zookeeper.client.Cnxn.Socket : org.apache.zookeeper.ClientCnxnSocketNetty
  zookeeper.client.secure : true
  zookeeper.ssl.protocol : SSL
  zookeeper.ssl.enabled.protocols : SSL
  zookeeper.ssl.keystore.location : kafka.stg.client.keystore.jks
  zookeeper.ssl.truststore.location : kafka.stg.client.truststore.jks
  zookeeper.ssl.endpoint.identification.algorithm : ''
  zookeeper.set.acl : true
```
**Version of Helm and Kubernetes**:

- Output of `helm version`:
```bash
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```
- Output of `kubectl version`:
```bash
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T08:10:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @cah-nitin-janavekar,

The error seems related to the variable [broker.id](https://kafka.apache.org/documentation/#brokerconfigs_broker.id), could you check the value?

**Comment by ishasenthila** [comment]
> Hi @cah-nitin-janavekar,
> 
> The error seems related to the variable [broker.id](https://kafka.apache.org/documentation/#brokerconfigs_broker.id), could you check the value?

I am also facing the same issue. could you please elaborate on what is missing or misconfigured

**Comment by migruiz4** [comment]
Hi @ishasenthila,

In this case, although no feedback was provided, I think the issue was caused by the setting `broker.id` missing in @cah-nitin-janavekar 's configuration.
