### ISSUE TITLE
bin/spark-submit from spark README will error with "SparkException: Must specify the driver container image"

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#8118]
**Which chart**:

spark

**Describe the bug**

Spark chart readme, ["Submit an Application"](https://github.com/bitnami/charts/tree/master/bitnami/spark#submit-an-application), is missing the required `--conf spark.kubernetes.container.image` as shown here:

https://spark.apache.org/docs/latest/running-on-kubernetes.html#cluster-mode

**To Reproduce**

```
bin/spark-submit \
  --class org.apache.spark.examples.SparkPi \
  --master k8s://https://REDACTED.gr7.REDACTED.eks.amazonaws.com:REDACTED \
  --deploy-mode cluster \
  --name spark-pi \
  ./examples/jars/spark-examples_2.12-3.2.0.jar \
  1000
```

Error:

```
Exception in thread "main" org.apache.spark.SparkException: Must specify the driver container image
	at org.apache.spark.deploy.k8s.features.BasicDriverFeatureStep.$anonfun$driverContainerImage$1(BasicDriverFeatureStep.scala:45)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.deploy.k8s.features.BasicDriverFeatureStep.<init>(BasicDriverFeatureStep.scala:45)
	at org.apache.spark.deploy.k8s.submit.KubernetesDriverBuilder.buildFromFeatures(KubernetesDriverBuilder.scala:46)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:106)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4(KubernetesClientApplication.scala:220)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4$adapted(KubernetesClientApplication.scala:214)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2713)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:214)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:186)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/11/12 14:58:53 INFO ShutdownHookManager: Shutdown hook called
21/11/12 14:58:53 INFO ShutdownHookManager: Deleting directory /tmp/spark-180d457b-8f9b-4330-ae8a-badc8e196ad1
```

**Expected behavior**

If you are going to give a "hello world" example, it should work as-is.

Amusingly in [Bitnami's own blog](https://docs.bitnami.com/tutorials/process-data-spark-kubernetes/), you don't even do it this way; you run a `kubectl exec` and submit to a `spark://` URL with the master-svc as the destination rather than submitting to the kube-apiserver with a k8s:// URL.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @brsolomon-deloitte 

Thanks so much for pointing this out. I just did a commit updating the README.md, see:

- https://github.com/bitnami/charts/commit/2e99b7de4d2c8fb576567003611a3d829a86ed85

> Amusingly in Bitnami's own blog, you don't even do it this way; you run a kubectl exec and submit to a spark:// URL with the master-svc as the destination rather than submitting to the kube-apiserver with a k8s:// URL.

Please note that blog post was writing almost a year ago. Software projects evolve with the time, so they evolve the preferred way to perform certain actions. We always use the upstream project documentation as the reference to build or examples, blogs and README.md(s). That said, they can get outdated with the time.

Outdated docs are a very good sign IMHO, they mean the project is alive!

**Comment by brsolomon-deloitte** [comment]
@juan131 thanks and sorry if I worded that rudely. I realize the conventions shown by the upstream doc can and will change over time. Thanks for correcting.

**Comment by juan131** [comment]
Don't worry @brsolomon-deloitte !! Thank you for being proactive and contact us to report the outdated examples.
