### ISSUE TITLE
Intermittent connection errors to DB

### ISSUE THREAD

**Issue by aditiagarwal30nov** [bitnami/charts#8186]
**Which chart**:
Airflow, 2.1.4-debian-10-r15
Running on Azure K8s service using Azure Postgres SQL server

**Describe the bug**
After upgrading to v2, we are experiencing that the worker intermittently is not able to connect to the DB and throws the below error, although the DB is correct running and not overloaded and has ability to receive more connections:
```
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection timed out
	Is the server running on host "postgresphdhuatairflow.postgres.database.azure.com" (40.78.233.2) and accepting
	TCP/IP connections on port 5432?

```
Config
SQL connection pool: 10
Database can support: > 200

Scheduler around the same time shows this error:
```
[2021-11-18 09:43:12,730] {manager.py:1165} ERROR - Processor for /opt/bitnami/airflow/dags/dynamic/pph_profile_batch_ingestion_v2.py with PID 15642 started at 2021-11-18T09:42:22.355213+00:00 has timed out, killing it.
[2021-11-18 09:43:12,731] {processor.py:243} WARNING - Killing DAGFileProcessorProcess (PID=15642)
Process ForkProcess-2:
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 370, in _run_processor_manager
    processor_manager.start()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 610, in start
    return self._run_parsing_loop()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 671, in _run_parsing_loop
    self._collect_results_from_processor(processor)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 981, in _collect_results_from_processor
    if processor.result is not None:
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 321, in result
    if not self.done:
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 286, in done
    if self._parent_channel.poll():
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

Postgres server logs show this:
```
2021-11-17 03:51:32 UTC-61947c44.b5438-LOG:  connection received: host=20.197.100.129 port=12520 pid=742456
2021-11-17 03:51:32 UTC-61947c44.b5438-LOG:  connection authorized: user=postgresairflowuserdatabase=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)
2021-11-17 03:51:32 UTC-61947c44.b543c-LOG:  connection received: host=20.197.100.129 port=7684 pid=742460
2021-11-17 03:51:32 UTC-61947c44.b543c-LOG:  connection authorized: user=postgresairflowuserdatabase=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)
2021-11-17 03:51:33 UTC-61947c45.b5440-LOG:  connection received: host=20.197.100.129 port=33472 pid=742464
2021-11-17 03:51:33 UTC-61947c45.b5440-LOG:  connection authorized: user=postgresairflowuserdatabase=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)
2021-11-17 03:51:33 UTC-61947c45.b5444-LOG:  connection received: host=20.197.100.129 port=30978 pid=742468
2021-11-17 03:51:33 UTC-61947c45.b5444-LOG:  connection authorized: user=postgresairflowuserdatabase=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)
2021-11-17 03:51:33 UTC-61947c45.b5444-LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.

```
**To Reproduce**

1. Upgrade to v2
2. Trigger dags
3. Intermittently see error
4. Logs for the task are also lost on the UI

**Expected behavior**
We do not expect the logs for the failed task to be not available and also not the task to fail and scheduler restarts sometimes.

**Version of Helm and Kubernetes**:
Helm: v2.16.9
K8s: 1.20.9
Postgres: v10

**Additional context**
On rerunning this failed task it goes through with no issue. But re-running the dag, some other task will fail with the same error.

**Comment by marcosbc** [comment]
Hi @aditiagarwal30nov, this definitely seems like a network issue in your cluster:

```
psycopg2.OperationalError: could not connect to server: Connection timed out
	Is the server running on host "postgresphdhuatairflow.postgres.database.azure.com" (40.78.233.2) and accepting
	TCP/IP connections on port 5432?
```

We recommend that you check the database load, but also any network related stats, as it may help you identify the problem.
