### ISSUE TITLE
[bitnami/airflow] Airflow worker pod start successfully even if it fails to init

### ISSUE THREAD

**Issue by Pol-Valentin** [bitnami/charts#8207]
**Which chart**:
Airflow 10.3.1

**Describe the bug**
On airflow worker pod, when cloning repositories in the "clone-repositories" init container, if it fails to clone a repository, the pod will still be started and affected task from the airflow scheduler, but will not be able to run them as it doesn't have repositories.

**To Reproduce**

1. Make init container fails to clone a repository
2. Run a DAG on airflow 
3. When a task is affected to this pod, see error

**Expected behavior**
The pod should fail to start if it can not clone a repository.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I think [this PR](https://github.com/bitnami/charts/pull/6063) should be reverted. That's not okay to start a pod if init fails.

**Comment by Mauraza** [comment]
Hi @Pol-Valentin,

Could you share the error and the values or example values are you using?

**Comment by Pol-Valentin** [comment]
Hi @Mauraza,

I can't send you my values because it's the one in production and there is secret in it.

I had these logs in my init container which clone repositories : 
```
$kubectl logs -f airflow-worker-0 -c clone-repositories
Cloning into '/dags_data-etl-dbt'...
Cloning into '/dags_data-etl-batch'...
fatal: unable to access 'https://github.com/Evaneos/data-etl-batch.git/': The requested URL returned error: 503
```
But it didn't fail as there is a `|| true` [after the git clone](https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/_git_helpers.tpl#L101)

So my pod was available as a worker for airflow, but when airflow send it tasks, I have thise kind of logs in my worker :
```
$kubectl logs -f airflow-worker-0 -c airflow-worker
[2021-11-22 08:36:18,901: INFO/MainProcess] Received task: airflow.executors.celery_executor.execute_command[03516ec3-ed33-48bf-a1f5-03f07e32947b]  
[2021-11-22 08:36:18,925: INFO/ForkPoolWorker-6] Executing command in Celery: ['airflow', 'tasks', 'run', 'dbt_daily_8', 'dbt_run_monitoring_after', '2021-11-21T08:30:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/opt/bitnami/airflow/dags/git_data-etl-batch/transformers/dbt_daily_8.py']
[2021-11-22 08:36:19,017: INFO/ForkPoolWorker-6] Filling up the DagBag from /opt/bitnami/airflow/dags/git_data-etl-batch/transformers/dbt_daily_8.py
[2021-11-22 08:36:19,438: ERROR/ForkPoolWorker-6] Failed to execute task dag_id could not be found: dbt_daily_8. Either the dag did not exist or it failed to parse..
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 117, in _execute_in_fork
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 220, in task_run
    dag = get_dag(args.subdir, args.dag_id)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 191, in get_dag
    raise AirflowException(
airflow.exceptions.AirflowException: dag_id could not be found: dbt_daily_8. Either the dag did not exist or it failed to parse.
[2021-11-22 08:36:19,489: ERROR/ForkPoolWorker-6] Task airflow.executors.celery_executor.execute_command[03516ec3-ed33-48bf-a1f5-03f07e32947b] raised unexpected: AirflowException('Celery command failed on host: airflow-worker-0.airflow-worker-headless.airflow.svc.cluster.local')
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 88, in execute_command
    _execute_in_fork(command_to_exec)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 99, in _execute_in_fork
    raise AirflowException('Celery command failed on host: ' + get_hostname())
airflow.exceptions.AirflowException: Celery command failed on host: airflow-worker-0.airflow-worker-headless.airflow.svc.cluster.local
```
It can not find the dags as the repo has not been cloned.

**Comment by Mauraza** [comment]
Hi @Pol-Valentin,

> fatal: unable to access 'https://github.com/Evaneos/data-etl-batch.git/': The requested URL returned error: 503

It seems you can't access that repository, maybe is a repository only-read. 
Could you check if you can run a git clone of that repository in the console of airflow?

**Comment by Pol-Valentin** [comment]
Yes, Its a private repo, I have access on it but I think github was unavailable when the pod started. My problem is more that we let the airflow worker pod to be ready even if the git clone of the dags has failed.

**Comment by Mauraza** [comment]
Hi @Pol-Valentin,

I think that question is more related with related to airflow behavior. You can create a issue in the airflow repository about this https://github.com/apache/airflow/issues

**Comment by Pol-Valentin** [comment]
Hi @Mauraza,

Sorry but I disagree, we just have to remove the `|| true` at the end of the [command which clone the repository](https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/_git_helpers.tpl#L101) and the pod will not be ready, neither the airflow scheduler.

**Comment by javsalgar** [comment]
Hi,

Looking at the context of the `|| true`, it is related to this https://github.com/bitnami/charts/pull/6063

I think it makes sense that the sync has this || true but not the init container. Would you like to contribute with a PR?

**Comment by Pol-Valentin** [comment]
Hi @javsalgar,

Here it is : https://github.com/bitnami/charts/pull/8342

**Comment by juan131** [comment]
Thanks @Pol-Valentin ! Your PR was merged, in a few hours a new version of the chart including your changes will be released

**Comment by Pol-Valentin** [comment]
Thanks @juan131 !
