### ISSUE TITLE
Fluentd on top of EKS: sending logs to AWS Elasticsearch but a pod is crashing

### ISSUE THREAD

**Issue by abhassine** [bitnami/charts#8310]
**Which chart**:
fluentd-3.4.0                     	App Version: 1.12.0

**Describe the bug**
Hey Folks,
I have some strange behaviour using Fluentd from bitnami version 1.12.0-debian-10-r40 running on top of EKS v 1.19 and sucessfully sending logs to AWS Easticsearch service 7.10. however one of the pod is not ready and CrashingloopBackOff

```
NAME                                   READY     STATUS      RESTARTS   AGE
fluentd-elasticsearch-0                1/1       Running     0          8h
fluentd-elasticsearch-7l9z8            1/1       Running     0          8h
fluentd-elasticsearch-hgd75            0/1       Running     113        8h
and the issue is following :
```
```
$ klon logging           fluentd-elasticsearch-hgd75

fluentd 22:58:02.07
fluentd 22:58:02.07 Welcome to the Bitnami fluentd container
fluentd 22:58:02.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-fluentd
fluentd 22:58:02.08 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-fluentd/issues
fluentd 22:58:02.08
fluentd 22:58:02.08 INFO  ==> ** Starting Fluentd setup **
fluentd 22:58:02.09 INFO  ==> ** Fluentd setup finished! **

fluentd 22:58:02.09 INFO  ==> ** Starting Fluentd **
2021-12-03 22:58:02 +0000 [info]: parsing config file is succeeded path="/opt/bitnami/fluentd/conf/fluentd.conf"
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.13'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.3.3'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-grafana-loki' version '1.2.16'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-kafka' version '0.15.3'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.2'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.8.5'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-s3' version '1.5.0'
2021-12-03 22:58:02 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2021-12-03 22:58:02 +0000 [info]: gem 'fluentd' version '1.12.0'
2021-12-03 22:58:02 +0000 [info]: gem 'fluentd' version '1.11.5'
2021-12-03 22:58:02 +0000 [warn]: 'type' is deprecated parameter name. use '@type' instead.
2021-12-03 22:58:04 +0000 [info]: 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2021-12-03 22:58:04 +0000 [warn]: define <match fluent.**> to capture fluentd logs in top level is deprecated. Use <label @FLUENT_LOG> instead
2021-12-03 22:58:04 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    path "/var/log/containers/*.log"
    pos_file "/var/log/es-containers.log.pos"
    time_format %Y-%m-%dT%H:%M:%S.%N
    tag "kubernetes.*"
    format json
    read_from_head true
    keep_time_key true
    <parse>
      @type "multi_format"
      unmatched_lines
      <pattern>
        format json
        time_key "time"
        time_type string
        time_format "%Y-%m-%dT%H:%M:%S.%NZ"
        keep_time_key false
      </pattern>
    </parse>
  </source>
  <filter kubernetes.**>
    type kubernetes_metadata
  </filter>
  <filter **>
    @type record_transformer
    <record>
      eks_cluster ada-uso-tsa-plt1
    </record>
  </filter>
  <filter **>
    @type parser
    @log_level "trace"
    key_name "log"
    reserve_data true
    remove_key_name_field true
    emit_invalid_record_to_error false
    <parse>
      @type "json"
    </parse>
  </filter>
  <match @FLUENT_LOG>
    @type null
  </match>
  <match fluentd.healthcheck>
    @type stdout
  </match>
  <match **>
    @type elasticsearch
    include_tag_key true
    host "vpc-es-ada-uso-tsa-plt1-3fpa4fbab3ynje2i2xaoj4kveu.us-east-2.es.amazonaws.com"
    port 443
    scheme https
    logstash_format true
    logstash_dateformat "%Y-%m-%d"
    logstash_prefix "ada-uso-tsa-plt1"
    max_retry_wait 60
    disable_retry_limit
    type_name "fluentd"
    time_key "time"
    reload_connections false
    reload_on_failure true
    reconnect_on_error true
    flush_interval 5s
    <buffer>
      flush_thread_count 8
      flush_interval 1s
      chunk_limit_size 10M
      queue_limit_length 16
      retry_max_interval 30
      retry_forever true
    </buffer>
  </match>
</ROOT>
2021-12-03 22:58:04 +0000 [info]: starting fluentd-1.12.0 pid=1 ruby="2.6.6"
2021-12-03 22:58:04 +0000 [info]: spawn command to main:  cmdline=["/opt/bitnami/ruby/bin/ruby", "-Eascii-8bit:ascii-8bit", "/opt/bitnami/fluentd/bin/fluentd", "--config", "/opt/bitnami/fluentd/conf/fluentd.conf", "--plugin", "/opt/bitnami/fluentd/plugins", "--under-supervisor"]
2021-12-03 22:58:05 +0000 [warn]: #0 'type' is deprecated parameter name. use '@type' instead.
2021-12-03 22:58:05 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2021-12-03 22:58:05 +0000 [info]: adding filter pattern="**" type="record_transformer"
2021-12-03 22:58:05 +0000 [info]: adding filter pattern="**" type="parser"
2021-12-03 22:58:05 +0000 [info]: adding match pattern="@FLUENT_LOG" type="null"
2021-12-03 22:58:05 +0000 [info]: adding match pattern="fluentd.healthcheck" type="stdout"
2021-12-03 22:58:06 +0000 [info]: adding match pattern="**" type="elasticsearch"
2021-12-03 22:58:07 +0000 [info]: #0 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2021-12-03 22:58:07 +0000 [warn]: #0 Detected ES 7.x: `_doc` will be used as the document `_type`.
2021-12-03 22:58:07 +0000 [info]: adding source type="tail"
2021-12-03 22:58:07 +0000 [warn]: #0 define <match fluent.**> to capture fluentd logs in top level is deprecated. Use <label @FLUENT_LOG> instead
2021-12-03 22:58:07 +0000 [warn]: parameter 'time_format' in <source>
  @type tail
  path "/var/log/containers/*.log"
  pos_file "/var/log/es-containers.log.pos"
  time_format %Y-%m-%dT%H:%M:%S.%N
  tag "kubernetes.*"
  format json
  read_from_head true
  keep_time_key true
  <parse>
    @type "multi_format"
    unmatched_lines
    <pattern>
      format json
      time_key "time"
      time_type string
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      keep_time_key false
    </pattern>
  </parse>
</source> is not used.
2021-12-03 22:58:07 +0000 [warn]: parameter 'format' in <source>
  @type tail
  path "/var/log/containers/*.log"
  pos_file "/var/log/es-containers.log.pos"
  time_format %Y-%m-%dT%H:%M:%S.%N
  tag "kubernetes.*"
  format json
  read_from_head true
  keep_time_key true
  <parse>
    @type "multi_format"
    unmatched_lines
    <pattern>
      format json
      time_key "time"
      time_type string
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      keep_time_key false
    </pattern>
  </parse>
</source> is not used.
2021-12-03 22:58:07 +0000 [warn]: parameter 'keep_time_key' in <source>
  @type tail
  path "/var/log/containers/*.log"
  pos_file "/var/log/es-containers.log.pos"
  time_format %Y-%m-%dT%H:%M:%S.%N
  tag "kubernetes.*"
  format json
  read_from_head true
  keep_time_key true
  <parse>
    @type "multi_format"
    unmatched_lines
    <pattern>
      format json
      time_key "time"
      time_type string
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      keep_time_key false
    </pattern>
  </parse>
</source> is not used.
2021-12-03 22:58:07 +0000 [warn]: parameter 'max_retry_wait' in <match **>
  @type elasticsearch
  include_tag_key true
  host "vpc-es-ada-uso-tsa-plt1-3fpa4fbab3ynje2i2xaoj4kveu.us-east-2.es.amazonaws.com"
  port 443
  scheme https
  logstash_format true
  logstash_dateformat "%Y-%m-%d"
  logstash_prefix "ada-uso-tsa-plt1"
  max_retry_wait 60
  disable_retry_limit
  type_name "fluentd"
  time_key "time"
  reload_connections false
  reload_on_failure true
  reconnect_on_error true
  flush_interval 5s
  <buffer>
    flush_thread_count 8
    flush_interval 1s
    chunk_limit_size 10M
    queue_limit_length 16
    retry_max_interval 30
    retry_forever true
  </buffer>
</match> is not used.
2021-12-03 22:58:07 +0000 [warn]: parameter 'disable_retry_limit' in <match **>
  @type elasticsearch
  include_tag_key true
  host "vpc-blablablbalba-3fpa4fbab3ynje2i2xaoj4kveu.us-east-2.es.amazonaws.com"
  port 443
  scheme https
  logstash_format true
  logstash_dateformat "%Y-%m-%d"
  logstash_prefix "ada-uso-tsa-plt1"
  max_retry_wait 60
  disable_retry_limit
  type_name "fluentd"
  time_key "time"
  reload_connections false
  reload_on_failure true
  reconnect_on_error true
  flush_interval 5s
  <buffer>
    flush_thread_count 8
    flush_interval 1s
    chunk_limit_size 10M
    queue_limit_length 16
    retry_max_interval 30
    retry_forever true
  </buffer>
</match> is not used.
i2xaoj4kveu.us-east-2.es.amazonaws.com\", :port=>443, :scheme=>\"https\"}): [413] {\"Message\":\"Request size exceeded 10485760 bytes\"}"
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/out_elasticsearch.rb:1085:in `rescue in send_bulk'
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/out_elasticsearch.rb:1047:in `send_bulk'
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/out_elasticsearch.rb:870:in `block in write'
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/out_elasticsearch.rb:869:in `each'
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/out_elasticsearch.rb:869:in `write'
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.12.0/lib/fluent/plugin/output.rb:1136:in `try_flush'
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.12.0/lib/fluent/plugin/output.rb:1448:in `flush_thread_run'
  2021-12-03 22:58:08 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.12.0/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
```

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

```
Message\":\"Request size exceeded 10485760 bytes
```

Could this be an issue in the AWS cluster load balancer configuration? Not sure if this can be checked in the AWS Panel

**Comment by Kydybets** [comment]
@abhassine 
suggest use this help chart in EKS
https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit

this config which is working for me,
we are having the 150GB of logs each day
```
resources:
    limits:
      cpu: 1100m
      memory: 900Mi
    requests:
      cpu: 100m
      memory: 384Mi
config:
    ## https://docs.fluentbit.io/manual/service
    service: |
      [SERVICE]
          Flush 1
          Daemon Off
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Parser docker
          Tag kube.*
          Mem_Buf_Limit 60MB
          Skip_Long_Lines Off
          Docker_Mode On
          Docker_Mode_Parser multiline_parser
      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On
      [INPUT]
          Name tail
          Path /var/log/messages
          Tag kubelet.*
          Parser kubelet
    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
      [FILTER]
          Name modify
          Match kube.*
          Add Level ERROR
          Condition Key_value_matches log ^.*[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}\s+ERROR\s.*$
      [FILTER]
          Name modify
          Match kube.*
          Add Level DEBUG
          Condition Key_value_matches log ^.*[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}\s+DEBUG\s.*$
      [FILTER]
          Name modify
          Match kube.*
          Add Level INFO
          Condition Key_value_matches log ^.*[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}\s+INFO\s.*$
      [FILTER]
          Name modify
          Match kube.*
          Add Level WARN
          Condition Key_value_matches log ^.*[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}\s+WARN\s.*$
      [FILTER]
          Name modify
          Match kubelet.*
          Add LogType kubelet

      
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host ~
          Logstash_Format On
          Retry_Limit False
      [OUTPUT]
          Name es
          Match host.*
          Host ~
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
    customParsers: |
      [PARSER]
          Name multiline_parser
          Format regex
          Regex /(?<log>^{"log":"[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}\s+(?<Level>\S+)\s+.*)/
      [PARSER]
          Name kubelet
          Format regex
          Regex /.*\s[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s(?<nodeName>ip-.*)\skubelet:\s(?<log>.*)/
          
```
