### ISSUE TITLE
ir_attachment issue in odoo pod while deploying on IBM cloud

### ISSUE THREAD

**Issue by truthfool** [bitnami/charts#8316]
odoo helm chart v12:

The UI of the odoo v12 does not appear on port forward.
I'm facing attachment issue while deploying odoo 12 on the IBM cloud. I'm using bitnami helm charts for the deployment of odoo pod on the IBM cloud. I cannot delete tables as "ir_attachment" has media files and has foreign key in another table.There is nothing in network logs too.

1. Go to 'charts/bitnami/odoo/'
2. Run using helm install ''helm install openg2p-erp12 -f values.yaml bitnami/odoo".(I have volume mounts on path '/mnt/extra-addons')
3. After pod initializes see the logs.

Logs of the odoo pod :
```
openg2p-erp12-odoo Traceback (most recent call last):                                                                                                      │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/api.py", line 1049, in get                                          │
│ openg2p-erp12-odoo     value = self._data[key][field][record._ids[0]]                                                                                      │
│ openg2p-erp12-odoo KeyError: 673                                                                                                                           │
│ openg2p-erp12-odoo During handling of the above exception, another exception occurred:                                                                     │
│ openg2p-erp12-odoo Traceback (most recent call last):                                                                                                      │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/fields.py", line 1064, in __get__                                   │
│ openg2p-erp12-odoo     value = record.env.cache.get(record, self)                                                                                          │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/api.py", line 1051, in get                                          │
│ openg2p-erp12-odoo     raise CacheMiss(record, field)                                                                                                      │
│ openg2p-erp12-odoo odoo.exceptions.CacheMiss: ('ir.attachment(673,).datas', None)                                                                          │
│ openg2p-erp12-odoo During handling of the above exception, another exception occurred:                                                                     │
│ openg2p-erp12-odoo Traceback (most recent call last):                                                                                                      │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read       │
│ openg2p-erp12-odoo     r = base64.b64encode(open(full_path,'rb').read())                                                                                   │
│ openg2p-erp12-odoo FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/odoo/data/filestore/openg2p/ba/ba534fd56e5dde52f5a9fe9a8c7451c4cb │
│ 2ba3b3'
```

Version of Helm and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"xxxxxxxxxxx", GitTreeState:"clean", GoVersion:"go1.14.11"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"xxxxxxxxxx", GitTreeState:"clean", BuildDate:"2021-07-15T21:01:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20+IKS", GitCommit:"xxxxxxxxxxxx", GitTreeState:"clean", BuildDate:"2021-06-18T14:01:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Please, note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart. This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
