### ISSUE TITLE
Get the following error: Cannot achieve consistency level LOCAL_ONE

### ISSUE THREAD

**Issue by LPinto98** [bitnami/charts#8404]
I have used the Apache Cassandra third-party service on IBM Cloud 
One of my three pods keeps throwing the following error: 
```
ERROR [main] 2021-12-14 07:21:26,508 CassandraDaemon.java:774 - Exception encountered during startup
java.lang.RuntimeException: A node required to move the data consistently is down (/172.30.160.84). If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
        at org.apache.cassandra.dht.RangeStreamer.getAllRangesWithStrictSourcesFor(RangeStreamer.java:294) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.dht.RangeStreamer.addRanges(RangeStreamer.java:177) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.dht.BootStrapper.bootstrap(BootStrapper.java:87) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:1530) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1024) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:718) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:652) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:397) [apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:630) [apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757) [apache-cassandra-3.11.6.jar:3.11.6]
INFO  [StorageServiceShutdownHook] 2021-12-14 07:21:26,512 HintsService.java:209 - Paused hints dispatch
WARN  [StorageServiceShutdownHook] 2021-12-14 07:21:26,513 Gossiper.java:1655 - No local state, state is in silent shutdown, or node hasn't joined, not announcing shutdown
INFO  [StorageServiceShutdownHook] 2021-12-14 07:21:26,513 MessagingService.java:985 - Waiting for messaging service to quiesce
INFO  [ACCEPT-/172.30.160.89] 2021-12-14 07:21:26,514 MessagingService.java:1346 - MessagingService has terminated the accept() thread
```

And when I run my application, I get the following error while inserting data: 
```
"msg": "Cannot achieve consistency level LOCAL_ONE"
```

**To Reproduce**

1. Installed the jaeger-tracing on kubernetes cluster using cassandra ( https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger )
2. Create a service in ibm cloud using the Apache Cassandra by Bitnami package 

**Expected behavior**
The spans from Jaeger to go in Cassandra 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+IKS", GitCommit:"8d49554e103d584f952cc4d28dcf9f410c268847", GitTreeState:"clean", BuildDate:"2021-11-18T19:18:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
How are you deploying the Cassandra Helm chart? Can you share the values you are using to deploy the chart?

**Comment by LPinto98** [comment]
@carrodher  I'm using the package service from IBM Cloud ( https://cloud.ibm.com/catalog/content/cassandra-Qml0bmFtaS1jYXNzYW5kcmE=-global ), I haven't made any changes to the default configuration, and I don't see any configuration for the consistency level.

**Comment by carrodher** [comment]
Unfortunately, I am not sure how can we help with this issue since it seems a very custom deployment. I just launched Cassandra with default parameters and only one replica is created, not sure why in your case you have 3 pods:
```console
$  kubectl get pods -n cassandra
NAME          READY   STATUS    RESTARTS   AGE
cassandra-0   1/1     Running   0          40m
```

For information regarding the application itself or customization of the content within the application, we highly recommend checking forums and user guides made available by the project behind the application.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by LPinto98** [comment]
@carrodher  I get 1 pod only, but for some reason the consistency level is set to Local_one
