### ISSUE TITLE
[bitnami/mongodb] Cannot connect to mongo instance after downscaling statefulset mongodb from 2 to 1 because mongo are looking for missing statefulset instance.

### ISSUE THREAD

**Issue by percenuage** [bitnami/charts#8419]
**Which chart**:
bitnami/mongodb@10.26.4

**Describe the bug**
I have a statefulset mongo instance with 2 replica (`hyper-db-0` and` hyper-db-1` pod names + 1 arbiter). My apps/pods are connecting to the instance using this uri: `mongodb://user:pass@hyper-db-headless/hyper-landlord? authSource=admin&replicaSet=rs0&readPreference=primaryPreferred`. By now all are working well.

I would like to have only 1 replica of mongo (`hyper-db-0` without arbiter). But some pods are connecting well and some others cannot connect connect to mongo. This is the application error:

```
Something went wrong while launching the server MongooseServerSelectionError: getaddrinfo ENOTFOUND hyper-db-1.hyper-db-headless.default.svc.cluster.local
    at Function.Model.$wrapCallback (/home/node/node_modules/mongoose/lib/model.js:5078:32)
    at /home/node/node_modules/mongoose/lib/query.js:4510:21
    at /home/node/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/node/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at model.Query.exec (/home/node/node_modules/mongoose/lib/query.js:4509:10)
    at model.Query.Query.then (/home/node/node_modules/mongoose/lib/query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: 'rs0',
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      'hyper-db-0.hyper-db-headless.default.svc.cluster.local:27017' => [ServerDescription],
      'hyper-db-1.hyper-db-headless.default.svc.cluster.local:27017' => [ServerDescription],
      'hyper-db-arbiter-0.hyper-db-arbiter-headless.default.svc.cluster.local:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: 30,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 9
  }
}
```

Like you read, the DNS of hyper-db seems to return the inexistant pod (`hyper-db-1`). I suppose it's a DNS issue but I'm not sure.

I tried also to modify `dnsPolicy `of one of my pod from `ClusterFirst` to `Default`. The error is a bit different:

```
Something went wrong while launching the server MongooseServerSelectionError: getaddrinfo ENOTFOUND hyper-db-headless.default.svc.cluster.local
    at NativeConnection.Connection.openUri (/home/node/node_modules/mongoose/lib/connection.js:846:32)
    at /home/node/node_modules/mongoose/lib/index.js:351:10
    at /home/node/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/node/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Proxy.Mongoose._promiseOrCallback (/home/node/node_modules/mongoose/lib/index.js:1149:10)
    at Proxy.Mongoose.connect (/home/node/node_modules/mongoose/lib/index.js:350:20)
    at initDatabase (/home/node/src/database/connect.js:7:19)
    at Object.<anonymous> (/home/node/src/index.js:8:1)
    at Generator.next (<anonymous>)
    at bl (/home/node/node_modules/esm/esm.js:1:245412)
    at kl (/home/node/node_modules/esm/esm.js:1:247659)
    at Object.u (/home/node/node_modules/esm/esm.js:1:287740)
    at Object.o (/home/node/node_modules/esm/esm.js:1:287137)
    at Object.<anonymous> (/home/node/node_modules/esm/esm.js:1:284879)
    at Object.apply (/home/node/node_modules/esm/esm.js:1:199341) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      'hyper-db-headless.default.svc.cluster.local:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```

I'm using GKE with addon [NodeLocal DNSCache](https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache).

What seems really strange to me is that it only blocks 2 pods out of the 8. The connection is the same among the 8.

Thx for your help or any ideas :)

**Expected behavior**
Connecting normally

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @percenuage ,
If you want to have a single replica of MongoDB why not using the standalone mode?

**Comment by percenuage** [comment]
Hi @miguelaeh,

Yes it's possible but sometimes I uninstalled my DB and with the standalone, I lost PVC/PV. So I would preferred the statefulset.

**Comment by miguelaeh** [comment]
Hi @percenuage ,
I am not sure if that's a normal behaviour or not. Failing should never be a normal behaviour, but in clustering solutions it will depend on if MongoDB supports running in cluster mode with just 1 replica or if that is considered a cluster disaster. In other solutions running in cluster mode sometimes there are a minimun required number of nodes running, and if the cluster goes under that number it is needed to be recovered with manual intervention.
I would recommend you to try to migrate the MongoDB database from your actual instances to a new deployment running on standalone mode.
