### ISSUE TITLE
Bitnami Apache Kafka - Topics are not able to pick the message and sometimes we are unable to send messages to topic

### ISSUE THREAD

**Issue by NNishikar70** [bitnami/charts#8525]
We are unable to send messages to kafka topic sometimes through kafka console Producer . PFB the error message:
```
2021-11-12T11:09:25.703 ERROR [pool-22-thread-6] c.t.b.p.kafka.runtime.SendActivity - TIBCO-BW-PALETTE-KAFKA-500005: Exception occurred while send message to broker. Expiring 7 record(s) for COPA.CNS.TERMINALINFO.RESPONSE-0:120000 ms has passed since batch creation.
2021-11-12T11:09:25.704 ERROR [pool-22-thread-5] c.t.b.p.kafka.runtime.SendActivity - TIBCO-BW-PALETTE-KAFKA-500005: Exception occurred while send message to broker. Expiring 7 record(s) for COPA.CNS.TERMINALINFO.RESPONSE-0:120000 ms has passed since batch creation.
2021-11-12T11:09:25.724 INFO  [bwEngThread:In-Memory Process Worker-8] c.t.b.p.g.L.c.c.p.a.Log - TIBCO-BW-PALETTE-KAFKA-500005: Exception occurred while send message to broker. Expiring 7 record(s) for COPA.CNS.TERMINALINFO.RESPONSE-0:120000 ms has passed since batch creation.-{ActivityName=KafkaSendMessage, ProcessName=copa.cns.adapters.aircraft.terminalinfo.FetchTerminalInfo, ModuleName=copa.cns.process.aircraftoperations}
        at com.tibco.bw.palette.kafka.runtime.SendActivity$SendActivityExecutor.sendMessages(SendActivity.java:1163)
        at com.tibco.bw.palette.kafka.runtime.SendActivity$SendActivityExecutor.run(SendActivity.java:962)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: Expiring 7 record(s) for COPA.CNS.TERMINALINFO.RESPONSE-0:120000 ms has passed since batch creation
        at com.tibco.bw.palette.kafka.runtime.SendActivity.buildOutput(SendActivity.java:1375)
        at com.tibco.bw.palette.kafka.runtime.SendActivity$SendActivityExecutor.sendMessages(SendActivity.java:1119)
        ... 6 more
```
Also sometimes the messages are not being picked up by the Topic.
Error Message:
```
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition COPA.CNS.TERMINALINFO.REQUEST-0 at offset 1. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Size of data received by LongDeserializer is not 8
07-12-2021 18:23:26.544 INFO  [bwEngThread:In-Memory Process Worker-3] c.t.b.p.g.L.c.c.p.a.Log - TIBCO-BW-PALETTE-KAFKA-500008: Exception occurred while receive message from broker. Error deserializing key/value for partition COPA.CNS.TERMINALINFO.REQUEST-0 at offset 1. If needed, please seek past the record to continue consumption..-{ProcessStarterActivityName=KafkaReceiveMessage, ProcessName=copa.cns.adapters.aircraft.terminalinfo.FetchTerminalInfo, ModuleName=copa.cns.process.aircraftoperations}
	at com.tibco.bw.core.runtime.bx.BWBxEngineContext.customizeFaultDetails(BWBxEngineContext.java:617)
	at com.tibco.bx.core.BxSystemImpl.customizeFaultDetails(BxSystemImpl.java:2120)
	at com.tibco.bx.core.behaviors.activity.BxCatchAllBehavior.processExtensionAttributes(BxCatchAllBehavior.java:86)
	at com.tibco.bx.core.behaviors.activity.BxCatchAllBehavior.doEval(BxCatchAllBehavior.java:39)
	at com.tibco.bx.core.behaviors.activity.BxActivityBaseBehavior.eval(BxActivityBaseBehavior.java:852)
	at com.tibco.bx.core.behaviors.activity.BxActivityBaseBehavior.eval(BxActivityBaseBehavior.java:1)
	at com.tibco.pvm.infra.api.impl.util.director.IpmEventDirectorBase.handleModelEvent(IpmEventDirectorBase.java:195)
	at com.tibco.pvm.infra.api.impl.util.director.IpmEventDirectorBase.handleEvent(IpmEventDirectorBase.java:111)
	at com.tibco.pvm.infra.support.work.impl.WorkItemAbstract.execute(WorkItemAbstract.java:189)
	at com.tibco.pvm.im.rt.xm.util.work.ImxSTWorkRunnable.doWorkBlock(ImxSTWorkRunnable.java:170)
	at com.tibco.pvm.infra.services.engine.impl.STWorkRunnable.run(STWorkRunnable.java:50)
	at com.tibco.pvm.im.rt.xm.util.work.ImxSTWorkRunnable.run(ImxSTWorkRunnable.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the bitnami/kafka Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by NNishikar70** [comment]
Hello,
The configuration from our end looks correct. Can you please let us know what exactly we need to alter from configuration perspective. Also can you please help us understand the root cause of this issue.

Thanks and Regards,
Nishant Nishikar

**Comment by carrodher** [comment]
I was trying to reproduce the issue by simply installing the chart with the default configuration and everything is up and running:
```console
$ helm install kafka -n kafka --create-namespace bitnami/kafka

$ kubectl get pods -n kafka
NAME                READY   STATUS              RESTARTS   AGE
kafka-0             1/1     Running             0          5m11s
kafka-zookeeper-0   1/1     Running             0          5m11s
```

Then I used the instructions provided in the installation notes to create some traffic and everything seems to be working fine:
```
$ kubectl run kafka-client --restart='Never' --image docker.io/bitnami/kafka:2.8.1-debian-10-r73 --namespace kafka --command -- sleep infinity
pod/kafka-client created

$ kubectl get pods -n kafka
NAME                READY   STATUS    RESTARTS   AGE
kafka-0             1/1     Running   0          5m48s
kafka-client        1/1     Running   0          73s
kafka-zookeeper-0   1/1     Running   0          5m48s

$ kubectl exec --tty -i kafka-client --namespace kafka -- bash
# Inside the container:
$ kafka-console-producer.sh --broker-list kafka-0.kafka-headless.kafka.svc.cluster.local:9092 --topic test
>Hi
>Bye
>hi
>bye
$ kafka-console-consumer.sh --bootstrap-server kafka.kafka.svc.cluster.local:9092 --topic test --from-beginning
Hi
Bye
hi
bye
```

**Comment by NNishikar70** [comment]
Hi Carrodher,

We also didn't face the issue in the beginning, what are the possibilities that this issue happens when partition get full?

Thanks and Regards,
Nishant Nishikar

**Comment by carrodher** [comment]
It is possible, but unfortunately, this kind of issue seems to be more related to how the application works or is configured rather than the Helm chart itself, and, unfortunately, we don't have such a level of expertise for every app in the catalog.

For information regarding the application itself, we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
