### ISSUE TITLE
CASSANDRA: ENABLE SASI INDEXES

### ISSUE THREAD

**Issue by cohabo** [bitnami/charts#8634]
Hi, 

Kindly share a way I can enable SASI Indexes on this chart https://github.com/bitnami/charts/tree/master/bitnami/cassandra, perhaps using the values.yaml if possible, or any other way that also works.
Good day

    ResponseError: SASI indexes are disabled. Enable in cassandra.yaml to use.
    at FrameReader.readError (/app_node/node_modules/cassandra-driver/lib/readers.js:389:17)                                                                                                          
    at Parser.parseBody (/app_node/node_modules/cassandra-driver/lib/streams.js:209:66)
    at Parser._transform (/app_node/node_modules/cassandra-driver/lib/streams.js:152:10)
    at Parser.Transform._read (_stream_transform.js:191:10)
    at Parser.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Parser.Writable.write (_stream_writable.js:318:11)
    at Protocol.ondata (_stream_readable.js:719:22)at Protocol.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Protocol.Readable.push (_stream_readable.js:214:10)
    at Protocol.Transform.push (_stream_transform.js:152:32)
    at Protocol.readItems (/app_node/node_modules/cassandra-driver/lib/streams.js:124:10)
    at Protocol._transform (/app_node/node_modules/cassandra-driver/lib/streams.js:47:10)
    at Protocol.Transform._read (_stream_transform.js:191:10)
    at Protocol.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Protocol.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:719:22) {
  info: 'Represents an error message from the server',
  code: 8704,
  coordinator: '10.152.183.117:9042',
  query: "CREATE CUSTOM INDEX IF NOT EXISTS filterTextIndex ON app.country(filter_text) USING 'org.apache.cassandra.index.sasi.SASIIndex' WITH OPTIONS = { 'mode': 'CONTAINS', 'analyzer_class': 'org.apache.cassandra.index.sasi.analyzer.StandardAnalyzer', 'case_sensitive': 'false' };"
}

**Comment by javsalgar** [comment]
Hi,

One option could be using a configmap with your custom configuration `cassandra.yaml`

```
## @param existingConfiguration ConfigMap with custom cassandra configuration files. This overrides any other Cassandra configuration set in the chart
##
existingConfiguration: ""
```

Could you try setting that?
