### ISSUE TITLE
[bitnami/cassandra] Metrics Container throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by pitwegner** [bitnami/charts#8802]
**Which chart**:

bitnami/cassandra version 

**Describe the bug**

The metrics container throws an UnsupportedOperationException.

**To Reproduce**

1. Deploy Cassandra using Helm Chart with metrics enabled
2. See Exception in Container Logs

**Expected behavior**

No Errors

**Additional context**

Error Logs:

```
metrics Caused by: java.lang.UnsupportedOperationException: This feature has been removed
metrics     at org.apache.cassandra.net.MessagingServiceMBeanImpl.getBackPressurePerHost(MessagingServiceMBeanImpl.java:262)
metrics     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
metrics     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
metrics     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
metrics     at java.lang.reflect.Method.invoke(Method.java:498)
metrics     at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
metrics     at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
metrics     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
metrics     at java.lang.reflect.Method.invoke(Method.java:498)
metrics     at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:276)
metrics     at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
metrics     at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
metrics     at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
metrics     at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
metrics     at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
metrics     at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
metrics     at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
metrics     at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
metrics     at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
metrics     at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
metrics     at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
metrics     at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
metrics     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
metrics     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
metrics     at java.lang.reflect.Method.invoke(Method.java:498)
metrics     at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
metrics     at sun.rmi.transport.Transport$1.run(Transport.java:200)
metrics     at sun.rmi.transport.Transport$1.run(Transport.java:197)
metrics     at java.security.AccessController.doPrivileged(Native Method)
metrics     at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
metrics     at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
metrics     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
metrics     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
metrics     at java.security.AccessController.doPrivileged(Native Method)
metrics     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
metrics     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
metrics     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
metrics     at java.lang.Thread.run(Thread.java:750)
```

**Comment by rafariossaa** [comment]
Hi,
  It seems to be an upstream issue of the cassandra exporter. https://github.com/criteo/cassandra_exporter/issues/102
  We have also reported it in that thread. We are waiting for feedback.

**Comment by rafariossaa** [comment]
Hi,
  There was  an upstream update.
  The chart was update to include the latest version of the exporter. 
  Could you give it a try ?
