### ISSUE TITLE
Unable to access /home directory in tomcat container. Also sysout statements from Java App not writing to log file.

### ISSUE THREAD

**Issue by Amithpn** [bitnami/charts#8824]
**Which chart**:

https://github.com/bitnami/charts/tree/master/bitnami/tomcat: 10.1.5

**Describe the bug**

Unable to access /home directory in tomcat container. Also sysout statements from Java App not writing to log file.
We are deploying the war file which is a java app. We are creating a file to save the user details into the file. But we are unable to create and access the directory due to which our app is failing.

Logs:
```
java.io.FileNotFoundException: /home/administrators/amith.ser (Permission denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at DataObjectsRTDBase.writeObjectInFile(DataObjectsRTDBase.java:40)
        at DataObjectsRTDBase.setObjectInDb(DataObjectsRTDBase.java:28)
        at Api.doPost(Api.java:159)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
```

**Comment by carrodher** [comment]
Please note this container/chart is running as non-root so you should properly configure the permission. [Here](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/) you can find more info about non-root containers.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by Amithpn** [comment]
Hi @carrodher , can you please point to the document which says how to create directory with write permissions so that my application can read/write to files in the directory. Im failing to find proper documentation for solution to my problem.

**Comment by Amithpn** [comment]
I found the solution. I can use /temp directory for read/writes from my application. /opt/bitnami/tomcat/temp to be precise.
