### ISSUE TITLE
Spark cluster and Jupyterhub Issue

### ISSUE THREAD

**Issue by lamyalfred** [bitnami/charts#8934]
### Name and Version

bitnami/spark

### What steps will reproduce the bug?

Hello,

I'm facing a problem already mentioned in other threads, but I still haven't managed to solve it.

I installed Bitnami Spark and Jupyterhub on Kubernetes and now I'm trying to use Pyspark from Jupyter :
![image](https://user-images.githubusercontent.com/99251037/153005219-88adb183-5060-4a9a-bfea-dabaab30f91a.png)

I really thought I had found the solution [here](https://github.com/bitnami/charts/issues/2946) with what jpellman suggested, but now I get the following error message:

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [1], in <module>
     10 def mod(x):
     11     return x % 2
---> 12 rdd = sc.parallelize(range(1000)).map(mod).take(10)

File /opt/conda/lib/python3.9/site-packages/pyspark/rdd.py:1568, in RDD.take(self, num)
   1565         taken += 1
   1567 p = range(partsScanned, min(partsScanned + numPartsToTry, totalParts))
-> 1568 res = self.context.runJob(self, takeUpToNumLeft, p)
   1570 items += res
   1571 partsScanned += numPartsToTry

File /opt/conda/lib/python3.9/site-packages/pyspark/context.py:1227, in SparkContext.runJob(self, rdd, partitionFunc, partitions, allowLocal)
   1223 # Implementation note: This is implemented as a mapPartitions followed
   1224 # by runJob() in order to avoid having to pass a Python lambda into
   1225 # SparkContext#runJob.
   1226 mappedRDD = rdd.mapPartitions(partitionFunc)
-> 1227 sock_info = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
   1228 return list(_load_from_socket(sock_info, mappedRDD._jrdd_deserializer))

File /opt/conda/lib/python3.9/site-packages/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /opt/conda/lib/python3.9/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (10.244.0.84 executor 3): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2403)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2352)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2351)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2351)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1109)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1109)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1109)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2591)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2533)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2522)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:898)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2214)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2235)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2254)
	at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Maybe I misinterpreted the explanations.

I'm using the HELM map provided [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html). I added the expected configuration in my config.yaml:
![image](https://user-images.githubusercontent.com/99251037/152963020-d5ba2d5c-0665-40a6-9777-34af47095e75.png)

During the installation, I install the HELM chart then I create the headless service resource:
![image](https://user-images.githubusercontent.com/99251037/152963083-106d8ee1-0369-43cd-b3ef-7d85c3cf0728.png)

Here is the headless-svc-jupyter.yaml file :
![image](https://user-images.githubusercontent.com/99251037/152963254-b559275f-7b28-473f-9b26-b8188ccb5093.png)

I run this command from Jupyter, and get the error message given above :
![image](https://user-images.githubusercontent.com/99251037/152963645-3e2d4d43-6030-4ac9-b6bf-d5cfbe16348c.png)

Can someone explain to me what I'm doing wrong?

**Comment by juan131** [comment]
It seems it is not an issue related to the Bitnami Spark chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by qremplak** [comment]
Hello,

Thank you for your reply.

I finally managed to establish the connection, and it was not easy.
- From the webui I did not have access to the executor logs. I was able to partially correct this from this [link](https://github.com/bitnami/charts/issues/8121).
- In the Worker logs, I observed a message suggesting that the version of spark on my driver differed from that of my cluster
- I aligned Spark versions in my Dockerfiles
- Then, I had the same problem with the versions of Python which were different
- I aligned Python versions in my Dockerfiles
![image](https://user-images.githubusercontent.com/41157653/153161794-d7174205-00ca-4894-8c0c-a7938b16b589.png)
- The connection has started to work:
![image](https://user-images.githubusercontent.com/41157653/153161945-36546141-43a1-4925-b193-2656b68f96fa.png)

Now everything seems to work, but I still have this kind of message in the logs continuously:

```
22/02/09 08:59:38 INFO Master: 10.240.0.6:12474 got disassociated, removing it.
22/02/09 08:59:38 INFO Master: 10.244.0.1:56473 got disassociated, removing it.
22/02/09 08:59:41 INFO Master: 10.240.0.4:48681 got disassociated, removing it.
22/02/09 08:59:44 INFO Master: 10.240.0.6:21949 got disassociated, removing it.
22/02/09 08:59:44 INFO Master: 10.244.0.1:39917 got disassociated, removing it.
22/02/09 08:59:47 INFO Master: 10.240.0.4:29514 got disassociated, removing it.
22/02/09 08:59:50 INFO Master: 10.240.0.6:9571 got disassociated, removing it.
22/02/09 08:59:50 INFO Master: 10.244.0.1:15642 got disassociated, removing it.
22/02/09 08:59:53 INFO Master: 10.240.0.4:27946 got disassociated, removing it.
22/02/09 08:59:56 INFO Master: 10.240.0.6:41145 got disassociated, removing it.
22/02/09 08:59:56 INFO Master: 10.244.0.1:46273 got disassociated, removing it.
22/02/09 08:59:59 INFO Master: 10.240.0.4:8005 got disassociated, removing it.
22/02/09 09:00:02 INFO Master: 10.240.0.6:54430 got disassociated, removing it.
22/02/09 09:00:02 INFO Master: 10.244.0.1:29181 got disassociated, removing it.
22/02/09 09:00:05 INFO Master: 10.240.0.4:43913 got disassociated, removing it.
22/02/09 09:00:08 INFO Master: 10.240.0.6:40701 got disassociated, removing it.
22/02/09 09:00:08 INFO Master: 10.244.0.1:1742 got disassociated, removing it.
22/02/09 09:00:11 INFO Master: 10.240.0.4:33876 got disassociated, removing it.
22/02/09 09:00:14 INFO Master: 10.240.0.6:7878 got disassociated, removing it.
22/02/09 09:00:14 INFO Master: 10.244.0.1:53025 got disassociated, removing it.
22/02/09 09:00:17 INFO Master: 10.240.0.4:31901 got disassociated, removing it.
22/02/09 09:00:20 INFO Master: 10.240.0.6:64634 got disassociated, removing it.
22/02/09 09:00:20 INFO Master: 10.244.0.1:56250 got disassociated, removing it.
22/02/09 09:00:23 INFO Master: 10.240.0.4:20992 got disassociated, removing it.
22/02/09 09:00:26 INFO Master: 10.240.0.6:20500 got disassociated, removing it.
22/02/09 09:00:26 INFO Master: 10.244.0.1:31039 got disassociated, removing it.
22/02/09 09:00:29 INFO Master: 10.240.0.4:15268 got disassociated, removing it.
22/02/09 09:00:32 INFO Master: 10.240.0.6:59434 got disassociated, removing it.
22/02/09 09:00:32 INFO Master: 10.244.0.1:32381 got disassociated, removing it.
22/02/09 09:00:35 INFO Master: 10.240.0.4:8198 got disassociated, removing it.
22/02/09 09:00:38 INFO Master: 10.240.0.6:19275 got disassociated, removing it.
22/02/09 09:00:38 INFO Master: 10.244.0.1:51032 got disassociated, removing it.
22/02/09 09:00:41 INFO Master: 10.240.0.4:15699 got disassociated, removing it.
22/02/09 09:00:44 INFO Master: 10.240.0.6:20956 got disassociated, removing it.
22/02/09 09:00:44 INFO Master: 10.244.0.1:12188 got disassociated, removing it.
22/02/09 09:00:47 INFO Master: 10.240.0.4:61137 got disassociated, removing it.
22/02/09 09:00:50 INFO Master: 10.240.0.6:40011 got disassociated, removing it.
22/02/09 09:00:50 INFO Master: 10.244.0.1:55665 got disassociated, removing it.
```

Everything seems to work, but I think this behavior is not normal, do you know how I could fix this ?

I found some leads on other topics explaining that the problem can be solved by mentioning the driver.host as an IP, but this is not applicable in my case because these messages appear continuously even before I establish the connection, and even after having stopped it.

**Comment by lamyalfred** [comment]
Hello,

Thank you for your reply.

I finally managed to establish the connection, and it was not easy.
- From the webui I did not have access to the executor logs. I was able to partially correct this from this [link](https://github.com/bitnami/charts/issues/8121).
- In the Worker logs, I observed a message suggesting that the version of spark on my driver differed from that of my cluster
- I aligned Spark versions in my Dockerfiles
- Then, I had the same problem with the versions of Python which were different
- I aligned Python versions in my Dockerfiles
![image](https://user-images.githubusercontent.com/41157653/153161794-d7174205-00ca-4894-8c0c-a7938b16b589.png)
- The connection has started to work:
![image](https://user-images.githubusercontent.com/41157653/153161945-36546141-43a1-4925-b193-2656b68f96fa.png)

Now everything seems to work, but I still have this kind of message in the logs continuously:

```
22/02/09 08:59:38 INFO Master: 10.240.0.6:12474 got disassociated, removing it.
22/02/09 08:59:38 INFO Master: 10.244.0.1:56473 got disassociated, removing it.
22/02/09 08:59:41 INFO Master: 10.240.0.4:48681 got disassociated, removing it.
22/02/09 08:59:44 INFO Master: 10.240.0.6:21949 got disassociated, removing it.
22/02/09 08:59:44 INFO Master: 10.244.0.1:39917 got disassociated, removing it.
22/02/09 08:59:47 INFO Master: 10.240.0.4:29514 got disassociated, removing it.
22/02/09 08:59:50 INFO Master: 10.240.0.6:9571 got disassociated, removing it.
22/02/09 08:59:50 INFO Master: 10.244.0.1:15642 got disassociated, removing it.
22/02/09 08:59:53 INFO Master: 10.240.0.4:27946 got disassociated, removing it.
22/02/09 08:59:56 INFO Master: 10.240.0.6:41145 got disassociated, removing it.
22/02/09 08:59:56 INFO Master: 10.244.0.1:46273 got disassociated, removing it.
22/02/09 08:59:59 INFO Master: 10.240.0.4:8005 got disassociated, removing it.
22/02/09 09:00:02 INFO Master: 10.240.0.6:54430 got disassociated, removing it.
22/02/09 09:00:02 INFO Master: 10.244.0.1:29181 got disassociated, removing it.
22/02/09 09:00:05 INFO Master: 10.240.0.4:43913 got disassociated, removing it.
22/02/09 09:00:08 INFO Master: 10.240.0.6:40701 got disassociated, removing it.
22/02/09 09:00:08 INFO Master: 10.244.0.1:1742 got disassociated, removing it.
22/02/09 09:00:11 INFO Master: 10.240.0.4:33876 got disassociated, removing it.
22/02/09 09:00:14 INFO Master: 10.240.0.6:7878 got disassociated, removing it.
22/02/09 09:00:14 INFO Master: 10.244.0.1:53025 got disassociated, removing it.
22/02/09 09:00:17 INFO Master: 10.240.0.4:31901 got disassociated, removing it.
22/02/09 09:00:20 INFO Master: 10.240.0.6:64634 got disassociated, removing it.
22/02/09 09:00:20 INFO Master: 10.244.0.1:56250 got disassociated, removing it.
22/02/09 09:00:23 INFO Master: 10.240.0.4:20992 got disassociated, removing it.
22/02/09 09:00:26 INFO Master: 10.240.0.6:20500 got disassociated, removing it.
22/02/09 09:00:26 INFO Master: 10.244.0.1:31039 got disassociated, removing it.
22/02/09 09:00:29 INFO Master: 10.240.0.4:15268 got disassociated, removing it.
22/02/09 09:00:32 INFO Master: 10.240.0.6:59434 got disassociated, removing it.
22/02/09 09:00:32 INFO Master: 10.244.0.1:32381 got disassociated, removing it.
22/02/09 09:00:35 INFO Master: 10.240.0.4:8198 got disassociated, removing it.
22/02/09 09:00:38 INFO Master: 10.240.0.6:19275 got disassociated, removing it.
22/02/09 09:00:38 INFO Master: 10.244.0.1:51032 got disassociated, removing it.
22/02/09 09:00:41 INFO Master: 10.240.0.4:15699 got disassociated, removing it.
22/02/09 09:00:44 INFO Master: 10.240.0.6:20956 got disassociated, removing it.
22/02/09 09:00:44 INFO Master: 10.244.0.1:12188 got disassociated, removing it.
22/02/09 09:00:47 INFO Master: 10.240.0.4:61137 got disassociated, removing it.
22/02/09 09:00:50 INFO Master: 10.240.0.6:40011 got disassociated, removing it.
22/02/09 09:00:50 INFO Master: 10.244.0.1:55665 got disassociated, removing it.
```

Everything seems to work, but I think this behavior is not normal, do you know how I could fix this ?

I found some leads on other topics explaining that the problem can be solved by mentioning the driver.host as an IP, but this is not applicable in my case because these messages appear continuously even before I establish the connection, and even after having stopped it.

**Comment by abhi413sh** [comment]
answer = self.gateway_client. send_command command) -> 1321
return_value = get_return_value 1322
answer, self.gateway_client, self.target_id, self.name) 1323
/ui/jupyterhub_data/anaconda3/lib/python3.8/site-packages/pyspark/sql/utils.py in deco(*a, **kw) 194
# Hide where the exception came from that shows a non-Pythonic 195
# JVM exception message. --> 196
raise converted from None 197
else:
raise
198
IllegalArgumentException: java.net.UnknownHostException: bdacdh-ns
