### ISSUE TITLE
[bitnami/kafka] SSLHandshakeException: Invalid CertificateVerify signature with type PEM

### ISSUE THREAD

**Issue by DamienFontaine** [bitnami/charts#9215]
### Name and Version

bitnami/kafka:15.3.1

### What steps will reproduce the bug?

1. Generate a certificate with cert-manger
2. Use the generated certificate in `auth.tls.existingSecrets` with `auth.tls.type: pem`
3. Install with Helm

### Are you using any custom parameters or values?
```yaml
kafka:
    auth:
      clientProtocol: sasl_tls
      externalClientProtocol: sasl_tls
      interBrokerProtocol: sasl_tls
      sasl:
        mechanisms: PLAIN
        interBrokerMechanism: PLAIN
        jaas:
          interBrokerUser: admin
          interBrokerPassword: admin
          zookeeperUser: zookeeper
          zookeeperPassword: zookeeper
          clientUsers:
            - user
          clientPasswords:
            - user
      tls:
        type: pem
        endpointIdentificationAlgorithm:
        existingSecrets:
          - secret-kafka-tls
```
### What is the expected behavior?

Use PEM certificates generated by cert-manger instead of JKS.

### What do you see instead?
```
2022-02-25 08:52:31,057] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: Invalid CertificateVerify signature for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
        at kafka.network.Processor.<init>(SocketServer.scala:853)
        at kafka.network.SocketServer.newProcessor(SocketServer.scala:442)
        at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:299)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:297)
        at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:262)
        at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:259)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:259)
        at kafka.network.SocketServer.startup(SocketServer.scala:131)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:301)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: Invalid CertificateVerify signature for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:102)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180)
        ... 17 more
```
### Additional information

The certificate generated by cert-manager works in a JKS keystore.

The certificate:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kafka-0.exemple.com
  namespace: myappli-dev
spec:
  secretName: secret-kafka-tls
  issuerRef:
    name: tls-ca-issuer
    kind: ClusterIssuer
  organization:
  - Exemple
  commonName: 10.0.0.1
  dnsNames:
    - kafka-0.exemple.com
  ipAddresses:
    - 10.0.0.1
```

**Comment by javsalgar** [comment]
Hi,

I've been trying with the `autogenerated` PEM files that the chart has and found no issue. It seems to me that it could be some incompatibility with the PEM files that cert-manager creates. Could you check the error with the upstream Kafka devs to see if they can provide more insight on what the issue is? It is not clear to me that the issue is directly related to the Bitnami packaging (taking into account that the autogenerated PEMs work)

**Comment by DamienFontaine** [comment]
Hi,

Same, Kafka works with `autogenerated ` . I will check with Kafka devs.

**Comment by rrileyca** [comment]
I'm curious how you even got this to boot up. Did the `Secret` from cert-manager include a `ca.crt`? The `auto-discovery.sh` script fails without it. See this issue I just raised: https://github.com/bitnami/charts/issues/9378

Maybe the `ca.crt` in your secret is what is causing the trouble? Could could test it with `openssl verify -CAfile ca.pem -untrusted subject.pem`.

**Comment by DamienFontaine** [comment]
Bellow the result of the command `openssl verify`
```
C = EN, O = Example, OU = Example Certificate Authority, CN = Example Kube TLS CA
error 2 at 1 depth lookup: unable to get issuer certificate
error kafka-0.exemple.com.pem: verification failed
```
Only the intermediate certificate is present.

**Comment by rrileyca** [comment]
Sorry - if you have 3 files:
- `ca.pem` - the root
- `sub.pem` - the subordinate
- `endpoint.pem` - the endpoint

You would check them with `openssl verify -CAfile ca.pem -untrusted sub.pem endpoint.pem`.

The autodiscovery script pulls the PEM ca chain from the `ca.crt` field in the `existingSecret` you provided, but I don't know what happens with that PEM after that. Maybe it gets put into a JKS and there's a bug in that process? Maybe @javsalgar could shed some light on how PEM is supposed to work.

I am using certs from Let's Encrypt, created by cert-manager, and I manually added the `ca.crt` and it's throwing a error like yours. I'm not sure why it fails. I even added the Root CA to the `ca.crt` PEM chain and it still fails.

**Comment by javsalgar** [comment]
Hi,

AFAIK, there's no conversion to JKS, you see the logic here https://github.com/bitnami/bitnami-docker-kafka/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh:

```
    if [[ "$KAFKA_TLS_TYPE" = "PEM" ]]; then
        file_to_multiline_property() {
            awk 'NR > 1{print line" \\"}{line=$0;}END{print $0" "}' <"${1:?missing file}"
        }
        configure_both ssl.keystore.key "$(file_to_multiline_property "${KAFKA_CERTS_DIR}/kafka.keystore.key")"
        configure_both ssl.keystore.certificate.chain "$(file_to_multiline_property "${KAFKA_CERTS_DIR}/kafka.keystore.pem")"
        configure_both ssl.truststore.certificates "$(file_to_multiline_property "${kafka_truststore_location}")"

```

**Comment by rrileyca** [comment]
Thanks @javsalgar. I ended up forming the repo and I got this working. I opened PR #9422

**Comment by rrileyca** [comment]
@DamienFontaine my PR is merged and may help you close this issue. Try using the `pemChainIncluded` feature. This is working for me with cert-manager and Let's Encrypt ACME.

**Comment by javsalgar** [comment]
Thank you so much @rrileyca !

**Comment by DamienFontaine** [comment]
@rrileyca I tried with version 15.5.1 and parameters:

      tls:
        type: pem
        pemChainIncluded: true
        existingSecrets:
          - secret-kafka-tls

But we have the following error: 
`[2022-03-23 14:48:52,911] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.InvalidConfigurationException: Invalid PEM keystore configs
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at kafka.server.BrokerToControllerChannelManagerImpl.newRequestThread(BrokerToControllerChannelManager.scala:189)
        at kafka.server.BrokerToControllerChannelManagerImpl.<init>(BrokerToControllerChannelManager.scala:168)
        at kafka.server.BrokerToControllerChannelManager$.apply(BrokerToControllerChannelManager.scala:131)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:276)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Invalid PEM keystore configs
Caused by: java.io.IOException: overrun, bytes = 1195
        at java.base/javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:98)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$PemStore.privateKey(DefaultSslEngineFactory.java:512)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$PemStore.createKeyStoreFromPem(DefaultSslEngineFactory.java:462)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$PemStore.<init>(DefaultSslEngineFactory.java:435)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createKeystore(DefaultSslEngineFactory.java:284)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:161)
        at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:140)
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:97)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at kafka.server.BrokerToControllerChannelManagerImpl.newRequestThread(BrokerToControllerChannelManager.scala:189)
        at kafka.server.BrokerToControllerChannelManagerImpl.<init>(BrokerToControllerChannelManager.scala:168)
        at kafka.server.BrokerToControllerChannelManager$.apply(BrokerToControllerChannelManager.scala:131)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:276)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)`

**Comment by rrileyca** [comment]
This is a generic error and could be a lot of things, so let's verify:

1. What cert-manager issuer are you using? An ACME? A custom CA? Is the Root Authority a public CA, or is it one of your own?
2. What does your secret look like? It should have 2 fields `tls.crt` and `tls.key`. 
3. If you copy the value out of `tls.crt` and echo it into base64 you can decode it back to PEM. Some thing like `echo -n "contents of tls.crt" | base64 -d`. What does this look like? Does it have `---BEGIN CERTIFICATE---` and `---END CERTIFICATE---`? Are there newlines after every 64th character? If not, it is not formatted correctly (a common issue is removing the newline characters from the PEM).
4. If the certs look good, are they in the correct order? Assuming you copy the contents of `tls.crt` into `certchain.pem`, try this: `csplit -z certchain.pem '/\-*END CERTIFICATE\-*/+1' '{*}'` which will make a few files in your current directory prefixed with `xx`, like `xx00`, `xx01`, `xx02`, etc.. You can then verify with a command like `openssl verify -untrusted xx02 -untrusted xx01 xx00`, assuming you have 3 `xx` files.

The order of the PEM chain matters. 

**If the openssl verify fails**, try re-ordering the `xx` files. Note the order of the `-untrusted` don't matter, but the last `xx**` is what is being verified so try permutations like:

- `openssl verify -untrusted xx01 -untrusted xx0 xx02`
- `openssl verify -untrusted xx02 -untrusted xx00 xx01`

Once you get an `OK`, that means the leaf is signed by the two `-untrusted`. Now you need to figure out which `untrusted` signed the other one with:
- `openssl verify -untrusted xx02 xx01`
- `openssl verify -untrusted xx01 xx02`

Then the PEM needs to be built in order from leaf at the top, to top-most intermediate CA at the bottom.

If all of this fails, then I'm confident the issue is in Kafka itself and not in the chart.
