### ISSUE TITLE
bitnami/fluentd and bitnami/elasticsearch compatability - The client noticed that the server is not Elasticsearch and we do not support this unknown product

### ISSUE THREAD

**Issue by PeterKneale** [bitnami/charts#9371]
### Name and Version

bitnami/fluentd latest and bitnami/elasticsearch latest (details below)

### What steps will reproduce the bug?

- install bitnami/elasticsearch
```sh
helm install infra-elasticsearch bitnami/elasticsearch
```

- Apply the config map found here as is
https://github.com/bitnami/charts/blob/master/bitnami/fluentd/README.md#forwarding-the-logs-to-another-service

- install fluentd just specifying the config map created above, passing in the host and port of your instance
```sh
helm install infra-fluentd bitnami/fluentd
# pass in your ip and port here
aggregator.configMap=elasticsearch-output
aggregator.extraEnv[0].name=ELASTICSEARCH_HOST
aggregator.extraEnv[0].value=your-ip-here
aggregator.extraEnv[1].name=ELASTICSEARCH_PORT
aggregator.extraEnv[1].value=your-port-here
```

Examine the logs and you will see that fluentd cannot connect to elastic search
```The client noticed that the server is not Elasticsearch and we do not support this unknown product```

I think the issue is related to the below stackoverflow question where the fluentd gems are unable to determine the elastic search server verison hence do not connect.
[stackoverflow](https://stackoverflow.com/questions/71274282/fluentd-elasticsearch-plugin-the-client-is-unable-to-verify-that-the-server-is)

I would like to know if this is the problem and if so which combination of fluentd and elastic search charts from bitnami might be compatibile.

Thanks!

### Are you using any custom parameters or values?

no

### What is the expected behavior?

fluentd will should forward logs to elastic search but it is unable to connect

I think the issue is related to the below stackoverflow question
[stackoverflow](https://stackoverflow.com/questions/71274282/fluentd-elasticsearch-plugin-the-client-is-unable-to-verify-that-the-server-is)

### What do you see instead?

```
2022-03-10 11:52:56 +0000 [error]: #0 unexpected error error_class=Elasticsearch::UnsupportedProductError error="The client noticed that the server is not Elasticsearch and we do not support this unknown product."
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:115:in `verify_with_version_or_header'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:104:in `verify_elasticsearch'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:70:in `method_missing'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-api-8.0.0/lib/elasticsearch/api/actions/info.rb:39:in `info'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:495:in `detect_es_major_version'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:487:in `block in handle_last_seen_es_major_version'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/elasticsearch_index_template.rb:56:in `retry_operate'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:484:in `handle_last_seen_es_major_version'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:336:in `configure'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:149:in `configure'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:716:in `block in run_worker'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:968:in `main_process'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:708:in `run_worker'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:372:in `<top (required)>'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `load'
2022-03-10 11:52:56 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
2022-03-10 11:52:56 +0000 [error]: Worker 0 finished unexpectedly with status 1
2022-03-10 11:52:57 +0000 [info]: adding match pattern="fluent.**" type="null"
2022-03-10 11:52:57 +0000 [info]: adding match pattern="fluentd.healthcheck" type="stdout"
2022-03-10 11:52:57 +0000 [info]: adding match pattern="**" type="elasticsearch"
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
2022-03-10 11:52:58 +0000 [error]: #0 unexpected error error_class=Elasticsearch::UnsupportedProductError error="The client noticed that the server is not Elasticsearch and we do not support this unknown product."
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:115:in `verify_with_version_or_header'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:104:in `verify_elasticsearch'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:70:in `method_missing'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-api-8.0.0/lib/elasticsearch/api/actions/info.rb:39:in `info'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:495:in `detect_es_major_version'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:487:in `block in handle_last_seen_es_major_version'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/elasticsearch_index_template.rb:56:in `retry_operate'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:484:in `handle_last_seen_es_major_version'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:336:in `configure'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
2022-03-10 11:52:58 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
```

### Additional information

**Versions**
looking into the error reported
- fluentd/gems/elasticsearch-8.0.0   <---- I BELIEVE THIS IS THE ISSUE
- fluentd/gems/fluentd-1.14.5
- fluentd/gems/fluent-plugin-elasticsearch-5.2.0

_bitnami/fluentd_ (latest)
- chart varsion: 5.0.8 
- app version: 1.14.5    

_bitnami/elasticsearch_ (latest)
- chart version: 17.9.8            
- app version :7.17.0 

_k8s (docker on desktop)_
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
Hi @PeterKneale, thanks for reporting this! This is definitely the issue:

> * fluentd/gems/elasticsearch-8.0.0 <---- I BELIEVE THIS IS THE ISSUE

We are actively working on releasing the Helm chart for Elasticsearch 8.0.0, which should fix this issue for anyone deploying the new version. Due to this, I'm not sure if it is worth reverting the change right now, given the release of the new version is inminent.

In the meantime, you could extend the container image to install the old version of the gem, so it works for your use case.

**Comment by PeterKneale** [comment]
Thanks for the quick reply - I will have a try, I will also experiment with the fluentd chart but modifying the `image.tag` to older releases to see if they contained older dependencies that might work.

It would be nice to have a combination of these two charts that worked together because the change to 8 involves a significant licence change doesn't it?

Do you know if you will be offering a bitnami open search chart ? and maybe a fluentd chart to match? :)

**Comment by marcosbc** [comment]
>It would be nice to have a combination of these two charts that worked together because the change to 8 involves a significant licence change doesn't it?

My understanding is that it happened already with Elasticsearch 7.11, see [FAQ on 2021 License Change](https://www.elastic.co/pricing/faq/licensing). So if you are already running that version, you shouldn't find any issues.

>Do you know if you will be offering a bitnami open search chart ? and maybe a fluentd chart to match? :)

Thanks for the suggestion! We don't have short-term plans for supporting it, but I will propose it so it gets considered. Unfortunately we will be unable to provide any sort of ETA when that decision will be made, and it likely won't happen in the short-term.

**Comment by rogersiri** [comment]
Hello
I am experiencing the same thing. 
Using:

bitnami/fluentd (latest)
    chart varsion: 5.1.5
    app version: 1.14.6
 
Managed Elasticsearch in Azure v.8.2.2

Any ETA on when bitnami/fluentd will support Elasticsearch v.8?

**Comment by rogersiri** [comment]
@marcosbc Thank you for verifying. We have gotten past the errors regarding version.

**Comment by EarthlingDavey** [comment]
A workaround to keep ES v7.x is to build upon the bitnami fluentd docker image.

```
FROM bitnami/fluentd:1.14.6-debian-11-r3
LABEL maintainer "Bitnami <containers@bitnami.com>"

USER 0

# https://rubygems.org/gems/elasticsearch/versions

RUN gem uninstall elasticsearch -v 8.2.2  --force -x
RUN gem uninstall elasticsearch-api -v 8.2.2  --force -x
RUN gem uninstall elastic-transport -v 8.0.1  --force -x
RUN gem uninstall elasticsearch-xpack -v 7.17.1 --force -x

RUN gem install elasticsearch -v 7.12
RUN gem install elasticsearch-api -v 7.12
RUN gem install elasticsearch-transport -v 7.12
RUN gem install elasticsearch-xpack -v 7.12
RUN gem install fluent-plugin-elasticsearch
RUN gem install fluent-plugin-rewrite-tag-filter
RUN gem install fluent-plugin-multi-format-parser

USER 1001
```

Then build and push

```
docker build . --platform linux/amd64 -t <your-account>/fluentd-es7:1.14.6-debian-11-r3
docker push <your-account>/fluentd-es7:1.14.6-debian-11-r3
```

And specify that image in helm values.

And in config

```
<match **>
    @type elasticsearch
    # Ref: https://stackoverflow.com/a/72249227/6671505
    verify_es_version_at_startup false
    default_elasticsearch_version 7
    # ...
</match>
```

I can confirm after multiple hours of trial and error that this works :)
