### ISSUE TITLE
java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes

### ISSUE THREAD

**Issue by TommyKTheDJ** [bitnami/charts#946]
I have deployed the Bitnami Elasticsearch helm chart to a Kubernetes v1.12.2 cluster having already created a couple of matching PersistentVolumes:

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install bitnami/elasticsearch --name elasticsearch --namespace monitoring
```

The resources start up OK and I can see the PVCs are bound to the PVs OK, but the 'data' pods always go into CrashLoopBackOff state.

```
E0427599:enabler_infrastructure kivlint$ kubectl get all,pv,pvc -n monitoring
NAME                                                                 READY     STATUS             RESTARTS   AGE
pod/elasticsearch-elasticsearch-coordinating-only-54bb8c9ddc-4c4cm   1/1       Running            0          16h
pod/elasticsearch-elasticsearch-coordinating-only-54bb8c9ddc-t969z   1/1       Running            0          16h
pod/elasticsearch-elasticsearch-data-0                               0/1       CrashLoopBackOff   5          92s
pod/elasticsearch-elasticsearch-data-1                               0/1       CrashLoopBackOff   190        16h
pod/elasticsearch-elasticsearch-master-786dbc6c87-cd2jd              1/1       Running            0          16h
pod/elasticsearch-elasticsearch-master-786dbc6c87-nphqb              1/1       Running            0          16h
pod/fluentd-es-fjq42                                                 1/1       Running            0          18h
pod/fluentd-es-kc79s                                                 1/1       Running            0          18h
pod/fluentd-es-l9mzm                                                 1/1       Running            0          18h
pod/fluentd-es-rxgmb                                                 1/1       Running            0          18h

NAME                                                    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/elasticsearch-elasticsearch-coordinating-only   ClusterIP   10.233.35.43   <none>        9200/TCP   16h
service/elasticsearch-elasticsearch-discovery           ClusterIP   None           <none>        9300/TCP   16h
service/elasticsearch-elasticsearch-master              ClusterIP   10.233.3.132   <none>        9300/TCP   16h
service/gluster-cluster                                 ClusterIP   10.233.17.75   <none>        1/TCP      16h

NAME                        DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/fluentd-es   4         4         4         4            4           <none>          18h

NAME                                                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/elasticsearch-elasticsearch-coordinating-only   2         2         2            2           16h
deployment.apps/elasticsearch-elasticsearch-master              2         2         2            2           16h

NAME                                                                       DESIRED   CURRENT   READY     AGE
replicaset.apps/elasticsearch-elasticsearch-coordinating-only-54bb8c9ddc   2         2         2         16h
replicaset.apps/elasticsearch-elasticsearch-master-786dbc6c87              2         2         2         16h

NAME                                                DESIRED   CURRENT   AGE
statefulset.apps/elasticsearch-elasticsearch-data   2         2         16h

NAME                              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                                                STORAGECLASS   REASON    AGE
persistentvolume/elasticsearch0   8Gi        RWO            Retain           Bound         monitoring/data-elasticsearch-elasticsearch-data-0                            16h
persistentvolume/elasticsearch1   8Gi        RWO            Retain           Bound         monitoring/data-elasticsearch-elasticsearch-data-1                            16h

NAME                                                            STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/data-elasticsearch-elasticsearch-data-0   Bound     elasticsearch0   8Gi        RWO                           16h
persistentvolumeclaim/data-elasticsearch-elasticsearch-data-1   Bound     elasticsearch1   8Gi        RWO                           16h
```

The logs within both 'data' pods shows a permissions error.  Search online suggests this is something that can be solved but should that be within the container (and therefore, is this a bug)?

```
Welcome to the Bitnami elasticsearch container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Elasticsearch setup **
INFO  ==> Configuring/Initializing Elasticsearch...
INFO  ==> Configuration Elasticsearch cluster settings...
INFO  ==> ** Elasticsearch setup finished! **

INFO  ==> ** Starting Elasticsearch **
[2018-11-22T08:45:55,957][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-elasticsearch-data-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
Caused by: java.lang.IllegalStateException: Failed to create node environment
	at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_191]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_191]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_191]
	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:270) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:203) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:267) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
	... 6 more
```

**Comment by kivi** [comment]
I am experiencing the same problem on Docker for Desktop on Windows with Kubernetes enabled.
Kubernetes Version is v1.15.5

It behaves very similar if I use **repo https://helm.elastic.co**

**Steps**
```
helm repo add bitnami https://charts.bitnami.com/bitnami 
helm install elasticsearch bitnami/elasticsearch
```

**Output** 
```
$ kubectl logs -f elasticsearch-elasticsearch-master-0
 20:26:17.68 
 20:26:17.68 Welcome to the Bitnami elasticsearch container
 20:26:17.68 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
 20:26:17.68 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
 20:26:17.68 Send us your feedback at containers@bitnami.com
 20:26:17.68 
 20:26:17.68 INFO  ==> ** Starting Elasticsearch setup **
 20:26:17.70 INFO  ==> Configuring/Initializing Elasticsearch...
 20:26:17.73 INFO  ==> Setting default configuration
 20:26:17.74 INFO  ==> Configuring Elasticsearch cluster settings...
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
 20:26:19.16 INFO  ==> ** Elasticsearch setup finished! **

 20:26:19.17 INFO  ==> ** Starting Elasticsearch **
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2020-01-02T20:26:22,465][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-elasticsearch-master-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/bitnami/elasticsearch/data/nodes];
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.5.1.jar:7.5.1]
Caused by: org.elasticsearch.ElasticsearchException: failed to bind service
        at org.elasticsearch.node.Node.<init>(Node.java:607) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:253) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.5.1.jar:7.5.1]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes
```

**Comment by juan131** [comment]
Hi @kivi 

It looks like an issue with the filesystem. As you can see it's complaining about being unable to access to the directory where the volumes are mounted in the ES pod (`/bitnami/elasticsearch`):

```console
Caused by: java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes
```

It's highly likely to be related to the virtualisation used on Windows to run Kubernetes and Linux containers. We've seen similar issues with Windows users and Docker/Kubernetes. I highly recommend you to explore other alternatives (based on Linux) to run Kubernetes since this platform was not designed for Windows originally and the performance is very poor.

**Comment by kivi** [comment]
@juan131 I think you are right, that it might be a problem with Docker on Windows with Kubernetes running. But let's not talk about performance without comparison... and highly recommend not to asume :) - I will try to fix the problem with Docker and I will come back.

The reason that Docker/Kubernetes on Windows 10 (hyperV) exists, is because there is need for it. Surely the history of virtualization could have gone different, but we are stuck with Docker (many ppl nowadays just work with that, I am just adjusting)

**Comment by sameersbn** [comment]
@kivi the quickest way to check if the issue is due to the filesystem is to disable persistence while installing the chart `--set master.persistence.enabled=false --set data.persistence.enabled=false`. 

If you are able to track down the issue and share your experiences/fixes with us, we would gladly include the fixes to the image.

**Comment by kagaya85** [comment]
Hi, I meet the same problems, and I use `--set master.persistence.enabled=false --set data.persistence.enabled=false`, everytings seems goes well.

But when I enable persistence, I got this error in elasticsearch-master log:

```
[2020-12-26T07:19:30,403][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-elasticsearch-master-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: FileSystemException[/bitnami/elasticsearch/data/nodes: Read-only file system];
```

I am using CentOS Linux 7 virtualized by VMware Virtual Platform, I would like to know why this happened and appreciate it if anyone could provide some ideas.

```
CHART elasticsearch-13.0.5	
APP VERSION 7.10.1
kubernetes 1.20.0 with containerd 1.4.3
```

**Comment by alemorcuq** [comment]
This looks like an issue with your persistent volume:

```
FileSystemException[/bitnami/elasticsearch/data/nodes: Read-only file system]
```

What kind of persistent volumes are you using? Have you tried the `volumePermissions` settings? (see: https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#adjust-permissions-of-persistent-volume-mountpoint)

**Comment by kagaya85** [comment]
@alemorcuq Thank you for your reply

I am using the persistent volumes defined by myself, using like `kubectl apply -f local-pv.yaml`

I tried to set `volumePermissions` to true, but the init container also failed to start with exit code 1
```bash
$ kubectl logs es-elasticsearch-master-0 -c volume-permissions -n efk-logs
chown: changing ownership of '//bitnami/elasticsearch/data': Read-only file system
```

In additon that I also meet this 'read-only file system' error in using `bitnami/kibana` to start a kibana service, I opend a [discussion](https://github.com/containerd/containerd/discussions/4890) in containerd to provide more infomation.

**Comment by juan131** [comment]
Hi @kagaya85 

You should ensure you attach Persistent Volume with RWO or RWX access modes. Otherwise, the ES container won't be able to write data in the volumes, nor change its ownership/permissions configuration.

Find more info at https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by Wladimir-N** [comment]
Similar issue with pvc rights in single mode.
`helm --namespace es install elasticsearch bitnami/elasticsearch --create-namespace --set config.discovery.type=single-node --set coordinating.replicaCount=0 --set data.replicaCount=0 --set ingest.replicaCount=0 --set master.replicaCount=1 --set image.tag=7.17.3-debian-10-r21`

I see in the pod logs

Unable to access 'path.data' (/opt/bitnami/elasticsearch/data)

I use Yandex cloud and there by default it belongs to root. That is, at the moment I will write a job that will correct the rights before installing elasticsearch, but I would like that no additional fixes are needed.

**Comment by carrodher** [comment]
There is an existing initcontainer to automatically configure the proper permission in most of the use cases, see https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#init-container-parameters.

You should be able to successfully deploy the Helm chart using this option unless there is any non-default setting/configuration in your environment or in case you are trying to solve a non-contemplated use case.

**Comment by Wladimir-N** [comment]
I'm trying to run elasticsearch in single node mode. I see a problem in the pod logs.

java.lang.IllegalStateException: Unable to access 'path.data' (**/opt/bitnami/elasticsearch/data**)

In this case, the data directory is mounted a completely different directory if you look in describe

    Mounts:
      **/bitnami/elasticsearch/data from data (rw)**
      /opt/bitnami/elasticsearch/config/elasticsearch.yml from config (rw,path="elasticsearch.yml")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x4xvz (ro)

Why is he trying to write to the wrong directory? How can I fix this?

**Comment by carrodher** [comment]
Did you try my suggestion in the previous comment? There is an init container for fixing some permission issues

**Comment by ragboy** [comment]
This issue was causing me some serious grief. I then realized that the volume permissions image was prepping

/bitnami/elasticsearch/data and not /opt/bitnami/elasticsearch/data

is this maybe an issue only with single node? So I changed this setting on my single node setup, changing path.data, and that has solved the problem. Here is my complete working setup for single-node. The PVC has nothing to do with it, this pvc setup was for longhorn with a prepared pvc.

```
image:
  tag: 7
master:
  masterOnly: false
  replicaCount: 1
  persistence:
    enabled: true
    existingClaim: "pvc-es"
    accessModes:
      - ReadWriteMany

extraConfig:
  path:
    data: /bitnami/elasticsearch/data

ingest:
  enabled: false
coordinating:
  replicaCount: 0
data:
  replicaCount: 0
volumePermissions:
  enabled: true
```
