### ISSUE TITLE
[bitnami/solr] tls with existing secret (tls.certificatesSecretName)

### ISSUE THREAD

**Issue by DirkDittmarMonday** [bitnami/charts#9506]
### Name and Version

bitnami/solr 3.0.10

### What steps will reproduce the bug?

We want to start the solr with a self-signed certificate (by cert-manager.io). I've boiled our setup down to this deployment script:
```
#!/bin/bash

echo "*** init helm"
helm repo add jetstack https://charts.jetstack.io
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

echo "*** create namespace 'test'"
kubectl create namespace test

echo "*** deploy cert-manager"
helm upgrade --install cert-manager -n test --version v1.7.1 jetstack/cert-manager -f certmanager-values.yaml
kubectl apply -f issuer.yaml

echo "*** deploy solr"
kubectl apply -f solr-secrets.yaml
helm upgrade --install search -n test --version 3.0.10 bitnami/solr -f solr-values.yaml
```
The cert-manager is installed with:
```
installCRDs: true

prometheus:
  enabled: false
```
and then bootstraped with `issuer.yaml`:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-selfsigned-issuer
  namespace: test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: test
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: my-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-ca-issuer
  namespace: test
spec:
  ca:
    secretName: my-root-secret
```
Then we create a certificate and a password-secret:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-solr-tls-cert
  namespace: test
spec:
  dnsNames:
    - 'search-solr-headless.default.svc.cluster.local'
    - '*.search-solr-headless.default.svc.cluster.local'
    - 'search-solr-headless'
    - 'search-solr-headless.default'
    - '*.search-solr-headless.default'
  isCA: false
  commonName: my-solr-tls-cert
  secretName: my-solr-tls-cert
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Secret
metadata:
  name: my-solr-pkcs12-password
  namespace: test
data:
  keystore-password: Zm9vYmFyMTIz # foobar123
  truststore-password: Zm9vYmFyMTIz # foobar123
```
... and then we install the `bitnami/solr` with:
```
tls:
  enabled: true
  autoGenerated: false
  existingSecret: true # see https://github.com/bitnami/charts/issues/9462
  certificatesSecretName: my-solr-tls-cert
  passwordsSecretName: my-solr-pkcs12-password
```

### What do you see instead?

the solr pods are going to a `CrashLoopBackoff` loop and I find this in the logs:
```
2022-03-22 08:31:19.981 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@163370c2{/solr,file:///opt/bitnami/solr/server/solr-webapp/webapp/,AVAILABLE}{/opt/bitnami/solr/server/solr-webapp/webapp}
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
	at org.eclipse.jetty.start.Main.start(Main.java:491)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.security.PrivilegedActionException: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857)
	... 7 more
Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:601)
	at sun.security.util.DerValue.init(DerValue.java:384)
	at sun.security.util.DerValue.<init>(DerValue.java:325)
	at sun.security.util.DerValue.<init>(DerValue.java:338)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1958)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1203)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:322)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1907)
	... 9 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
	at org.eclipse.jetty.start.Main.start(Main.java:491)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.security.PrivilegedActionException: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857)
	... 7 more
Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:601)
	at sun.security.util.DerValue.init(DerValue.java:384)
	at sun.security.util.DerValue.<init>(DerValue.java:325)
	at sun.security.util.DerValue.<init>(DerValue.java:338)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1958)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1203)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:322)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1907)
	... 9 more
```
I guess solr could not read the keystore or the truststore.

### Additional information

As I understand the keystore/truststore for java is generated with the `init-certs.sh` Script here:
https://github.com/bitnami/charts/blob/master/bitnami/solr/templates/scripts-configmap.yaml
The script builds the keystore and the truststore (`/opt/bitnami/solr/certs/keystore.p12` and `/opt/bitnami/solr/certs/truststore.p12`).

If I download the certificate files (`ca.crt`, `tls.key` and `tls.crt`) and do what the script is doing by hand I could not see find a problem with the gernerated files. I see that the script is executed successfully (in the logs of the init-container).

Another think I noticed: The cert-manager can provide a `keystore.p12` and `truststore.p12` with the certificate. If I add this to the certifcate
```
…
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: my-solr-pkcs12-password
        key: password
```
and change the init-script so it only copies the `keystore.p12` and `truststore.p12` (like in the `else` of the script) everything works fine.

**Comment by carrodher** [comment]
Thanks for creating this issue, I was trying to reproduce the issue on my side but without luck.
As it seems a very specific issue related to the application itself, customization of the content within the application I am not sure if we can help with this topic. On the other hand, if you think there is something wrong with your specific use case and the Helm chart can be improved to support that scenario... would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
