### ISSUE TITLE
Missing required configuration `zookeeper.connect` which has no default value

### ISSUE THREAD

**Issue by sharmavickram** [bitnami/charts#9782]
### Name and Version

bitnami/kafka   tag: 2.8.0-debian-10-r0

### What steps will reproduce the bug?

3 instances kafka should be running without any issue

### What do you see instead?

08:09:21.11 INFO ==> ** Starting Kafka **
[2022-04-13 08:09:22,680] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2022-04-13 08:09:23,586] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2022-04-13 08:09:23,612] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Missing required configuration `zookeeper.connect` which has no default value.
at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1901)
at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1896)
at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1389)
at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1327)
at kafka.Kafka$.buildServer(Kafka.scala:67)
at kafka.Kafka$.main(Kafka.scala:87)
at kafka.Kafka.main(Kafka.scala)

**Comment by OneCricketeer** [comment]
Is this before or after #9736?

**Comment by dellnoantechnp** [comment]
1. delete pvc 
2. reinstall chart
