### ISSUE TITLE
Spark job cannot read Azure Storage, egging error 'Java gateway process exited before sending its port number'

### ISSUE THREAD

**Issue by porscheme** [bitnami/charts#9806]
### Name and Version

bitnami/spark 5.9.9

### What steps will reproduce the bug?

1. Setup AKS cluster
2. Create custom spark container image with additional JAR files, see below docker file
-- [Dockerfile.spark.txt](https://github.com/bitnami/charts/files/8492727/Dockerfile.spark.txt) 
3. Deploy spark cluster by running below command using custom image
-- helm repo add bitnami https://charts.bitnami.com/bitnami
-- helm install my-release bitnami/spark
4. Use below code snippet from Jupyter Notebook
```
conf = SparkConf()
conf.setMaster("spark://spark-cluster-master-svc.cohort-workbench.svc.cluster.local:7077")
conf.setAppName("MyApp")
conf.set('spark.driver.host', socket.gethostbyname(socket.gethostname()))
conf.set('spark.submit.deployMode', 'client')
conf.set("spark.jars.packages", "org.apache.hadoop:hadoop-azure-3.3.1,com.microsoft.azure:azure-storage:8.6.6")
conf.set('spark.executor.instances', '2')
spark = SparkSession.builder.config(conf=conf).getOrCreate()

sc = spark.sparkContext

hd_conf = sc._jsc.hadoopConfiguration()
hd_conf.set("fs.azure.sas." + storage_container + "." + storage_account_name + ".blob.core.windows.net", storage_sas_token)
hd_conf.set("fs.azure","org.apache.hadoop.fs.azure.NativeAzureFileSystem")
hd_conf.set("spark.hadoop.fs.wasbs.impl","org.apache.hadoop.fs.azure.NativeAzureFileSystem")
hd_conf.set("fs.AbstractFileSystem.wasbs.impl", "org.apache.hadoop.fs.azure.Wasbs")
hd_conf.set("fs.wasbs.impl", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
hd_conf.set("spark.hadoop.fs.adl.impl", "org.apache.hadoop.fs.adl.AdlFileSystem")
    
parquet_file = "wasbs://" + doc_ath
df = spark.read.parquet(parquet_file)
sc.stop()
```

 

### Are you using any custom parameters or values?

-- Yes, see the attached values file [test.spark.values.txt](https://github.com/bitnami/charts/files/8492743/test.spark.values.txt)

### What is the expected behavior?

Job should read the azure storage account

### What do you see instead?

Java gateway process exited before sending its port number

### Additional information

We below error if not 'spark.jars.packages' set in notebook code
```
Py4JJavaError: An error occurred while calling o39.parquet.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:747)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:745)
	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:577)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:596)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by porscheme** [comment]
@kubernetes-bitnami

**Comment by javsalgar** [comment]
Hi,

I'm afraid that the level of customization of this image is high enough for us to provide regular support. If this is the only plugin that is failing, then maybe there is an issue with the plugin itself. Did you try checking with the Azure plugin developers? I will leave this ticket open in case someone from the community wants to add their experience. If the azure plugin devs mention we have to change something in the Bitnami Spark configuration, please let us know.
