### ISSUE TITLE
Upgrade chart from bitnami/zookeeper 2.2.4 to 8.1.1

### ISSUE THREAD

**Issue by leonidUH** [bitnami/charts#9811]
### Name and Version

bitnami/zookeeper:8.1.1

### What steps will reproduce the bug?

1. install bitnami/zookeeper 2.2.4
2. add some data
3. install  bitnami/zookeeper 8.1.1

### What do you see instead?

New pod in crash loop mode with errors:

 ZooKeeper JMX enabled by default
 Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
 2022-04-17 07:51:52,721 [myid:1] - ERROR [main:ZooKeeperServerMain@91] - Unexpected exception, exiting abnormally
 java.io.IOException: No snapshot found, but there are log entries. Something is broken!                                                                                                                         
     at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:290)
     at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:286)
     at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:516)
     at org.apache.zookeeper.server.ZooKeeperServer.startdata(ZooKeeperServer.java:683)
     at org.apache.zookeeper.server.NIOServerCnxnFactory.startup(NIOServerCnxnFactory.java:744)
     at org.apache.zookeeper.server.ServerCnxnFactory.startup(ServerCnxnFactory.java:130)
     at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:161)
     at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:113)
     at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:68)
     at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:141)
     at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:91)
 2022-04-17 07:51:52,726 [myid:1] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1              

### Additional information

Is there any way to perform data migration or some other way to save old data?

**Comment by leonidUH** [comment]
I found solution 
Need to add "snapshot.trust.empty=true" to conf file
