### ISSUE TITLE
GKE data nodes failing to join cluster with masters - failed send ping

### ISSUE THREAD

**Issue by hawksight** [bitnami/charts#984]
**Which chart**:

bitnami/elasticsearch --version 4.2.5

**Description**

After initialising a clean cluster on GKE (v1.10.9-gke.7) installing helm with tiller in the `tiller` namespace. The data nodes seem to error constantly on startup with the following error:

```
[2018-12-17T16:22:47,587][WARN ][o.e.d.z.UnicastZenPing   ] [staging-elasticsearch-data-2] [35] failed send ping to {10.44.3.15:9300}{NBRfGnyIS--x1dOB6asT-g}{staging-elasticsearch-discovery}{10.44.3.15:9300}
java.lang.IllegalStateException: handshake failed, mismatched cluster name [Cluster [<nil>]] - {10.44.3.15:9300}{NBRfGnyIS--x1dOB6asT-g}{staging-elasticsearch-discovery}{10.44.3.15:9300}
	at org.elasticsearch.transport.TransportService.handshake(TransportService.java:448) ~[elasticsearch-6.5.2.jar:6.5.2]
	at org.elasticsearch.transport.TransportService.handshake(TransportService.java:412) ~[elasticsearch-6.5.2.jar:6.5.2]
	at org.elasticsearch.discovery.zen.UnicastZenPing$PingingRound.getOrConnect(UnicastZenPing.java:366) ~[elasticsearch-6.5.2.jar:6.5.2]
	at org.elasticsearch.discovery.zen.UnicastZenPing$3.doRun(UnicastZenPing.java:471) [elasticsearch-6.5.2.jar:6.5.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.2.jar:6.5.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.2.jar:6.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

I deployed a quick alpine debugging pod to check the ports:
```
/app $ nslookup staging-elasticsearch-discovery
nslookup: can't resolve '(null)': Name does not resolve

Name:      staging-elasticsearch-discovery
Address 1: 10.44.3.15
Address 2: 10.44.3.16
Address 3: 10.44.4.16
Address 4: 10.44.4.17
Address 5: 10.44.5.16
Address 6: 10.44.5.18
Address 7: 10.44.5.19
Address 8: 10.44.3.14

/app $ nc -v staging-elasticsearch-discovery:9300
staging-elasticsearch-discovery:9300 (10.44.3.15:9300) open
^Cpunt!

/app $ nc -v staging-elasticsearch-discovery:9300
staging-elasticsearch-discovery:9300 (10.44.3.14:9300) open
^Cpunt!

/app $ nc -v staging-elasticsearch-discovery:9300
staging-elasticsearch-discovery:9300 (10.44.3.15:9300) open
^Cpunt!

/app $ ^C
/app $ nc -v staging-elasticsearch-discovery:9300
staging-elasticsearch-discovery:9300 (10.44.3.16:9300) open
^Cpunt!

/app $ nc -v staging-elasticsearch-discovery:9300^C
/app $ nc -v staging-elasticsearch-discovery:9300
staging-elasticsearch-discovery:9300 (10.44.4.16:9300) open
^Cpunt!

/app $ nc -v staging-elasticsearch-discovery:9300
staging-elasticsearch-discovery:9300 (10.44.3.14:9300) open
^Cpunt!

/app $ ^C
/app $ nc -v staging-elasticsearch-discovery:9200
staging-elasticsearch-discovery:9200 (10.44.4.17:9200) open
^Cpunt!

/app $ ^C
/app $ nc -v staging-elasticsearch-discovery:9200
staging-elasticsearch-discovery:9200 (10.44.4.16:9200) open
^Cpunt!

/app $ nc -v staging-elasticsearch-discovery:9200
staging-elasticsearch-discovery:9200 (10.44.4.17:9200) open
^Cpunt!

/app $ ^C
/app $ nc -v staging-elasticsearch-discovery:9200
staging-elasticsearch-discovery:9200 (10.44.5.16:9200) open
^Cpunt!

/app $ nc -v staging-elasticsearch-discovery:9200
staging-elasticsearch-discovery:9200 (10.44.4.17:9200) open
```

Example of the services:
```
NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kubernetes                                ClusterIP   10.47.240.1     <none>        443/TCP    7h
staging-elasticsearch-coordinating-only   ClusterIP   10.47.255.65    <none>        9200/TCP   21m
staging-elasticsearch-discovery           ClusterIP   None            <none>        9300/TCP   21m
staging-elasticsearch-master              ClusterIP   10.47.242.185   <none>        9300/TCP   21m
staging-elasticsearch-metrics             ClusterIP   10.47.243.36    <none>        9108/TCP   21m
```

**Steps to reproduce the issue:**

1. Build a GKE cluster on 1.10.9-gke7
2. Install helm with tiller in `tiller` namespace:
`helm init --tiller-namespace=tiller --service-account tiller`
3. Configure the values for `values-production.yaml` from the chart. 
Setting `name` to something like `staging`.
Setting sysctl to be `true` and disabling the `ingest` nodes.
`helm repo add bitnami https://charts.bitnami.com`
4. Install the helm chart as so: `helm install bitnami/elasticsearch --version 4.2.5 --name="staging" --values values-production.yaml`
5. Wait and then watch logs for errors on data nodes. `kubectl logs .....`

**Describe the results you received:**

Everything seems to run (apart from metrics) but when you try to query the coordinating-only nodes the requests time out with a master error:

Some curls as example:
```
/app $ curl http://${STAGING_ELASTICSEARCH_COORDINATING_ONLY_SERVICE_HOST}:9200/
{
  "name" : "staging-elasticsearch-coordinating-only-dc95ffd9f-pdjsh",
  "cluster_name" : "staging",
  "cluster_uuid" : "_na_",
  "version" : {
    "number" : "6.5.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "9434bed",
    "build_date" : "2018-11-29T23:58:20.891072Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

/app $ curl http://${STAGING_ELASTICSEARCH_COORDINATING_ONLY_SERVICE_HOST}:9200/_cluster/health?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "master_not_discovered_exception",
        "reason" : null
      }
    ],
    "type" : "master_not_discovered_exception",
    "reason" : null
  },
  "status" : 503
}
```

**Describe the results you expected:**

I was expecting the data nodes to be part of the cluster.
When checking the master nodes, it seems that they are alive and well, but only know about the masters:

```
$ curl http://0.0.0.0:9200/_cluster/health?pretty
{
  "cluster_name" : "<nil>",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 0,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

- output of `kubectl api-versions`

```
❯ kubectl api-versions

admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
cloud.google.com/v1beta1
extensions/v1beta1
metrics.k8s.io/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scalingpolicy.kope.io/v1alpha1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

Cluster has the following scopes:
```
    oauthScopes:
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/compute
```

Addonconfig as follows from `gcloud` cli

```
addonsConfig:
  horizontalPodAutoscaling: {}
  httpLoadBalancing: {}
  kubernetesDashboard: {}
  networkPolicyConfig:
    disabled: true
```

The metics pod fails to run as its trying to talk to the coordination-only service which seems to not respond.

Example of pods 'running':

```
NAME                                                      READY     STATUS             RESTARTS   AGE
alpine-python-deploy-5c4d45bf97-tl8t5                     1/1       Running            0          48m
staging-elasticsearch-coordinating-only-dc95ffd9f-2n84h   1/1       Running            0          55m
staging-elasticsearch-coordinating-only-dc95ffd9f-pdjsh   1/1       Running            0          55m
staging-elasticsearch-data-0                              1/1       Running            0          55m
staging-elasticsearch-data-1                              1/1       Running            0          53m
staging-elasticsearch-data-2                              1/1       Running            0          51m
staging-elasticsearch-master-588cf95c9-6972r              1/1       Running            0          55m
staging-elasticsearch-master-588cf95c9-f9pg9              1/1       Running            0          55m
staging-elasticsearch-master-588cf95c9-rz95q              1/1       Running            0          55m
staging-elasticsearch-metrics-74d8d9bcdc-8g9t9            0/1       CrashLoopBackOff   17         55m
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
❯ helm version

Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
❯ kubectl version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.7", GitCommit:"572a070abf31a08a8f0d104220da467ea1e3d5f2", GitTreeState:"clean", BuildDate:"2018-11-14T05:26:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

I re-read the installation documentation but can't see any steps I've missed. The only other thing I can think is that I need something extra on GKE / to configure the cluster in a specific way?
The image for the cluster is COS.

**Comment by hawksight** [comment]
I've just noticed that getting the master deployment it seems the cluster name has not been set from the name value (`k get deployment staging-elasticsearch-master -o yaml`):

```
      containers:
      - env:
        - name: ELASTICSEARCH_CLUSTER_NAME
          value: <nil>
        - name: ELASTICSEARCH_HEAP_SIZE
          value: 128m
        - name: ELASTICSEARCH_IS_DEDICATED_NODE
          value: "yes"
        - name: ELASTICSEARCH_NODE_TYPE
          value: master
```

And I can see that getting the information from `helm get` the following:
```
        env:
        - name: ELASTICSEARCH_CLUSTER_NAME
          value: "staging"
          value: "<nil>"
        - name: ELASTICSEARCH_HEAP_SIZE
          value: "128m"
        - name: ELASTICSEARCH_IS_DEDICATED_NODE
          value: "yes"
        - name: ELASTICSEARCH_NODE_TYPE
          value: "master"
```

Data and coordinating nodes are both correct in that they have:
```
        env:
        - name: ELASTICSEARCH_CLUSTER_NAME
          value: "staging"
```

Actually just realised I think this is the issue:
https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/master-deploy.yaml#L82

```
        env:
        - name: ELASTICSEARCH_CLUSTER_NAME
          value: {{ .Values.name | quote }}
        {{- if .Values.plugins }}
        - name: ELASTICSEARCH_PLUGINS
        {{- end }}
          value: {{ .Values.plugins | quote }}
```

I have no plugins set, so the `{{ end }}` needs moved down a line.

**Comment by hawksight** [comment]
since applying the fix in #985 I seem to have a fully functioning ES cluster:
```
/app $ curl -s http://${STAGING_ELASTICSEARCH_COORDINATING_ONLY_SERVICE_HOST}:9200/_cluster/health?pretty | jq .
{
  "cluster_name": "staging",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 8,
  "number_of_data_nodes": 3,
  "active_primary_shards": 0,
  "active_shards": 0,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```

**Comment by juan131** [comment]
Hi @hawksight 

I agree!! It was an issue with the plugins. I just created another PR since I forgot to mentioned you that should increase the chart patch version.

**Comment by juan131** [comment]
Hi @hawksight 

Could you please confirm that the new version of the chart `4.2.6` works as expected?

**Comment by hawksight** [comment]
Thanks for merging and releasing the new version @juan131. I can confirm that it worked perfectly this morning with version 4.2.6. Issue is resolved.

**Comment by juan131** [comment]
Great @hawksight 

I proceed to close this issue as solved! Please feel free to reopen it if you need further assistance.
