### ISSUE TITLE
keycloak run error at 7

### ISSUE THREAD

**Issue by taoyonggang** [bitnami/charts#9871]
### Name and Version

bitnami/charts/keycloak

### What steps will reproduce the bug?

1, version:7.0 ~ 7.1
2, depoly with chart
3, keycloak throw error and exit
```
02:58:49,086 INFO  [org.infinispan.CONFIG] (MSC service thread 1-2) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-7,ejb,camunda-platform-key-0) ISPN000474: Error processing request 0@keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap') 	
    at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
    at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400) 	
    at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32) 	
    at org.infinispan@12.1.7.Final//org.infinispan.commands.topology.RebalanceStartCommand.readFrom(RebalanceStartCommand.java:98) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1374)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
 	at java.base/java.lang.Thread.run(Thread.java:829)

 02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-6,ejb,camunda-platform-key-0) ISPN000475: Error processing response for request 2 from keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:252)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:235)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:72)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:60)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1407)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1317)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
 	at java.base/java.lang.Thread.run(Thread.java:829)

 02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-12,ejb,camunda-platform-key-0) ISPN000474: Error processing request 0@keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.commands.topology.RebalanceStartCommand.readFrom(RebalanceStartCommand.java:98)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1374)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
 	at java.base/java.lang.Thread.run(Thread.java:829)

 02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-9,ejb,camunda-platform-key-0) ISPN000475: Error processing response for request 2 from keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:252)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:235)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:72)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:60)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1407)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1317)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Fa
```

### What do you see instead?

The errors may be coming from keycloak 16.
The keycloak has no error with version 15.

**Comment by carrodher** [comment]
It seems an error with the application itself instead of an error with the Bitnami Helm chart, but we will try to reproduce it on our side. In order to do that, could you provide the parameters used to deploy the Helm chart? Are you installing it from scratch or doing an upgrade?

**Comment by taoyonggang** [comment]
This is the keycloak docker image error.  I have test  the docker.io/bitnami/keycloak:16.1.1-debian-10-r85. The large version at 16 always has the error.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue, could you provide more details about the k8s platform you are using? Which values are you using to deploy the chart?

**Comment by jack1902** [comment]
@javsalgar i've been able to reproduce this by going down the following path:

- Deploy chart version `5.2.8` which deploys keycloak `15.1.1`
- Upgrade to chart version `6.1.1` which deploys keycloak `16.1.1`

It appears that when `16` get's requests from `15` then endpoints are no longer compatible. I don't see that as a "major" issue because if i remove the other replica which is running `15` then `16` comes up happily.

For additional context, my values i use are:

```yaml
pdb:
  create: true

autoscaling:
  enabled: true
  minReplicas: 2

cache:
  ownersCount: 2
  authOwnersCount: 2

proxyAddressForwarding: true
replicaCount: 2

# ServiceDiscovery, serviceAccount and rbac required when more than 1 replica exists
serviceDiscovery:
  enabled: true
serviceAccount:
  # required as KUBE_PING is used as the discovery mechanism
  automountServiceAccountToken: true
rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
```

I have a feeling that due to the `update` being `rolling`, it messes with Kubernetes as the new pod `16` can't come up meaning it is forever stuck until i manually come along and remove the replica running `15`. Not sure if the `pdb` is causing this but i am aware that `parallel` on the podManagementPolicy doesn't impact `updates`. I would have read some documentation on how to upgrade from `15` -> `16` but i cannot see any on the linked bitnami website here: https://docs.bitnami.com/kubernetes/apps/keycloak/administration/upgrade/ (from the charts README)

**Comment by javsalgar** [comment]
Hi,

Could you try changing the update strategy from RollingUpdate to Recreate? Would that work with the upgrade? In this case it would be worth adding a note in the Readme

**Comment by jack1902** [comment]
@javsalgar yeah i'll give that whirl. I've been upgrading to v18 and identifying any pain points along the way. I've documented the majority of them within this issue: https://github.com/bitnami/charts/issues/10236

I'll feedback on this issue about the `updateStrategy` to see if that addresses it

**Comment by jack1902** [comment]
@javsalgar  looking at versions `6.1.1`, `7.0.0` and `7.1.18` of the chart I see the below and a link to https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies

Only possible values are `RollingUpdate` and `OnDelete` (on delete being a manual process)

Only way I can see to do this is to scale down to `1`, update then scale back up (or tear out keycloak and put it back [Warning: could cause issues with your postgres deployment if using the on-cluster postgres])


![image](https://user-images.githubusercontent.com/39212456/169020051-a1cc1268-6218-4c1e-8031-09191c0d2505.png)

**Comment by jack1902** [comment]
also run into issues around `password` not being in my secret since previously the `key` was `postgresql-password` but has since been updated. Feels like `helm` isn't updating my secret from a previous release (helm upgrade is my go to)

**Comment by javsalgar** [comment]
Hi,

The thing is that you are trying to upgrade between major versions via `helm upgrade`, which is not something we expect to work out of the box. However, if you can let us know the steps that helped in the migration we would appreciate it.
