### ISSUE TITLE
[bitnami/airflow]

### ISSUE THREAD

**Issue by kodeine** [bitnami/charts#9901]
### Name and Version

bitnami/airflow 12.2.0

### What steps will reproduce the bug?

```
executor=KubernetesExecutor
redis.enabled=false
rbac.create=true
serviceaccount.create=true
serviceaccount.annotations:
   iam.gke.io/gcp-service-account: apache-airflow@redacted.iam.gserviceaccount.com
```

### What do you see instead?

```
[2022-04-24 22:21:00,469] {kubernetes_executor.py:790} INFO - Shutting down Kubernetes executor
45
[2022-04-24 22:21:00,485] {manager.py:373} WARNING - Ending without manager process.
44
[2022-04-24 22:21:00,485] {scheduler_job.py:753} INFO - Exited execute loop
43
Traceback (most recent call last):
42
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
41
    sys.exit(main())
40
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 48, in main
39
    args.func(args)
38
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
37
    return func(*args, **kwargs)
36
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
35
    return f(*args, **kwargs)
34
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 75, in scheduler
33
    _run_scheduler_job(args=args)
32
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 46, in _run_scheduler_job
31
    job.run()
30
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/base_job.py", line 246, in run
29
    self._execute()
28
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 718, in _execute
27
    self.executor.start()
26
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/kubernetes_executor.py", line 520, in start
25
    self.clear_not_launched_queued_tasks()
24
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
23
    return func(*args, session=session, **kwargs)
22
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/kubernetes_executor.py", line 481, in clear_not_launched_queued_tasks
21
    pod_list = self.kube_client.list_namespaced_pod(self.kube_config.kube_namespace, **kwargs)
20
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 12803, in list_namespaced_pod
19
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
18
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 12891, in list_namespaced_pod_with_http_info
17
    return self.api_client.call_api(
16
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
15
    return self.__call_api(resource_path, method,
14
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
13
    response_data = self.request(
12
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 362, in request
11
    return self.rest_client.GET(url,
10
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kubernetes/client/rest.py", line 237, in GET
9
    return self.request("GET", url,
8
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kubernetes/client/rest.py", line 231, in request
7
    raise ApiException(http_resp=r)
6
kubernetes.client.rest.ApiException: (403)
5
Reason: Forbidden
4
HTTP response headers: HTTPHeaderDict({'Audit-Id': '468b29d5-7c5c-4acd-a7a5-5d2385df989e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'cada7c59-dc59-4169-a5bc-6177fa6a78f7', 'X-Kubernetes-Pf-Prioritylevel-Uid': '516019a5-90e0-44c3-a276-0bb9fd013a42', 'Date': 'Sun, 24 Apr 2022 22:21:00 GMT', 'Content-Length': '289'})
3
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:airflow-cluster:apache-airflow\" cannot list resource \"pods\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"pods"},"code":403}
2
1

```

### Additional information

even if i remove `annotations`, its still unable to create pods. `CeleryExecutor` works fine.

**Comment by javsalgar** [comment]
Hi!

Could you add more details to reproduce the issue? I deployed with the values but did not find the error:

```
❯ kubectl get pods -w
NAME                                 READY   STATUS    RESTARTS   AGE
airflow-postgresql-0                 1/1     Running   0          4m7s
airflow-redis-master-0               1/1     Running   0          4m7s
airflow-scheduler-565fd7bcc7-l6r99   1/1     Running   0          4m7s
airflow-web-75cb6889f4-67nh6         1/1     Running   0          4m7s
```

**Comment by javsalgar** [comment]
Hi,

We test our charts daily in GKE and do not find issues. Does it directly crash when deploying the chart or do I need to trigger something?
